import type { BodyPathophysiologyScenarioId } from './bodyPathophysiologyNetwork'
import type { PharmacologyMechanismId } from './bodyPharmacologyMechanismNetwork'

export type CausalBridgeRelation = 'upstream-driver' | 'propagation-node' | 'downstream-modifier' | 'systems-context'

export interface BodyMechanismCausalLink {
  id: string
  scenarioId: BodyPathophysiologyScenarioId
  scenarioStepIds: readonly string[]
  pharmacologyMechanismId: PharmacologyMechanismId
  relation: CausalBridgeRelation
  title: string
  explanation: string
  doesNotImply: string
}

export const BODY_MECHANISM_CAUSAL_BRIDGE: readonly BodyMechanismCausalLink[] = [
  { id: 'atherosclerosis-statin-lipid-axis', scenarioId: 'atherosclerosis', scenarioStepIds: ['lipid-inflammatory-recruitment', 'plaque-remodeling'], pharmacologyMechanismId: 'statin-hmgcr', relation: 'upstream-driver', title: 'LDL biology intersects plaque lipid-inflammatory burden', explanation: 'The HMGCR → hepatic LDLR → circulating LDL clearance mechanism connects upstream lipoprotein exposure to the lipid-rich inflammatory environment represented in plaque growth and remodeling.', doesNotImply: 'This link does not quantify plaque regression, fibrous-cap stabilization, event reduction, treatment intensity or an individual LDL target.' },
  { id: 'atherosclerosis-pcsk9-ldlr-axis', scenarioId: 'atherosclerosis', scenarioStepIds: ['lipid-inflammatory-recruitment', 'plaque-remodeling'], pharmacologyMechanismId: 'pcsk9-inhibition', relation: 'upstream-driver', title: 'LDLR preservation converges on the same lipoprotein exposure axis', explanation: 'PCSK9-pathway inhibition reduces LDL-receptor degradation, increasing hepatic LDLR availability and linking a distinct molecular target to the same upstream apoB/LDL exposure axis relevant to atherosclerotic plaque biology.', doesNotImply: 'Convergence on LDLR biology does not make statins and PCSK9-targeting strategies interchangeable or establish patient-specific indication, sequence or intensity.' },
  { id: 'atherosclerosis-aspirin-thromboxane-axis', scenarioId: 'atherosclerosis', scenarioStepIds: ['plaque-disruption', 'atherothrombosis'], pharmacologyMechanismId: 'aspirin-cox1', relation: 'propagation-node', title: 'Platelet thromboxane signaling intersects post-disruption thrombosis', explanation: 'The platelet COX-1 → thromboxane A2 pathway sits within platelet activation after a thrombogenic vascular surface is exposed, connecting pharmacology to the thrombotic propagation branch rather than to plaque formation itself.', doesNotImply: 'This relation does not determine whether antiplatelet therapy is indicated, sufficient, contraindicated or net-beneficial for any individual.' },
  { id: 'heart-failure-ace-raas-axis', scenarioId: 'heart-failure', scenarioStepIds: ['neurohormonal-response', 'volume-pressure-congestion', 'remodeling-loop'], pharmacologyMechanismId: 'ace-inhibition', relation: 'propagation-node', title: 'ACE inhibition intersects the RAAS compensation-remodeling loop', explanation: 'ACE inhibition reduces angiotensin-II generation and downstream aldosterone drive, directly intersecting the neurohormonal compensation branch that couples vascular tone, renal sodium-water handling and chronic remodeling pressure.', doesNotImply: 'This systems bridge does not model blood pressure, renal function, potassium, cough/angioedema risk, titration or patient-specific benefit.' },
  { id: 'heart-failure-beta-sympathetic-axis', scenarioId: 'heart-failure', scenarioStepIds: ['neurohormonal-response', 'remodeling-loop'], pharmacologyMechanismId: 'beta1-blockade', relation: 'propagation-node', title: 'β-adrenergic blockade intersects chronic sympathetic compensation', explanation: 'Reduced β-adrenergic signaling connects to the sympathetic compensation node through myocardial catecholamine drive and renin-axis signaling, creating a heart-kidney-autonomic bridge within the chronic heart-failure network.', doesNotImply: 'The bridge does not simulate acute decompensation, conduction disease, bronchospasm, titration, drug selectivity differences or individual hemodynamic tolerance.' },
  { id: 'heart-failure-sglt2-cardiorenal-axis', scenarioId: 'heart-failure', scenarioStepIds: ['volume-pressure-congestion', 'remodeling-loop'], pharmacologyMechanismId: 'sglt2-inhibition', relation: 'systems-context', title: 'Proximal-tubule transport connects to the cardiorenal loading environment', explanation: 'Canonical proximal-tubule SGLT2 inhibition changes sodium-glucose handling and renal volume context, providing a mechanistic bridge to congestion/loading while broader myocardial mechanisms remain an active systems-research field.', doesNotImply: 'This link does not estimate diuresis, glycosuria, ketoacidosis risk, kidney response, volume status or clinical outcome for an individual.' },
  { id: 'ischemic-stroke-statin-upstream-axis', scenarioId: 'ischemic-stroke', scenarioStepIds: ['cerebral-flow-interruption'], pharmacologyMechanismId: 'statin-hmgcr', relation: 'upstream-driver', title: 'Lipid-lowering biology sits upstream of some arterial stroke mechanisms', explanation: 'HMGCR inhibition changes LDL exposure relevant to atherosclerotic vascular disease, which can sit upstream of some ischemic-stroke mechanisms, while the acute neurovascular injury cascade begins only after cerebral perfusion is critically reduced.', doesNotImply: 'The relationship does not identify stroke etiology, determine acute treatment, estimate penumbra, select secondary prevention or infer an individual vascular mechanism.' },
  { id: 'ischemic-stroke-aspirin-platelet-axis', scenarioId: 'ischemic-stroke', scenarioStepIds: ['cerebral-flow-interruption'], pharmacologyMechanismId: 'aspirin-cox1', relation: 'systems-context', title: 'Platelet COX-1 biology can intersect thrombotic arterial occlusion', explanation: 'The aspirin-sensitive COX-1/thromboxane branch influences platelet activation in thrombotic vascular disease, but the ischemic-stroke cascade itself is agnostic to the many possible causes of flow interruption.', doesNotImply: 'This contextual link does not determine stroke subtype, hemorrhage exclusion, timing, eligibility, dose or any acute antiplatelet decision.' },
  { id: 'vte-factor-xa-coagulation-axis', scenarioId: 'venous-thromboembolism', scenarioStepIds: ['venous-thrombus-initiation', 'thrombus-propagation'], pharmacologyMechanismId: 'factor-xa-inhibition', relation: 'propagation-node', title: 'Factor Xa inhibition intersects fibrin-rich thrombus propagation', explanation: 'Direct Xa inhibition reduces prothrombinase activity and thrombin generation, connecting directly to the coagulation-amplification branch that supports fibrin-rich venous thrombus propagation.', doesNotImply: 'The mechanism map does not select anticoagulant, dose, duration, renal adjustment, bleeding-risk strategy, reversal plan or treatment setting.' },
] as const

export const BODY_MECHANISM_CAUSAL_BRIDGE_BOUNDARY = 'Educational disease ↔ pharmacology causal bridge only. Links identify literature-consistent mechanistic intersections between an existing pathophysiology node and a class-level pharmacology mechanism. This bridge does not establish indication, contraindication, comparative efficacy, dose, timing, treatment sequence, patient-specific response, or clinical outcome.'

export function listCausalLinksForScenario(scenarioId: BodyPathophysiologyScenarioId): readonly BodyMechanismCausalLink[] { return BODY_MECHANISM_CAUSAL_BRIDGE.filter((link) => link.scenarioId === scenarioId) }
export function listCausalLinksForPharmacology(mechanismId: PharmacologyMechanismId): readonly BodyMechanismCausalLink[] { return BODY_MECHANISM_CAUSAL_BRIDGE.filter((link) => link.pharmacologyMechanismId === mechanismId) }
