// DIBUAT OTOMATIS oleh scripts/daftarKalkulator.mjs — jangan disunting tangan.
//
// Judul tiap kalkulator di dalam halaman Kalkulator Klinis. Diperlukan karena
// kalkulator-kalkulator itu bagian di dalam satu halaman, bukan rute
// tersendiri, sehingga mesin pencari tidak dapat menemukannya tanpa daftar.
export const KALKULATOR_KLINIS: string[] = [
  "APGAR Score",
  "GCS + GCS-Pupil (Improved GCS)",
  "CURB-65",
  "Bishop Score",
  "CKD-EPI 2021 (eGFR)",
  "Antropometri WHO (Permenkes 2/2020)",
  "Neonatus WHO (0–30 Hari)",
  "Antropometri CDC (2–20 Tahun)",
  "Ballard Score + Lubchenco → SOAP",
  "qSOFA",
  "Holliday-Segar (Maintenance Fluid)",
  "Parkland Formula",
  "Naegele's Rule",
  "Mean Arterial Pressure (MAP)",
  "Alvarado Score",
  "Siriraj Stroke Score",
  "Algoritma Stroke Gadjah Mada",
  "Centor / McIsaac Score",
  "Electrolyte Correction (Na & K)",
  "Broca's Formula (Ideal Body Weight)",
  "Mid-Parental Height",
  "Fletcher Index",
  "NOSE Score",
  "Reflux Symptom Index (RSI)",
  "ABCD² Score",
  "FOUR Score",
  "McDonald's Rule",
  "Paradise Criteria",
  "NIH Stroke Scale (NIHSS)",
  "Fluid Balance (24 hours)",
  "Pediatric Medication Dosing Calculator",
  "VBAC — Flamm-Geiger Score",
  "Denver II (Simplified)",
  "Trauma Primary Survey (XABCDE)",
  "Blood Gas Analysis (ABG)",
  "Advanced Burn Calculator",
  "Cranial Nerves + Meningeal Signs",
  "Competency Tracker (SKDI)",
  "Unlock Clinical Calculators",
  "Broca–Lorentz Calorie Calculator",
  "IV Fluid Drip Rate",
  "ARIA Criteria",
  "ACLS Guide"
]
