// International medical licensing exam practice bank.
//
// IMPORTANT — legal & honesty note: these are ORIGINAL practice questions
// written to match each exam's known format and content blueprint. They are
// NOT real/leaked past questions — actual board questions are copyrighted by
// their administering bodies (NBME, GMC, SCFHS, etc.) and no legitimate
// source of real past papers exists for an app to redistribute. Every track
// below states this plainly so nobody mistakes practice content for official
// material. Where a question leans on country-specific epidemiology (e.g.
// consanguinity screening in Saudi, HIV/TB co-infection in South Africa),
// that reflects genuine regional disease burden, not stereotype.

export type ExamTrack =
  | 'usmle' | 'plab' | 'saudi_smle' | 'uae' | 'singapore' | 'japan'
  | 'taiwan' | 'china' | 'europe_de' | 'south_africa' | 'israel'

export interface ExamInfo {
  id: ExamTrack
  flag: string
  country: string
  examName: string
  body: string
  format: string
}

export interface ExamQuestion {
  id: string
  vignette: string
  options: string[]
  answer: number
  explanation: string
}

export const EXAM_INFO: Record<ExamTrack, ExamInfo> = {
  usmle: { id: 'usmle', flag: '🇺🇸', country: 'Amerika Serikat', examName: 'USMLE (Step 1/2 CK)', body: 'NBME/FSMB', format: 'MCQ vignette klinis, single best answer' },
  plab: { id: 'plab', flag: '🇬🇧', country: 'Inggris (UK)', examName: 'PLAB 1 & 2', body: 'General Medical Council (GMC)', format: 'MCQ + OSCE, penekanan etika & NHS guideline' },
  saudi_smle: { id: 'saudi_smle', flag: '🇸🇦', country: 'Arab Saudi', examName: 'SMLE', body: 'Saudi Commission for Health Specialties (SCFHS)', format: 'MCQ vignette klinis' },
  uae: { id: 'uae', flag: '🇦🇪', country: 'UEA', examName: 'DHA/MOH/HAAD Exam', body: 'Prometric (untuk DHA/MOH/DOH)', format: 'MCQ berbasis komputer' },
  singapore: { id: 'singapore', flag: '🇸🇬', country: 'Singapura', examName: 'SMC Qualifying Exam', body: 'Singapore Medical Council (SMC)', format: 'MCQ + klinis' },
  japan: { id: 'japan', flag: '🇯🇵', country: 'Jepang', examName: 'National Medical Practitioners Qualifying Examination', body: 'Kementerian Kesehatan Jepang (MHLW)', format: 'MCQ, berbahasa Jepang' },
  taiwan: { id: 'taiwan', flag: '🇹🇼', country: 'Taiwan', examName: 'Medical Licensing Examination', body: 'Ministry of Examination Taiwan', format: 'MCQ, dua tahap' },
  china: { id: 'china', flag: '🇨🇳', country: 'Tiongkok', examName: 'National Medical Licensing Examination (NMLE)', body: 'National Medical Examination Center (NMEC)', format: 'MCQ komputer + skill klinis' },
  europe_de: { id: 'europe_de', flag: '🇩🇪', country: 'Jerman (contoh Eropa)', examName: 'Kenntnisprüfung', body: 'Landesärztekammer (dewan kedokteran negara bagian)', format: 'Ujian lisan/klinis untuk pengakuan gelar non-UE' },
  south_africa: { id: 'south_africa', flag: '🇿🇦', country: 'Afrika Selatan', examName: 'HPCSA Board Exam', body: 'Health Professions Council of South Africa', format: 'MCQ + OSCE untuk lulusan asing' },
  israel: { id: 'israel', flag: '🇮🇱', country: 'Israel', examName: 'Rishuy (Israeli Medical Licensing Exam)', body: 'Kementerian Kesehatan Israel', format: 'MCQ, tersedia versi bahasa Inggris' },
}

export const EXAM_ORDER: ExamTrack[] = ['usmle', 'plab', 'saudi_smle', 'uae', 'singapore', 'japan', 'taiwan', 'china', 'europe_de', 'south_africa', 'israel']

export const EXAM_BANK: Record<ExamTrack, ExamQuestion[]> = {
  usmle: [
    { id: 'usmle-1',
      vignette: 'Wanita 32 tahun datang dengan palpitasi, tremor halus, penurunan berat badan meski nafsu makan meningkat, dan goiter difus disertai eksoftalmus. TSH rendah, free T4 tinggi.',
      options: ['Tiroiditis subakut (De Quervain)', "Graves' disease", 'Adenoma toksik', 'Hashimoto tirotoksikosis transien'],
      answer: 1,
      explanation: "Goiter difus + eksoftalmus + hipertiroid adalah trias klasik Graves' disease — autoantibodi TSI (thyroid-stimulating immunoglobulin) mengaktifkan reseptor TSH secara terus-menerus, memicu hipertrofi & hiperfungsi difus kelenjar tiroid serta manifestasi ekstratiroid (oftalmopati) akibat reaktivitas silang antigen retro-orbital." },
    { id: 'usmle-2',
      vignette: 'Pasien laki-laki dengan defisiensi G6PD mengalami hemolisis akut 2 hari setelah minum obat antimalaria untuk terapi radikal Plasmodium vivax.',
      options: ['Primakuin', 'Metformin', 'Atorvastatin', 'Lisinopril'],
      answer: 0,
      explanation: 'Primakuin (dan obat oksidan lain seperti dapson, sulfonamid) menghasilkan spesies oksigen reaktif yang tidak bisa dinetralisir sel darah merah defisien G6PD (kurang NADPH untuk regenerasi glutation tereduksi) — menyebabkan denaturasi hemoglobin (Heinz bodies) dan hemolisis.' },
    { id: 'usmle-3',
      vignette: 'Pria 58 tahun dengan nyeri dada tipikal saat aktivitas, mereda dengan istirahat, EKG istirahat normal. Anda ingin mengevaluasi kemungkinan penyakit jantung koroner stabil.',
      options: ['Troponin serial saja', 'Tes treadmill (exercise stress ECG) sebagai lini awal pada pasien risiko menengah', 'CT scan kepala', 'Rontgen toraks saja'],
      answer: 1,
      explanation: 'Pada angina stabil dengan EKG istirahat normal & kemampuan berolahraga baik, exercise stress test adalah investigasi awal standar (guideline ACC/AHA/ESC) untuk menilai iskemia yang terprovokasi aktivitas — troponin dipakai untuk sindrom koroner akut, bukan evaluasi angina stabil kronis.' },
    { id: 'usmle-4',
      vignette: 'Pasien fibrilasi atrium nonvalvular memakai warfarin dengan target INR 2-3, kemudian diberi resep metronidazole untuk infeksi anaerob.',
      options: ['Tidak ada interaksi bermakna', 'Metronidazole menghambat CYP2C9 sehingga meningkatkan kadar warfarin & risiko perdarahan — perlu pemantauan INR ketat', 'Metronidazole menurunkan efek warfarin', 'Kombinasi ini dikontraindikasikan mutlak, ganti warfarin permanen'],
      answer: 1,
      explanation: 'Metronidazole adalah penghambat kuat CYP2C9, enzim utama metabolisme warfarin (terutama S-warfarin yang lebih poten) — kombinasi ini klasik meningkatkan INR signifikan dalam beberapa hari; pemantauan INR ketat & penyesuaian dosis diperlukan, bukan penghentian otomatis salah satu obat.' },
    { id: 'usmle-5',
      vignette: 'Bayi 2 bulan dengan muntah proyektil non-bilier setelah menyusu, tampak semakin lapar, teraba massa "olive" di epigastrium, USG menunjukkan penebalan otot pilorus.',
      options: ['Refluks gastroesofageal fisiologis', 'Stenosis pilorus hipertrofik — perlu piloromiotomi', 'Atresia duodenum', 'Intususepsi'],
      answer: 1,
      explanation: 'Muntah proyektil non-bilier progresif + massa olive teraba + gambaran USG "target sign"/penebalan otot pilorus >4mm adalah klasik stenosis pilorus hipertrofik, tersering pada bayi laki-laki 2-8 minggu — tatalaksana definitif piloromiotomi setelah koreksi alkalosis metabolik hipokloremik akibat muntah asam lambung berulang.' },
    { id: 'usmle-6',
      vignette: 'Pria 60 tahun perokok berat dengan penurunan berat badan, nyeri tulang, dan hiperkalsemia tanpa metastasis tulang jelas pada pencitraan; PTH serum rendah/tertekan.',
      options: ['Hiperparatiroidisme primer', 'Hiperkalsemia keganasan akibat PTHrP (parathyroid hormone-related peptide) dari karsinoma sel skuamosa paru', 'Intoksikasi vitamin D', 'Sarkoidosis'],
      answer: 1,
      explanation: 'Hiperkalsemia humoral keganasan (paling sering karsinoma sel skuamosa paru) disebabkan sekresi PTHrP yang berikatan reseptor PTH menyerupai efeknya, namun PTH asli tertekan oleh umpan balik negatif kalsium tinggi — pola PTH rendah + kalsium tinggi ini membedakannya dari hiperparatiroidisme primer (PTH tinggi/inappropriate normal).' },
    { id: 'usmle-7',
      vignette: 'Wanita 28 tahun dengan nyeri sendi simetris pada tangan, ruam malar yang memburuk oleh sinar matahari, dan proteinuria. ANA positif titer tinggi, anti-dsDNA positif.',
      options: ['Artritis reumatoid', 'Lupus eritematosus sistemik (SLE) dengan kemungkinan nefritis lupus', 'Dermatomiositis', 'Skleroderma sistemik'],
      answer: 1,
      explanation: 'Ruam malar fotosensitif + artritis simetris + proteinuria (curiga nefritis lupus) + anti-dsDNA (spesifik untuk SLE dan berkorelasi dengan aktivitas nefritis) memenuhi kriteria klasifikasi SLE — anti-dsDNA dan anti-Smith adalah antibodi paling spesifik, berbeda dari ANA yang sensitif namun tidak spesifik.' },
    { id: 'usmle-8',
      vignette: 'Neonatus tampak ikterik pada hari ke-2 kehidupan, bilirubin total tinggi namun bilirubin direk normal, ibu golongan darah O+ dan bayi A+.',
      options: ['Atresia bilier', 'Inkompatibilitas ABO menyebabkan hemolisis & hiperbilirubinemia indirek', 'Hepatitis neonatal', 'Sepsis neonatorum'],
      answer: 1,
      explanation: 'Ikterus dini (<24-48 jam) dengan bilirubin indirek dominan pada ibu O dengan bayi A/B adalah pola klasik inkompatibilitas ABO — antibodi anti-A/anti-B ibu (IgG, dapat melewati plasenta) menghemolisis eritrosit janin/bayi; berbeda dari atresia bilier yang khas bilirubin direk meningkat dan muncul lebih lambat (minggu ke-2 ke atas).' },
    { id: 'usmle-9',
      vignette: 'Pria 45 tahun dengan nyeri epigastrium berat mendadak menjalar ke punggung setelah pesta minum alkohol, amilase & lipase serum jauh di atas normal.',
      options: ['Kolesistitis akut', 'Pankreatitis akut — nilai keparahan dengan kriteria (mis. BISAP/Ranson) dan resusitasi cairan agresif', 'Ulkus peptikum perforasi', 'Infark miokard inferior'],
      answer: 1,
      explanation: 'Nyeri epigastrium menjalar ke punggung + lipase/amilase meningkat >3x batas atas normal pada konteks konsumsi alkohol berat adalah presentasi klasik pankreatitis akut — tatalaksana awal berfokus resusitasi cairan agresif (mengurangi nekrosis pankreas akibat hipoperfusi) dan penilaian keparahan untuk stratifikasi risiko komplikasi sistemik.' },
  ],
  plab: [
    { id: 'plab-1',
      vignette: 'Anak perempuan 15 tahun datang sendiri meminta resep pil kontrasepsi, menolak orang tuanya diberi tahu. Ia tampak memahami risiko & manfaat terapi dengan baik.',
      options: ['Tolak meresepkan tanpa persetujuan orang tua', 'Nilai kompetensi Gillick — jika terpenuhi, boleh diresepkan tanpa memberi tahu orang tua', 'Hubungi orang tua terlebih dahulu sebelum konsultasi lanjut', 'Rujuk ke polisi karena di bawah umur'],
      answer: 1,
      explanation: 'Prinsip "Gillick competence" (kasus hukum Gillick v West Norfolk, 1985) memungkinkan anak di bawah 16 tahun menerima layanan kesehatan tanpa persetujuan orang tua jika dokter menilai ia cukup matang memahami implikasi keputusannya — inti pendekatan GMC pada etika & kerahasiaan remaja.' },
    { id: 'plab-2',
      vignette: 'Pasien asma datang dengan eksaserbasi akut sedang: bicara kalimat penuh, RR 22x/menit, SpO2 95% udara ruangan.',
      options: ['Kortikosteroid oral sebagai langkah pertama', 'Salbutamol nebulisasi/inhaler dosis tinggi sebagai langkah pertama', 'Intubasi elektif', 'Antibiotik empiris'],
      answer: 1,
      explanation: 'Bronkodilator kerja cepat (SABA) adalah lini pertama pada semua tingkat keparahan eksaserbasi asma (British Thoracic Society/NICE guideline) — steroid oral ditambahkan untuk mengurangi inflamasi & mencegah relaps, tapi onsetnya lambat sehingga bukan langkah pertama untuk perbaikan gejala akut.' },
    { id: 'plab-3',
      vignette: 'Dokter perlu menyampaikan diagnosis kanker stadium lanjut kepada pasien yang belum tahu apa-apa, dalam konsultasi terjadwal 15 menit.',
      options: ['Sampaikan diagnosis secara langsung tanpa basa-basi agar efisien waktu', 'Gunakan pendekatan bertahap (mis. kerangka SPIKES): nilai kesiapan pasien, beri "warning shot", sampaikan informasi bertahap, dan beri ruang emosi', 'Tunda penyampaian hingga keluarga datang tanpa persetujuan pasien', 'Minta perawat yang menyampaikan agar dokter tidak perlu terlibat'],
      answer: 1,
      explanation: 'Kerangka SPIKES (Setting, Perception, Invitation, Knowledge, Empathy, Strategy/Summary) adalah standar komunikasi berita buruk yang diajarkan & diuji di PLAB — inti utamanya menyesuaikan kecepatan & kedalaman informasi dengan kesiapan pasien, memberi respons empatik, bukan sekadar menyampaikan fakta medis secepat mungkin.' },
    { id: 'plab-4',
      vignette: 'Pasien 55 tahun tanpa gejala datang untuk general check-up rutin di NHS. Ia bertanya soal skrining kanker usus besar yang direkomendasikan.',
      options: ['Kolonoskopi rutin setiap tahun untuk semua orang dewasa', 'Program skrining nasional FIT test (fecal immunochemical test) berkala untuk usia yang memenuhi syarat', 'Skrining tidak direkomendasikan tanpa gejala', 'CT scan abdomen rutin sebagai skrining lini pertama'],
      answer: 1,
      explanation: 'Program skrining kanker kolorektal NHS memakai FIT test (mendeteksi darah samar tinja lewat antibodi spesifik hemoglobin manusia) secara berkala pada kelompok usia yang ditetapkan — non-invasif, murah, dan efektif menurunkan mortalitas lewat deteksi dini; kolonoskopi diperuntukkan follow-up hasil positif atau kelompok risiko tinggi, bukan skrining massal lini pertama.' },
    { id: 'plab-5',
      vignette: 'Pasien lansia dengan demensia sedang kehilangan kapasitas mengambil keputusan finansial. Keluarga meminta dokter menandatangani dokumen tanpa penilaian formal.',
      options: ['Tanda tangani saja atas permintaan keluarga', 'Lakukan penilaian kapasitas formal (Mental Capacity Act 2005) sebelum keputusan apapun diambil atas nama pasien', 'Kapasitas dianggap otomatis hilang begitu diagnosis demensia ditegakkan', 'Rujuk langsung ke pengadilan tanpa penilaian klinis'],
      answer: 1,
      explanation: 'Mental Capacity Act 2005 menegaskan kapasitas dinilai per-keputusan (decision-specific), bukan status global — diagnosis demensia saja tidak otomatis berarti tidak berkapasitas; penilaian formal (memahami, mengingat, menimbang informasi, mengomunikasikan keputusan) wajib sebelum keputusan "best interest" diambil oleh pihak lain.' },
    { id: 'plab-6',
      vignette: 'Bayi 6 minggu dengan batuk paroksismal berat disertai "whoop", riwayat imunisasi tidak lengkap, kontak dengan orang dewasa batuk kronis di rumah.',
      options: ['Bronkiolitis RSV', 'Pertusis (batuk rejan) — konfirmasi PCR nasofaring, terapi makrolid & profilaksis kontak erat', 'Croup viral', 'Asma bayi'],
      answer: 1,
      explanation: 'Batuk paroksismal dengan whoop pada bayi dengan riwayat vaksinasi tidak lengkap sangat sugestif pertusis — makrolid (azitromisin/eritromisin) mengurangi penularan meski efek terhadap durasi batuk terbatas jika diberikan lambat; profilaksis pasca-pajanan pada kontak dekat penting karena bayi <6 bulan berisiko tinggi komplikasi apnea/pneumonia.' },
    { id: 'plab-7',
      vignette: 'Pasien datang meminta second opinion setelah tidak puas dengan diagnosis dokter sebelumnya, dan meminta salinan rekam medis lengkapnya dikirim ke dokter baru.',
      options: ['Tolak memberikan rekam medis tanpa alasan', 'Pasien berhak mengakses & meminta salinan rekam medisnya sendiri (Data Protection Act/UK GDPR) — proses permintaan sesuai prosedur, umumnya tanpa biaya', 'Hanya dokter yang boleh memutuskan apakah rekam medis dibagikan', 'Perlu izin pengadilan untuk transfer rekam medis'],
      answer: 1,
      explanation: 'Di bawah UK GDPR/Data Protection Act, pasien memiliki hak akses subjek data (subject access right) atas rekam medisnya sendiri — permintaan transfer ke penyedia layanan lain harus difasilitasi dalam kerangka waktu yang ditetapkan hukum, mencerminkan prinsip otonomi & kepemilikan data pasien atas informasi kesehatannya.' },
    { id: 'plab-8',
      vignette: 'Wanita hamil 32 minggu dengan tekanan darah 160/105 mmHg, proteinuria signifikan, dan nyeri kepala berat disertai gangguan penglihatan.',
      options: ['Preeklamsia berat — magnesium sulfat untuk profilaksis kejang & rencana terminasi kehamilan sesuai usia gestasi', 'Hipertensi gestasional ringan, cukup observasi rawat jalan', 'Migrain biasa, terapi simtomatik saja', 'Eklamsia hanya didiagnosis setelah kejang terjadi'],
      answer: 0,
      explanation: 'Preeklamsia berat (TD ≥160/110 + proteinuria + gejala berat seperti sakit kepala/gangguan visual) memerlukan magnesium sulfat (mencegah progresi ke eklamsia lewat stabilisasi membran neuron & vasodilatasi serebral) dan perencanaan persalinan — menunggu hingga kejang terjadi (definisi eklamsia) sudah terlambat untuk pencegahan primer.' },
    { id: 'plab-9',
      vignette: 'Pasien dengan riwayat depresi berat mengungkapkan rencana bunuh diri konkret dengan metode & waktu spesifik saat konsultasi rutin.',
      options: ['Catat di rekam medis dan jadwalkan kontrol rutin berikutnya', 'Nilai risiko segera secara komprehensif dan pertimbangkan rujukan psikiatri darurat/rawat inap involunter bila risiko tinggi, dengan pelanggaran kerahasiaan dibenarkan demi keselamatan pasien', 'Tunggu pasien pulang dan hubungi keluarga tanpa evaluasi lanjut', 'Berikan resep antidepresan tanpa evaluasi risiko lebih lanjut'],
      answer: 1,
      explanation: 'Rencana bunuh diri konkret (metode + waktu) adalah tanda risiko tinggi yang memerlukan evaluasi psikiatri segera — kerahasiaan pasien dapat dilanggar secara etis & legal ketika ada risiko serius terhadap keselamatan nyawa, prinsip yang diuji luas di PLAB sebagai batas etika kerahasiaan versus kewajiban melindungi nyawa.' },
  ],
  saudi_smle: [
    { id: 'smle-1',
      vignette: 'Pasangan calon pengantin menjalani program skrining pranikah wajib nasional di Arab Saudi. Program ini terutama ditujukan mendeteksi kondisi genetik resesif yang meningkat akibat pernikahan kerabat (consanguinity).',
      options: ['Diabetes tipe 2', 'Talasemia & anemia sel sabit', 'Hipertensi esensial', 'Osteoporosis'],
      answer: 1,
      explanation: 'Program skrining pranikah Arab Saudi (sejak 2004) berfokus pada hemoglobinopati (talasemia, anemia sel sabit) karena prevalensinya meningkat signifikan akibat tingginya angka pernikahan kerabat dekat (consanguineous marriage) — kondisi resesif autosomal jauh lebih sering muncul saat kedua orang tua carrier gen yang sama.' },
    { id: 'smle-2',
      vignette: 'Selama musim haji, seorang jamaah kolaps dengan suhu tubuh 41°C, kulit kering, dan penurunan kesadaran di tengah cuaca ekstrem.',
      options: ['Antipiretik oral segera', 'Pendinginan eksternal cepat (evaporative/immersion cooling) + resusitasi cairan', 'Antibiotik spektrum luas empiris', 'Observasi tanpa intervensi aktif'],
      answer: 1,
      explanation: 'Ini heat stroke klasik (bukan infeksi) — mekanisme utama kematian adalah kegagalan termoregulasi menyebabkan denaturasi protein & disfungsi multiorgan. Tatalaksana prioritas adalah pendinginan cepat (target turun <39°C dalam 30 menit) karena kecepatan pendinginan berkorelasi langsung dengan mortalitas, bukan antipiretik yang bekerja pada mekanisme demam berbeda (bukan gangguan hipotalamus akibat panas eksternal).' },
    { id: 'smle-3',
      vignette: 'Pasien dewasa muda datang untuk pemeriksaan rutin. Meski tinggal di negara dengan sinar matahari melimpah, pemeriksaan lab menunjukkan kadar 25-hidroksivitamin D rendah.',
      options: ['Tidak mungkin defisiensi vitamin D di negara tropis, ulangi pemeriksaan', 'Defisiensi vitamin D tetap umum akibat gaya hidup indoor & pakaian tertutup yang membatasi paparan sinar UVB kulit — pertimbangkan suplementasi', 'Vitamin D tidak perlu diperiksa rutin di populasi manapun', 'Segera rujuk untuk biopsi tulang'],
      answer: 1,
      explanation: 'Sintesis vitamin D kulit bergantung paparan UVB langsung, bukan sekadar lokasi geografis — gaya hidup banyak di dalam ruangan (ber-AC), pakaian menutup sebagian besar kulit, dan penggunaan tabir surya membuat defisiensi vitamin D tetap sangat prevalen di kawasan Teluk meski sinar matahari melimpah; suplementasi oral menjadi solusi praktis yang tidak bergantung paparan sinar matahari.' },
    { id: 'smle-4',
      vignette: 'Anak dari orang tua yang menikah kerabat dekat (sepupu pertama) datang dengan keterlambatan perkembangan, kejang, dan bau urin khas seperti sirup maple.',
      options: ['Fenilketonuria (PKU)', 'Maple syrup urine disease (MSUD) — gangguan metabolisme asam amino rantai cabang', 'Galaktosemia', 'Defisiensi biotinidase'],
      answer: 1,
      explanation: 'MSUD adalah kelainan resesif autosomal akibat defisiensi enzim dehidrogenase alfa-ketoasid rantai cabang, menyebabkan penumpukan leusin/isoleusin/valin — bau urin manis khas "sirup maple" adalah tanda patognomonik. Prevalensi kelainan resesif langka meningkat pada populasi dengan angka pernikahan kerabat tinggi seperti di Arab Saudi.' },
    { id: 'smle-5',
      vignette: 'Pasien pekerja migran dari Asia Selatan dengan batuk kronis >3 minggu, penurunan berat badan, keringat malam, dan foto toraks menunjukkan infiltrat kavitas lobus atas.',
      options: ['Pneumonia komunitas biasa', 'Tuberkulosis paru — perlu pemeriksaan sputum BTA/GeneXpert dan isolasi sampai konfirmasi', 'Kanker paru primer', 'Bronkitis kronis akibat merokok'],
      answer: 1,
      explanation: 'Trias batuk kronis + penurunan berat badan + keringat malam dengan infiltrat kavitas lobus atas sangat sugestif TB paru — penting diwaspadai pada populasi pekerja migran dari negara beban TB tinggi; GeneXpert MTB/RIF memberikan konfirmasi cepat sekaligus deteksi resistensi rifampisin.' },
    { id: 'smle-6',
      vignette: 'Pasien dengan nyeri kolik hebat di pinggang menjalar ke selangkangan, hematuria mikroskopik, mual muntah — riwayat asupan cairan rendah karena kerja di lingkungan sangat panas.',
      options: ['Pielonefritis akut', 'Nefrolitiasis (batu ginjal) — dorong hidrasi, analgesia, dan pencitraan (CT non-kontras) untuk konfirmasi', 'Apendisitis akut', 'Kista ovarium terpuntir'],
      answer: 1,
      explanation: 'Nyeri kolik khas menjalar ke selangkangan + hematuria mikroskopik pada pasien dengan dehidrasi kronis (lingkungan panas, asupan cairan rendah) adalah presentasi klasik urolitiasis — dehidrasi meningkatkan konsentrasi zat pembentuk batu (kalsium oksalat tersering); CT non-kontras adalah baku emas diagnosis.' },
    { id: 'smle-7',
      vignette: 'Wanita hamil trimester pertama dengan riwayat diabetes gestasional pada kehamilan sebelumnya datang untuk konsultasi antenatal awal.',
      options: ['Skrining glukosa cukup dilakukan di trimester ketiga saja seperti kehamilan risiko rendah', 'Lakukan skrining glukosa lebih awal (trimester pertama) karena riwayat diabetes gestasional sebelumnya meningkatkan risiko rekurensi signifikan', 'Diabetes gestasional tidak akan berulang pada kehamilan berikutnya', 'Tidak perlu skrining karena HbA1c terakhir normal'],
      answer: 1,
      explanation: 'Riwayat diabetes gestasional sebelumnya adalah faktor risiko kuat rekurensi (hingga 40-60%) — pedoman antenatal merekomendasikan skrining glukosa lebih awal pada kehamilan berikutnya, bukan menunggu jadwal skrining standar trimester ketiga, untuk deteksi & tatalaksana dini yang mencegah komplikasi makrosomia/hipoglikemia neonatal.' },
    { id: 'smle-8',
      vignette: 'Pasien pria muda dengan nyeri sendi berulang, nyeri pinggang bawah kronis memburuk saat istirahat & membaik dengan aktivitas, kekakuan pagi hari >30 menit.',
      options: ['Osteoartritis lumbal', 'Spondiloartritis aksial (mis. ankylosing spondylitis) — pertimbangkan HLA-B27 & MRI sakroiliaka', 'Hernia nukleus pulposus akut', 'Fibromialgia'],
      answer: 1,
      explanation: 'Nyeri punggung inflamasi (membaik dengan aktivitas, memburuk dengan istirahat, kekakuan pagi lama) pada pria muda adalah pola klasik spondiloartritis aksial — HLA-B27 sering positif dan MRI sakroiliaka dapat mendeteksi sakroiliitis dini sebelum perubahan radiografik konvensional tampak (bedanya dengan osteoartritis mekanik yang memburuk dengan aktivitas).' },
    { id: 'smle-9',
      vignette: 'Anak dengan anemia hemolitik kronis, splenomegali, dan riwayat keluarga serupa; apus darah tepi menunjukkan sel sabit, elektroforesis hemoglobin mengonfirmasi HbSS.',
      options: ['Talasemia beta mayor', 'Anemia sel sabit (sickle cell disease) — profilaksis penisilin, vaksinasi pneumokokus, dan edukasi krisis vaso-oklusif', 'Sferositosis herediter', 'Anemia defisiensi besi kronis'],
      answer: 1,
      explanation: 'HbSS pada elektroforesis mengonfirmasi anemia sel sabit homozigot — pasien berisiko tinggi infeksi ensapsulasi akibat autosplenektomi fungsional (splenomegali awal lalu atrofi progresif), sehingga profilaksis penisilin & vaksinasi pneumokokus/meningokokus/Hib adalah bagian standar tatalaksana preventif seumur hidup.' },
  ],
  uae: [
    { id: 'uae-1',
      vignette: 'Pria 45 tahun ekspatriat di UEA dengan obesitas sentral, HbA1c 8.2%, riwayat keluarga diabetes tipe 2 kuat — populasi UEA termasuk salah satu prevalensi diabetes tertinggi dunia.',
      options: ['Insulin basal sebagai lini pertama', 'Modifikasi gaya hidup + metformin sebagai lini pertama', 'Sulfonilurea sebagai monoterapi awal', 'Tidak perlu terapi farmakologis'],
      answer: 1,
      explanation: 'Metformin tetap lini pertama DM tipe 2 pada mayoritas pasien (kecuali kontraindikasi) — bekerja menurunkan produksi glukosa hepatik (menghambat glukoneogenesis lewat aktivasi AMPK) dan meningkatkan sensitivitas insulin perifer, dengan risiko hipoglikemia rendah dibanding sulfonilurea.' },
    { id: 'uae-2',
      vignette: 'Pasien datang dengan nyeri dada substernal khas, EKG menunjukkan ST elevasi di V1-V4.',
      options: ['STEMI anterior — evaluasi reperfusi segera (PCI primer/fibrinolitik)', 'Perikarditis akut', 'Angina stabil, rawat jalan', 'GERD, terapi PPI empiris'],
      answer: 0,
      explanation: 'ST elevasi V1-V4 menunjukkan infark dinding anterior, khas oklusi LAD (Left Anterior Descending) — teritori terbesar ventrikel kiri, sehingga membutuhkan reperfusi tercepat (door-to-balloon <90 menit untuk PCI primer) untuk membatasi luasnya nekrosis miokard.' },
    { id: 'uae-3',
      vignette: 'Pasien obesitas dengan leher besar, mendengkur keras, dan mengantuk berlebihan di siang hari datang untuk evaluasi.',
      options: ['Kuesioner STOP-BANG untuk skrining risiko obstructive sleep apnea (OSA), lanjut polisomnografi bila risiko tinggi', 'Tidak perlu evaluasi lebih lanjut, ini normal pada obesitas', 'Langsung CPAP tanpa konfirmasi diagnosis', 'Rujuk psikiatri untuk gangguan tidur primer'],
      answer: 0,
      explanation: 'STOP-BANG (Snoring, Tiredness, Observed apnea, Pressure/hipertensi, BMI, Age, Neck circumference, Gender) adalah alat skrining tervalidasi untuk OSA — penting di populasi dengan prevalensi obesitas tinggi karena OSA tidak terdiagnosis meningkatkan risiko kardiovaskular & metabolik jangka panjang; polisomnografi tetap baku emas konfirmasi diagnosis sebelum terapi CPAP dimulai.' },
    { id: 'uae-4',
      vignette: 'Pasien DM tipe 2 dengan eGFR 25 mL/min/1.73m² (gagal ginjal kronik stadium 4) sedang memakai metformin dosis penuh.',
      options: ['Lanjutkan metformin dosis penuh tanpa perubahan', 'Metformin dikontraindikasikan/perlu dihentikan pada eGFR <30 karena risiko asidosis laktat akibat akumulasi obat', 'Naikkan dosis metformin untuk kontrol gula lebih baik', 'Ganti ke insulin tidak pernah diperlukan pada CKD'],
      answer: 1,
      explanation: 'Metformin diekskresi ginjal tanpa dimetabolisme — pada gangguan ginjal berat obat terakumulasi, meningkatkan risiko asidosis laktat (metformin menghambat gluconeogenesis & rantai respirasi mitokondria, mendorong metabolisme anaerob). Pedoman umum: kontraindikasi pada eGFR <30, perlu penyesuaian dosis hati-hati pada 30-45.' },
    { id: 'uae-5',
      vignette: 'Pekerja konstruksi bekerja di luar ruangan pada suhu ambien >45°C mengalami kram otot, kelelahan, dan pusing, namun kesadaran tetap baik dan suhu tubuh inti 38.5°C.',
      options: ['Heat stroke — perlu pendinginan darurat segera', 'Heat exhaustion — pindahkan ke tempat sejuk, rehidrasi oral/IV, tanpa gangguan kesadaran', 'Serangan panas biasa, tidak perlu intervensi', 'Infark miokard akut'],
      answer: 1,
      explanation: 'Heat exhaustion (kelelahan panas) ditandai gejala sistemik akibat panas namun kesadaran & termoregulasi masih relatif terjaga (suhu <40°C, tanpa disfungsi neurologis berat) — berbeda dari heat stroke yang mengancam nyawa dengan gangguan kesadaran & suhu >40°C; regulasi keselamatan kerja UEA menekankan jam istirahat wajib saat suhu ekstrem untuk mencegah progresi ke heat stroke.' },
    { id: 'uae-6',
      vignette: 'Wanita 34 tahun trimester kedua dengan tekanan darah 148/95 mmHg tanpa proteinuria maupun gejala berat, riwayat tekanan darah normal sebelum kehamilan.',
      options: ['Hipertensi kronis', 'Hipertensi gestasional — pantau ketat untuk progresi ke preeklamsia', 'Preeklamsia berat, segera terminasi kehamilan', 'Normal, tidak perlu tindak lanjut'],
      answer: 1,
      explanation: 'Hipertensi baru muncul setelah 20 minggu kehamilan tanpa proteinuria/gejala berat diklasifikasikan hipertensi gestasional — memerlukan pemantauan ketat (tekanan darah, proteinuria, gejala) karena sebagian berkembang menjadi preeklamsia; berbeda dari hipertensi kronis yang sudah ada sebelum kehamilan atau sebelum 20 minggu.' },
    { id: 'uae-7',
      vignette: 'Anak usia 4 tahun ekspatriat yang baru tiba dari negara dengan cakupan vaksinasi rendah belum menerima imunisasi campak. Terjadi kontak erat dengan kasus campak terkonfirmasi 2 hari lalu.',
      options: ['Tidak perlu tindakan karena sudah terlambat', 'Berikan vaksin MMR pascapajanan dalam 72 jam bila belum ada kontraindikasi, sebagai profilaksis pascapajanan', 'Berikan antibiotik profilaksis', 'Karantina saja tanpa intervensi medis'],
      answer: 1,
      explanation: 'Vaksin MMR yang diberikan dalam 72 jam pascapajanan dapat mencegah atau meringankan penyakit campak pada individu rentan — penting dalam konteks populasi ekspatriat dengan riwayat vaksinasi bervariasi; imunoglobulin dipertimbangkan untuk kelompok risiko tinggi (bayi, imunokompromais) di luar jendela waktu vaksin.' },
    { id: 'uae-8',
      vignette: 'Pasien 50 tahun dengan nyeri dada saat aktivitas berat, faktor risiko multipel (merokok, diabetes, dislipidemia), hasil kalsium skor arteri koroner (CAC) sangat tinggi pada CT skrining.',
      options: ['CAC tinggi tidak relevan tanpa gejala', 'Skor CAC tinggi menandakan beban plak aterosklerotik signifikan — perlu stratifikasi risiko lanjut dan optimalisasi terapi pencegahan sekunder agresif', 'Cukup ulangi CT setahun lagi tanpa intervensi', 'Segera kateterisasi jantung pada semua kasus CAC tinggi tanpa gejala'],
      answer: 1,
      explanation: 'Skor kalsium arteri koroner (Agatston) yang tinggi mencerminkan beban aterosklerosis kalsifikasi kumulatif — pada pasien dengan gejala & faktor risiko multipel, ini memperkuat indikasi optimalisasi statin intensif, kontrol tekanan darah/glukosa, dan evaluasi lanjut (mis. stress test) sebelum keputusan invasif, bukan otomatis kateterisasi tanpa gejala iskemik jelas.' },
    { id: 'uae-9',
      vignette: 'Bayi prematur 32 minggu mengalami distres napas progresif segera setelah lahir, foto toraks menunjukkan gambaran ground-glass difus dan air bronchogram.',
      options: ['Transient tachypnea of the newborn (TTN)', 'Respiratory distress syndrome (RDS) akibat defisiensi surfaktan — pertimbangkan surfaktan eksogen & CPAP/ventilasi', 'Pneumonia bakterial neonatal', 'Hernia diafragmatika kongenital'],
      answer: 1,
      explanation: 'RDS pada bayi prematur disebabkan imaturitas produksi surfaktan oleh pneumosit tipe II, menyebabkan atelektasis alveolar difus & gambaran ground-glass klasik pada foto toraks — surfaktan eksogen intratrakeal menggantikan defisiensi ini, dikombinasi dukungan tekanan positif (CPAP/ventilasi mekanik) untuk menjaga alveoli tetap terbuka.' },
  ],
  singapore: [
    { id: 'sg-1',
      vignette: 'Pasien dengan demam 3 hari, nyeri retro-orbital, ruam, lalu tiba-tiba tampak membaik namun muncul nyeri perut hebat, muntah persisten, dan perdarahan mukosa — di negara endemis dengue seperti Singapura.',
      options: ['Ini fase pemulihan normal, pulangkan pasien', 'Warning signs dengue berat — perlu rawat inap & monitoring ketat', 'Diagnosis banding utama adalah malaria', 'Berikan aspirin untuk demam'],
      answer: 1,
      explanation: '"Warning signs" dengue (nyeri perut hebat, muntah persisten, perdarahan mukosa, letargi) tepat pada masa transisi ke fase kritis (biasanya hari 3-7) menandakan risiko kebocoran plasma (plasma leakage) akibat disfungsi endotel — memerlukan pemantauan hematokrit & cairan ketat. Aspirin dikontraindikasikan karena efek antiplatelet memperberat risiko perdarahan.' },
    { id: 'sg-2',
      vignette: 'Pria etnis Asia Selatan 50 tahun dengan lingkar pinggang besar namun BMI hanya 24 kg/m², profil lipid menunjukkan trigliserida tinggi dan HDL rendah.',
      options: ['Bukan risiko kardiovaskular karena BMI normal', 'Fenotipe "metabolically obese normal weight" — tetap berisiko tinggi sindrom metabolik', 'Perlu evaluasi untuk anoreksia', 'Cukup pantau tanpa intervensi'],
      answer: 1,
      explanation: 'Populasi Asia Selatan/Asia secara umum cenderung memiliki lebih banyak lemak viseral pada BMI yang sama dibanding populasi Barat — karena itu ambang batas obesitas Asia lebih rendah (WHO Asia-Pacific: overweight ≥23, obesitas ≥25 kg/m²) dan lingkar pinggang/rasio pinggang-pinggul menjadi penanda risiko metabolik yang lebih relevan dari BMI saja.' },
    { id: 'sg-3',
      vignette: 'Pekerja konstruksi dengan diabetes tipe 2 tidak terkontrol datang dengan demam, pneumonia berat, dan abses hati multipel di negara tropis Asia Tenggara.',
      options: ['Infeksi Burkholderia pseudomallei (melioidosis) — pertimbangkan terutama pada pasien diabetes dengan paparan tanah/air tergenang', 'Infeksi virus dengue', 'Tifoid tanpa komplikasi', 'Reaksi obat'],
      answer: 0,
      explanation: 'Melioidosis endemik di Asia Tenggara termasuk Singapura, disebabkan bakteri tanah/air Burkholderia pseudomallei — diabetes adalah faktor risiko terkuat (disfungsi neutrofil & makrofag), dan penyakit ini terkenal karena presentasinya sangat bervariasi ("the great mimicker"), termasuk abses multipel di paru, hati, atau limpa.' },
    { id: 'sg-4',
      vignette: 'Pasien lansia Tionghoa-Singapura dengan nyeri sendi lutut kronis, kaku setelah istirahat <30 menit, krepitasi, dan rontgen menunjukkan penyempitan celah sendi & osteofit.',
      options: ['Artritis reumatoid', 'Osteoartritis lutut — tatalaksana konservatif (penurunan berat badan, latihan penguatan, analgesik) sebagai lini pertama', 'Gout akut', 'Artritis septik'],
      answer: 1,
      explanation: 'Kekakuan pagi singkat (<30 menit), krepitasi, dan gambaran radiologis penyempitan celah sendi + osteofit adalah klasik osteoartritis (bedakan dari artritis reumatoid yang kekakuan paginya >1 jam dan simetris poliartikular) — tatalaksana lini pertama non-farmakologis (penurunan berat badan, penguatan otot kuadriseps) sebelum eskalasi ke analgesik/injeksi.' },
    { id: 'sg-5',
      vignette: 'Anak 5 tahun dengan riwayat atopi (eksim, rinitis alergi) datang dengan episode mengi berulang yang membaik dengan bronkodilator, terutama dipicu infeksi virus & aktivitas fisik.',
      options: ['Bronkiolitis akut satu kali episode', 'Asma anak — mulai kontroler (kortikosteroid inhalasi) bila episode sering/berat sesuai step terapi', 'Croup berulang', 'Aspirasi benda asing berulang'],
      answer: 1,
      explanation: 'Mengi berulang responsif bronkodilator pada anak dengan latar belakang atopik (march atopik: eksim → rinitis alergi → asma) sangat sugestif asma — kortikosteroid inhalasi dosis rendah adalah kontroler lini pertama untuk asma persisten guna mengurangi inflamasi jalan napas kronis, bukan hanya mengandalkan pereda saat serangan.' },
    { id: 'sg-6',
      vignette: 'Pekerja migran datang dengan demam intermiten, splenomegali, anemia, dan riwayat tinggal di area endemis di negara asalnya sebelum tiba di Singapura 3 bulan lalu.',
      options: ['Skrining malaria (apus darah tebal-tipis atau rapid diagnostic test) harus dipertimbangkan mengingat riwayat perjalanan/asal endemis', 'Malaria tidak mungkin karena sudah 3 bulan di Singapura', 'Cukup terapi antipiretik simtomatik tanpa investigasi lanjut', 'Diagnosis pasti adalah leukemia tanpa pemeriksaan lanjut'],
      answer: 0,
      explanation: 'Malaria (terutama P. vivax/ovale yang dapat relaps dari hipnozoit hati berbulan-bulan kemudian) harus selalu dipikirkan pada demam dengan riwayat asal/perjalanan endemis, berapa pun lamanya sejak kedatangan — apus darah tebal-tipis tetap baku emas meski RDT dapat mempercepat skrining awal.' },
    { id: 'sg-7',
      vignette: 'Pasien lansia dengan fibrilasi atrium non-valvular, CHA2DS2-VASc score 4, sedang dipertimbangkan terapi antikoagulan untuk pencegahan stroke.',
      options: ['Aspirin monoterapi sudah cukup untuk skor risiko ini', 'Antikoagulan oral (mis. NOAC atau warfarin dengan target INR) diindikasikan karena skor CHA2DS2-VASc ≥2 menandakan risiko stroke bermakna', 'Tidak perlu terapi apapun karena usia lanjut meningkatkan risiko perdarahan', 'Ablasi kateter adalah satu-satunya pilihan pada skor ini'],
      answer: 1,
      explanation: 'CHA2DS2-VASc ≥2 pada pria (atau ≥3 pada wanita) mengindikasikan antikoagulasi oral untuk pencegahan stroke pada fibrilasi atrium non-valvular — NOAC (mis. apixaban, dabigatran) umumnya lebih disukai dibanding warfarin karena profil keamanan & tanpa perlu pemantauan INR rutin, kecuali kontraindikasi spesifik (mis. katup mekanik, stenosis mitral berat).' },
    { id: 'sg-8',
      vignette: 'Bayi baru lahir dari ibu carrier HBsAg positif. Rencana pencegahan penularan vertikal hepatitis B perlu disiapkan segera setelah lahir.',
      options: ['Vaksin hepatitis B saja tanpa imunoglobulin', 'Vaksin hepatitis B + imunoglobulin hepatitis B (HBIG) diberikan dalam 12-24 jam pertama kehidupan', 'Tunda vaksinasi hingga usia 6 bulan', 'Tidak perlu profilaksis jika ibu asimtomatik'],
      answer: 1,
      explanation: 'Kombinasi vaksin hepatitis B aktif + HBIG (imunisasi pasif-aktif) dalam 12-24 jam pertama kehidupan memberikan proteksi >90% terhadap transmisi vertikal hepatitis B dari ibu HBsAg-positif — HBIG memberikan proteksi segera sementara vaksin membangun imunitas jangka panjang, keduanya krusial karena jendela waktu pemberian sangat sempit.' },
    { id: 'sg-9',
      vignette: 'Pasien dengan riwayat merokok lama datang dengan batuk kronis produktif, sesak progresif, dan spirometri menunjukkan FEV1/FVC <0.7 pasca-bronkodilator, tanpa reversibilitas signifikan.',
      options: ['Asma bronkial', 'Penyakit Paru Obstruktif Kronik (PPOK) — hentikan rokok, mulai bronkodilator kerja panjang sesuai derajat gejala', 'Bronkitis akut viral', 'Fibrosis paru idiopatik'],
      answer: 1,
      explanation: 'Rasio FEV1/FVC <0.7 pasca-bronkodilator tanpa reversibilitas signifikan pada perokok kronis adalah kriteria diagnostik PPOK (GOLD) — penghentian rokok adalah intervensi tunggal paling efektif memperlambat penurunan fungsi paru, dengan bronkodilator kerja panjang (LABA/LAMA) sebagai terapi farmakologis inti sesuai derajat gejala & risiko eksaserbasi.' },
  ],
  japan: [
    { id: 'jpn-1',
      vignette: 'Anak 2 tahun dengan demam ≥5 hari, konjungtivitis bilateral non-purulen, ruam polimorfik, perubahan ekstremitas (edema/eritema telapak), bibir merah pecah-pecah, dan limfadenopati servikal.',
      options: ['Demam skarlatina', 'Penyakit Kawasaki', 'Campak (rubeola)', 'Sindrom Steven-Johnson'],
      answer: 1,
      explanation: 'Penyakit Kawasaki (pertama dideskripsikan oleh Dr. Tomisaku Kawasaki di Jepang, 1967) adalah vaskulitis akut pembuluh darah sedang, terutama arteri koroner — kriteria diagnostik utama: demam ≥5 hari + minimal 4 dari 5 kriteria (konjungtivitis, perubahan mukosa oral, ruam, perubahan ekstremitas, limfadenopati servikal). Tatalaksana IVIG dini krusial mencegah aneurisma koroner.' },
    { id: 'jpn-2',
      vignette: 'Pasien dengan hepatitis B kronis, HBeAg positif, DNA HBV tinggi, ALT meningkat — negara dengan riwayat program skrining & vaksinasi hepatitis B nasional yang luas.',
      options: ['Tidak perlu terapi karena asimtomatik', 'Pertimbangkan terapi antivirus (mis. entecavir/tenofovir) untuk menekan replikasi virus & mencegah progresi ke sirosis/HCC', 'Cukup pemantauan tahunan tanpa terapi', 'Transplantasi hati segera'],
      answer: 1,
      explanation: 'Analog nukleos(t)ida seperti entecavir/tenofovir menghambat reverse transcriptase HBV, menekan replikasi virus jangka panjang — pada fase HBeAg-positif dengan ALT & DNA tinggi (fase imun aktif), terapi menurunkan risiko progresi ke sirosis dan karsinoma hepatoseluler (HCC), komplikasi jangka panjang utama hepatitis B kronis.' },
    { id: 'jpn-3',
      vignette: 'Pasien dengan tukak lambung berulang, hasil biopsi & tes urease menunjukkan infeksi Helicobacter pylori positif.',
      options: ['Terapi eradikasi triple/quadruple therapy (PPI + 2 antibiotik, mis. amoksisilin+klaritromisin)', 'Cukup PPI tunggal jangka panjang tanpa antibiotik', 'Tidak perlu eradikasi jika asimtomatik sementara', 'Operasi gastrektomi sebagai lini pertama'],
      answer: 0,
      explanation: 'Eradikasi H. pylori (PPI + kombinasi antibiotik selama 7-14 hari) adalah standar tatalaksana tukak peptikum terkait infeksi ini — penting khususnya di Jepang yang punya program skrining & eradikasi nasional aktif karena H. pylori adalah faktor risiko utama kanker lambung, keganasan dengan insidensi historis tinggi di negara ini.' },
    { id: 'jpn-4',
      vignette: 'Populasi Jepang yang menua pesat menjadikan skrining demensia rutin bagian penting layanan primer geriatri. Pasien 78 tahun menunjukkan penurunan memori progresif, kesulitan aktivitas sehari-hari, MMSE 18/30.',
      options: ['Penuaan normal, tidak perlu evaluasi lanjut', 'Kemungkinan demensia (mis. Alzheimer) — lanjutkan evaluasi penyebab reversibel (fungsi tiroid, B12, neuroimaging) sebelum diagnosis definitif', 'Depresi mayor semata tanpa perlu skrining kognitif', 'Delirium akut, cukup observasi'],
      answer: 1,
      explanation: 'MMSE <24 dengan gangguan fungsional aktivitas harian mengarah ke demensia, namun pedoman geriatri selalu mewajibkan penyingkiran penyebab reversibel (hipotiroidisme, defisiensi B12, hidrosefalus tekanan normal) sebelum menegakkan diagnosis Alzheimer/demensia vaskular definitif — penting di Jepang mengingat populasi lansia terbesar dunia proporsional.' },
    { id: 'jpn-5',
      vignette: 'Pasien lansia dengan riwayat gastrektomi parsial akibat kanker lambung menunjukkan anemia makrositik beberapa tahun kemudian, disertai gejala neurologis (parestesia, gangguan gaya berjalan).',
      options: ['Anemia defisiensi besi akibat perdarahan kronis', 'Defisiensi vitamin B12 akibat hilangnya faktor intrinsik pasca-gastrektomi — perlu suplementasi B12 parenteral seumur hidup', 'Anemia penyakit kronis', 'Talasemia laten'],
      answer: 1,
      explanation: 'Gastrektomi menghilangkan sel parietal penghasil faktor intrinsik yang esensial untuk absorpsi B12 di ileum terminal — defisiensi B12 muncul bertahun-tahun kemudian (cadangan hati besar) dengan anemia makrositik + gejala neurologis (degenerasi kombinasi subakut medula spinalis) khas, memerlukan suplementasi parenteral karena absorpsi oral tidak lagi adekuat.' },
    { id: 'jpn-6',
      vignette: 'Pasien muda dengan nyeri tenggorokan berat, demam tinggi, kesulitan menelan air liur sendiri (drooling), suara teredam ("hot potato voice"), dan tampak toksik.',
      options: ['Faringitis viral biasa', 'Epiglotitis akut — kondisi darurat jalan napas, hindari manipulasi orofaring berlebihan, siapkan jalan napas definitif', 'Tonsilitis kronik', 'Refluks laringofaringeal'],
      answer: 1,
      explanation: 'Drooling + suara teredam + distres pada pasien toksik adalah tanda bahaya epiglotitis akut (klasik akibat H. influenzae tipe b, meski insidensi menurun pasca-vaksinasi Hib) — pemeriksaan orofaring paksa dapat memicu obstruksi jalan napas total lewat spasme laring, sehingga tatalaksana prioritas mengamankan jalan napas di lingkungan terkontrol (kamar operasi) sebelum investigasi lanjut.' },
    { id: 'jpn-7',
      vignette: 'Pasien dengan riwayat konsumsi ikan laut mentah (sashimi) datang dengan nyeri epigastrium akut mendadak, mual muntah, beberapa jam setelah makan.',
      options: ['Keracunan makanan bakterial biasa', 'Anisakiasis — infestasi larva cacing Anisakis dari ikan laut mentah, sering memerlukan ekstraksi endoskopik', 'Apendisitis akut', 'Alergi makanan sederhana'],
      answer: 1,
      explanation: 'Anisakiasis akibat larva Anisakis simplex dari ikan laut mentah (relevan khususnya di budaya kuliner sashimi/sushi Jepang) menyebabkan nyeri epigastrium akut hebat saat larva menembus mukosa lambung — endoskopi diagnostik sekaligus terapeutik (ekstraksi larva langsung) adalah tatalaksana utama.' },
    { id: 'jpn-8',
      vignette: 'Pasien lansia dengan riwayat gempa bumi/bencana alam baru-baru ini mengalami nyeri tungkai bengkak setelah berjam-jam duduk statis di tempat pengungsian, kemudian sesak napas mendadak.',
      options: ['Selulitis tungkai', 'Trombosis vena dalam (DVT) dengan kemungkinan emboli paru — kondisi terkait imobilisasi lama pasca-bencana ("economy class syndrome")', 'Ruptur tendon Achilles', 'Gout akut pergelangan kaki'],
      answer: 1,
      explanation: 'Imobilisasi lama di tempat pengungsian pasca-bencana adalah faktor risiko dikenal DVT (dijuluki "economy class syndrome" karena kemiripan dengan imobilisasi penerbangan panjang) — progresi ke sesak napas mendadak mengindikasikan kemungkinan emboli paru, komplikasi yang dilaporkan meningkat pasca-gempa besar di Jepang, mendorong protokol pencegahan tromboemboli di pengungsian.' },
    { id: 'jpn-9',
      vignette: 'Bayi ASI eksklusif tanpa suplementasi mengalami perdarahan intrakranial mendadak pada usia 6 minggu, profil koagulasi menunjukkan PT memanjang signifikan.',
      options: ['Hemofilia A', 'Defisiensi vitamin K (late-onset vitamin K deficiency bleeding) — pentingnya profilaksis vitamin K saat lahir', 'Trombositopenia imun', 'Penyakit von Willebrand'],
      answer: 1,
      explanation: 'ASI rendah kandungan vitamin K, dan tanpa profilaksis injeksi vitamin K saat lahir bayi berisiko perdarahan defisiensi vitamin K onset lambat (minggu ke-2 hingga ke-12), termasuk perdarahan intrakranial serius — inilah dasar rekomendasi universal pemberian vitamin K intramuskular rutin segera setelah lahir di seluruh dunia termasuk Jepang.' },
  ],
  taiwan: [
    { id: 'tw-1',
      vignette: 'Taiwan dikenal sebagai salah satu contoh sukses program vaksinasi hepatitis B universal bayi baru lahir sejak 1984, menurunkan drastis insidensi karsinoma hepatoseluler pada generasi setelahnya.',
      options: ['Vaksin hepatitis B tidak berhubungan dengan risiko HCC', 'Vaksinasi hepatitis B universal mengurangi HCC karena mencegah infeksi kronis yang menjadi pemicu utama karsinogenesis hepatosit', 'HCC di Taiwan terutama disebabkan alkohol, bukan virus', 'Program ini terbukti tidak efektif menurunkan HCC'],
      answer: 1,
      explanation: 'Infeksi HBV kronis adalah penyebab utama HCC secara global lewat integrasi genom virus ke DNA hepatosit & inflamasi kronis berulang (siklus nekrosis-regenerasi meningkatkan mutasi). Studi kohort Taiwan pasca-vaksinasi universal (Chang et al., NEJM 1997) menjadi salah satu bukti epidemiologis terkuat bahwa vaksin virus dapat mencegah kanker.' },
    { id: 'tw-2',
      vignette: 'Anak dengan demam, luka/vesikel di mulut, telapak tangan, dan telapak kaki, dikonfirmasi infeksi Enterovirus 71 selama wabah musiman.',
      options: ['Hand, foot, and mouth disease (HFMD)', 'Varicella (cacar air)', 'Sifilis kongenital', 'Impetigo bulosa'],
      answer: 0,
      explanation: 'HFMD klasik disebabkan Coxsackievirus A16 atau Enterovirus 71 — EV71 penting secara klinis karena berpotensi menyebabkan komplikasi neurologis berat (ensefalitis batang otak, edema paru neurogenik) terutama pada anak kecil, dan menjadi perhatian kesehatan masyarakat besar di kawasan Asia Timur termasuk Taiwan.' },
    { id: 'tw-3',
      vignette: 'Bayi baru lahir menjalani skrining wajib nasional yang mencakup pemeriksaan enzim eritrosit tertentu, karena defisiensinya cukup umum di populasi Asia Timur & Tenggara dan berisiko menyebabkan kernikterus bila tidak diketahui.',
      options: ['Skrining fenilketonuria (PKU) saja sudah cukup', 'Skrining G6PD (glukosa-6-fosfat dehidrogenase) — penting mencegah hemolisis & hiperbilirubinemia berat pada neonatus', 'Skrining ini tidak diperlukan secara rutin di mana pun', 'Skrining hanya untuk anak laki-laki karena X-linked'],
      answer: 1,
      explanation: 'Defisiensi G6PD adalah kelainan enzim X-linked yang relatif prevalen di populasi Asia — skrining neonatus penting karena neonatus defisien G6PD berisiko hemolisis akut & hiperbilirubinemia berat (ikterus neonatorum ekstrem) yang bisa berujung kernikterus bila terlambat dideteksi; meski X-linked, perempuan carrier heterozigot juga bisa bergejala akibat lyonization, sehingga skrining tetap dilakukan pada kedua jenis kelamin.' },
    { id: 'tw-4',
      vignette: 'Pasien lansia dengan riwayat merokok & konsumsi sirih (betel nut) bertahun-tahun datang dengan lesi putih tidak dapat dikerok di mukosa bukal yang tidak nyeri.',
      options: ['Kandidiasis oral', 'Leukoplakia — lesi prakanker terkait konsumsi sirih & rokok, perlu biopsi untuk menyingkirkan displasia/karsinoma sel skuamosa', 'Lichen planus oral', 'Stomatitis aftosa'],
      answer: 1,
      explanation: 'Leukoplakia (lesi putih tidak dapat dikerok) sangat terkait konsumsi sirih (areca nut/betel quid) yang prevalen di Taiwan dan sebagian Asia — berisiko transformasi maligna signifikan, terutama kombinasi dengan rokok & alkohol; biopsi wajib untuk menyingkirkan displasia atau karsinoma sel skuamosa oral yang tersembunyi.' },
    { id: 'tw-5',
      vignette: 'Pasien dengan riwayat keluarga kanker kolorektal onset muda (multipel generasi, usia <50 tahun) menjalani konseling genetik untuk sindrom Lynch.',
      options: ['Sindrom Lynch tidak memerlukan skrining lebih awal dari populasi umum', 'Sindrom Lynch (HNPCC) meningkatkan risiko kanker kolorektal & endometrium onset muda — kolonoskopi skrining dimulai lebih awal dan lebih sering', 'Hanya kanker kolorektal yang berisiko, organ lain tidak terpengaruh', 'Skrining genetik tidak relevan tanpa gejala saat ini'],
      answer: 1,
      explanation: 'Sindrom Lynch (mutasi gen mismatch repair seperti MLH1/MSH2) meningkatkan risiko kanker kolorektal, endometrium, ovarium, dan lainnya pada usia lebih muda dari populasi umum — pedoman merekomendasikan kolonoskopi skrining dimulai jauh lebih awal (sering usia 20-25) dan interval lebih pendek dibanding skrining populasi umum.' },
    { id: 'tw-6',
      vignette: 'Pekerja pabrik dengan paparan kronis debu logam berat datang dengan nyeri perut kolik, konstipasi, anemia mikrositik, dan garis biru-hitam di gusi (Burton line).',
      options: ['Anemia defisiensi besi biasa', 'Keracunan timbal (plumbism) kronis — perlu pemeriksaan kadar timbal darah dan kelasi bila tinggi', 'Porfiria akut intermiten', 'Intoksikasi merkuri'],
      answer: 1,
      explanation: 'Trias nyeri kolik abdomen + konstipasi + garis Burton pada gusi dengan anemia mikrositik pada pekerja terpapar logam berat sangat sugestif keracunan timbal kronis — timbal menghambat enzim sintesis heme (ALA dehidratase, ferrochelatase), menyebabkan anemia dan gejala neurologis/gastrointestinal; kelasi (mis. EDTA, DMSA) diindikasikan pada kadar tinggi bergejala.' },
    { id: 'tw-7',
      vignette: 'Pasien dengan riwayat topan/banjir besar baru-baru ini datang dengan demam, mialgia berat, ikterus, dan gagal ginjal akut setelah kontak air banjir yang terkontaminasi.',
      options: ['Demam dengue', 'Leptospirosis — terkait paparan air/tanah terkontaminasi urin hewan pengerat pasca-banjir, terapi doksisiklin/penisilin', 'Hepatitis A akut', 'Malaria'],
      answer: 1,
      explanation: 'Leptospirosis (Weil disease pada bentuk berat) klasik muncul setelah paparan air banjir terkontaminasi urin hewan pengerat — trias demam, ikterus, dan gagal ginjal akut (sindrom Weil) adalah presentasi berat yang memerlukan antibiotik segera (penisilin IV pada kasus berat, doksisiklin pada kasus ringan) karena mortalitas tinggi bila terlambat diobati.' },
    { id: 'tw-8',
      vignette: 'Bayi baru lahir tampak sianosis sentral tidak membaik dengan pemberian oksigen 100%, ekokardiografi menunjukkan aorta keluar dari ventrikel kanan dan arteri pulmonalis dari ventrikel kiri.',
      options: ['Tetralogy of Fallot', 'Transposisi arteri besar (Transposition of the Great Arteries) — perlu prostaglandin E1 untuk menjaga duktus arteriosus paten sebelum koreksi bedah', 'Defek septum ventrikel sederhana', 'Koarktasio aorta'],
      answer: 1,
      explanation: 'Transposisi arteri besar menciptakan dua sirkulasi paralel terpisah (bukan seri) yang inkompatibel dengan kehidupan tanpa percampuran darah — duktus arteriosus paten (dijaga terbuka dengan prostaglandin E1) atau foramen ovale menjadi jalur pencampuran darah vital sementara menunggu koreksi bedah definitif (arterial switch operation).' },
    { id: 'tw-9',
      vignette: 'Pasien lansia dengan gangguan gerak progresif: tremor istirahat, bradikinesia, rigiditas roda gigi, dan langkah kecil-kecil (shuffling gait), respons baik terhadap levodopa.',
      options: ['Tremor esensial', 'Penyakit Parkinson idiopatik — levodopa/carbidopa sebagai terapi lini pertama untuk gejala motorik', 'Stroke lakunar multipel', 'Hidrosefalus tekanan normal'],
      answer: 1,
      explanation: 'Trias tremor istirahat + bradikinesia + rigiditas roda gigi dengan respons dramatis terhadap levodopa adalah karakteristik klasik penyakit Parkinson idiopatik (degenerasi neuron dopaminergik substansia nigra pars compacta) — populasi menua di Taiwan menjadikan diagnosis dini & tatalaksana gejala motorik prioritas layanan geriatri neurologi.' },
  ],
  china: [
    { id: 'cn-1',
      vignette: 'Pasien TB paru baru terdiagnosis (kasus baru, belum pernah terapi), sputum BTA positif.',
      options: ['Monoterapi rifampisin', 'Regimen 4 obat (isoniazid, rifampisin, pirazinamid, etambutol) fase intensif 2 bulan, dilanjutkan fase lanjutan', 'Hanya observasi, TB paru bisa sembuh sendiri', 'Streptomisin tunggal seumur hidup'],
      answer: 1,
      explanation: 'Regimen standar TB kasus baru (WHO, diadopsi luas termasuk program nasional Tiongkok yang menanggung beban TB tinggi secara global): fase intensif 2 bulan HRZE menekan populasi basil secara cepat & mencegah resistensi, dilanjutkan fase lanjutan 4 bulan HR untuk mengeliminasi basil persisten/dorman.' },
    { id: 'cn-2',
      vignette: 'Wabah musiman pada anak-anak: demam, vesikel oral-tangan-kaki, sebagian kecil berkembang komplikasi neurologis berat.',
      options: ['Rubella', 'Enterovirus 71 (hand, foot, mouth disease berat)', 'Difteri', 'Pertusis'],
      answer: 1,
      explanation: 'EV71 adalah penyebab HFMD yang berisiko komplikasi neurologis serius (rhombencephalitis, edema paru neurogenik) — Tiongkok mengalami wabah besar berulang, mendorong pengembangan vaksin EV71 inaktivasi yang mulai digunakan di beberapa provinsi.' },
    { id: 'cn-3',
      vignette: 'Pasien dewasa dengan tekanan darah terukur 145/92 mmHg pada dua kunjungan terpisah, tanpa gejala akut.',
      options: ['Belum memenuhi kriteria hipertensi, tidak perlu tindak lanjut', 'Hipertensi — mulai modifikasi gaya hidup (diet rendah garam, aktivitas fisik, berat badan) sebagai lini pertama, farmakoterapi bila target tidak tercapai atau risiko tinggi', 'Langsung berikan 3 obat antihipertensi kombinasi sejak awal pada semua kasus', 'Rawat inap wajib untuk semua kasus hipertensi baru'],
      answer: 1,
      explanation: 'Ambang diagnosis hipertensi klasik ≥140/90 mmHg pada pengukuran berulang. Pendekatan awal standar adalah modifikasi gaya hidup (efektif menurunkan TD beberapa mmHg dan memperbaiki profil risiko metabolik secara keseluruhan), dengan farmakoterapi ditambahkan berdasarkan derajat peningkatan TD, kerusakan organ target, dan risiko kardiovaskular total pasien.' },
    { id: 'cn-4',
      vignette: 'Pasien lansia di daerah pedesaan dengan riwayat konsumsi makanan asin & fermentasi tinggi datang dengan penurunan berat badan, anemia, dan gastroskopi menunjukkan massa ulseratif di antrum lambung, biopsi mengonfirmasi adenokarsinoma.',
      options: ['Ulkus peptikum jinak biasa', 'Adenokarsinoma lambung — faktor risiko termasuk H. pylori kronis, diet tinggi garam/nitrat, dan riwayat keluarga', 'Limfoma MALT lambung', 'GIST (Gastrointestinal Stromal Tumor)'],
      answer: 1,
      explanation: 'Kanker lambung memiliki insidensi historis tinggi di Asia Timur termasuk Tiongkok, berkaitan dengan infeksi H. pylori kronis, diet tinggi garam & makanan fermentasi/asap (nitrosamin), dan faktor genetik — biopsi endoskopik adalah wajib pada setiap lesi ulseratif mencurigakan untuk membedakan keganasan dari ulkus jinak, karena gambaran makroskopik saja tidak selalu dapat membedakan keduanya.' },
    { id: 'cn-5',
      vignette: 'Pekerja tambang batu bara dengan riwayat paparan debu silika bertahun-tahun datang dengan sesak progresif, foto toraks menunjukkan nodul kecil difus terutama di lobus atas.',
      options: ['Asma okupasional', 'Silikosis — penyakit paru akibat inhalasi kronis partikel silika, tidak reversibel, fokus pada pencegahan paparan lebih lanjut', 'Pneumonia atipikal', 'Edema paru kardiogenik'],
      answer: 1,
      explanation: 'Silikosis adalah pneumokoniosis akibat inhalasi kronis debu silika kristalin (umum pada penambang, pekerja batu) — partikel silika memicu respons inflamasi & fibrosis progresif nodular terutama lobus atas; tidak ada terapi kuratif untuk fibrosis yang sudah terjadi, sehingga pencegahan paparan (APD, ventilasi) adalah fokus kesehatan kerja utama.' },
    { id: 'cn-6',
      vignette: 'Anak dengan demam tinggi mendadak 3-5 hari yang tiba-tiba turun, diikuti munculnya ruam makulopapular pada tubuh yang tidak gatal, tetap tampak aktif & sehat.',
      options: ['Campak', 'Roseola infantum (exanthem subitum) — infeksi HHV-6/7, ruam muncul setelah demam turun', 'Demam berdarah dengue', 'Rubella'],
      answer: 1,
      explanation: 'Pola khas roseola: demam tinggi mendadak selama beberapa hari yang turun tiba-tiba, DIIKUTI ruam (bukan bersamaan dengan demam seperti campak) — disebabkan HHV-6 (kadang HHV-7), umumnya pada anak <2 tahun, prognosis jinak dengan tatalaksana suportif; anak biasanya tetap tampak relatif sehat meski demam tinggi ("looks well despite high fever").' },
    { id: 'cn-7',
      vignette: 'Pasien dengan riwayat hepatitis B kronis tanpa terapi antivirus, USG rutin menunjukkan nodul hati baru 2cm dengan pola enhancement arterial dan washout vena porta pada CT triphasic.',
      options: ['Hemangioma hati', 'Karsinoma hepatoseluler (HCC) — pola "arterial enhancement dengan washout" sangat spesifik pada pasien risiko tinggi (sirosis/hepatitis B kronis)', 'Abses hati piogenik', 'Adenoma hepatoseluler jinak'],
      answer: 1,
      explanation: 'Pola pencitraan "arterial phase hyperenhancement dengan washout fase vena porta/delayed" pada pasien risiko tinggi (hepatitis B kronis, sirosis) memenuhi kriteria diagnostik non-invasif HCC (LI-RADS/AASLD) tanpa perlu biopsi konfirmasi pada banyak kasus — mencerminkan neovaskularisasi arterial tumor yang khas berbeda dari lesi jinak seperti hemangioma (pola pengisian sentripetal progresif berbeda).' },
    { id: 'cn-8',
      vignette: 'Wanita usia reproduktif dengan siklus haid tidak teratur, hirsutisme, jerawat, dan USG ovarium menunjukkan banyak folikel kecil perifer ("string of pearls").',
      options: ['Endometriosis', 'Sindrom ovarium polikistik (PCOS) — tatalaksana meliputi modifikasi gaya hidup, kontrasepsi hormonal, atau metformin sesuai tujuan (kontrol siklus vs kesuburan)', 'Kista ovarium fungsional sederhana', 'Kanker ovarium'],
      answer: 1,
      explanation: 'Kriteria Rotterdam PCOS memerlukan 2 dari 3: oligo/anovulasi, hiperandrogenisme klinis/biokimia, dan morfologi ovarium polikistik pada USG — resistensi insulin sering mendasari patofisiologi, menjelaskan mengapa metformin dan penurunan berat badan efektif memperbaiki keteraturan siklus dan profil metabolik pada banyak pasien.' },
    { id: 'cn-9',
      vignette: 'Pasien lansia dengan nyeri dada retrosternal terbakar setelah makan, memburuk saat berbaring, endoskopi menunjukkan esofagitis erosif, biopsi menyingkirkan Barrett esophagus.',
      options: ['Angina pektoris stabil', 'Penyakit refluks gastroesofageal (GERD) dengan esofagitis erosif — PPI dosis penuh sebagai terapi lini pertama', 'Akalasia esofagus', 'Spasme esofagus difus'],
      answer: 1,
      explanation: 'Nyeri retrosternal terbakar terkait makan & posisi berbaring, dikonfirmasi esofagitis erosif endoskopik, adalah GERD simtomatik klasik — PPI (menghambat pompa proton H+/K+-ATPase sel parietal) adalah terapi paling efektif menekan asam lambung & menyembuhkan esofagitis; skrining Barrett penting pada GERD kronis karena risiko metaplasia intestinal prakanker.' },
  ],
  europe_de: [
    { id: 'de-1',
      vignette: 'Pasien dengan demam, hipotensi, takikardia, laktat serum meningkat, dan kecurigaan kuat sumber infeksi — dievaluasi menggunakan kriteria Sepsis-3 (qSOFA/SOFA).',
      options: ['Sepsis didefinisikan cukup dengan SIRS ≥2 kriteria (definisi lama)', 'Sepsis-3 mendefinisikan sepsis sebagai disfungsi organ mengancam nyawa akibat respons host yang tidak teregulasi terhadap infeksi, dinilai lewat perubahan skor SOFA ≥2', 'Sepsis hanya bisa didiagnosis dengan kultur darah positif', 'qSOFA menggantikan kebutuhan pemberian antibiotik segera'],
      answer: 1,
      explanation: 'Konsensus Sepsis-3 (2016, dipakai luas termasuk pedoman Jerman/Eropa) meninggalkan kriteria SIRS yang terlalu sensitif-nonspesifik, menggantinya dengan disfungsi organ (∆SOFA≥2) sebagai inti definisi — mencerminkan pemahaman patofisiologi bahwa sepsis adalah kegagalan regulasi imun-host, bukan sekadar infeksi + inflamasi.' },
    { id: 'de-2',
      vignette: 'Dalam ujian Kenntnisprüfung, kandidat ditanya mengenai dasar hukum informed consent sebelum tindakan medis invasif di sistem kesehatan Jerman.',
      options: ['Persetujuan lisan tanpa dokumentasi selalu cukup secara hukum', 'Informed consent memerlukan penjelasan risiko, manfaat, dan alternatif yang dipahami pasien, didokumentasikan, sebelum tindakan non-darurat', 'Informed consent hanya diperlukan untuk tindakan bedah mayor', 'Dokter dapat memutuskan tanpa persetujuan pasien jika demi "kebaikan pasien"'],
      answer: 1,
      explanation: 'Prinsip informed consent (Aufklärungspflicht) dalam hukum kedokteran Jerman mewajibkan penjelasan komprehensif & terdokumentasi sebelum tindakan non-darurat — kegagalan memenuhi ini dapat dianggap sebagai pelanggaran (Körperverletzung) terlepas dari keberhasilan medis tindakannya, mencerminkan prinsip otonomi pasien di atas paternalisme medis.' },
    { id: 'de-3',
      vignette: 'Pasien dengan fibrilasi atrium memakai dabigatran (antikoagulan oral non-vitamin K) mengalami perdarahan intrakranial dan memerlukan reversal segera.',
      options: ['Vitamin K intravena', 'Idarucizumab — antibodi monoklonal yang mengikat dabigatran secara spesifik & langsung menetralisir efeknya', 'Protamin sulfat', 'Tidak ada agen reversal, hanya terapi suportif'],
      answer: 1,
      explanation: 'Idarucizumab adalah fragmen antibodi manusiawi yang berikatan dengan afinitas sangat tinggi terhadap dabigatran (jauh lebih tinggi dari afinitas dabigatran ke trombin), menetralisir efek antikoagulannya dalam hitungan menit — berbeda dari vitamin K (hanya efektif untuk antagonis vitamin K seperti warfarin) atau protamin (reversal heparin).' },
    { id: 'de-4',
      vignette: 'Pasien 70 tahun dengan riwayat merokok panjang, batuk darah, penurunan berat badan, dan CT toraks menunjukkan massa spikulasi di lobus atas kanan disertai limfadenopati mediastinum.',
      options: ['Pneumonia dengan efusi parapneumonik', 'Kecurigaan kuat karsinoma paru — perlu biopsi (bronkoskopi/CT-guided) dan staging lengkap sebelum rencana terapi', 'Tuberkulosis paru reaktivasi tanpa perlu biopsi', 'Aspergilloma'],
      answer: 1,
      explanation: 'Massa spikulasi lobus atas + limfadenopati mediastinum pada perokok kronis dengan hemoptisis & penurunan berat badan sangat mencurigakan keganasan paru — biopsi histopatologis wajib untuk konfirmasi jenis sel & staging (TNM) menentukan pilihan terapi (bedah, kemoterapi, radioterapi, atau targeted therapy berdasarkan profil molekular).' },
    { id: 'de-5',
      vignette: 'Kandidat Kenntnisprüfung ditanya mengenai kewajiban dokter terkait Schweigepflicht (kerahasiaan medis) ketika polisi meminta informasi rekam medis pasien tanpa perintah pengadilan.',
      options: ['Berikan informasi lengkap karena diminta aparat hukum', 'Kerahasiaan medis (Schweigepflicht) tetap berlaku — informasi hanya dapat diberikan dengan persetujuan pasien atau perintah pengadilan yang sah, kecuali pengecualian hukum spesifik (mis. ancaman nyawa serius)', 'Dokter wajib menolak seluruh permintaan hukum tanpa pengecualian', 'Kerahasiaan hanya berlaku untuk pasien psikiatri'],
      answer: 1,
      explanation: 'Schweigepflicht adalah kewajiban hukum kerahasiaan medis yang kuat dalam hukum Jerman (§203 StGB) — pengungkapan tanpa persetujuan pasien memerlukan dasar hukum jelas (perintah pengadilan, kewajiban pelaporan spesifik, atau situasi bahaya nyawa mendesak/Rechtfertigender Notstand), bukan sekadar permintaan otoritas penegak hukum tanpa proses hukum yang sesuai.' },
    { id: 'de-6',
      vignette: 'Pasien dengan gagal jantung kronis dengan fraksi ejeksi tereduksi (HFrEF, EF 30%) sudah dalam terapi ACE inhibitor, beta-blocker, dan diuretik, namun tetap simtomatik.',
      options: ['Tidak ada terapi tambahan yang terbukti bermanfaat', 'Pertimbangkan penambahan antagonis reseptor mineralokortikoid (mis. spironolakton) dan/atau SGLT2 inhibitor sesuai pedoman terapi kuadrupel HFrEF terkini', 'Hentikan seluruh terapi karena tidak efektif', 'Transplantasi jantung sebagai langkah berikutnya tanpa optimalisasi obat dulu'],
      answer: 1,
      explanation: 'Pedoman ESC/AHA terkini merekomendasikan "terapi kuadrupel" HFrEF: ACE-I/ARNI, beta-blocker, antagonis reseptor mineralokortikoid, dan SGLT2 inhibitor — kombinasi keempatnya secara bermakna menurunkan mortalitas & rawat inap dibanding kombinasi tradisional 2-3 obat, dan diinisiasi bertahap cepat bukan ditunda hingga eskalasi ke transplantasi.' },
    { id: 'de-7',
      vignette: 'Bayi dengan riwayat keterlambatan tumbuh kembang, hipotonia, wajah datar, lipatan epikantus, dan celah simian pada telapak tangan; kariotipe menunjukkan trisomi 21.',
      options: ['Sindrom Edwards (trisomi 18)', 'Sindrom Down (trisomi 21) — perlu skrining rutin untuk komorbiditas terkait (jantung kongenital, hipotiroid, gangguan pendengaran)', 'Sindrom Patau (trisomi 13)', 'Sindrom Turner'],
      answer: 1,
      explanation: 'Trisomi 21 (sindrom Down) memiliki fenotipe karakteristik (hipotonia, epikantus, simian crease) dan memerlukan skrining komorbiditas terstruktur seumur hidup — defek jantung kongenital (terutama AV canal defect) terjadi pada ~40-50% kasus, sehingga ekokardiografi rutin sejak diagnosis adalah bagian standar tatalaksana holistik, bukan hanya fokus pada gambaran fenotipik saja.' },
    { id: 'de-8',
      vignette: 'Pasien dengan nyeri sendi metatarsofalangeal pertama mendadak, bengkak, kemerahan hebat di malam hari, riwayat konsumsi alkohol & daging merah tinggi, kadar asam urat serum meningkat.',
      options: ['Artritis septik', 'Gout akut (artritis gout) — NSAID/kolkisin untuk serangan akut, pertimbangkan terapi penurun urat jangka panjang setelah serangan mereda', 'Pseudogout (deposit kalsium pirofosfat)', 'Artritis reaktif'],
      answer: 1,
      explanation: 'Nyeri mendadak sendi MTP-1 (podagra) dengan faktor pencetus diet purin tinggi & alkohol adalah presentasi klasik gout — kristal monosodium urat memicu inflamasi akut; terapi akut (NSAID/kolkisin/steroid) berbeda dari terapi penurun urat jangka panjang (allopurinol) yang justru dapat memperburuk serangan akut bila dimulai saat episode berlangsung.' },
    { id: 'de-9',
      vignette: 'Pasien pasca-operasi ortopedi besar mengalami sesak mendadak, takikardia, dan hipoksemia 3 hari pasca-operasi, D-dimer meningkat signifikan.',
      options: ['Pneumonia pasca-operasi', 'Emboli paru akut — pertimbangkan CT pulmonary angiography dan mulai antikoagulasi bila probabilitas klinis tinggi', 'Atelektasis sederhana', 'Reaksi alergi obat anestesi'],
      answer: 1,
      explanation: 'Trias sesak mendadak + takikardia + hipoksemia pasca-operasi ortopedi besar (faktor risiko tromboemboli tinggi akibat imobilisasi & kerusakan jaringan) sangat mencurigakan emboli paru — CT pulmonary angiography adalah baku emas konfirmasi, dan antikoagulasi empiris dapat dimulai sebelum konfirmasi pencitraan bila probabilitas klinis pra-tes tinggi dan risiko perdarahan rendah.' },
  ],
  south_africa: [
    { id: 'za-1',
      vignette: 'Pasien HIV-positif baru terdiagnosis TB paru aktif, CD4 180 sel/µL, di negara dengan beban HIV-TB koinfeksi tertinggi di dunia.',
      options: ['Tunda ART hingga terapi TB selesai penuh (6 bulan)', 'Mulai terapi TB dulu, lalu mulai ART dalam 2-8 minggu (lebih cepat pada CD4 sangat rendah)', 'Mulai ART dan TB bersamaan di hari yang sama tanpa jeda', 'ART tidak diperlukan jika TB sudah diobati'],
      answer: 1,
      explanation: 'Pedoman WHO/Afrika Selatan: mulai terapi TB terlebih dulu untuk menstabilkan pasien, lalu ART diinisiasi dalam 2 minggu bila CD4 <50, atau dalam 8 minggu bila CD4 lebih tinggi — jeda ini menyeimbangkan risiko mortalitas terkait HIV vs risiko IRIS (Immune Reconstitution Inflammatory Syndrome) yang bisa memperberat gejala TB saat sistem imun pulih mendadak.' },
    { id: 'za-2',
      vignette: 'Pasien dari area endemis malaria falciparum datang dengan demam siklik, dan hasil apus darah tipis-tebal mengonfirmasi Plasmodium falciparum tanpa tanda bahaya (komplikata).',
      options: ['Klorokuin sebagai lini pertama', 'ACT (Artemisinin-based Combination Therapy) sebagai lini pertama', 'Observasi tanpa terapi antimalaria', 'Kina intravena wajib meski tanpa tanda bahaya'],
      answer: 1,
      explanation: 'P. falciparum di sebagian besar Afrika (termasuk Afrika Selatan) sudah resisten luas terhadap klorokuin — ACT (mis. artemether-lumefantrine) menjadi lini pertama WHO untuk malaria falciparum tanpa komplikasi, bekerja cepat menurunkan parasitemia lewat pembentukan radikal bebas yang merusak protein parasit.' },
    { id: 'za-3',
      vignette: 'Ibu hamil HIV-positif datang untuk antenatal care rutin. Anda perlu merencanakan strategi mencegah penularan HIV ke bayi.',
      options: ['ART tidak diperlukan selama kehamilan, hanya setelah melahirkan', 'Mulai/lanjutkan ART sepanjang kehamilan untuk menekan viral load ibu, ditambah profilaksis ARV pada bayi & hindari ASI eksklusif bila alternatif aman tersedia', 'Seksio sesarea wajib pada semua ibu HIV-positif tanpa syarat', 'Skrining HIV tidak perlu diulang selama kehamilan'],
      answer: 1,
      explanation: 'Program PMTCT (Prevention of Mother-to-Child Transmission) menekankan ART sepanjang kehamilan untuk menekan viral load ibu serendah mungkin (viral load tidak terdeteksi = risiko transmisi sangat rendah), profilaksis ARV pada neonatus, dan konseling pemberian makan yang mempertimbangkan keseimbangan risiko transmisi vs manfaat ASI — pendekatan komprehensif ini telah menurunkan drastis transmisi vertikal HIV di negara dengan beban tinggi.' },
    { id: 'za-4',
      vignette: 'Pasien HIV-positif dengan CD4 40 sel/µL datang dengan sakit kepala progresif, demam ringan, dan perubahan status mental; pungsi lumbal menunjukkan tekanan pembukaan sangat tinggi, tinta India positif.',
      options: ['Meningitis bakterial biasa', 'Meningitis kriptokokus — perlu amfoterisin B + flusitosin fase induksi, dan manajemen agresif tekanan intrakranial tinggi', 'Meningitis tuberkulosis', 'Ensefalitis herpes simpleks'],
      answer: 1,
      explanation: 'Meningitis kriptokokus adalah infeksi oportunistik utama pada HIV lanjut (CD4 <100) di negara beban HIV tinggi — tinta India positif mengonfirmasi diagnosis; tekanan intrakranial sangat tinggi memerlukan pungsi lumbal berulang/drainase untuk mengurangi risiko herniasi, terpisah dari terapi antifungal amfoterisin B + flusitosin fase induksi yang menjadi standar WHO.' },
    { id: 'za-5',
      vignette: 'Anak dengan edema seluruh tubuh, perut buncit, rambut jarang & berubah warna, kulit mengelupas, riwayat asupan protein sangat rendah meski kalori total cukup dari karbohidrat.',
      options: ['Marasmus (malnutrisi energi-protein berat tipe wasting)', 'Kwashiorkor — defisiensi protein berat dengan edema, tatalaksana refeeding bertahap hati-hati untuk mencegah refeeding syndrome', 'Defisiensi vitamin A semata', 'Rakhitis'],
      answer: 1,
      explanation: 'Kwashiorkor khas ditandai edema (akibat hipoalbuminemia berat dari defisiensi protein meski kalori total dari karbohidrat relatif cukup), perubahan rambut & kulit — berbeda dari marasmus (wasting berat tanpa edema akibat defisiensi kalori-protein global). Refeeding harus bertahap karena risiko refeeding syndrome (pergeseran elektrolit fosfat/kalium/magnesium mendadak) dapat fatal.' },
    { id: 'za-6',
      vignette: 'Pasien dengan gigitan ular tidak diketahui jenisnya di area pedesaan, muncul pembengkakan progresif, nyeri hebat, dan gangguan koagulasi (perdarahan gusi spontan) dalam beberapa jam.',
      options: ['Observasi tanpa antivenom karena jenis ular tidak diketahui', 'Berikan antivenom polivalen sesuai gejala klinis (sindrom sitotoksik/hemotoksik) tanpa harus menunggu identifikasi spesies pasti, plus tatalaksana suportif', 'Insisi & suction pada luka gigitan sebagai tatalaksana utama', 'Tourniquet ketat dipertahankan lama sampai ke rumah sakit'],
      answer: 1,
      explanation: 'Tatalaksana envenomasi ular didasarkan pada sindrom klinis (sitotoksik, hemotoksik, neurotoksik) yang muncul, bukan semata identifikasi spesies pasti yang sering tidak memungkinkan di lapangan — antivenom polivalen diberikan berdasarkan pola klinis; insisi/suction dan tourniquet ketat berkepanjangan justru terbukti memperburuk kerusakan jaringan lokal dan tidak direkomendasikan lagi.' },
    { id: 'za-7',
      vignette: 'Pasien HIV-positif dengan kepatuhan ART buruk selama 2 tahun terakhir datang dengan viral load tinggi meski sedang memakai regimen lini pertama; resistensi obat dicurigai.',
      options: ['Lanjutkan regimen yang sama tanpa evaluasi', 'Evaluasi kepatuhan terlebih dahulu, lalu pertimbangkan genotyping resistensi dan beralih ke regimen lini kedua bila kegagalan virologis dikonfirmasi', 'Langsung hentikan seluruh ART', 'Naikkan dosis obat lini pertama tanpa ganti regimen'],
      answer: 1,
      explanation: 'Kegagalan virologis pada ART memerlukan evaluasi sistematis: pertama singkirkan ketidakpatuhan (penyebab tersering), lalu pertimbangkan uji resistensi genotipik untuk memandu pemilihan regimen lini kedua yang tepat — pendekatan bertahap ini mencegah pergantian regimen sia-sia bila akar masalah sebenarnya adalah kepatuhan, bukan resistensi virus.' },
    { id: 'za-8',
      vignette: 'Bayi baru lahir dari ibu dengan sifilis tidak diobati selama kehamilan menunjukkan hepatosplenomegali, ruam kulit, dan perubahan tulang panjang pada rontgen (periostitis).',
      options: ['Infeksi TORCH lain seperti toksoplasmosis', 'Sifilis kongenital — perlu penisilin G sebagai terapi definitif dan evaluasi menyeluruh organ terkait', 'Sepsis neonatal bakterial biasa', 'Eritroblastosis fetalis akibat inkompatibilitas Rh'],
      answer: 1,
      explanation: 'Sifilis kongenital akibat transmisi transplasenta Treponema pallidum dari ibu tidak diobati menghasilkan spektrum luas manifestasi (hepatosplenomegali, ruam, kelainan tulang seperti periostitis/pseudoparalisis Parrot) — penisilin G tetap terapi lini pertama efektif untuk seluruh stadium sifilis termasuk kongenital, mendasari pentingnya skrining sifilis antenatal rutin.' },
    { id: 'za-9',
      vignette: 'Pekerja tambang emas dengan riwayat paparan debu silika bertahun-tahun, kini juga terdiagnosis HIV, datang dengan batuk kronis, penurunan berat badan, dan foto toraks menunjukkan infiltrat kavitas.',
      options: ['Silikosis murni tanpa infeksi', 'Silikotuberkulosis — silikosis secara independen meningkatkan risiko reaktivasi TB, diperberat lagi oleh koinfeksi HIV', 'Kanker paru primer', 'Pneumonia jamur oportunistik semata'],
      answer: 1,
      explanation: 'Silikosis merusak fungsi makrofag alveolar sehingga secara independen meningkatkan risiko signifikan reaktivasi/infeksi TB (silikotuberkulosis) — kombinasi dengan HIV (yang juga menekan imunitas seluler) menciptakan risiko sinergis sangat tinggi pada populasi pekerja tambang Afrika Selatan, mendorong program skrining TB rutin & ketat pada pekerja tambang dengan riwayat paparan silika.' },
  ],
  israel: [
    { id: 'il-1',
      vignette: 'Pasien keturunan Yahudi Sefardik dengan episode berulang demam disertai nyeri perut hebat, nyeri sendi, dan nyeri dada pleuritik, masing-masing episode mereda spontan dalam 1-3 hari.',
      options: ['Familial Mediterranean Fever (FMF), terapi profilaksis kolkisin', 'Apendisitis akut berulang', 'Lupus eritematosus sistemik', 'Porfiria intermiten akut'],
      answer: 0,
      explanation: 'FMF adalah penyakit autoinflamasi autosomal resesif akibat mutasi gen MEFV (mengkode pyrin) — lebih prevalen pada populasi Mediterania termasuk Yahudi Sefardik, Armenia, dan Arab. Kolkisin (menghambat polimerisasi mikrotubulus, mengganggu aktivasi inflammasom pyrin) adalah terapi profilaksis standar yang mencegah episode & komplikasi jangka panjang (amiloidosis AA).' },
    { id: 'il-2',
      vignette: 'Bayi baru lahir dari populasi dengan prevalensi tinggi penyakit Tay-Sachs menjalani skrining genetik pra-konsepsi rutin pada pasangan keturunan Yahudi Ashkenazi.',
      options: ['Tay-Sachs disebabkan defisiensi enzim heksosaminidase A, terakumulasi gangliosida GM2 di neuron', 'Tay-Sachs adalah penyakit menular', 'Tay-Sachs hanya memengaruhi tulang', 'Skrining ini tidak relevan secara populasi'],
      answer: 0,
      explanation: 'Tay-Sachs adalah penyakit penimbunan lisosomal akibat defisiensi heksosaminidase A, menyebabkan akumulasi gangliosida GM2 toksik di neuron — frekuensi carrier jauh lebih tinggi pada populasi Yahudi Ashkenazi (efek founder), mendasari program skrining carrier pra-konsepsi yang sangat sukses menurunkan insidensi penyakit di populasi ini.' },
    { id: 'il-3',
      vignette: 'Dokter menemukan tanda-tanda kemungkinan kekerasan pada anak saat pemeriksaan rutin. Orang tua menyangkal dan menolak pemeriksaan lebih lanjut.',
      options: ['Hormati penolakan orang tua sepenuhnya dan hentikan evaluasi', 'Dokter memiliki kewajiban hukum melaporkan kecurigaan kekerasan anak (mandatory reporting) kepada otoritas berwenang, terlepas persetujuan orang tua', 'Cukup dicatat di rekam medis tanpa tindakan lanjut', 'Tunggu anak cukup umur untuk melaporkan sendiri'],
      answer: 1,
      explanation: 'Mandatory reporting kecurigaan kekerasan/pengabaian anak adalah kewajiban hukum & etik dokter di hampir semua yurisdiksi modern (termasuk Israel) — kewajiban melindungi anak yang rentan ini mengalahkan kerahasiaan/persetujuan orang tua dalam skenario spesifik ini, prinsip yang diuji luas di ujian lisensi berbagai negara sebagai inti etika kedokteran anak.' },
    { id: 'il-4',
      vignette: 'Pasangan keturunan Yahudi Ashkenazi dengan riwayat keluarga kanker payudara & ovarium onset muda pada beberapa generasi menjalani konseling genetik pra-konsepsi.',
      options: ['Mutasi BRCA1/BRCA2 tidak lebih umum pada populasi ini', 'Mutasi founder BRCA1/BRCA2 secara bermakna lebih prevalen pada populasi Yahudi Ashkenazi — pertimbangkan uji genetik & pemantauan skrining lebih ketat', 'Skrining genetik hanya relevan untuk anggota keluarga yang sudah bergejala', 'Kanker payudara herediter selalu diturunkan dari garis ayah saja'],
      answer: 1,
      explanation: 'Tiga mutasi founder spesifik BRCA1/BRCA2 memiliki prevalensi jauh lebih tinggi pada populasi Yahudi Ashkenazi dibanding populasi umum (efek founder genetik) — pembawa mutasi menghadapi risiko kumulatif kanker payudara & ovarium yang jauh lebih tinggi, mendasari rekomendasi uji genetik proaktif & program skrining intensif (MRI payudara, USG transvaginal) pada populasi berisiko ini.' },
    { id: 'il-5',
      vignette: 'Pasien dengan nyeri sendi berulang, demam periodik, dan riwayat keluarga serupa mengalami perbaikan dramatis gejala setelah dimulai terapi kolkisin harian, namun kadar kreatinin mulai naik perlahan setelah bertahun-tahun tanpa terapi adekuat.',
      options: ['Fungsi ginjal tidak terkait penyakit dasar', 'Kemungkinan amiloidosis AA sekunder akibat inflamasi kronis tidak terkontrol pada FMF — pentingnya kepatuhan kolkisin jangka panjang untuk mencegah komplikasi ini', 'Nefrotoksisitas kolkisin dosis biasa', 'Nefropati diabetik yang tidak terkait'],
      answer: 1,
      explanation: 'Komplikasi jangka panjang paling ditakuti pada FMF yang tidak terkontrol adalah amiloidosis AA (deposit protein amiloid serum A di ginjal akibat inflamasi kronis berulang) yang dapat berujung gagal ginjal — kepatuhan kolkisin seumur hidup terbukti menurunkan drastis risiko ini dengan menekan frekuensi & intensitas episode inflamasi, menjadikannya bukan sekadar terapi simtomatik tapi juga pencegahan komplikasi jangka panjang.' },
    { id: 'il-6',
      vignette: 'Wanita hamil menjalani skrining trimester pertama rutin, hasil menunjukkan risiko tinggi trisomi 21 pada kombinasi NT (nuchal translucency) + biomarker serum; ia meminta konfirmasi diagnostik non-invasif jika memungkinkan.',
      options: ['Amniosentesis adalah satu-satunya pilihan konfirmasi', 'NIPT (Non-Invasive Prenatal Testing) berbasis cfDNA janin dalam darah ibu dapat menjadi langkah konfirmasi lanjutan sebelum tindakan invasif, meski hasil positif tetap perlu konfirmasi diagnostik definitif', 'Tidak ada pemeriksaan lanjutan yang diperlukan', 'CVS (chorionic villus sampling) wajib dilakukan segera tanpa mempertimbangkan NIPT'],
      answer: 1,
      explanation: 'NIPT menganalisis fragmen cfDNA janin bebas dalam plasma ibu dengan sensitivitas tinggi untuk trisomi umum (21, 18, 13) — sifatnya skrining lanjutan non-invasif tanpa risiko keguguran (berbeda dari amniosentesis/CVS), namun hasil positif tetap memerlukan konfirmasi diagnostik invasif sebelum keputusan klinis definitif karena NIPT bukan tes diagnostik pasti.' },
    { id: 'il-7',
      vignette: 'Pasien lansia dengan penyakit ginjal kronis stadium akhir sedang menjalani dialisis rutin, keluarga dan pasien mendiskusikan keinginan menghentikan dialisis dan beralih ke perawatan paliatif murni.',
      options: ['Permintaan penghentian dialisis tidak dapat dihormati karena akan menyebabkan kematian', 'Pasien dengan kapasitas pengambilan keputusan penuh berhak menolak/menghentikan terapi life-sustaining termasuk dialisis — fokus beralih ke perawatan paliatif yang menghormati otonomi pasien', 'Hanya keluarga yang berhak memutuskan penghentian dialisis', 'Penghentian dialisis dianggap eutanasia dan dilarang mutlak'],
      answer: 1,
      explanation: 'Prinsip otonomi pasien dalam etika kedokteran modern menegaskan pasien berkapasitas penuh berhak menolak atau menghentikan terapi penopang hidup apapun, termasuk dialisis — ini secara etis & hukum berbeda dari eutanasia aktif (penghentian terapi atas permintaan pasien vs tindakan aktif mengakhiri hidup), dan perawatan paliatif menjadi fokus perawatan yang bermartabat setelahnya.' },
    { id: 'il-8',
      vignette: 'Bayi dengan hipoglikemia berulang, hepatomegali masif, dan wajah "doll-like", asam laktat tinggi; dicurigai kelainan penyimpanan glikogen herediter.',
      options: ['Diabetes melitus neonatal', 'Glycogen storage disease tipe I (von Gierke) — defisiensi glukosa-6-fosfatase, tatalaksana pemberian karbohidrat kompleks/tepung jagung mentah berkala untuk mencegah hipoglikemia', 'Galaktosemia klasik', 'Penyakit Gaucher'],
      answer: 1,
      explanation: 'Von Gierke disease (GSD tipe I) akibat defisiensi glukosa-6-fosfatase mencegah pelepasan glukosa bebas dari glikogen hati, menyebabkan hipoglikemia berat saat puasa singkat, hepatomegali masif akibat penumpukan glikogen, dan asidosis laktat — tatalaksana utama pemberian karbohidrat kompleks lambat cerna (tepung jagung mentah) berkala menjaga normoglikemia tanpa lonjakan insulin berlebihan.' },
    { id: 'il-9',
      vignette: 'Pasien pria muda dengan nyeri testis akut mendadak, pembengkakan, dan refleks kremaster hilang pada sisi yang nyeri; USG Doppler diperlukan segera.',
      options: ['Epididimitis akut, terapi antibiotik saja tanpa urgensi bedah', 'Torsio testis — kegawatdaruratan bedah, eksplorasi segera dalam beberapa jam untuk menyelamatkan viabilitas testis', 'Hidrokel sederhana', 'Varikokel simtomatik'],
      answer: 1,
      explanation: 'Nyeri mendadak + refleks kremaster hilang adalah tanda klasik torsio testis — iskemia progresif akibat terpuntirnya korda spermatika berarti waktu sangat kritis (viabilitas testis menurun tajam setelah 6 jam), sehingga eksplorasi bedah darurat tidak boleh ditunda untuk pencitraan berkepanjangan bila kecurigaan klinis tinggi, berbeda dari epididimitis yang cenderung onset lebih bertahap dengan refleks kremaster utuh.' },
    { id: 'il-10',
      vignette: 'Pasien dengan riwayat perjalanan ke area gurun datang dengan lesi kulit ulseratif kronis tidak nyeri yang tidak sembuh dengan antibiotik topikal biasa, riwayat gigitan serangga di area tersebut.',
      options: ['Selulitis bakterial resisten', 'Leishmaniasis kutaneus — transmisi lalat pasir (sandfly), memerlukan konfirmasi parasitologis dan terapi antiparasit spesifik', 'Dermatitis kontak alergi', 'Infeksi jamur superfisial'],
      answer: 1,
      explanation: 'Leishmaniasis kutaneus (endemik di area Timur Tengah termasuk sebagian Israel) ditularkan lalat pasir (Phlebotomus) dan menghasilkan lesi ulseratif kronis khas yang tidak merespons antibiotik biasa karena penyebabnya protozoa, bukan bakteri — diagnosis memerlukan konfirmasi parasitologis (kerokan lesi/PCR) dan terapi spesifik antiparasit (mis. antimon pentavalen, miltefosine) bukan antibiotik konvensional.' },
  ],
}

export function questionsForExam(track: ExamTrack): ExamQuestion[] {
  return EXAM_BANK[track] ?? []
}
