export type EyeAtlasLayer = 'orbit' | 'adnexa' | 'globe' | 'anterior-segment' | 'uvea' | 'lens' | 'vitreous' | 'retina' | 'optic-pathway' | 'vascular' | 'innervation' | 'microanatomy'
export type EyeAtlasLevel = 'region' | 'organ' | 'tissue' | 'structure' | 'microstructure' | 'cell'
export type EyeGeometryStatus = 'native-or-source-match-required' | 'teaching-overlay-only' | 'not-represented'

export interface EyeAtlasSource {
  id: string
  title: string
  kind: 'peer-reviewed-review' | 'textbook-reference'
  url: string
  boundary: string
}

export interface EyeAtlasNode {
  id: string
  label: string
  layer: EyeAtlasLayer
  level: EyeAtlasLevel
  parentId?: string
  nodeHints: string[]
  geometry: EyeGeometryStatus
  function: string
  relations: string[]
  bloodSupply?: string[]
  innervation?: string[]
  clinicalBoundary: string
  sourceIds: string[]
}

export const EYE_ATLAS_SOURCES: EyeAtlasSource[] = [
  { id: 'orbital-anatomy-2026', title: 'Orbital Anatomy', kind: 'peer-reviewed-review', url: 'https://pubmed.ncbi.nlm.nih.gov/42230053/', boundary: 'Gross orbital/globe anatomy and imaging relationships; educational reference, not patient-specific geometry.' },
  { id: 'webvision-gross-eye', title: 'Gross Anatomy of the Eye — Webvision', kind: 'textbook-reference', url: 'https://www.ncbi.nlm.nih.gov/books/NBK11534/', boundary: 'Gross ocular anatomy and retinal orientation; not a substitute for histopathology or individualized imaging.' },
  { id: 'statpearls-eye-muscles', title: 'Anatomy, Head and Neck: Eye Muscles', kind: 'textbook-reference', url: 'https://www.ncbi.nlm.nih.gov/books/NBK470534/', boundary: 'Extraocular/intraocular muscle anatomy and innervation; educational reference.' },
  { id: 'statpearls-visual-pathway', title: 'Neuroanatomy, Visual Pathway', kind: 'textbook-reference', url: 'https://www.ncbi.nlm.nih.gov/books/NBK553189/', boundary: 'Visual pathway and ocular motor neuroanatomy; educational reference.' },
]

const B = 'Educational anatomy only; do not infer diagnosis, surgical candidacy, retinal disease, visual field defect, or patient-specific anatomy from this atlas.'
const S = ['orbital-anatomy-2026', 'webvision-gross-eye']

export const EYE_ORBIT_ATLAS: EyeAtlasNode[] = [
  { id:'orbit', label:'Bony orbit', layer:'orbit', level:'region', nodeHints:['orbit','orbital cavity','orbital wall'], geometry:'native-or-source-match-required', function:'Protects and spatially organizes the globe, muscles, nerves, vessels, lacrimal structures and fat.', relations:['roof','floor','medial wall','lateral wall','optic canal','superior orbital fissure','inferior orbital fissure'], clinicalBoundary:B, sourceIds:['orbital-anatomy-2026'] },
  { id:'orbit-roof', label:'Orbital roof', layer:'orbit', level:'structure', parentId:'orbit', nodeHints:['orbital roof','frontal bone','lesser wing sphenoid'], geometry:'native-or-source-match-required', function:'Superior bony boundary of orbit.', relations:['frontal sinus region','anterior cranial fossa'], clinicalBoundary:B, sourceIds:['orbital-anatomy-2026'] },
  { id:'orbit-floor', label:'Orbital floor', layer:'orbit', level:'structure', parentId:'orbit', nodeHints:['orbital floor','maxilla','zygomatic','palatine'], geometry:'native-or-source-match-required', function:'Inferior support of globe and orbital contents.', relations:['maxillary sinus','inferior orbital fissure'], clinicalBoundary:B, sourceIds:['orbital-anatomy-2026'] },
  { id:'orbit-medial-wall', label:'Medial orbital wall', layer:'orbit', level:'structure', parentId:'orbit', nodeHints:['lamina papyracea','ethmoid','lacrimal bone'], geometry:'native-or-source-match-required', function:'Separates orbit from ethmoid air cells and nasal cavity.', relations:['ethmoid sinus','lacrimal sac fossa'], clinicalBoundary:B, sourceIds:['orbital-anatomy-2026'] },
  { id:'orbit-lateral-wall', label:'Lateral orbital wall', layer:'orbit', level:'structure', parentId:'orbit', nodeHints:['lateral orbital wall','zygomatic','greater wing sphenoid'], geometry:'native-or-source-match-required', function:'Thick lateral protective wall.', relations:['temporal fossa','middle cranial fossa'], clinicalBoundary:B, sourceIds:['orbital-anatomy-2026'] },
  { id:'optic-canal', label:'Optic canal', layer:'orbit', level:'structure', parentId:'orbit', nodeHints:['optic canal','optic foramen'], geometry:'native-or-source-match-required', function:'Passage for optic nerve and ophthalmic artery.', relations:['orbital apex','middle cranial fossa'], bloodSupply:['ophthalmic artery'], innervation:['optic nerve (CN II)'], clinicalBoundary:B, sourceIds:['orbital-anatomy-2026','statpearls-visual-pathway'] },
  { id:'sof', label:'Superior orbital fissure', layer:'orbit', level:'structure', parentId:'orbit', nodeHints:['superior orbital fissure'], geometry:'native-or-source-match-required', function:'Neurovascular communication between orbit and middle cranial fossa.', relations:['cavernous sinus region','orbital apex'], innervation:['CN III','CN IV','CN V1 branches','CN VI'], clinicalBoundary:B, sourceIds:['orbital-anatomy-2026','statpearls-eye-muscles'] },

  { id:'globe', label:'Globe', layer:'globe', level:'organ', nodeHints:['eyeball','globe','eye'], geometry:'native-or-source-match-required', function:'Optical and neural organ that focuses light and transduces it into retinal neural signals.', relations:['cornea','sclera','uvea','lens','vitreous','retina','optic nerve'], clinicalBoundary:B, sourceIds:S },
  { id:'cornea', label:'Cornea', layer:'anterior-segment', level:'tissue', parentId:'globe', nodeHints:['cornea'], geometry:'native-or-source-match-required', function:'Major transparent refractive surface and anterior protective tissue.', relations:['tear film','limbus','anterior chamber'], innervation:['long ciliary nerves via nasociliary division of V1'], clinicalBoundary:B, sourceIds:S },
  { id:'corneal-epithelium', label:'Corneal epithelium', layer:'microanatomy', level:'microstructure', parentId:'cornea', nodeHints:['corneal epithelium'], geometry:'teaching-overlay-only', function:'Barrier and rapidly renewing anterior epithelial surface.', relations:['tear film','Bowman layer'], clinicalBoundary:B, sourceIds:['webvision-gross-eye'] },
  { id:'bowman', label:'Bowman layer', layer:'microanatomy', level:'microstructure', parentId:'cornea', nodeHints:['Bowman layer'], geometry:'teaching-overlay-only', function:'Acellular anterior stromal interface.', relations:['corneal epithelium','corneal stroma'], clinicalBoundary:B, sourceIds:['webvision-gross-eye'] },
  { id:'corneal-stroma', label:'Corneal stroma', layer:'microanatomy', level:'microstructure', parentId:'cornea', nodeHints:['corneal stroma'], geometry:'teaching-overlay-only', function:'Ordered collagenous bulk of cornea supporting transparency and shape.', relations:['Bowman layer','Descemet membrane'], clinicalBoundary:B, sourceIds:['webvision-gross-eye'] },
  { id:'descemet', label:'Descemet membrane', layer:'microanatomy', level:'microstructure', parentId:'cornea', nodeHints:['Descemet membrane'], geometry:'teaching-overlay-only', function:'Basement membrane of corneal endothelium.', relations:['corneal stroma','corneal endothelium'], clinicalBoundary:B, sourceIds:['webvision-gross-eye'] },
  { id:'corneal-endothelium', label:'Corneal endothelium', layer:'microanatomy', level:'cell', parentId:'cornea', nodeHints:['corneal endothelium'], geometry:'teaching-overlay-only', function:'Maintains stromal deturgescence through fluid transport.', relations:['Descemet membrane','anterior chamber'], clinicalBoundary:B, sourceIds:['webvision-gross-eye'] },
  { id:'limbus', label:'Corneoscleral limbus', layer:'anterior-segment', level:'structure', parentId:'globe', nodeHints:['limbus','corneoscleral junction'], geometry:'teaching-overlay-only', function:'Transition zone between cornea and sclera; houses aqueous outflow structures.', relations:['cornea','sclera','trabecular meshwork'], clinicalBoundary:B, sourceIds:S },
  { id:'sclera', label:'Sclera', layer:'globe', level:'tissue', parentId:'globe', nodeHints:['sclera'], geometry:'native-or-source-match-required', function:'Fibrous outer coat maintaining globe shape and providing muscle insertion.', relations:['cornea','choroid','extraocular muscle insertions'], clinicalBoundary:B, sourceIds:S },

  { id:'anterior-chamber', label:'Anterior chamber', layer:'anterior-segment', level:'structure', parentId:'globe', nodeHints:['anterior chamber'], geometry:'teaching-overlay-only', function:'Aqueous-filled space between cornea and iris.', relations:['corneal endothelium','iris','trabecular meshwork'], clinicalBoundary:B, sourceIds:S },
  { id:'posterior-chamber', label:'Posterior chamber', layer:'anterior-segment', level:'structure', parentId:'globe', nodeHints:['posterior chamber'], geometry:'teaching-overlay-only', function:'Narrow aqueous-filled space between posterior iris and anterior lens/ciliary body.', relations:['iris','lens','ciliary processes','pupil'], clinicalBoundary:B, sourceIds:S },
  { id:'trabecular-meshwork', label:'Trabecular meshwork', layer:'anterior-segment', level:'microstructure', parentId:'limbus', nodeHints:['trabecular meshwork','iridocorneal angle'], geometry:'teaching-overlay-only', function:'Conventional aqueous humor outflow filter at the iridocorneal angle.', relations:['Schlemm canal','anterior chamber','scleral spur'], clinicalBoundary:B, sourceIds:S },
  { id:'schlemm', label:'Canal of Schlemm', layer:'anterior-segment', level:'microstructure', parentId:'limbus', nodeHints:['Schlemm canal','scleral venous sinus'], geometry:'teaching-overlay-only', function:'Collects aqueous humor from trabecular outflow pathway.', relations:['trabecular meshwork','collector channels'], clinicalBoundary:B, sourceIds:S },

  { id:'iris', label:'Iris', layer:'uvea', level:'tissue', parentId:'globe', nodeHints:['iris'], geometry:'native-or-source-match-required', function:'Adjusts pupil aperture and regulates retinal illumination.', relations:['pupil','ciliary body','anterior chamber','posterior chamber'], bloodSupply:['major arterial circle of iris'], innervation:['parasympathetic sphincter pupillae','sympathetic dilator pupillae'], clinicalBoundary:B, sourceIds:S },
  { id:'pupil', label:'Pupil', layer:'anterior-segment', level:'structure', parentId:'iris', nodeHints:['pupil'], geometry:'teaching-overlay-only', function:'Variable central aperture in iris.', relations:['iris','lens','visual axis'], clinicalBoundary:B, sourceIds:S },
  { id:'ciliary-body', label:'Ciliary body', layer:'uvea', level:'tissue', parentId:'globe', nodeHints:['ciliary body','ciliary process'], geometry:'native-or-source-match-required', function:'Produces aqueous humor and changes zonular tension for accommodation.', relations:['iris','choroid','zonules','lens','posterior chamber'], bloodSupply:['long posterior ciliary arteries','anterior ciliary arteries'], innervation:['parasympathetic via CN III → ciliary ganglion → short ciliary nerves'], clinicalBoundary:B, sourceIds:S },
  { id:'ciliary-muscle', label:'Ciliary muscle', layer:'microanatomy', level:'structure', parentId:'ciliary-body', nodeHints:['ciliary muscle'], geometry:'teaching-overlay-only', function:'Changes zonular tension during accommodation.', relations:['zonules','ciliary body','scleral spur'], innervation:['parasympathetic via short ciliary nerves'], clinicalBoundary:B, sourceIds:['statpearls-eye-muscles','webvision-gross-eye'] },
  { id:'choroid', label:'Choroid', layer:'uvea', level:'tissue', parentId:'globe', nodeHints:['choroid'], geometry:'teaching-overlay-only', function:'Vascular pigmented layer supporting outer retina and absorbing stray light.', relations:['sclera','retinal pigment epithelium','ciliary body'], bloodSupply:['short posterior ciliary arteries'], clinicalBoundary:B, sourceIds:S },

  { id:'lens', label:'Crystalline lens', layer:'lens', level:'organ', parentId:'globe', nodeHints:['lens','crystalline lens'], geometry:'native-or-source-match-required', function:'Transparent adjustable optical element for fine focus.', relations:['iris','posterior chamber','zonules','vitreous'], clinicalBoundary:B, sourceIds:S },
  { id:'lens-capsule', label:'Lens capsule', layer:'microanatomy', level:'microstructure', parentId:'lens', nodeHints:['lens capsule'], geometry:'teaching-overlay-only', function:'Elastic basement-membrane envelope of lens.', relations:['lens epithelium','zonules'], clinicalBoundary:B, sourceIds:['webvision-gross-eye'] },
  { id:'lens-epithelium', label:'Lens epithelium', layer:'microanatomy', level:'cell', parentId:'lens', nodeHints:['lens epithelium'], geometry:'teaching-overlay-only', function:'Anterior epithelial layer contributing to lens homeostasis and fiber generation.', relations:['lens capsule','lens fibers'], clinicalBoundary:B, sourceIds:['webvision-gross-eye'] },
  { id:'zonules', label:'Zonular fibers', layer:'lens', level:'microstructure', parentId:'lens', nodeHints:['zonule','suspensory ligament lens'], geometry:'teaching-overlay-only', function:'Transmit ciliary-body tension to lens capsule.', relations:['ciliary processes','lens capsule'], clinicalBoundary:B, sourceIds:['webvision-gross-eye'] },

  { id:'vitreous', label:'Vitreous body', layer:'vitreous', level:'tissue', parentId:'globe', nodeHints:['vitreous','vitreous body'], geometry:'teaching-overlay-only', function:'Transparent gel filling posterior segment and supporting globe geometry.', relations:['lens','retina','optic disc'], clinicalBoundary:B, sourceIds:S },

  { id:'retina', label:'Neural retina', layer:'retina', level:'tissue', parentId:'globe', nodeHints:['retina'], geometry:'native-or-source-match-required', function:'Phototransduction and initial neural processing of visual information.', relations:['RPE','vitreous','macula','optic disc'], bloodSupply:['central retinal artery','choroidal circulation for outer retina'], clinicalBoundary:B, sourceIds:S },
  { id:'rpe', label:'Retinal pigment epithelium', layer:'retina', level:'cell', parentId:'retina', nodeHints:['retinal pigment epithelium','RPE'], geometry:'teaching-overlay-only', function:'Supports photoreceptors, visual cycle, barrier function and outer segment phagocytosis.', relations:['photoreceptors','Bruch membrane','choroid'], clinicalBoundary:B, sourceIds:['webvision-gross-eye'] },
  { id:'photoreceptors', label:'Rods and cones', layer:'microanatomy', level:'cell', parentId:'retina', nodeHints:['rod photoreceptor','cone photoreceptor'], geometry:'teaching-overlay-only', function:'Convert photons into graded electrical signals.', relations:['RPE','bipolar cells','horizontal cells'], clinicalBoundary:B, sourceIds:['webvision-gross-eye'] },
  { id:'bipolar-cells', label:'Bipolar cells', layer:'microanatomy', level:'cell', parentId:'retina', nodeHints:['retinal bipolar cell'], geometry:'teaching-overlay-only', function:'Relay photoreceptor signals toward ganglion-cell pathways.', relations:['photoreceptors','amacrine cells','ganglion cells'], clinicalBoundary:B, sourceIds:['webvision-gross-eye'] },
  { id:'ganglion-cells', label:'Retinal ganglion cells', layer:'microanatomy', level:'cell', parentId:'retina', nodeHints:['retinal ganglion cell'], geometry:'teaching-overlay-only', function:'Output neurons of retina; axons form optic nerve.', relations:['inner plexiform layer','nerve fiber layer','optic disc'], clinicalBoundary:B, sourceIds:['webvision-gross-eye','statpearls-visual-pathway'] },
  { id:'macula', label:'Macula lutea', layer:'retina', level:'structure', parentId:'retina', nodeHints:['macula','macula lutea'], geometry:'teaching-overlay-only', function:'Central retina specialized for high-acuity vision.', relations:['fovea','posterior pole'], clinicalBoundary:B, sourceIds:['webvision-gross-eye'] },
  { id:'fovea', label:'Fovea centralis', layer:'retina', level:'microstructure', parentId:'macula', nodeHints:['fovea','fovea centralis'], geometry:'teaching-overlay-only', function:'Center of maximal spatial acuity and cone specialization.', relations:['macula','visual axis'], clinicalBoundary:B, sourceIds:['webvision-gross-eye'] },
  { id:'optic-disc', label:'Optic disc / nerve head', layer:'retina', level:'structure', parentId:'retina', nodeHints:['optic disc','optic nerve head'], geometry:'native-or-source-match-required', function:'Exit point of retinal ganglion-cell axons and entry/exit of central retinal vessels.', relations:['optic nerve','central retinal artery','central retinal vein'], bloodSupply:['short posterior ciliary circulation'], clinicalBoundary:B, sourceIds:S },

  { id:'optic-nerve', label:'Optic nerve (CN II)', layer:'optic-pathway', level:'structure', parentId:'globe', nodeHints:['optic nerve','CN II'], geometry:'native-or-source-match-required', function:'Carries retinal ganglion-cell axons from globe to optic chiasm.', relations:['optic disc','optic canal','optic chiasm'], bloodSupply:['ophthalmic/central retinal and pial branches'], clinicalBoundary:B, sourceIds:['orbital-anatomy-2026','statpearls-visual-pathway'] },
  { id:'optic-chiasm', label:'Optic chiasm', layer:'optic-pathway', level:'structure', parentId:'optic-nerve', nodeHints:['optic chiasm'], geometry:'native-or-source-match-required', function:'Partial decussation of retinal fibers.', relations:['optic nerves','optic tracts','pituitary region'], clinicalBoundary:B, sourceIds:['statpearls-visual-pathway'] },
  { id:'optic-tract', label:'Optic tract', layer:'optic-pathway', level:'structure', parentId:'optic-chiasm', nodeHints:['optic tract'], geometry:'native-or-source-match-required', function:'Carries post-chiasmal visual information toward thalamic and reflex targets.', relations:['optic chiasm','lateral geniculate nucleus'], clinicalBoundary:B, sourceIds:['statpearls-visual-pathway'] },
  { id:'lgn', label:'Lateral geniculate nucleus', layer:'optic-pathway', level:'structure', parentId:'optic-tract', nodeHints:['lateral geniculate nucleus','LGN'], geometry:'native-or-source-match-required', function:'Thalamic relay for conscious visual pathway.', relations:['optic tract','optic radiations'], clinicalBoundary:B, sourceIds:['statpearls-visual-pathway'] },
  { id:'optic-radiations', label:'Optic radiations', layer:'optic-pathway', level:'structure', parentId:'lgn', nodeHints:['optic radiation','Meyer loop'], geometry:'native-or-source-match-required', function:'Project visual signals from LGN to primary visual cortex.', relations:['temporal lobe','parietal lobe','visual cortex'], clinicalBoundary:B, sourceIds:['statpearls-visual-pathway'] },
  { id:'v1', label:'Primary visual cortex', layer:'optic-pathway', level:'structure', parentId:'optic-radiations', nodeHints:['calcarine cortex','primary visual cortex','V1'], geometry:'native-or-source-match-required', function:'Initial cortical processing of visual input.', relations:['calcarine sulcus','occipital lobe'], clinicalBoundary:B, sourceIds:['statpearls-visual-pathway'] },

  { id:'eom', label:'Extraocular muscle cone', layer:'adnexa', level:'tissue', parentId:'orbit', nodeHints:['extraocular muscle','rectus muscle','oblique muscle'], geometry:'native-or-source-match-required', function:'Controls binocular alignment and globe rotation.', relations:['annulus of Zinn','globe','orbital apex'], innervation:['CN III','CN IV','CN VI'], clinicalBoundary:B, sourceIds:['statpearls-eye-muscles','orbital-anatomy-2026'] },
  { id:'superior-rectus', label:'Superior rectus', layer:'adnexa', level:'structure', parentId:'eom', nodeHints:['superior rectus'], geometry:'native-or-source-match-required', function:'Elevates, adducts and intorts the globe.', relations:['annulus of Zinn','superior globe'], innervation:['CN III superior division'], clinicalBoundary:B, sourceIds:['statpearls-eye-muscles','statpearls-visual-pathway'] },
  { id:'inferior-rectus', label:'Inferior rectus', layer:'adnexa', level:'structure', parentId:'eom', nodeHints:['inferior rectus'], geometry:'native-or-source-match-required', function:'Depresses, adducts and extorts the globe.', relations:['annulus of Zinn','inferior globe'], innervation:['CN III inferior division'], clinicalBoundary:B, sourceIds:['statpearls-eye-muscles','statpearls-visual-pathway'] },
  { id:'medial-rectus', label:'Medial rectus', layer:'adnexa', level:'structure', parentId:'eom', nodeHints:['medial rectus'], geometry:'native-or-source-match-required', function:'Adducts the globe.', relations:['annulus of Zinn','medial globe'], innervation:['CN III inferior division'], clinicalBoundary:B, sourceIds:['statpearls-eye-muscles','statpearls-visual-pathway'] },
  { id:'lateral-rectus', label:'Lateral rectus', layer:'adnexa', level:'structure', parentId:'eom', nodeHints:['lateral rectus'], geometry:'native-or-source-match-required', function:'Abducts the globe.', relations:['annulus of Zinn','lateral globe'], innervation:['CN VI'], clinicalBoundary:B, sourceIds:['statpearls-eye-muscles','statpearls-visual-pathway'] },
  { id:'superior-oblique', label:'Superior oblique', layer:'adnexa', level:'structure', parentId:'eom', nodeHints:['superior oblique','trochlea'], geometry:'native-or-source-match-required', function:'Intorts and depresses the globe, especially in adduction; also abducts.', relations:['trochlea','superomedial orbit'], innervation:['CN IV'], clinicalBoundary:B, sourceIds:['statpearls-eye-muscles','statpearls-visual-pathway'] },
  { id:'inferior-oblique', label:'Inferior oblique', layer:'adnexa', level:'structure', parentId:'eom', nodeHints:['inferior oblique'], geometry:'native-or-source-match-required', function:'Extorts and elevates the globe, especially in adduction; also abducts.', relations:['anteromedial orbital floor','inferolateral globe'], innervation:['CN III inferior division'], clinicalBoundary:B, sourceIds:['statpearls-eye-muscles','statpearls-visual-pathway'] },
  { id:'levator', label:'Levator palpebrae superioris', layer:'adnexa', level:'structure', parentId:'orbit', nodeHints:['levator palpebrae superioris'], geometry:'native-or-source-match-required', function:'Elevates upper eyelid.', relations:['superior rectus','upper eyelid','orbital roof'], innervation:['CN III superior division'], clinicalBoundary:B, sourceIds:['statpearls-eye-muscles'] },

  { id:'lacrimal-gland', label:'Lacrimal gland', layer:'adnexa', level:'organ', parentId:'orbit', nodeHints:['lacrimal gland'], geometry:'native-or-source-match-required', function:'Produces aqueous component of tear film.', relations:['superolateral orbit','conjunctival fornix','lacrimal ducts'], innervation:['parasympathetic secretomotor via facial nerve pathway','sensory via lacrimal nerve V1'], clinicalBoundary:B, sourceIds:['orbital-anatomy-2026'] },
  { id:'lacrimal-drainage', label:'Lacrimal drainage pathway', layer:'adnexa', level:'structure', parentId:'orbit', nodeHints:['lacrimal punctum','canaliculus','lacrimal sac','nasolacrimal duct'], geometry:'teaching-overlay-only', function:'Drains tears from ocular surface to inferior nasal meatus.', relations:['medial canthus','lacrimal sac fossa','nasal cavity'], clinicalBoundary:B, sourceIds:['orbital-anatomy-2026'] },

  { id:'ophthalmic-artery', label:'Ophthalmic artery', layer:'vascular', level:'structure', parentId:'orbit', nodeHints:['ophthalmic artery'], geometry:'native-or-source-match-required', function:'Principal arterial supply to orbit and eye.', relations:['optic canal','optic nerve','central retinal artery','ciliary arteries'], bloodSupply:['internal carotid artery origin'], clinicalBoundary:B, sourceIds:['orbital-anatomy-2026','statpearls-eye-muscles'] },
  { id:'central-retinal-artery', label:'Central retinal artery', layer:'vascular', level:'structure', parentId:'ophthalmic-artery', nodeHints:['central retinal artery'], geometry:'native-or-source-match-required', function:'Supplies inner retina.', relations:['optic nerve','optic disc','retinal arterial tree'], clinicalBoundary:B, sourceIds:['orbital-anatomy-2026'] },
  { id:'ciliary-arteries', label:'Posterior/anterior ciliary arterial system', layer:'vascular', level:'structure', parentId:'ophthalmic-artery', nodeHints:['posterior ciliary artery','anterior ciliary artery'], geometry:'teaching-overlay-only', function:'Supplies choroid, ciliary body, iris and optic nerve head regions.', relations:['choroid','ciliary body','iris','optic nerve head'], clinicalBoundary:B, sourceIds:['orbital-anatomy-2026'] },
  { id:'ophthalmic-veins', label:'Superior and inferior ophthalmic veins', layer:'vascular', level:'structure', parentId:'orbit', nodeHints:['superior ophthalmic vein','inferior ophthalmic vein'], geometry:'native-or-source-match-required', function:'Major venous drainage routes of orbit.', relations:['cavernous sinus','facial venous connections'], clinicalBoundary:B, sourceIds:['orbital-anatomy-2026'] },

  { id:'cn3', label:'Oculomotor nerve (CN III)', layer:'innervation', level:'structure', parentId:'orbit', nodeHints:['oculomotor nerve','CN III'], geometry:'native-or-source-match-required', function:'Motor supply to most extraocular muscles, levator, and parasympathetic pupil/accommodation pathway.', relations:['superior orbital fissure','ciliary ganglion'], innervation:['superior rectus','medial rectus','inferior rectus','inferior oblique','levator palpebrae','parasympathetic ciliary ganglion'], clinicalBoundary:B, sourceIds:['statpearls-eye-muscles','statpearls-visual-pathway'] },
  { id:'cn4', label:'Trochlear nerve (CN IV)', layer:'innervation', level:'structure', parentId:'orbit', nodeHints:['trochlear nerve','CN IV'], geometry:'native-or-source-match-required', function:'Motor supply to superior oblique.', relations:['superior orbital fissure','superior oblique'], clinicalBoundary:B, sourceIds:['statpearls-eye-muscles','statpearls-visual-pathway'] },
  { id:'cn6', label:'Abducens nerve (CN VI)', layer:'innervation', level:'structure', parentId:'orbit', nodeHints:['abducens nerve','CN VI'], geometry:'native-or-source-match-required', function:'Motor supply to lateral rectus.', relations:['superior orbital fissure','lateral rectus'], clinicalBoundary:B, sourceIds:['statpearls-eye-muscles','statpearls-visual-pathway'] },
  { id:'v1', label:'Ophthalmic division of trigeminal nerve (V1)', layer:'innervation', level:'structure', parentId:'orbit', nodeHints:['ophthalmic nerve','V1','nasociliary nerve','lacrimal nerve','frontal nerve'], geometry:'native-or-source-match-required', function:'Principal somatic sensory pathway of cornea, globe, upper eyelid, forehead and orbit.', relations:['superior orbital fissure','nasociliary nerve','lacrimal nerve','frontal nerve'], clinicalBoundary:B, sourceIds:['orbital-anatomy-2026'] },
  { id:'ciliary-ganglion', label:'Ciliary ganglion and short ciliary nerves', layer:'innervation', level:'microstructure', parentId:'orbit', nodeHints:['ciliary ganglion','short ciliary nerve'], geometry:'teaching-overlay-only', function:'Parasympathetic relay for sphincter pupillae and ciliary muscle; also carries sensory/sympathetic fibers.', relations:['optic nerve','lateral rectus region','globe'], clinicalBoundary:B, sourceIds:['statpearls-eye-muscles'] },
]

export const EYE_ATLAS_LAYER_ORDER: EyeAtlasLayer[] = ['orbit','adnexa','globe','anterior-segment','uvea','lens','vitreous','retina','optic-pathway','vascular','innervation','microanatomy']

export function eyeAtlasChildren(parentId: string) {
  return EYE_ORBIT_ATLAS.filter((node) => node.parentId === parentId)
}

export function eyeAtlasByLayer(layer: EyeAtlasLayer) {
  return EYE_ORBIT_ATLAS.filter((node) => node.layer === layer)
}

export function eyeAtlasCoverage() {
  const layers = new Set(EYE_ORBIT_ATLAS.map((node) => node.layer))
  const sourceBacked = EYE_ORBIT_ATLAS.every((node) => node.sourceIds.length > 0)
  const bounded = EYE_ORBIT_ATLAS.every((node) => node.clinicalBoundary.includes('Educational anatomy only'))
  return { nodes: EYE_ORBIT_ATLAS.length, layers: layers.size, sourceBacked, bounded }
}
