// ICD diagnosis catalogue for the AI-EMR Assessment (Diagnosis Utama).
//
// Codes follow ICD-10 (the standard used by SATUSEHAT/BPJS in Indonesia); the
// ICD-11 successor is noted in comments where relevant. This is a curated,
// frequently-used subset across primary care, internal medicine, emergency,
// pediatrics, ob-gyn, surgery, psychiatry & infectious disease — searchable by
// code or Indonesian/English term.
export interface ICDCode {
  code: string // ICD-10 code
  id: string // Indonesian name
  en: string // English name
  chapter: string // body-system / category grouping
}

export const ICD_CODES: ICDCode[] = [
  // Infeksi & penyakit menular
  { code: 'A09', id: 'Diare & gastroenteritis (dugaan infeksi)', en: 'Diarrhoea & gastroenteritis', chapter: 'Infeksi' },
  { code: 'A15', id: 'Tuberkulosis paru', en: 'Respiratory tuberculosis', chapter: 'Infeksi' },
  { code: 'A90', id: 'Demam dengue', en: 'Dengue fever', chapter: 'Infeksi' },
  { code: 'A91', id: 'Demam berdarah dengue (DBD)', en: 'Dengue haemorrhagic fever', chapter: 'Infeksi' },
  { code: 'A01.0', id: 'Demam tifoid', en: 'Typhoid fever', chapter: 'Infeksi' },
  { code: 'B50', id: 'Malaria falciparum', en: 'Plasmodium falciparum malaria', chapter: 'Infeksi' },
  { code: 'B34.2', id: 'Infeksi coronavirus (COVID-19)', en: 'Coronavirus infection', chapter: 'Infeksi' },
  { code: 'B20', id: 'Penyakit HIV', en: 'HIV disease', chapter: 'Infeksi' },
  { code: 'B19', id: 'Hepatitis virus', en: 'Viral hepatitis', chapter: 'Infeksi' },
  { code: 'A46', id: 'Erisipelas/selulitis', en: 'Erysipelas', chapter: 'Infeksi' },
  // Pernapasan
  { code: 'J00', id: 'Nasofaringitis akut (common cold)', en: 'Acute nasopharyngitis', chapter: 'Pernapasan' },
  { code: 'J02.9', id: 'Faringitis akut', en: 'Acute pharyngitis', chapter: 'Pernapasan' },
  { code: 'J03.9', id: 'Tonsilitis akut', en: 'Acute tonsillitis', chapter: 'Pernapasan' },
  { code: 'J06.9', id: 'ISPA akut', en: 'Acute upper respiratory infection', chapter: 'Pernapasan' },
  { code: 'J18.9', id: 'Pneumonia', en: 'Pneumonia, unspecified', chapter: 'Pernapasan' },
  { code: 'J45.9', id: 'Asma', en: 'Asthma', chapter: 'Pernapasan' },
  { code: 'J44.9', id: 'PPOK (COPD)', en: 'Chronic obstructive pulmonary disease', chapter: 'Pernapasan' },
  { code: 'J20.9', id: 'Bronkitis akut', en: 'Acute bronchitis', chapter: 'Pernapasan' },
  { code: 'J30.4', id: 'Rinitis alergi', en: 'Allergic rhinitis', chapter: 'Pernapasan' },
  { code: 'J01.9', id: 'Sinusitis akut', en: 'Acute sinusitis', chapter: 'Pernapasan' },
  // Kardiovaskular
  { code: 'I10', id: 'Hipertensi esensial (primer)', en: 'Essential hypertension', chapter: 'Kardiovaskular' },
  { code: 'I20.0', id: 'Angina tidak stabil', en: 'Unstable angina', chapter: 'Kardiovaskular' },
  { code: 'I21.9', id: 'Infark miokard akut (serangan jantung)', en: 'Acute myocardial infarction', chapter: 'Kardiovaskular' },
  { code: 'I25.1', id: 'Penyakit jantung koroner', en: 'Atherosclerotic heart disease', chapter: 'Kardiovaskular' },
  { code: 'I50.9', id: 'Gagal jantung', en: 'Heart failure', chapter: 'Kardiovaskular' },
  { code: 'I48', id: 'Fibrilasi & flutter atrium', en: 'Atrial fibrillation and flutter', chapter: 'Kardiovaskular' },
  { code: 'I63.9', id: 'Stroke iskemik (infark serebral)', en: 'Cerebral infarction', chapter: 'Kardiovaskular' },
  { code: 'I64', id: 'Stroke (tidak ditentukan perdarahan/infark)', en: 'Stroke, not specified', chapter: 'Kardiovaskular' },
  { code: 'I83.9', id: 'Varises tungkai', en: 'Varicose veins of lower extremities', chapter: 'Kardiovaskular' },
  // Endokrin & metabolik
  { code: 'E11.9', id: 'Diabetes melitus tipe 2', en: 'Type 2 diabetes mellitus', chapter: 'Endokrin & Metabolik' },
  { code: 'E10.9', id: 'Diabetes melitus tipe 1', en: 'Type 1 diabetes mellitus', chapter: 'Endokrin & Metabolik' },
  { code: 'E78.5', id: 'Dislipidemia/hiperlipidemia', en: 'Hyperlipidaemia', chapter: 'Endokrin & Metabolik' },
  { code: 'E03.9', id: 'Hipotiroidisme', en: 'Hypothyroidism', chapter: 'Endokrin & Metabolik' },
  { code: 'E05.9', id: 'Hipertiroidisme', en: 'Thyrotoxicosis', chapter: 'Endokrin & Metabolik' },
  { code: 'E66.9', id: 'Obesitas', en: 'Obesity', chapter: 'Endokrin & Metabolik' },
  { code: 'E79.0', id: 'Hiperurisemia (asam urat)', en: 'Hyperuricaemia', chapter: 'Endokrin & Metabolik' },
  { code: 'E86', id: 'Dehidrasi', en: 'Volume depletion', chapter: 'Endokrin & Metabolik' },
  // Saluran cerna
  { code: 'K29.7', id: 'Gastritis (maag)', en: 'Gastritis', chapter: 'Saluran Cerna' },
  { code: 'K21.9', id: 'GERD (refluks gastroesofageal)', en: 'Gastro-oesophageal reflux disease', chapter: 'Saluran Cerna' },
  { code: 'K27.9', id: 'Ulkus peptikum', en: 'Peptic ulcer', chapter: 'Saluran Cerna' },
  { code: 'K35.8', id: 'Apendisitis akut (usus buntu)', en: 'Acute appendicitis', chapter: 'Saluran Cerna' },
  { code: 'K40.9', id: 'Hernia inguinalis', en: 'Inguinal hernia', chapter: 'Saluran Cerna' },
  { code: 'K80.2', id: 'Batu empedu (kolelitiasis)', en: 'Gallstones', chapter: 'Saluran Cerna' },
  { code: 'K59.0', id: 'Konstipasi', en: 'Constipation', chapter: 'Saluran Cerna' },
  { code: 'K58.9', id: 'Sindrom usus iritabel (IBS)', en: 'Irritable bowel syndrome', chapter: 'Saluran Cerna' },
  { code: 'K76.0', id: 'Perlemakan hati (fatty liver)', en: 'Fatty liver', chapter: 'Saluran Cerna' },
  { code: 'K74.6', id: 'Sirosis hati', en: 'Cirrhosis of liver', chapter: 'Saluran Cerna' },
  { code: 'K52.9', id: 'Gastroenteritis & kolitis non-infeksi', en: 'Noninfective gastroenteritis', chapter: 'Saluran Cerna' },
  // Ginjal & saluran kemih
  { code: 'N39.0', id: 'Infeksi saluran kemih (ISK)', en: 'Urinary tract infection', chapter: 'Ginjal & Kemih' },
  { code: 'N18.9', id: 'Penyakit ginjal kronik', en: 'Chronic kidney disease', chapter: 'Ginjal & Kemih' },
  { code: 'N17.9', id: 'Gagal ginjal akut', en: 'Acute kidney failure', chapter: 'Ginjal & Kemih' },
  { code: 'N20.0', id: 'Batu ginjal (nefrolitiasis)', en: 'Kidney stone', chapter: 'Ginjal & Kemih' },
  { code: 'N40', id: 'Pembesaran prostat jinak (BPH)', en: 'Benign prostatic hyperplasia', chapter: 'Ginjal & Kemih' },
  // Muskuloskeletal
  { code: 'M54.5', id: 'Nyeri punggung bawah (low back pain)', en: 'Low back pain', chapter: 'Muskuloskeletal' },
  { code: 'M54.2', id: 'Nyeri leher (servikalgia)', en: 'Cervicalgia', chapter: 'Muskuloskeletal' },
  { code: 'M17.9', id: 'Osteoartritis lutut', en: 'Osteoarthritis of knee', chapter: 'Muskuloskeletal' },
  { code: 'M06.9', id: 'Artritis reumatoid', en: 'Rheumatoid arthritis', chapter: 'Muskuloskeletal' },
  { code: 'M10.9', id: 'Gout (artritis pirai)', en: 'Gout', chapter: 'Muskuloskeletal' },
  { code: 'M79.1', id: 'Mialgia (nyeri otot)', en: 'Myalgia', chapter: 'Muskuloskeletal' },
  { code: 'M81.9', id: 'Osteoporosis', en: 'Osteoporosis', chapter: 'Muskuloskeletal' },
  { code: 'S52.5', id: 'Fraktur ujung distal radius', en: 'Fracture of lower end of radius', chapter: 'Muskuloskeletal' },
  // Saraf
  { code: 'G43.9', id: 'Migrain', en: 'Migraine', chapter: 'Saraf' },
  { code: 'G44.2', id: 'Nyeri kepala tipe tegang', en: 'Tension-type headache', chapter: 'Saraf' },
  { code: 'R51', id: 'Sefalgia (nyeri kepala)', en: 'Headache', chapter: 'Saraf' },
  { code: 'G40.9', id: 'Epilepsi', en: 'Epilepsy', chapter: 'Saraf' },
  { code: 'G62.9', id: 'Polineuropati', en: 'Polyneuropathy', chapter: 'Saraf' },
  { code: 'G47.0', id: 'Insomnia', en: 'Insomnia', chapter: 'Saraf' },
  { code: 'H81.1', id: 'Vertigo posisi paroksismal (BPPV)', en: 'Benign paroxysmal vertigo', chapter: 'Saraf' },
  // Jiwa
  { code: 'F32.9', id: 'Depresi', en: 'Depressive episode', chapter: 'Kesehatan Jiwa' },
  { code: 'F41.1', id: 'Gangguan cemas menyeluruh', en: 'Generalized anxiety disorder', chapter: 'Kesehatan Jiwa' },
  { code: 'F41.0', id: 'Gangguan panik', en: 'Panic disorder', chapter: 'Kesehatan Jiwa' },
  { code: 'F43.1', id: 'Gangguan stres pascatrauma (PTSD)', en: 'Post-traumatic stress disorder', chapter: 'Kesehatan Jiwa' },
  { code: 'F20.9', id: 'Skizofrenia', en: 'Schizophrenia', chapter: 'Kesehatan Jiwa' },
  // Kulit
  { code: 'L20.9', id: 'Dermatitis atopik (eksim)', en: 'Atopic dermatitis', chapter: 'Kulit' },
  { code: 'L23.9', id: 'Dermatitis kontak alergi', en: 'Allergic contact dermatitis', chapter: 'Kulit' },
  { code: 'L50.9', id: 'Urtikaria (biduran)', en: 'Urticaria', chapter: 'Kulit' },
  { code: 'L70.0', id: 'Akne vulgaris (jerawat)', en: 'Acne vulgaris', chapter: 'Kulit' },
  { code: 'B35.9', id: 'Dermatofitosis (kurap/panu)', en: 'Dermatophytosis', chapter: 'Kulit' },
  { code: 'L40.9', id: 'Psoriasis', en: 'Psoriasis', chapter: 'Kulit' },
  // Mata & THT
  { code: 'H10.9', id: 'Konjungtivitis', en: 'Conjunctivitis', chapter: 'Mata & THT' },
  { code: 'H66.9', id: 'Otitis media', en: 'Otitis media', chapter: 'Mata & THT' },
  { code: 'H60.9', id: 'Otitis eksterna', en: 'Otitis externa', chapter: 'Mata & THT' },
  { code: 'H25.9', id: 'Katarak senilis', en: 'Senile cataract', chapter: 'Mata & THT' },
  { code: 'H40.9', id: 'Glaukoma', en: 'Glaucoma', chapter: 'Mata & THT' },
  // Darah & gizi
  { code: 'D50.9', id: 'Anemia defisiensi besi', en: 'Iron deficiency anaemia', chapter: 'Darah & Gizi' },
  { code: 'D64.9', id: 'Anemia', en: 'Anaemia, unspecified', chapter: 'Darah & Gizi' },
  { code: 'E44.0', id: 'Malnutrisi energi-protein sedang', en: 'Moderate protein-energy malnutrition', chapter: 'Darah & Gizi' },
  { code: 'E55.9', id: 'Defisiensi vitamin D', en: 'Vitamin D deficiency', chapter: 'Darah & Gizi' },
  // Ob-gyn
  { code: 'O80', id: 'Persalinan spontan normal', en: 'Single spontaneous delivery', chapter: 'Obstetri & Ginekologi' },
  { code: 'O14.9', id: 'Preeklampsia', en: 'Pre-eclampsia', chapter: 'Obstetri & Ginekologi' },
  { code: 'N91.2', id: 'Amenorea', en: 'Amenorrhoea', chapter: 'Obstetri & Ginekologi' },
  { code: 'N95.1', id: 'Keadaan menopause', en: 'Menopausal state', chapter: 'Obstetri & Ginekologi' },
  { code: 'N76.0', id: 'Vaginitis akut', en: 'Acute vaginitis', chapter: 'Obstetri & Ginekologi' },
  // Anak
  { code: 'P07.3', id: 'Bayi prematur', en: 'Preterm infant', chapter: 'Anak' },
  { code: 'A08.0', id: 'Rotavirus enteritis', en: 'Rotaviral enteritis', chapter: 'Anak' },
  { code: 'J21.9', id: 'Bronkiolitis akut', en: 'Acute bronchiolitis', chapter: 'Anak' },
  { code: 'B01.9', id: 'Varicella (cacar air)', en: 'Varicella', chapter: 'Anak' },
  // Gejala & tanda umum
  { code: 'R50.9', id: 'Demam', en: 'Fever, unspecified', chapter: 'Gejala Umum' },
  { code: 'R10.4', id: 'Nyeri perut', en: 'Abdominal pain', chapter: 'Gejala Umum' },
  { code: 'R05', id: 'Batuk', en: 'Cough', chapter: 'Gejala Umum' },
  { code: 'R07.4', id: 'Nyeri dada', en: 'Chest pain, unspecified', chapter: 'Gejala Umum' },
  { code: 'R11', id: 'Mual & muntah', en: 'Nausea and vomiting', chapter: 'Gejala Umum' },
  { code: 'R42', id: 'Pusing & vertigo', en: 'Dizziness and giddiness', chapter: 'Gejala Umum' },
  { code: 'R53', id: 'Lemas & lelah (malaise)', en: 'Malaise and fatigue', chapter: 'Gejala Umum' },
  { code: 'R55', id: 'Sinkop & kolaps', en: 'Syncope and collapse', chapter: 'Gejala Umum' },
  { code: 'Z00.0', id: 'Pemeriksaan kesehatan umum', en: 'General medical examination', chapter: 'Pemeriksaan' },

  // ── Tambahan: kasus SKDI 4A dan keadaan gawat darurat yang lazim diujikan ──
  // Infeksi & penyakit menular
  { code: 'A00.9', id: 'Kolera', en: 'Cholera', chapter: 'Infeksi' },
  { code: 'A03.9', id: 'Disentri basiler (shigelosis)', en: 'Shigellosis', chapter: 'Infeksi' },
  { code: 'A06.0', id: 'Disentri amuba akut', en: 'Acute amoebic dysentery', chapter: 'Infeksi' },
  { code: 'A16.2', id: 'TB paru tanpa konfirmasi bakteriologis', en: 'TB of lung without bacteriological confirmation', chapter: 'Infeksi' },
  { code: 'A17.0', id: 'Meningitis tuberkulosis', en: 'Tuberculous meningitis', chapter: 'Infeksi' },
  { code: 'A30.9', id: 'Kusta (lepra)', en: 'Leprosy', chapter: 'Infeksi' },
  { code: 'A33', id: 'Tetanus neonatorum', en: 'Tetanus neonatorum', chapter: 'Infeksi' },
  { code: 'A35', id: 'Tetanus', en: 'Other tetanus', chapter: 'Infeksi' },
  { code: 'A36.9', id: 'Difteri', en: 'Diphtheria', chapter: 'Infeksi' },
  { code: 'A37.9', id: 'Pertusis (batuk rejan)', en: 'Whooping cough', chapter: 'Infeksi' },
  { code: 'A41.9', id: 'Sepsis', en: 'Sepsis, unspecified', chapter: 'Infeksi' },
  { code: 'A27.9', id: 'Leptospirosis', en: 'Leptospirosis', chapter: 'Infeksi' },
  { code: 'A51.0', id: 'Sifilis primer genital', en: 'Primary genital syphilis', chapter: 'Infeksi' },
  { code: 'A54.9', id: 'Gonore', en: 'Gonococcal infection', chapter: 'Infeksi' },
  { code: 'A63.0', id: 'Kondiloma akuminata', en: 'Anogenital warts', chapter: 'Infeksi' },
  { code: 'A82.9', id: 'Rabies', en: 'Rabies', chapter: 'Infeksi' },
  { code: 'A92.0', id: 'Chikungunya', en: 'Chikungunya virus disease', chapter: 'Infeksi' },
  { code: 'A97.2', id: 'Dengue berat', en: 'Severe dengue', chapter: 'Infeksi' },
  { code: 'B05.9', id: 'Campak (morbili)', en: 'Measles', chapter: 'Infeksi' },
  { code: 'B26.9', id: 'Parotitis epidemika (gondongan)', en: 'Mumps', chapter: 'Infeksi' },
  { code: 'B51.9', id: 'Malaria vivax', en: 'Plasmodium vivax malaria', chapter: 'Infeksi' },
  { code: 'B54', id: 'Malaria tidak ditentukan', en: 'Unspecified malaria', chapter: 'Infeksi' },
  { code: 'B77.9', id: 'Askariasis (cacing gelang)', en: 'Ascariasis', chapter: 'Infeksi' },
  { code: 'B76.9', id: 'Ankilostomiasis (cacing tambang)', en: 'Hookworm disease', chapter: 'Infeksi' },
  { code: 'B86', id: 'Skabies', en: 'Scabies', chapter: 'Infeksi' },
  { code: 'B37.9', id: 'Kandidiasis', en: 'Candidiasis', chapter: 'Infeksi' },
  { code: 'B02.9', id: 'Herpes zoster', en: 'Zoster', chapter: 'Infeksi' },
  { code: 'B00.9', id: 'Infeksi herpes simpleks', en: 'Herpesviral infection', chapter: 'Infeksi' },
  // Pernapasan
  { code: 'J09', id: 'Influenza karena virus influenza zoonotik', en: 'Influenza, zoonotic virus', chapter: 'Pernapasan' },
  { code: 'J11.1', id: 'Influenza dengan manifestasi pernapasan', en: 'Influenza with respiratory manifestations', chapter: 'Pernapasan' },
  { code: 'J15.9', id: 'Pneumonia bakterial', en: 'Bacterial pneumonia', chapter: 'Pernapasan' },
  { code: 'J46', id: 'Status asmatikus (asma serangan berat)', en: 'Status asthmaticus', chapter: 'Pernapasan' },
  { code: 'J38.5', id: 'Spasme laring', en: 'Laryngeal spasm', chapter: 'Pernapasan' },
  { code: 'J05.0', id: 'Laringitis obstruktif akut (croup)', en: 'Acute obstructive laryngitis (croup)', chapter: 'Pernapasan' },
  { code: 'J90', id: 'Efusi pleura', en: 'Pleural effusion', chapter: 'Pernapasan' },
  { code: 'J93.9', id: 'Pneumotoraks', en: 'Pneumothorax', chapter: 'Pernapasan' },
  { code: 'J81', id: 'Edema paru', en: 'Pulmonary oedema', chapter: 'Pernapasan' },
  { code: 'J96.0', id: 'Gagal napas akut', en: 'Acute respiratory failure', chapter: 'Pernapasan' },
  { code: 'J47', id: 'Bronkiektasis', en: 'Bronchiectasis', chapter: 'Pernapasan' },
  { code: 'J32.9', id: 'Sinusitis kronik', en: 'Chronic sinusitis', chapter: 'Pernapasan' },
  { code: 'J35.0', id: 'Tonsilitis kronik', en: 'Chronic tonsillitis', chapter: 'Pernapasan' },
  // Kardiovaskular
  { code: 'I11.0', id: 'Penyakit jantung hipertensif dengan gagal jantung', en: 'Hypertensive heart disease with heart failure', chapter: 'Kardiovaskular' },
  { code: 'I16.0', id: 'Hipertensi urgensi', en: 'Hypertensive urgency', chapter: 'Kardiovaskular' },
  { code: 'I16.1', id: 'Hipertensi emergensi', en: 'Hypertensive emergency', chapter: 'Kardiovaskular' },
  { code: 'I21.0', id: 'STEMI dinding anterior', en: 'Acute transmural MI of anterior wall', chapter: 'Kardiovaskular' },
  { code: 'I21.1', id: 'STEMI dinding inferior', en: 'Acute transmural MI of inferior wall', chapter: 'Kardiovaskular' },
  { code: 'I21.4', id: 'NSTEMI', en: 'Acute subendocardial myocardial infarction', chapter: 'Kardiovaskular' },
  { code: 'I26.9', id: 'Emboli paru', en: 'Pulmonary embolism', chapter: 'Kardiovaskular' },
  { code: 'I46.9', id: 'Henti jantung', en: 'Cardiac arrest', chapter: 'Kardiovaskular' },
  { code: 'I47.1', id: 'Takikardia supraventrikular (SVT)', en: 'Supraventricular tachycardia', chapter: 'Kardiovaskular' },
  { code: 'I49.0', id: 'Fibrilasi & flutter ventrikel', en: 'Ventricular fibrillation and flutter', chapter: 'Kardiovaskular' },
  { code: 'I44.2', id: 'Blok atrioventrikular total', en: 'Complete atrioventricular block', chapter: 'Kardiovaskular' },
  { code: 'I60.9', id: 'Perdarahan subaraknoid', en: 'Subarachnoid haemorrhage', chapter: 'Kardiovaskular' },
  { code: 'I61.9', id: 'Stroke perdarahan intraserebral', en: 'Intracerebral haemorrhage', chapter: 'Kardiovaskular' },
  { code: 'I73.9', id: 'Penyakit arteri perifer', en: 'Peripheral vascular disease', chapter: 'Kardiovaskular' },
  { code: 'I80.2', id: 'Trombosis vena dalam tungkai (DVT)', en: 'Deep vein thrombosis of lower extremity', chapter: 'Kardiovaskular' },
  { code: 'I84.9', id: 'Hemoroid', en: 'Haemorrhoids', chapter: 'Kardiovaskular' },
  { code: 'I01.9', id: 'Demam reumatik akut dengan keterlibatan jantung', en: 'Acute rheumatic heart disease', chapter: 'Kardiovaskular' },
  { code: 'I05.0', id: 'Stenosis mitral reumatik', en: 'Rheumatic mitral stenosis', chapter: 'Kardiovaskular' },
  // Endokrin & metabolik
  { code: 'E10.1', id: 'DM tipe 1 dengan ketoasidosis', en: 'Type 1 diabetes with ketoacidosis', chapter: 'Endokrin & Metabolik' },
  { code: 'E11.0', id: 'DM tipe 2 dengan koma hiperosmolar', en: 'Type 2 diabetes with hyperosmolar coma', chapter: 'Endokrin & Metabolik' },
  { code: 'E11.6', id: 'DM tipe 2 dengan kaki diabetik', en: 'Type 2 diabetes with other specified complications', chapter: 'Endokrin & Metabolik' },
  { code: 'E16.2', id: 'Hipoglikemia', en: 'Hypoglycaemia, unspecified', chapter: 'Endokrin & Metabolik' },
  { code: 'E05.5', id: 'Krisis tiroid (badai tiroid)', en: 'Thyroid crisis or storm', chapter: 'Endokrin & Metabolik' },
  { code: 'E01.0', id: 'Goiter difus akibat defisiensi yodium', en: 'Iodine-deficiency diffuse goitre', chapter: 'Endokrin & Metabolik' },
  { code: 'E27.1', id: 'Insufisiensi adrenokortikal primer (Addison)', en: 'Primary adrenocortical insufficiency', chapter: 'Endokrin & Metabolik' },
  { code: 'E24.9', id: 'Sindrom Cushing', en: 'Cushing syndrome', chapter: 'Endokrin & Metabolik' },
  { code: 'E87.6', id: 'Hipokalemia', en: 'Hypokalaemia', chapter: 'Endokrin & Metabolik' },
  { code: 'E87.5', id: 'Hiperkalemia', en: 'Hyperkalaemia', chapter: 'Endokrin & Metabolik' },
  { code: 'E87.1', id: 'Hiponatremia', en: 'Hypo-osmolality and hyponatraemia', chapter: 'Endokrin & Metabolik' },
  { code: 'E87.2', id: 'Asidosis', en: 'Acidosis', chapter: 'Endokrin & Metabolik' },
  // Saluran cerna
  { code: 'K25.0', id: 'Ulkus lambung akut dengan perdarahan', en: 'Acute gastric ulcer with haemorrhage', chapter: 'Saluran Cerna' },
  { code: 'K30', id: 'Dispepsia fungsional', en: 'Functional dyspepsia', chapter: 'Saluran Cerna' },
  { code: 'K44.9', id: 'Hernia diafragma', en: 'Diaphragmatic hernia', chapter: 'Saluran Cerna' },
  { code: 'K42.9', id: 'Hernia umbilikalis', en: 'Umbilical hernia', chapter: 'Saluran Cerna' },
  { code: 'K56.6', id: 'Obstruksi usus', en: 'Intestinal obstruction', chapter: 'Saluran Cerna' },
  { code: 'K57.9', id: 'Penyakit divertikular usus', en: 'Diverticular disease of intestine', chapter: 'Saluran Cerna' },
  { code: 'K60.2', id: 'Fisura ani', en: 'Anal fissure', chapter: 'Saluran Cerna' },
  { code: 'K61.0', id: 'Abses anal', en: 'Anal abscess', chapter: 'Saluran Cerna' },
  { code: 'K70.3', id: 'Sirosis hati alkoholik', en: 'Alcoholic cirrhosis of liver', chapter: 'Saluran Cerna' },
  { code: 'K72.9', id: 'Gagal hati', en: 'Hepatic failure', chapter: 'Saluran Cerna' },
  { code: 'K81.0', id: 'Kolesistitis akut', en: 'Acute cholecystitis', chapter: 'Saluran Cerna' },
  { code: 'K85.9', id: 'Pankreatitis akut', en: 'Acute pancreatitis', chapter: 'Saluran Cerna' },
  { code: 'K92.2', id: 'Perdarahan saluran cerna', en: 'Gastrointestinal haemorrhage', chapter: 'Saluran Cerna' },
  { code: 'K11.5', id: 'Sialolitiasis', en: 'Sialolithiasis', chapter: 'Saluran Cerna' },
  { code: 'K12.0', id: 'Stomatitis aftosa (sariawan)', en: 'Recurrent oral aphthae', chapter: 'Saluran Cerna' },
  // Ginjal & kemih
  { code: 'N10', id: 'Pielonefritis akut', en: 'Acute tubulo-interstitial nephritis', chapter: 'Ginjal & Kemih' },
  { code: 'N30.0', id: 'Sistitis akut', en: 'Acute cystitis', chapter: 'Ginjal & Kemih' },
  { code: 'N34.2', id: 'Uretritis', en: 'Other urethritis', chapter: 'Ginjal & Kemih' },
  { code: 'N04.9', id: 'Sindrom nefrotik', en: 'Nephrotic syndrome', chapter: 'Ginjal & Kemih' },
  { code: 'N00.9', id: 'Sindrom nefritik akut', en: 'Acute nephritic syndrome', chapter: 'Ginjal & Kemih' },
  { code: 'N45.9', id: 'Orkitis & epididimitis', en: 'Orchitis and epididymitis', chapter: 'Ginjal & Kemih' },
  { code: 'N44', id: 'Torsio testis', en: 'Torsion of testis', chapter: 'Ginjal & Kemih' },
  { code: 'N47', id: 'Fimosis & parafimosis', en: 'Redundant prepuce, phimosis and paraphimosis', chapter: 'Ginjal & Kemih' },
  { code: 'N48.3', id: 'Priapismus', en: 'Priapism', chapter: 'Ginjal & Kemih' },
  { code: 'R33', id: 'Retensi urin', en: 'Retention of urine', chapter: 'Ginjal & Kemih' },
  // Muskuloskeletal & cedera
  { code: 'M51.1', id: 'HNP lumbal dengan radikulopati', en: 'Lumbar disc disorder with radiculopathy', chapter: 'Muskuloskeletal' },
  { code: 'M75.1', id: 'Sindrom rotator cuff', en: 'Rotator cuff syndrome', chapter: 'Muskuloskeletal' },
  { code: 'M77.1', id: 'Epikondilitis lateral (tennis elbow)', en: 'Lateral epicondylitis', chapter: 'Muskuloskeletal' },
  { code: 'M65.9', id: 'Sinovitis & tenosinovitis', en: 'Synovitis and tenosynovitis', chapter: 'Muskuloskeletal' },
  { code: 'G56.0', id: 'Sindrom terowongan karpal', en: 'Carpal tunnel syndrome', chapter: 'Muskuloskeletal' },
  { code: 'M86.9', id: 'Osteomielitis', en: 'Osteomyelitis', chapter: 'Muskuloskeletal' },
  { code: 'S06.0', id: 'Komosio serebri (gegar otak)', en: 'Concussion', chapter: 'Muskuloskeletal' },
  { code: 'S72.0', id: 'Fraktur leher femur', en: 'Fracture of neck of femur', chapter: 'Muskuloskeletal' },
  { code: 'S42.3', id: 'Fraktur batang humerus', en: 'Fracture of shaft of humerus', chapter: 'Muskuloskeletal' },
  { code: 'S82.6', id: 'Fraktur maleolus lateral', en: 'Fracture of lateral malleolus', chapter: 'Muskuloskeletal' },
  { code: 'S93.4', id: 'Sprain pergelangan kaki', en: 'Sprain of ankle', chapter: 'Muskuloskeletal' },
  { code: 'S43.0', id: 'Dislokasi bahu', en: 'Dislocation of shoulder joint', chapter: 'Muskuloskeletal' },
  { code: 'T14.1', id: 'Luka terbuka (vulnus)', en: 'Open wound of unspecified body region', chapter: 'Muskuloskeletal' },
  { code: 'T30.0', id: 'Luka bakar', en: 'Burn of unspecified body region', chapter: 'Muskuloskeletal' },
  { code: 'T63.0', id: 'Gigitan ular berbisa', en: 'Toxic effect of snake venom', chapter: 'Muskuloskeletal' },
  { code: 'T78.2', id: 'Syok anafilaktik', en: 'Anaphylactic shock', chapter: 'Muskuloskeletal' },
  { code: 'T75.1', id: 'Tenggelam & submersi tidak fatal', en: 'Drowning and nonfatal submersion', chapter: 'Muskuloskeletal' },
  { code: 'T67.0', id: 'Heat stroke', en: 'Heatstroke and sunstroke', chapter: 'Muskuloskeletal' },
  { code: 'T68', id: 'Hipotermia', en: 'Hypothermia', chapter: 'Muskuloskeletal' },
  { code: 'T17.9', id: 'Benda asing saluran napas', en: 'Foreign body in respiratory tract', chapter: 'Muskuloskeletal' },
  // Saraf
  { code: 'G00.9', id: 'Meningitis bakterial', en: 'Bacterial meningitis', chapter: 'Saraf' },
  { code: 'G04.9', id: 'Ensefalitis', en: 'Encephalitis, unspecified', chapter: 'Saraf' },
  { code: 'G41.9', id: 'Status epileptikus', en: 'Status epilepticus', chapter: 'Saraf' },
  { code: 'G45.9', id: 'Serangan iskemik sepintas (TIA)', en: 'Transient cerebral ischaemic attack', chapter: 'Saraf' },
  { code: 'G51.0', id: 'Bell palsy', en: 'Bell palsy', chapter: 'Saraf' },
  { code: 'G50.0', id: 'Neuralgia trigeminus', en: 'Trigeminal neuralgia', chapter: 'Saraf' },
  { code: 'G61.0', id: 'Sindrom Guillain-Barré', en: 'Guillain-Barre syndrome', chapter: 'Saraf' },
  { code: 'G20', id: 'Penyakit Parkinson', en: 'Parkinson disease', chapter: 'Saraf' },
  { code: 'G35', id: 'Sklerosis multipel', en: 'Multiple sclerosis', chapter: 'Saraf' },
  { code: 'G47.3', id: 'Apnea tidur', en: 'Sleep apnoea', chapter: 'Saraf' },
  { code: 'R40.2', id: 'Koma', en: 'Coma, unspecified', chapter: 'Saraf' },
  { code: 'R56.0', id: 'Kejang demam', en: 'Febrile convulsions', chapter: 'Saraf' },
  // Jiwa
  { code: 'F31.9', id: 'Gangguan bipolar', en: 'Bipolar affective disorder', chapter: 'Kesehatan Jiwa' },
  { code: 'F05.9', id: 'Delirium', en: 'Delirium, unspecified', chapter: 'Kesehatan Jiwa' },
  { code: 'F03', id: 'Demensia', en: 'Unspecified dementia', chapter: 'Kesehatan Jiwa' },
  { code: 'F10.2', id: 'Ketergantungan alkohol', en: 'Alcohol dependence syndrome', chapter: 'Kesehatan Jiwa' },
  { code: 'F17.2', id: 'Ketergantungan nikotin', en: 'Nicotine dependence', chapter: 'Kesehatan Jiwa' },
  { code: 'F45.9', id: 'Gangguan somatoform', en: 'Somatoform disorder', chapter: 'Kesehatan Jiwa' },
  { code: 'F50.0', id: 'Anoreksia nervosa', en: 'Anorexia nervosa', chapter: 'Kesehatan Jiwa' },
  { code: 'F90.9', id: 'Gangguan pemusatan perhatian & hiperaktivitas (ADHD)', en: 'Hyperkinetic disorder', chapter: 'Kesehatan Jiwa' },
  { code: 'F84.0', id: 'Autisme masa kanak', en: 'Childhood autism', chapter: 'Kesehatan Jiwa' },
  // Kulit
  { code: 'L01.0', id: 'Impetigo', en: 'Impetigo', chapter: 'Kulit' },
  { code: 'L02.9', id: 'Abses kulit, furunkel & karbunkel', en: 'Cutaneous abscess, furuncle and carbuncle', chapter: 'Kulit' },
  { code: 'L03.9', id: 'Selulitis', en: 'Cellulitis', chapter: 'Kulit' },
  { code: 'L21.9', id: 'Dermatitis seboroik', en: 'Seborrhoeic dermatitis', chapter: 'Kulit' },
  { code: 'L24.9', id: 'Dermatitis kontak iritan', en: 'Irritant contact dermatitis', chapter: 'Kulit' },
  { code: 'L30.9', id: 'Dermatitis numularis', en: 'Dermatitis, unspecified', chapter: 'Kulit' },
  { code: 'L43.9', id: 'Liken planus', en: 'Lichen planus', chapter: 'Kulit' },
  { code: 'L51.1', id: 'Sindrom Stevens-Johnson', en: 'Stevens-Johnson syndrome', chapter: 'Kulit' },
  { code: 'L80', id: 'Vitiligo', en: 'Vitiligo', chapter: 'Kulit' },
  { code: 'L89.9', id: 'Ulkus dekubitus', en: 'Pressure ulcer', chapter: 'Kulit' },
  { code: 'B36.0', id: 'Pitiriasis versikolor (panu)', en: 'Pityriasis versicolor', chapter: 'Kulit' },
  { code: 'B07', id: 'Veruka vulgaris (kutil)', en: 'Viral warts', chapter: 'Kulit' },
  // Mata & THT
  { code: 'H00.0', id: 'Hordeolum (bintitan)', en: 'Hordeolum', chapter: 'Mata & THT' },
  { code: 'H01.0', id: 'Blefaritis', en: 'Blepharitis', chapter: 'Mata & THT' },
  { code: 'H16.0', id: 'Ulkus kornea', en: 'Corneal ulcer', chapter: 'Mata & THT' },
  { code: 'H20.9', id: 'Uveitis anterior', en: 'Iridocyclitis', chapter: 'Mata & THT' },
  { code: 'H33.2', id: 'Ablasio retina', en: 'Retinal detachment', chapter: 'Mata & THT' },
  { code: 'H36.0', id: 'Retinopati diabetik', en: 'Diabetic retinopathy', chapter: 'Mata & THT' },
  { code: 'H52.1', id: 'Miopia', en: 'Myopia', chapter: 'Mata & THT' },
  { code: 'H52.4', id: 'Presbiopia', en: 'Presbyopia', chapter: 'Mata & THT' },
  { code: 'H11.0', id: 'Pterigium', en: 'Pterygium', chapter: 'Mata & THT' },
  { code: 'H61.2', id: 'Serumen obturans', en: 'Impacted cerumen', chapter: 'Mata & THT' },
  { code: 'H65.9', id: 'Otitis media non-supuratif (OME)', en: 'Nonsuppurative otitis media', chapter: 'Mata & THT' },
  { code: 'H72.0', id: 'Perforasi membran timpani', en: 'Central perforation of tympanic membrane', chapter: 'Mata & THT' },
  { code: 'H81.0', id: 'Penyakit Meniere', en: 'Meniere disease', chapter: 'Mata & THT' },
  { code: 'H90.3', id: 'Tuli sensorineural', en: 'Sensorineural hearing loss', chapter: 'Mata & THT' },
  { code: 'H93.1', id: 'Tinitus', en: 'Tinnitus', chapter: 'Mata & THT' },
  { code: 'R04.0', id: 'Epistaksis (mimisan)', en: 'Epistaxis', chapter: 'Mata & THT' },
  { code: 'J34.2', id: 'Deviasi septum nasi', en: 'Deviated nasal septum', chapter: 'Mata & THT' },
  // Darah & gizi
  { code: 'D53.1', id: 'Anemia megaloblastik', en: 'Other megaloblastic anaemias', chapter: 'Darah & Gizi' },
  { code: 'D56.9', id: 'Talasemia', en: 'Thalassaemia', chapter: 'Darah & Gizi' },
  { code: 'D57.1', id: 'Anemia sel sabit', en: 'Sickle-cell disease without crisis', chapter: 'Darah & Gizi' },
  { code: 'D59.9', id: 'Anemia hemolitik didapat', en: 'Acquired haemolytic anaemia', chapter: 'Darah & Gizi' },
  { code: 'D69.3', id: 'Purpura trombositopenik imun (ITP)', en: 'Immune thrombocytopenic purpura', chapter: 'Darah & Gizi' },
  { code: 'D66', id: 'Hemofilia A', en: 'Hereditary factor VIII deficiency', chapter: 'Darah & Gizi' },
  { code: 'C92.0', id: 'Leukemia mieloblastik akut', en: 'Acute myeloblastic leukaemia', chapter: 'Darah & Gizi' },
  { code: 'E43', id: 'Malnutrisi energi-protein berat', en: 'Severe protein-energy malnutrition', chapter: 'Darah & Gizi' },
  { code: 'E40', id: 'Kwashiorkor', en: 'Kwashiorkor', chapter: 'Darah & Gizi' },
  { code: 'E41', id: 'Marasmus', en: 'Nutritional marasmus', chapter: 'Darah & Gizi' },
  { code: 'E50.9', id: 'Defisiensi vitamin A', en: 'Vitamin A deficiency', chapter: 'Darah & Gizi' },
  { code: 'E51.1', id: 'Beri-beri (defisiensi tiamin)', en: 'Beriberi', chapter: 'Darah & Gizi' },
  { code: 'E53.8', id: 'Defisiensi vitamin B12', en: 'Deficiency of other specified B group vitamins', chapter: 'Darah & Gizi' },
  // Ob-gyn
  { code: 'O03.9', id: 'Abortus spontan', en: 'Spontaneous abortion', chapter: 'Obstetri & Ginekologi' },
  { code: 'O00.1', id: 'Kehamilan ektopik tuba', en: 'Tubal pregnancy', chapter: 'Obstetri & Ginekologi' },
  { code: 'O15.9', id: 'Eklampsia', en: 'Eclampsia', chapter: 'Obstetri & Ginekologi' },
  { code: 'O21.0', id: 'Hiperemesis gravidarum ringan', en: 'Mild hyperemesis gravidarum', chapter: 'Obstetri & Ginekologi' },
  { code: 'O44.1', id: 'Plasenta previa dengan perdarahan', en: 'Placenta praevia with haemorrhage', chapter: 'Obstetri & Ginekologi' },
  { code: 'O45.9', id: 'Solusio plasenta', en: 'Premature separation of placenta', chapter: 'Obstetri & Ginekologi' },
  { code: 'O72.1', id: 'Perdarahan pascapersalinan (HPP)', en: 'Other immediate postpartum haemorrhage', chapter: 'Obstetri & Ginekologi' },
  { code: 'O42.9', id: 'Ketuban pecah dini', en: 'Premature rupture of membranes', chapter: 'Obstetri & Ginekologi' },
  { code: 'O24.4', id: 'Diabetes melitus gestasional', en: 'Diabetes mellitus arising in pregnancy', chapter: 'Obstetri & Ginekologi' },
  { code: 'O99.0', id: 'Anemia dalam kehamilan', en: 'Anaemia complicating pregnancy', chapter: 'Obstetri & Ginekologi' },
  { code: 'N70.9', id: 'Salpingo-ooforitis', en: 'Salpingitis and oophoritis', chapter: 'Obstetri & Ginekologi' },
  { code: 'N73.9', id: 'Penyakit radang panggul (PID)', en: 'Female pelvic inflammatory disease', chapter: 'Obstetri & Ginekologi' },
  { code: 'N80.9', id: 'Endometriosis', en: 'Endometriosis', chapter: 'Obstetri & Ginekologi' },
  { code: 'N83.2', id: 'Kista ovarium', en: 'Ovarian cyst', chapter: 'Obstetri & Ginekologi' },
  { code: 'D25.9', id: 'Mioma uteri', en: 'Leiomyoma of uterus', chapter: 'Obstetri & Ginekologi' },
  { code: 'N92.0', id: 'Menoragia', en: 'Excessive menstruation with regular cycle', chapter: 'Obstetri & Ginekologi' },
  { code: 'N94.6', id: 'Dismenorea', en: 'Dysmenorrhoea', chapter: 'Obstetri & Ginekologi' },
  { code: 'E28.2', id: 'Sindrom ovarium polikistik (PCOS)', en: 'Polycystic ovarian syndrome', chapter: 'Obstetri & Ginekologi' },
  { code: 'N61', id: 'Mastitis', en: 'Inflammatory disorders of breast', chapter: 'Obstetri & Ginekologi' },
  { code: 'C50.9', id: 'Kanker payudara', en: 'Malignant neoplasm of breast', chapter: 'Obstetri & Ginekologi' },
  { code: 'C53.9', id: 'Kanker serviks', en: 'Malignant neoplasm of cervix uteri', chapter: 'Obstetri & Ginekologi' },
  // Anak & neonatus
  { code: 'P59.9', id: 'Ikterus neonatorum', en: 'Neonatal jaundice', chapter: 'Anak' },
  { code: 'P36.9', id: 'Sepsis neonatorum', en: 'Bacterial sepsis of newborn', chapter: 'Anak' },
  { code: 'P21.9', id: 'Asfiksia lahir', en: 'Birth asphyxia', chapter: 'Anak' },
  { code: 'P22.0', id: 'Sindrom gawat napas neonatus', en: 'Respiratory distress syndrome of newborn', chapter: 'Anak' },
  { code: 'P07.1', id: 'Berat lahir rendah', en: 'Other low birth weight', chapter: 'Anak' },
  { code: 'R62.8', id: 'Gagal tumbuh & perawakan pendek (stunting)', en: 'Other lack of expected normal development', chapter: 'Anak' },
  { code: 'Q21.0', id: 'Defek septum ventrikel (VSD)', en: 'Ventricular septal defect', chapter: 'Anak' },
  { code: 'Q25.0', id: 'Duktus arteriosus persisten (PDA)', en: 'Patent ductus arteriosus', chapter: 'Anak' },
  { code: 'Q21.3', id: 'Tetralogi Fallot', en: 'Tetralogy of Fallot', chapter: 'Anak' },
  { code: 'Q35.9', id: 'Palatoskisis (celah langit-langit)', en: 'Cleft palate', chapter: 'Anak' },
  { code: 'Q37.9', id: 'Labiopalatoskisis', en: 'Cleft palate with cleft lip', chapter: 'Anak' },
  { code: 'Q53.9', id: 'Kriptorkismus (testis tidak turun)', en: 'Undescended testicle', chapter: 'Anak' },
  { code: 'Q40.0', id: 'Stenosis pilorus hipertrofik', en: 'Congenital hypertrophic pyloric stenosis', chapter: 'Anak' },
  { code: 'Q90.9', id: 'Sindrom Down', en: 'Down syndrome', chapter: 'Anak' },
  // Gejala & tanda umum
  { code: 'R60.0', id: 'Edema setempat', en: 'Localized oedema', chapter: 'Gejala Umum' },
  { code: 'R63.4', id: 'Penurunan berat badan tidak wajar', en: 'Abnormal weight loss', chapter: 'Gejala Umum' },
  { code: 'R57.0', id: 'Syok kardiogenik', en: 'Cardiogenic shock', chapter: 'Gejala Umum' },
  { code: 'R57.1', id: 'Syok hipovolemik', en: 'Hypovolaemic shock', chapter: 'Gejala Umum' },
  { code: 'R06.0', id: 'Dispnea (sesak napas)', en: 'Dyspnoea', chapter: 'Gejala Umum' },
  { code: 'R04.2', id: 'Hemoptisis (batuk darah)', en: 'Haemoptysis', chapter: 'Gejala Umum' },
  { code: 'R17', id: 'Ikterus', en: 'Unspecified jaundice', chapter: 'Gejala Umum' },
  { code: 'R18', id: 'Asites', en: 'Ascites', chapter: 'Gejala Umum' },
  { code: 'R19.0', id: 'Massa & benjolan perut', en: 'Intra-abdominal swelling, mass and lump', chapter: 'Gejala Umum' },
  { code: 'R31', id: 'Hematuria', en: 'Unspecified haematuria', chapter: 'Gejala Umum' },
  { code: 'R59.9', id: 'Pembesaran kelenjar getah bening', en: 'Enlarged lymph nodes', chapter: 'Gejala Umum' },
  { code: 'R73.9', id: 'Hiperglikemia', en: 'Hyperglycaemia, unspecified', chapter: 'Gejala Umum' },
  // Pemeriksaan & pencegahan
  { code: 'Z23', id: 'Kontak untuk imunisasi', en: 'Encounter for immunization', chapter: 'Pemeriksaan' },
  { code: 'Z34.9', id: 'Pengawasan kehamilan normal', en: 'Supervision of normal pregnancy', chapter: 'Pemeriksaan' },
  { code: 'Z30.9', id: 'Kontrasepsi', en: 'Encounter for contraceptive management', chapter: 'Pemeriksaan' },
  { code: 'Z71.3', id: 'Konseling & pengawasan diet', en: 'Dietary counselling and surveillance', chapter: 'Pemeriksaan' },
  { code: 'Z20.9', id: 'Kontak dengan penyakit menular', en: 'Contact with communicable disease', chapter: 'Pemeriksaan' },
  // ── Tambahan kedua: bab yang masih tipis dan kode yang sering dipakai ──
  // Infeksi
  { code: 'A04.7', id: 'Enterokolitis Clostridioides difficile', en: 'Enterocolitis due to C. difficile', chapter: 'Infeksi' },
  { code: 'A05.9', id: 'Keracunan makanan bakterial', en: 'Bacterial foodborne intoxication', chapter: 'Infeksi' },
  { code: 'A18.0', id: 'TB tulang dan sendi', en: 'Tuberculosis of bones and joints', chapter: 'Infeksi' },
  { code: 'A18.2', id: 'Limfadenitis tuberkulosis', en: 'Tuberculous peripheral lymphadenopathy', chapter: 'Infeksi' },
  { code: 'A19.9', id: 'TB milier', en: 'Miliary tuberculosis', chapter: 'Infeksi' },
  { code: 'A23.9', id: 'Bruselosis', en: 'Brucellosis', chapter: 'Infeksi' },
  { code: 'A38', id: 'Demam skarlatina', en: 'Scarlet fever', chapter: 'Infeksi' },
  { code: 'A48.0', id: 'Gangren gas', en: 'Gas gangrene', chapter: 'Infeksi' },
  { code: 'A49.0', id: 'Infeksi stafilokokus', en: 'Staphylococcal infection', chapter: 'Infeksi' },
  { code: 'A56.0', id: 'Infeksi klamidia saluran genitourinaria bawah', en: 'Chlamydial infection of lower genitourinary tract', chapter: 'Infeksi' },
  { code: 'A59.0', id: 'Trikomoniasis urogenital', en: 'Urogenital trichomoniasis', chapter: 'Infeksi' },
  { code: 'A60.0', id: 'Herpes genital', en: 'Herpesviral infection of genitalia', chapter: 'Infeksi' },
  { code: 'A64', id: 'Penyakit menular seksual tidak ditentukan', en: 'Unspecified sexually transmitted disease', chapter: 'Infeksi' },
  { code: 'A75.9', id: 'Tifus (riketsiosis)', en: 'Typhus fever', chapter: 'Infeksi' },
  { code: 'A87.9', id: 'Meningitis virus', en: 'Viral meningitis', chapter: 'Infeksi' },
  { code: 'A98.4', id: 'Demam berdarah Ebola', en: 'Ebola virus disease', chapter: 'Infeksi' },
  { code: 'B08.4', id: 'Penyakit tangan-kaki-mulut', en: 'Hand, foot and mouth disease', chapter: 'Infeksi' },
  { code: 'B15.9', id: 'Hepatitis A', en: 'Hepatitis A without hepatic coma', chapter: 'Infeksi' },
  { code: 'B16.9', id: 'Hepatitis B akut', en: 'Acute hepatitis B', chapter: 'Infeksi' },
  { code: 'B18.1', id: 'Hepatitis B kronik', en: 'Chronic viral hepatitis B', chapter: 'Infeksi' },
  { code: 'B18.2', id: 'Hepatitis C kronik', en: 'Chronic viral hepatitis C', chapter: 'Infeksi' },
  { code: 'B24', id: 'HIV tanpa keterangan', en: 'Unspecified HIV disease', chapter: 'Infeksi' },
  { code: 'B44.9', id: 'Aspergilosis', en: 'Aspergillosis', chapter: 'Infeksi' },
  { code: 'B49', id: 'Mikosis tidak ditentukan', en: 'Unspecified mycosis', chapter: 'Infeksi' },
  { code: 'B55.1', id: 'Leishmaniasis kutis', en: 'Cutaneous leishmaniasis', chapter: 'Infeksi' },
  { code: 'B58.9', id: 'Toksoplasmosis', en: 'Toxoplasmosis', chapter: 'Infeksi' },
  { code: 'B65.9', id: 'Skistosomiasis', en: 'Schistosomiasis', chapter: 'Infeksi' },
  { code: 'B68.9', id: 'Teniasis (cacing pita)', en: 'Taeniasis', chapter: 'Infeksi' },
  { code: 'B80', id: 'Enterobiasis (cacing kremi)', en: 'Enterobiasis', chapter: 'Infeksi' },
  { code: 'B85.0', id: 'Pedikulosis kapitis (kutu kepala)', en: 'Pediculosis due to head louse', chapter: 'Infeksi' },
  { code: 'B99', id: 'Penyakit infeksi tidak ditentukan', en: 'Unspecified infectious disease', chapter: 'Infeksi' },
  // Pernapasan
  { code: 'J04.0', id: 'Laringitis akut', en: 'Acute laryngitis', chapter: 'Pernapasan' },
  { code: 'J04.1', id: 'Trakeitis akut', en: 'Acute tracheitis', chapter: 'Pernapasan' },
  { code: 'J13', id: 'Pneumonia pneumokokus', en: 'Pneumonia due to Streptococcus pneumoniae', chapter: 'Pernapasan' },
  { code: 'J17.0', id: 'Pneumonia pada penyakit bakteri', en: 'Pneumonia in bacterial diseases', chapter: 'Pernapasan' },
  { code: 'J31.0', id: 'Rinitis kronik', en: 'Chronic rhinitis', chapter: 'Pernapasan' },
  { code: 'J33.9', id: 'Polip hidung', en: 'Nasal polyp', chapter: 'Pernapasan' },
  { code: 'J36', id: 'Abses peritonsilar', en: 'Peritonsillar abscess', chapter: 'Pernapasan' },
  { code: 'J39.0', id: 'Abses retrofaring', en: 'Retropharyngeal abscess', chapter: 'Pernapasan' },
  { code: 'J42', id: 'Bronkitis kronik', en: 'Unspecified chronic bronchitis', chapter: 'Pernapasan' },
  { code: 'J44.1', id: 'PPOK eksaserbasi akut', en: 'COPD with acute exacerbation', chapter: 'Pernapasan' },
  { code: 'J45.0', id: 'Asma alergi', en: 'Predominantly allergic asthma', chapter: 'Pernapasan' },
  { code: 'J69.0', id: 'Pneumonia aspirasi', en: 'Pneumonitis due to food and vomit', chapter: 'Pernapasan' },
  { code: 'J80', id: 'Sindrom gawat napas akut (ARDS)', en: 'Adult respiratory distress syndrome', chapter: 'Pernapasan' },
  { code: 'J86.9', id: 'Empiema toraks', en: 'Pyothorax without fistula', chapter: 'Pernapasan' },
  { code: 'J98.1', id: 'Kolaps paru (atelektasis)', en: 'Pulmonary collapse', chapter: 'Pernapasan' },
  { code: 'J96.1', id: 'Gagal napas kronik', en: 'Chronic respiratory failure', chapter: 'Pernapasan' },
  { code: 'C34.9', id: 'Kanker paru', en: 'Malignant neoplasm of bronchus and lung', chapter: 'Pernapasan' },
  // Kardiovaskular
  { code: 'I15.0', id: 'Hipertensi renovaskular', en: 'Renovascular hypertension', chapter: 'Kardiovaskular' },
  { code: 'I12.0', id: 'Penyakit ginjal hipertensif dengan gagal ginjal', en: 'Hypertensive renal disease with renal failure', chapter: 'Kardiovaskular' },
  { code: 'I24.9', id: 'Penyakit jantung iskemik akut', en: 'Acute ischaemic heart disease', chapter: 'Kardiovaskular' },
  { code: 'I27.0', id: 'Hipertensi pulmonal primer', en: 'Primary pulmonary hypertension', chapter: 'Kardiovaskular' },
  { code: 'I30.9', id: 'Perikarditis akut', en: 'Acute pericarditis', chapter: 'Kardiovaskular' },
  { code: 'I31.9', id: 'Efusi perikard / tamponade', en: 'Disease of pericardium, unspecified', chapter: 'Kardiovaskular' },
  { code: 'I33.0', id: 'Endokarditis infektif akut', en: 'Acute infective endocarditis', chapter: 'Kardiovaskular' },
  { code: 'I35.0', id: 'Stenosis aorta', en: 'Aortic valve stenosis', chapter: 'Kardiovaskular' },
  { code: 'I34.0', id: 'Regurgitasi mitral', en: 'Mitral valve insufficiency', chapter: 'Kardiovaskular' },
  { code: 'I40.9', id: 'Miokarditis akut', en: 'Acute myocarditis', chapter: 'Kardiovaskular' },
  { code: 'I42.0', id: 'Kardiomiopati dilatasi', en: 'Dilated cardiomyopathy', chapter: 'Kardiovaskular' },
  { code: 'I42.1', id: 'Kardiomiopati hipertrofik obstruktif', en: 'Obstructive hypertrophic cardiomyopathy', chapter: 'Kardiovaskular' },
  { code: 'I45.6', id: 'Sindrom pra-eksitasi (WPW)', en: 'Pre-excitation syndrome', chapter: 'Kardiovaskular' },
  { code: 'I47.2', id: 'Takikardia ventrikel', en: 'Ventricular tachycardia', chapter: 'Kardiovaskular' },
  { code: 'I49.5', id: 'Sindrom sinus sakit', en: 'Sick sinus syndrome', chapter: 'Kardiovaskular' },
  { code: 'I71.0', id: 'Diseksi aorta', en: 'Dissection of aorta', chapter: 'Kardiovaskular' },
  { code: 'I74.3', id: 'Emboli arteri tungkai', en: 'Embolism of arteries of lower extremities', chapter: 'Kardiovaskular' },
  { code: 'I95.1', id: 'Hipotensi ortostatik', en: 'Orthostatic hypotension', chapter: 'Kardiovaskular' },
  // Endokrin & metabolik
  { code: 'E04.1', id: 'Nodul tiroid soliter non-toksik', en: 'Nontoxic single thyroid nodule', chapter: 'Endokrin & Metabolik' },
  { code: 'E06.3', id: 'Tiroiditis autoimun (Hashimoto)', en: 'Autoimmune thyroiditis', chapter: 'Endokrin & Metabolik' },
  { code: 'E05.0', id: 'Penyakit Graves', en: 'Thyrotoxicosis with diffuse goitre', chapter: 'Endokrin & Metabolik' },
  { code: 'E21.0', id: 'Hiperparatiroidisme primer', en: 'Primary hyperparathyroidism', chapter: 'Endokrin & Metabolik' },
  { code: 'E20.9', id: 'Hipoparatiroidisme', en: 'Hypoparathyroidism', chapter: 'Endokrin & Metabolik' },
  { code: 'E22.0', id: 'Akromegali', en: 'Acromegaly and pituitary gigantism', chapter: 'Endokrin & Metabolik' },
  { code: 'E23.2', id: 'Diabetes insipidus sentral', en: 'Diabetes insipidus', chapter: 'Endokrin & Metabolik' },
  { code: 'E26.0', id: 'Hiperaldosteronisme primer (Conn)', en: 'Primary hyperaldosteronism', chapter: 'Endokrin & Metabolik' },
  { code: 'E27.5', id: 'Feokromositoma (hiperfungsi medula adrenal)', en: 'Adrenomedullary hyperfunction', chapter: 'Endokrin & Metabolik' },
  { code: 'E88.9', id: 'Sindrom metabolik', en: 'Metabolic disorder, unspecified', chapter: 'Endokrin & Metabolik' },
  { code: 'E87.0', id: 'Hipernatremia', en: 'Hyperosmolality and hypernatraemia', chapter: 'Endokrin & Metabolik' },
  { code: 'E83.5', id: 'Gangguan metabolisme kalsium', en: 'Disorders of calcium metabolism', chapter: 'Endokrin & Metabolik' },
  // Saluran cerna & hepatobilier
  { code: 'K05.1', id: 'Gingivitis kronik', en: 'Chronic gingivitis', chapter: 'Saluran Cerna' },
  { code: 'K04.7', id: 'Abses periapikal', en: 'Periapical abscess without sinus', chapter: 'Saluran Cerna' },
  { code: 'K02.9', id: 'Karies gigi', en: 'Dental caries, unspecified', chapter: 'Saluran Cerna' },
  { code: 'K20', id: 'Esofagitis', en: 'Oesophagitis', chapter: 'Saluran Cerna' },
  { code: 'K22.6', id: 'Sindrom Mallory-Weiss', en: 'Gastro-oesophageal laceration-haemorrhage', chapter: 'Saluran Cerna' },
  { code: 'K31.8', id: 'Gastroparesis', en: 'Other specified diseases of stomach', chapter: 'Saluran Cerna' },
  { code: 'K50.9', id: 'Penyakit Crohn', en: 'Crohn disease, unspecified', chapter: 'Saluran Cerna' },
  { code: 'K51.9', id: 'Kolitis ulseratif', en: 'Ulcerative colitis, unspecified', chapter: 'Saluran Cerna' },
  { code: 'K55.0', id: 'Iskemia usus akut', en: 'Acute vascular disorders of intestine', chapter: 'Saluran Cerna' },
  { code: 'K56.4', id: 'Volvulus / obstruksi lain', en: 'Other impaction of intestine', chapter: 'Saluran Cerna' },
  { code: 'K58.0', id: 'IBS dengan diare', en: 'Irritable bowel syndrome with diarrhoea', chapter: 'Saluran Cerna' },
  { code: 'K63.1', id: 'Perforasi usus', en: 'Perforation of intestine', chapter: 'Saluran Cerna' },
  { code: 'K65.0', id: 'Peritonitis akut', en: 'Acute peritonitis', chapter: 'Saluran Cerna' },
  { code: 'K71.9', id: 'Penyakit hati akibat obat', en: 'Toxic liver disease', chapter: 'Saluran Cerna' },
  { code: 'K73.9', id: 'Hepatitis kronik', en: 'Chronic hepatitis, unspecified', chapter: 'Saluran Cerna' },
  { code: 'K75.0', id: 'Abses hati', en: 'Abscess of liver', chapter: 'Saluran Cerna' },
  { code: 'K83.0', id: 'Kolangitis', en: 'Cholangitis', chapter: 'Saluran Cerna' },
  { code: 'K86.1', id: 'Pankreatitis kronik', en: 'Other chronic pancreatitis', chapter: 'Saluran Cerna' },
  { code: 'C16.9', id: 'Kanker lambung', en: 'Malignant neoplasm of stomach', chapter: 'Saluran Cerna' },
  { code: 'C18.9', id: 'Kanker kolon', en: 'Malignant neoplasm of colon', chapter: 'Saluran Cerna' },
  { code: 'C22.0', id: 'Karsinoma hepatoseluler', en: 'Liver cell carcinoma', chapter: 'Saluran Cerna' },
  // Ginjal & kemih
  { code: 'N03.9', id: 'Sindrom nefritik kronik', en: 'Chronic nephritic syndrome', chapter: 'Ginjal & Kemih' },
  { code: 'N13.3', id: 'Hidronefrosis', en: 'Other and unspecified hydronephrosis', chapter: 'Ginjal & Kemih' },
  { code: 'N15.9', id: 'Penyakit tubulointerstisial ginjal', en: 'Renal tubulo-interstitial disease', chapter: 'Ginjal & Kemih' },
  { code: 'N21.0', id: 'Batu kandung kemih', en: 'Calculus in bladder', chapter: 'Ginjal & Kemih' },
  { code: 'N28.1', id: 'Kista ginjal', en: 'Cyst of kidney, acquired', chapter: 'Ginjal & Kemih' },
  { code: 'N41.0', id: 'Prostatitis akut', en: 'Acute prostatitis', chapter: 'Ginjal & Kemih' },
  { code: 'N43.3', id: 'Hidrokel', en: 'Hydrocele, unspecified', chapter: 'Ginjal & Kemih' },
  { code: 'N50.8', id: 'Varikokel', en: 'Other specified disorders of male genital organs', chapter: 'Ginjal & Kemih' },
  { code: 'N52.9', id: 'Disfungsi ereksi', en: 'Male erectile dysfunction', chapter: 'Ginjal & Kemih' },
  { code: 'N19', id: 'Gagal ginjal tidak ditentukan', en: 'Unspecified kidney failure', chapter: 'Ginjal & Kemih' },
  { code: 'C61', id: 'Kanker prostat', en: 'Malignant neoplasm of prostate', chapter: 'Ginjal & Kemih' },
  { code: 'C64', id: 'Kanker ginjal', en: 'Malignant neoplasm of kidney', chapter: 'Ginjal & Kemih' },
  // Muskuloskeletal & cedera
  { code: 'M13.9', id: 'Artritis tidak ditentukan', en: 'Arthritis, unspecified', chapter: 'Muskuloskeletal' },
  { code: 'M15.9', id: 'Poliosteoartritis', en: 'Polyarthrosis, unspecified', chapter: 'Muskuloskeletal' },
  { code: 'M16.9', id: 'Osteoartritis panggul', en: 'Coxarthrosis, unspecified', chapter: 'Muskuloskeletal' },
  { code: 'M32.9', id: 'Lupus eritematosus sistemik', en: 'Systemic lupus erythematosus', chapter: 'Muskuloskeletal' },
  { code: 'M45', id: 'Spondilitis ankilosa', en: 'Ankylosing spondylitis', chapter: 'Muskuloskeletal' },
  { code: 'M47.9', id: 'Spondilosis', en: 'Spondylosis, unspecified', chapter: 'Muskuloskeletal' },
  { code: 'M62.8', id: 'Rabdomiolisis', en: 'Other specified disorders of muscle', chapter: 'Muskuloskeletal' },
  { code: 'M70.4', id: 'Bursitis prepatelar', en: 'Prepatellar bursitis', chapter: 'Muskuloskeletal' },
  { code: 'M72.2', id: 'Fasiitis plantaris', en: 'Plantar fascial fibromatosis', chapter: 'Muskuloskeletal' },
  { code: 'M76.6', id: 'Tendinitis Achilles', en: 'Achilles tendinitis', chapter: 'Muskuloskeletal' },
  { code: 'M79.7', id: 'Fibromialgia', en: 'Fibromyalgia', chapter: 'Muskuloskeletal' },
  { code: 'S02.0', id: 'Fraktur atap tengkorak', en: 'Fracture of vault of skull', chapter: 'Muskuloskeletal' },
  { code: 'S06.5', id: 'Perdarahan subdural traumatik', en: 'Traumatic subdural haemorrhage', chapter: 'Muskuloskeletal' },
  { code: 'S06.4', id: 'Perdarahan epidural', en: 'Epidural haemorrhage', chapter: 'Muskuloskeletal' },
  { code: 'S22.4', id: 'Fraktur iga multipel', en: 'Multiple fractures of ribs', chapter: 'Muskuloskeletal' },
  { code: 'S32.0', id: 'Fraktur vertebra lumbal', en: 'Fracture of lumbar vertebra', chapter: 'Muskuloskeletal' },
  { code: 'S52.0', id: 'Fraktur ujung proksimal ulna', en: 'Fracture of upper end of ulna', chapter: 'Muskuloskeletal' },
  { code: 'S62.6', id: 'Fraktur jari tangan', en: 'Fracture of other finger', chapter: 'Muskuloskeletal' },
  { code: 'S72.3', id: 'Fraktur batang femur', en: 'Fracture of shaft of femur', chapter: 'Muskuloskeletal' },
  { code: 'S82.2', id: 'Fraktur batang tibia', en: 'Fracture of shaft of tibia', chapter: 'Muskuloskeletal' },
  { code: 'S83.5', id: 'Sprain ligamen krusiatum lutut', en: 'Sprain of cruciate ligament of knee', chapter: 'Muskuloskeletal' },
  { code: 'T20.2', id: 'Luka bakar derajat 2 kepala dan leher', en: 'Burn of second degree of head and neck', chapter: 'Muskuloskeletal' },
  { code: 'T31.2', id: 'Luka bakar 20-29% permukaan tubuh', en: 'Burns involving 20-29% of body surface', chapter: 'Muskuloskeletal' },
  { code: 'T39.1', id: 'Keracunan parasetamol', en: 'Poisoning by 4-aminophenol derivatives', chapter: 'Muskuloskeletal' },
  { code: 'T40.2', id: 'Keracunan opioid', en: 'Poisoning by other opioids', chapter: 'Muskuloskeletal' },
  { code: 'T60.0', id: 'Keracunan pestisida organofosfat', en: 'Toxic effect of organophosphate insecticides', chapter: 'Muskuloskeletal' },
  { code: 'T58', id: 'Keracunan karbon monoksida', en: 'Toxic effect of carbon monoxide', chapter: 'Muskuloskeletal' },
  { code: 'T51.0', id: 'Keracunan alkohol (etanol)', en: 'Toxic effect of ethanol', chapter: 'Muskuloskeletal' },
  { code: 'T88.7', id: 'Reaksi obat tidak ditentukan', en: 'Unspecified adverse effect of drug', chapter: 'Muskuloskeletal' },
  { code: 'W57', id: 'Gigitan serangga tidak berbisa', en: 'Bitten or stung by nonvenomous insect', chapter: 'Muskuloskeletal' },
  { code: 'W54', id: 'Gigitan anjing', en: 'Bitten or struck by dog', chapter: 'Muskuloskeletal' },
  // Saraf & jiwa
  { code: 'G06.0', id: 'Abses otak', en: 'Intracranial abscess and granuloma', chapter: 'Saraf' },
  { code: 'G12.2', id: 'Penyakit neuron motorik (ALS)', en: 'Motor neuron disease', chapter: 'Saraf' },
  { code: 'G24.9', id: 'Distonia', en: 'Dystonia, unspecified', chapter: 'Saraf' },
  { code: 'G25.0', id: 'Tremor esensial', en: 'Essential tremor', chapter: 'Saraf' },
  { code: 'G40.2', id: 'Epilepsi fokal', en: 'Localization-related symptomatic epilepsy', chapter: 'Saraf' },
  { code: 'G54.1', id: 'Gangguan pleksus lumbosakral', en: 'Lumbosacral plexus disorders', chapter: 'Saraf' },
  { code: 'G70.0', id: 'Miastenia gravis', en: 'Myasthenia gravis', chapter: 'Saraf' },
  { code: 'G91.9', id: 'Hidrosefalus', en: 'Hydrocephalus, unspecified', chapter: 'Saraf' },
  { code: 'G93.6', id: 'Edema serebri', en: 'Cerebral oedema', chapter: 'Saraf' },
  { code: 'G80.9', id: 'Palsi serebral', en: 'Cerebral palsy, unspecified', chapter: 'Saraf' },
  { code: 'F19.2', id: 'Ketergantungan zat psikoaktif multipel', en: 'Multiple drug dependence', chapter: 'Kesehatan Jiwa' },
  { code: 'F23.9', id: 'Gangguan psikotik akut', en: 'Acute and transient psychotic disorder', chapter: 'Kesehatan Jiwa' },
  { code: 'F25.9', id: 'Gangguan skizoafektif', en: 'Schizoaffective disorder', chapter: 'Kesehatan Jiwa' },
  { code: 'F33.9', id: 'Gangguan depresi berulang', en: 'Recurrent depressive disorder', chapter: 'Kesehatan Jiwa' },
  { code: 'F40.1', id: 'Fobia sosial', en: 'Social phobias', chapter: 'Kesehatan Jiwa' },
  { code: 'F42.9', id: 'Gangguan obsesif-kompulsif', en: 'Obsessive-compulsive disorder', chapter: 'Kesehatan Jiwa' },
  { code: 'F51.0', id: 'Insomnia non-organik', en: 'Nonorganic insomnia', chapter: 'Kesehatan Jiwa' },
  { code: 'F53.0', id: 'Depresi pascapersalinan', en: 'Postnatal depression', chapter: 'Kesehatan Jiwa' },
  { code: 'F70.9', id: 'Retardasi mental ringan', en: 'Mild mental retardation', chapter: 'Kesehatan Jiwa' },
  { code: 'X84', id: 'Percobaan bunuh diri', en: 'Intentional self-harm by unspecified means', chapter: 'Kesehatan Jiwa' },
  // Kulit
  { code: 'L04.9', id: 'Limfadenitis akut', en: 'Acute lymphadenitis, unspecified', chapter: 'Kulit' },
  { code: 'L08.9', id: 'Infeksi lokal kulit', en: 'Local infection of skin', chapter: 'Kulit' },
  { code: 'L27.0', id: 'Erupsi obat generalisata', en: 'Generalized skin eruption due to drugs', chapter: 'Kulit' },
  { code: 'L28.0', id: 'Liken simpleks kronikus (neurodermatitis)', en: 'Lichen simplex chronicus', chapter: 'Kulit' },
  { code: 'L42', id: 'Pitiriasis rosea', en: 'Pityriasis rosea', chapter: 'Kulit' },
  { code: 'L53.9', id: 'Eritema tidak ditentukan', en: 'Erythematous condition, unspecified', chapter: 'Kulit' },
  { code: 'L51.2', id: 'Nekrolisis epidermal toksik', en: 'Toxic epidermal necrolysis', chapter: 'Kulit' },
  { code: 'L60.0', id: 'Kuku tumbuh ke dalam', en: 'Ingrowing nail', chapter: 'Kulit' },
  { code: 'L63.9', id: 'Alopesia areata', en: 'Alopecia areata, unspecified', chapter: 'Kulit' },
  { code: 'L71.9', id: 'Rosasea', en: 'Rosacea, unspecified', chapter: 'Kulit' },
  { code: 'L73.9', id: 'Folikulitis', en: 'Follicular disorder, unspecified', chapter: 'Kulit' },
  { code: 'L84', id: 'Klavus dan kalus', en: 'Corns and callosities', chapter: 'Kulit' },
  { code: 'C43.9', id: 'Melanoma maligna kulit', en: 'Malignant melanoma of skin', chapter: 'Kulit' },
  // Mata & THT
  { code: 'H02.0', id: 'Entropion', en: 'Entropion of eyelid', chapter: 'Mata & THT' },
  { code: 'H04.3', id: 'Dakriosistitis akut', en: 'Acute inflammation of lacrimal passages', chapter: 'Mata & THT' },
  { code: 'H10.1', id: 'Konjungtivitis alergi akut', en: 'Acute atopic conjunctivitis', chapter: 'Mata & THT' },
  { code: 'H15.1', id: 'Episkleritis', en: 'Episcleritis', chapter: 'Mata & THT' },
  { code: 'H16.2', id: 'Keratokonjungtivitis sika (mata kering)', en: 'Keratoconjunctivitis sicca', chapter: 'Mata & THT' },
  { code: 'H21.0', id: 'Hifema', en: 'Hyphaema', chapter: 'Mata & THT' },
  { code: 'H35.0', id: 'Retinopati hipertensif', en: 'Background retinopathy', chapter: 'Mata & THT' },
  { code: 'H34.2', id: 'Oklusi arteri retina', en: 'Other retinal artery occlusion', chapter: 'Mata & THT' },
  { code: 'H40.2', id: 'Glaukoma sudut tertutup primer', en: 'Primary angle-closure glaucoma', chapter: 'Mata & THT' },
  { code: 'H44.0', id: 'Endoftalmitis purulen', en: 'Purulent endophthalmitis', chapter: 'Mata & THT' },
  { code: 'H50.0', id: 'Esotropia (juling ke dalam)', en: 'Convergent concomitant strabismus', chapter: 'Mata & THT' },
  { code: 'H52.0', id: 'Hipermetropia', en: 'Hypermetropia', chapter: 'Mata & THT' },
  { code: 'H52.2', id: 'Astigmatisme', en: 'Astigmatism', chapter: 'Mata & THT' },
  { code: 'H54.0', id: 'Kebutaan kedua mata', en: 'Blindness, binocular', chapter: 'Mata & THT' },
  { code: 'H66.1', id: 'Otitis media supuratif kronik', en: 'Chronic tubotympanic suppurative otitis media', chapter: 'Mata & THT' },
  { code: 'H71', id: 'Kolesteatoma telinga tengah', en: 'Cholesteatoma of middle ear', chapter: 'Mata & THT' },
  { code: 'H83.0', id: 'Labirintitis', en: 'Labyrinthitis', chapter: 'Mata & THT' },
  { code: 'H91.2', id: 'Tuli mendadak idiopatik', en: 'Sudden idiopathic hearing loss', chapter: 'Mata & THT' },
  { code: 'J34.0', id: 'Abses dan selulitis hidung', en: 'Abscess, furuncle and carbuncle of nose', chapter: 'Mata & THT' },
  { code: 'T16', id: 'Benda asing di telinga', en: 'Foreign body in ear', chapter: 'Mata & THT' },
  { code: 'T15.0', id: 'Benda asing di kornea', en: 'Foreign body in cornea', chapter: 'Mata & THT' },
  { code: 'T18.1', id: 'Benda asing di esofagus', en: 'Foreign body in oesophagus', chapter: 'Mata & THT' },
  // Darah & gizi
  { code: 'D51.0', id: 'Anemia pernisiosa', en: 'Vitamin B12 deficiency anaemia due to intrinsic factor deficiency', chapter: 'Darah & Gizi' },
  { code: 'D52.9', id: 'Anemia defisiensi folat', en: 'Folate deficiency anaemia', chapter: 'Darah & Gizi' },
  { code: 'D61.9', id: 'Anemia aplastik', en: 'Aplastic anaemia, unspecified', chapter: 'Darah & Gizi' },
  { code: 'D63.0', id: 'Anemia pada penyakit kronik', en: 'Anaemia in neoplastic disease', chapter: 'Darah & Gizi' },
  { code: 'D65', id: 'Koagulasi intravaskular diseminata (DIC)', en: 'Disseminated intravascular coagulation', chapter: 'Darah & Gizi' },
  { code: 'D68.9', id: 'Gangguan koagulasi', en: 'Coagulation defect, unspecified', chapter: 'Darah & Gizi' },
  { code: 'D70', id: 'Agranulositosis / neutropenia', en: 'Agranulocytosis', chapter: 'Darah & Gizi' },
  { code: 'D75.1', id: 'Polisitemia sekunder', en: 'Secondary polycythaemia', chapter: 'Darah & Gizi' },
  { code: 'C91.0', id: 'Leukemia limfoblastik akut', en: 'Acute lymphoblastic leukaemia', chapter: 'Darah & Gizi' },
  { code: 'C81.9', id: 'Limfoma Hodgkin', en: 'Hodgkin lymphoma, unspecified', chapter: 'Darah & Gizi' },
  { code: 'C85.9', id: 'Limfoma non-Hodgkin', en: 'Non-Hodgkin lymphoma, unspecified', chapter: 'Darah & Gizi' },
  { code: 'C90.0', id: 'Mieloma multipel', en: 'Multiple myeloma', chapter: 'Darah & Gizi' },
  { code: 'E56.9', id: 'Defisiensi vitamin tidak ditentukan', en: 'Vitamin deficiency, unspecified', chapter: 'Darah & Gizi' },
  { code: 'E54', id: 'Defisiensi vitamin C (skorbut)', en: 'Ascorbic acid deficiency', chapter: 'Darah & Gizi' },
  { code: 'E61.1', id: 'Defisiensi besi', en: 'Iron deficiency', chapter: 'Darah & Gizi' },
  { code: 'E60', id: 'Defisiensi zinc', en: 'Dietary zinc deficiency', chapter: 'Darah & Gizi' },
  // Ob-gyn
  { code: 'O02.1', id: 'Missed abortion', en: 'Missed abortion', chapter: 'Obstetri & Ginekologi' },
  { code: 'O01.9', id: 'Mola hidatidosa', en: 'Hydatidiform mole, unspecified', chapter: 'Obstetri & Ginekologi' },
  { code: 'O13', id: 'Hipertensi gestasional', en: 'Gestational hypertension', chapter: 'Obstetri & Ginekologi' },
  { code: 'O23.4', id: 'Infeksi saluran kemih dalam kehamilan', en: 'Unspecified infection of urinary tract in pregnancy', chapter: 'Obstetri & Ginekologi' },
  { code: 'O36.5', id: 'Pertumbuhan janin terhambat', en: 'Maternal care for poor fetal growth', chapter: 'Obstetri & Ginekologi' },
  { code: 'O47.9', id: 'Kontraksi palsu (Braxton Hicks)', en: 'False labour, unspecified', chapter: 'Obstetri & Ginekologi' },
  { code: 'O60.1', id: 'Persalinan preterm', en: 'Preterm spontaneous labour with preterm delivery', chapter: 'Obstetri & Ginekologi' },
  { code: 'O62.0', id: 'Kontraksi lemah primer (inersia uteri)', en: 'Primary inadequate contractions', chapter: 'Obstetri & Ginekologi' },
  { code: 'O64.9', id: 'Distosia karena malposisi janin', en: 'Obstructed labour due to malposition', chapter: 'Obstetri & Ginekologi' },
  { code: 'O71.1', id: 'Ruptur uteri saat persalinan', en: 'Rupture of uterus during labour', chapter: 'Obstetri & Ginekologi' },
  { code: 'O85', id: 'Sepsis puerperalis', en: 'Puerperal sepsis', chapter: 'Obstetri & Ginekologi' },
  { code: 'O91.2', id: 'Mastitis nonpurulen dalam masa nifas', en: 'Nonpurulent mastitis associated with childbirth', chapter: 'Obstetri & Ginekologi' },
  { code: 'N71.9', id: 'Endometritis', en: 'Inflammatory disease of uterus', chapter: 'Obstetri & Ginekologi' },
  { code: 'N81.2', id: 'Prolaps uteri', en: 'Incomplete uterovaginal prolapse', chapter: 'Obstetri & Ginekologi' },
  { code: 'N93.8', id: 'Perdarahan uterus abnormal', en: 'Other specified abnormal uterine bleeding', chapter: 'Obstetri & Ginekologi' },
  { code: 'N97.9', id: 'Infertilitas perempuan', en: 'Female infertility, unspecified', chapter: 'Obstetri & Ginekologi' },
  { code: 'N46', id: 'Infertilitas laki-laki', en: 'Male infertility', chapter: 'Obstetri & Ginekologi' },
  { code: 'N60.1', id: 'Fibroadenoma / kista payudara', en: 'Diffuse cystic mastopathy', chapter: 'Obstetri & Ginekologi' },
  { code: 'C56', id: 'Kanker ovarium', en: 'Malignant neoplasm of ovary', chapter: 'Obstetri & Ginekologi' },
  // Anak & neonatus
  { code: 'P92.5', id: 'Kesulitan menyusu pada neonatus', en: 'Neonatal difficulty in feeding at breast', chapter: 'Anak' },
  { code: 'P39.9', id: 'Infeksi perinatal', en: 'Infection specific to the perinatal period', chapter: 'Anak' },
  { code: 'P55.1', id: 'Inkompatibilitas ABO', en: 'ABO isoimmunization of fetus and newborn', chapter: 'Anak' },
  { code: 'P70.4', id: 'Hipoglikemia neonatus', en: 'Other neonatal hypoglycaemia', chapter: 'Anak' },
  { code: 'P77', id: 'Enterokolitis nekrotikans', en: 'Necrotizing enterocolitis of fetus and newborn', chapter: 'Anak' },
  { code: 'P83.9', id: 'Kelainan integumen neonatus', en: 'Condition involving the integument of fetus and newborn', chapter: 'Anak' },
  { code: 'R62.5', id: 'Keterlambatan perkembangan', en: 'Other and unspecified lack of expected normal physiological development', chapter: 'Anak' },
  { code: 'E44.1', id: 'Malnutrisi energi-protein ringan', en: 'Mild protein-energy malnutrition', chapter: 'Anak' },
  { code: 'Q05.9', id: 'Spina bifida', en: 'Spina bifida, unspecified', chapter: 'Anak' },
  { code: 'Q03.9', id: 'Hidrosefalus kongenital', en: 'Congenital hydrocephalus', chapter: 'Anak' },
  { code: 'Q39.0', id: 'Atresia esofagus', en: 'Atresia of oesophagus without fistula', chapter: 'Anak' },
  { code: 'Q41.9', id: 'Atresia usus halus', en: 'Congenital absence of small intestine', chapter: 'Anak' },
  { code: 'Q42.3', id: 'Atresia ani', en: 'Congenital absence of anus', chapter: 'Anak' },
  { code: 'Q54.9', id: 'Hipospadia', en: 'Hypospadias, unspecified', chapter: 'Anak' },
  { code: 'Q65.9', id: 'Displasia panggul bawaan', en: 'Congenital deformity of hip', chapter: 'Anak' },
  { code: 'Q66.0', id: 'Talipes ekuinovarus (CTEV)', en: 'Talipes equinovarus', chapter: 'Anak' },
  { code: 'Q79.0', id: 'Hernia diafragmatika kongenital', en: 'Congenital diaphragmatic hernia', chapter: 'Anak' },
  // Gejala & tanda umum
  { code: 'R00.0', id: 'Takikardia', en: 'Tachycardia, unspecified', chapter: 'Gejala Umum' },
  { code: 'R00.1', id: 'Bradikardia', en: 'Bradycardia, unspecified', chapter: 'Gejala Umum' },
  { code: 'R03.0', id: 'Tekanan darah tinggi tanpa diagnosis hipertensi', en: 'Elevated blood-pressure reading', chapter: 'Gejala Umum' },
  { code: 'R06.2', id: 'Mengi', en: 'Wheezing', chapter: 'Gejala Umum' },
  { code: 'R09.0', id: 'Asfiksia', en: 'Asphyxia', chapter: 'Gejala Umum' },
  { code: 'R13', id: 'Disfagia (sulit menelan)', en: 'Dysphagia', chapter: 'Gejala Umum' },
  { code: 'R14', id: 'Kembung dan flatulens', en: 'Flatulence and related conditions', chapter: 'Gejala Umum' },
  { code: 'R21', id: 'Ruam kulit', en: 'Rash and other nonspecific skin eruption', chapter: 'Gejala Umum' },
  { code: 'R30.0', id: 'Disuria', en: 'Dysuria', chapter: 'Gejala Umum' },
  { code: 'R35', id: 'Poliuria', en: 'Polyuria', chapter: 'Gejala Umum' },
  { code: 'R41.0', id: 'Disorientasi', en: 'Disorientation, unspecified', chapter: 'Gejala Umum' },
  { code: 'R47.0', id: 'Disfasia dan afasia', en: 'Dysphasia and aphasia', chapter: 'Gejala Umum' },
  { code: 'R52.2', id: 'Nyeri kronik', en: 'Other chronic pain', chapter: 'Gejala Umum' },
  { code: 'R57.2', id: 'Syok septik', en: 'Septic shock', chapter: 'Gejala Umum' },
  { code: 'R58', id: 'Perdarahan tidak ditentukan', en: 'Haemorrhage, not elsewhere classified', chapter: 'Gejala Umum' },
  { code: 'R61.9', id: 'Hiperhidrosis (keringat berlebih)', en: 'Hyperhidrosis, unspecified', chapter: 'Gejala Umum' },
  { code: 'R63.0', id: 'Anoreksia (hilang nafsu makan)', en: 'Anorexia', chapter: 'Gejala Umum' },
  { code: 'R64', id: 'Kaheksia', en: 'Cachexia', chapter: 'Gejala Umum' },
  { code: 'R68.8', id: 'Gejala umum tidak ditentukan lain', en: 'Other specified general symptoms and signs', chapter: 'Gejala Umum' },
  // Pemeriksaan & pencegahan
  { code: 'Z01.4', id: 'Pemeriksaan ginekologi', en: 'Gynaecological examination', chapter: 'Pemeriksaan' },
  { code: 'Z03.9', id: 'Observasi dugaan penyakit', en: 'Observation for suspected disease', chapter: 'Pemeriksaan' },
  { code: 'Z12.4', id: 'Skrining kanker serviks', en: 'Special screening for neoplasm of cervix', chapter: 'Pemeriksaan' },
  { code: 'Z13.1', id: 'Skrining diabetes melitus', en: 'Special screening for diabetes mellitus', chapter: 'Pemeriksaan' },
  { code: 'Z39.1', id: 'Perawatan dan pemeriksaan ibu menyusui', en: 'Care and examination of lactating mother', chapter: 'Pemeriksaan' },
  { code: 'Z51.1', id: 'Kemoterapi', en: 'Chemotherapy session for neoplasm', chapter: 'Pemeriksaan' },
  { code: 'Z72.0', id: 'Merokok', en: 'Tobacco use', chapter: 'Pemeriksaan' },
  { code: 'Z76.0', id: 'Permintaan pengulangan resep', en: 'Encounter for issue of repeat prescription', chapter: 'Pemeriksaan' },
]

// ICD-11 (the newest WHO revision) stem codes for the most common diagnoses,
// mapped from their ICD-10 counterpart. Provided for diagnoses where the
// crosswalk is well-established; the treating doctor verifies the final code.
export const ICD11_MAP: Record<string, string> = {
  // Infeksi
  A15: '1B11', A90: '1D20', 'A01.0': '1A07', B20: '1C62', 'B34.2': 'RA01', 'B35.9': '1F28',
  // Pernapasan
  J00: 'CA00', 'J45.9': 'CA23', 'J44.9': 'CA22', 'J18.9': 'CA40', 'J30.4': 'CA08',
  // Kardiovaskular
  I10: 'BA00', 'I20.0': 'BA40', 'I21.9': 'BA41', 'I50.9': 'BD10', I48: 'BC81', 'I63.9': '8B11',
  // Endokrin & metabolik
  'E11.9': '5A11', 'E10.9': '5A10', 'E78.5': '5C80', 'E03.9': '5A00', 'E05.9': '5A02', 'E66.9': '5B81', 'E55.9': '5B57',
  // Saluran cerna
  'K21.9': 'DA22', 'K29.7': 'DA42', 'K35.8': 'DB10', 'K40.9': 'DD50', 'K80.2': 'DC11',
  // Ginjal & kemih
  'N18.9': 'GB61', 'N39.0': 'GC08', 'N20.0': 'GB70', N40: 'GA90',
  // Muskuloskeletal
  'M10.9': 'FA25', 'M17.9': 'FA01', 'M06.9': 'FA20',
  // Saraf & jiwa
  'G43.9': '8A80', 'G40.9': '8A6Z', 'F32.9': '6A70', 'F41.1': '6B00', 'F41.0': '6B01', 'F20.9': '6A20',
  // Kulit
  'L20.9': 'EA80', 'L50.9': 'EB05', 'L70.0': 'ED80',
  // Darah & gizi
  'D50.9': '3A00',
  // Gejala umum
  'R50.9': 'MG26', R05: 'MD12',
}

export function icd11(code: string): string | undefined {
  return ICD11_MAP[code]
}

// Distinct chapters (for grouping / filters).
export const ICD_CHAPTERS = Array.from(new Set(ICD_CODES.map((c) => c.chapter)))

// Search by code or Indonesian/English term (ranked: code prefix > word start).
export function searchICD(query: string, limit = 20): ICDCode[] {
  const q = query.trim().toLowerCase()
  if (!q) return ICD_CODES.slice(0, limit)
  const scored = ICD_CODES.map((c) => {
    const code = c.code.toLowerCase()
    const hay = `${c.id} ${c.en}`.toLowerCase()
    let score = 0
    if (code === q) score = 100
    else if (code.startsWith(q)) score = 80
    else if (hay.includes(q)) score = hay.startsWith(q) ? 60 : 40
    else if (q.split(/\s+/).every((w) => hay.includes(w))) score = 30
    return { c, score }
  }).filter((s) => s.score > 0)
  scored.sort((a, b) => b.score - a.score)
  return scored.slice(0, limit).map((s) => s.c)
}

// Best-effort auto-match an AI free-text diagnosis to an ICD code (keyword
// overlap). Returns undefined when nothing reasonable matches.
export function matchICD(text: string): ICDCode | undefined {
  const t = (text || '').toLowerCase()
  if (!t) return undefined
  let best: { c: ICDCode; n: number } | undefined
  for (const c of ICD_CODES) {
    const words = `${c.id} ${c.en}`.toLowerCase().split(/[^a-z0-9]+/).filter((w) => w.length > 3)
    const n = words.filter((w) => t.includes(w)).length
    if (n > 0 && (!best || n > best.n)) best = { c, n }
  }
  return best?.c
}
