// Katalog fitur — tujuan yang selama ini hanya bisa ditemukan dari dalam hub.
//
// Halaman "Semua Fitur" dibangun dari daftar menu, yang memuat 59 tujuan.
// Keempat hub bersama-sama menunjuk 135. Selisihnya terukur: 112 tujuan --
// termasuk Wells, SOFA, MELD, Child-Pugh, Ranson, Braden, dan seluruh
// kalkulator berdiri sendiri lainnya -- tidak pernah muncul di halaman yang
// namanya justru berjanji memuat semuanya.
//
// Nama, keterangan, dan kata kuncinya diangkat apa adanya dari hub masing-
// masing, bukan ditulis ulang, supaya tidak ada yang berubah maknanya.

export interface Fitur {
  to: string
  nama: string
  apa: string
  /** Kata kunci pencarian. */
  kw: string
  grup: string
}

export const FITUR_DARI_HUB: Fitur[] = [
  { to: '/health-simulator', nama: 'What-If Health Simulator', apa: 'See how today’s choices reshape your 10-year risk', kw: 'simulator digital twin future risk what-if prevent timeline', grup: 'Longevity' },
  { to: '/findrisc', nama: 'Diabetes Risk (FINDRISC)', apa: 'Your 10-year diabetes risk — and how to lower it', kw: 'diabetes findrisc prediabetes prevention metabolic glucose', grup: 'Longevity' },
  { to: '/biological-age', nama: 'Biological Age', apa: 'How old your body is really functioning, from your data', kw: 'phenoage biomarker aging longevity', grup: 'Longevity' },
  { to: '/longevity', nama: 'Longevity Blueprint', apa: 'Your personalized healthspan levers and risk drivers', kw: 'lifespan healthspan risk', grup: 'Longevity' },
  { to: '/organ-vitality', nama: 'Organ Vitality', apa: 'System-by-system health snapshot', kw: 'organ heart liver kidney vitality', grup: 'Longevity' },
  { to: '/supplements', nama: 'Supplement Guide', apa: 'Evidence-graded longevity supplements', kw: 'supplement vitamin omega creatine stack', grup: 'Longevity' },
  { to: '/family-health', nama: 'Family Health History', apa: 'Early-screening flags from your family history', kw: 'family history genogram legacy tree hereditary risk', grup: 'Longevity' },
  { to: '/gene-info', nama: 'Gene Info', apa: 'Look up what a gene does and why it matters', kw: 'gene genetics dna hereditary', grup: 'Longevity' },
  { to: '/connect', nama: 'Connect — Friends & Partners', apa: 'Profil, filter dan kecocokan berbasis gaya hidup sehat — bukan pemasangan perangkat', kw: 'connect kenalan teman pasangan jodoh relasi relationship match kecocokan deck profil sosial dating', grup: 'Longevity' },
  { to: '/breathwork', nama: 'Breathwork Pacer', apa: 'Animated paced breathing to calm you in minutes', kw: 'breathing box 478 coherence anxiety stress calm vagus', grup: 'Longevity' },
  { to: '/gratitude', nama: 'Gratitude Journal', apa: '"Three Good Things" — a proven mood lift', kw: 'gratitude journal happiness positive psychology mood', grup: 'Longevity' },
  { to: '/mental-health-screen', nama: 'Mental Health Check', apa: 'Validated depression & anxiety screening', kw: 'phq gad depression anxiety screen mental', grup: 'Longevity' },
  { to: '/substance-use-screen', nama: 'Alcohol & Tobacco Screening', apa: 'Validated substance-use screening', kw: 'audit fagerstrom alcohol tobacco smoking screen substance', grup: 'Longevity' },
  { to: '/ikigai', nama: 'Ikigai & Purpose', apa: 'Find your reason for being', kw: 'ikigai purpose meaning japanese', grup: 'Longevity' },
  { to: '/harada', nama: 'Harada 9×9 Goal Grid', apa: 'One goal, eight pillars, 64 concrete actions', kw: 'harada mandal-art mandala 9x9 goal target sasaran tujuan rencana ohtani grid kisi', grup: 'Longevity' },
  { to: '/life-compass', nama: 'Life Compass', apa: 'Plan your vision, mission, and next step', kw: 'vision mission purpose goals future anxiety worry planning', grup: 'Longevity' },
  { to: '/resilience-stories', nama: 'Resilience Stories', apa: 'Real people, real hardship, real comebacks', kw: 'motivation inspiration resilience hardship comeback stories', grup: 'Longevity' },
  { to: '/sleep-debt', nama: 'Sleep Debt', apa: 'Track the rolling gap between sleep need and sleep got', kw: 'sleep debt insomnia tired rest hours', grup: 'Longevity' },
  { to: '/chronotype', nama: 'Chronotype', apa: 'Are you a morning lark or night owl?', kw: 'chronotype morning owl circadian rmeq', grup: 'Longevity' },
  { to: '/epworth-sleepiness', nama: 'Epworth Sleepiness', apa: 'How sleepy are you during the day?', kw: 'epworth sleepiness daytime somnolence', grup: 'Longevity' },
  { to: '/sleep-apnea-screen', nama: 'Sleep Apnea (STOP-BANG)', apa: 'Screen your risk of obstructive sleep apnea', kw: 'apnea snoring stopbang osa', grup: 'Longevity' },
  { to: '/fasting', nama: 'Metabolic Fasting', apa: 'Time-restricted eating window & metabolic phases', kw: 'fasting intermittent eating window metabolic autophagy', grup: 'Longevity' },
  { to: '/thermal-therapy', nama: 'Thermal Therapy', apa: 'Sauna & cold-exposure protocols with the evidence', kw: 'sauna cold plunge heat ice thermal recovery', grup: 'Longevity' },
  { to: '/macro-lab', nama: 'Macro Lab', apa: 'Macronutrient targets and meal composition', kw: 'macro protein karbohidrat lemak gizi makro kalori', grup: 'Longevity' },
  { to: '/sehat-sibuk', nama: 'Healthy While Busy', apa: 'Health habits that fit a packed schedule', kw: 'sibuk busy habit kebiasaan praktis waktu terbatas', grup: 'Longevity' },
  { to: '/carbon-diet', nama: 'Carbon-Footprint Diet', apa: 'Dietary choices weighed by carbon footprint', kw: 'carbon jejak karbon diet lingkungan iklim makanan', grup: 'Longevity' },
  { to: '/nutrition', nama: 'Nutrition & BMR', apa: 'Calories, macros, and metabolic rate', kw: 'nutrition calorie macro bmr tdee diet', grup: 'Longevity' },
  { to: '/hydration', nama: 'Hydration', apa: 'Your daily water target', kw: 'water hydration drink fluid', grup: 'Longevity' },
  { to: '/alcohol', nama: 'Alcohol Unit & BAC Estimator', apa: 'Standard drinks and an educational BAC estimate', kw: 'alcohol drink bac widmark unit', grup: 'Longevity' },
  { to: '/caffeine', nama: 'Caffeine & Sleep', apa: 'See how today’s caffeine lingers into tonight’s sleep', kw: 'caffeine coffee sleep half-life', grup: 'Longevity' },
  { to: '/air-quality', nama: 'Air Quality & Lungs', apa: 'Local air quality and what it means for your lungs', kw: 'air quality aqi pollution lungs pm2.5', grup: 'Longevity' },
  { to: '/aesthetic', nama: 'Aesthetic Studio', apa: 'Skin, face, and aesthetic guidance', kw: 'aesthetic skin face beauty antiaging glow', grup: 'Longevity' },
  { to: '/sun-exposure', nama: 'Sun & Vitamin D', apa: 'Safe sun for vitamin D without skin damage', kw: 'sun uv vitamin d sunscreen skin', grup: 'Longevity' },
  { to: '/first-aid', nama: 'First Aid Quick Guide', apa: 'Plain-language steps for choking, CPR, bleeding & more', kw: 'first aid cpr choking bleeding burns seizure fainting stroke anaphylaxis emergency', grup: 'Longevity' },
  { to: '/vaccine-tracker', nama: 'Vaccine / Immunization Tracker', apa: 'Log your last dose, see when the next is due', kw: 'vaccine immunization booster flu tdap covid schedule', grup: 'Longevity' },
  { to: '/allergy-tracker', nama: 'Allergy Tracker', apa: 'Log food, drink, medication & contact (DKA) allergies', kw: 'allergy allergies food drink medication contact dermatitis kontak alergi dka anaphylaxis', grup: 'Longevity' },
  { to: '/blood-donation', nama: 'Blood Donation Eligibility', apa: 'A quick pre-screen and your next-eligible date', kw: 'blood donation donor eligibility hemoglobin', grup: 'Longevity' },
  { to: '/organ-donor', nama: 'Organ Donor Pledge', apa: 'Clarify your wishes, then talk to your family', kw: 'organ donor pledge donation transplant', grup: 'Longevity' },
  { to: '/visit-prep', nama: 'Doctor-Visit Prep Checklist', apa: 'What to bring and what to ask, before you walk in', kw: 'doctor visit checklist prepare questions appointment', grup: 'Longevity' },
  { to: '/posture-breaks', nama: 'Posture & Desk-Break Reminder', apa: 'A gentle nudge to stand, stretch, or rest your eyes', kw: 'posture desk break timer eye strain 20-20-20 sedentary', grup: 'Longevity' },
  { to: '/pain-diary', nama: 'Pain / Symptom Diary', apa: 'Track severity over time — useful for you and your clinician', kw: 'pain symptom diary tracker severity trend', grup: 'Longevity' },
  { to: '/second-opinion', nama: 'Second Opinion', apa: 'AI drafts privately, a real doctor reviews and approves', kw: 'second opinion doctor review diagnosis ai emr', grup: 'Longevity' },
  { to: '/sleep-toolkit', nama: 'Sleep Toolkit', apa: 'Cycle alarm, nap timer, consistency score, dream journal, soundscape generator & more', kw: 'sleep cycle alarm nap timer consistency dream journal bedtime toolkit binaural beats white noise pink noise soundscape', grup: 'Longevity' },
  { to: '/movement-toolkit', nama: 'Movement Longevity Toolkit', apa: 'Grip strength, balance test, Zone 2, micro-workouts & squat streak', kw: 'grip strength balance zone 2 cardio micro workout squat challenge toolkit', grup: 'Longevity' },
  { to: '/mind-toolkit', nama: 'Cognitive Longevity Toolkit', apa: 'Brain puzzle, memory game, reaction time, stress inventory & more', kw: 'brain puzzle memory game reaction time word stress digital detox meditation toolkit', grup: 'Longevity' },
  { to: '/nutrition-toolkit', nama: 'Nutrition Longevity Toolkit', apa: 'Mediterranean checklist, sugar streak, plant diversity & more', kw: 'mediterranean diet sugar streak antioxidant plant diversity coffee electrolyte toolkit', grup: 'Longevity' },
  { to: '/toxin-checklist', nama: 'Environment & Toxin Checklist', apa: 'Everyday exposure reduction — plastics, cleaning, EMF, air quality', kw: 'toxin environment plastic emf endocrine disruptor cleaning swap air purifier checklist', grup: 'Longevity' },
  { to: '/longevity-science', nama: 'Longevity Science Explainers', apa: 'Hallmarks of aging, NAD+, sirtuins, rapamycin & more, explained', kw: 'hallmarks aging nad sirtuins spermidine urolithin metformin rapamycin methylene blue science', grup: 'Longevity' },
  { to: '/self-assessment-toolkit', nama: 'Self-Assessment Toolkit', apa: 'Telomere quiz, inflammation score, waist-to-height & more', kw: 'telomere quiz inflammation score aging factor waist height ratio toolkit', grup: 'Longevity' },
  { to: '/body-toolkit', nama: 'Body & Skin Toolkit', apa: 'Skincare routine builder, symptom map, NEAT tracker', kw: 'skincare routine builder symptom body map neat non-exercise activity toolkit', grup: 'Longevity' },
  { to: '/longevity-game-center', nama: 'Longevity Game Center', apa: 'Habit bingo, a shareable report card, and a daily quote', kw: 'habit bingo report card shareable quote game viral', grup: 'Longevity' },
  { to: '/rppg-heart-rate', nama: 'rPPG Heart Rate', apa: 'Estimate your pulse from your webcam — no wearable needed', kw: 'rppg heart rate webcam camera photoplethysmography pulse experimental', grup: 'Longevity' },
  { to: '/vocal-biomarkers', nama: 'Vocal Biomarker Analyzer', apa: 'Pitch, jitter & shimmer from a 5-second voice sample', kw: 'voice vocal biomarker jitter shimmer pitch acoustic experimental', grup: 'Longevity' },
  { to: '/snp-profiler', nama: 'Local SNP Longevity Profiler', apa: 'Upload raw DNA data — parsed entirely in your browser, never uploaded', kw: 'dna snp gene genotype 23andme foxo3 apoe mthfr profiler local', grup: 'Longevity' },
  { to: '/predictive-models-toolkit', nama: 'Predictive Models Toolkit', apa: 'Autophagy timing, cortisol curve, glycemic load & more', kw: 'autophagy cortisol sauna nova glycemic load healthspan predictive model toolkit', grup: 'Longevity' },
  { to: '/data-lab-advanced', nama: 'Data Lab Advanced', apa: 'Blood trend forecaster, PhenoAge, encrypted vault & more', kw: 'blood panel forecaster phenoage glucose variability omega microbiome supplement vault local data', grup: 'Longevity' },
  { to: '/bio-simulators', nama: 'Bio-Simulators', apa: 'Illustrative mTOR/AMPK, circadian, and telomere visualizations', kw: 'mtor ampk circadian telomere attrition simulator illustrative', grup: 'Longevity' },
  { to: '/athlete', nama: 'Athlete', apa: 'Your training dashboard — HR zones, load, GPS runs', kw: 'athlete dashboard heart rate zones gps run', grup: 'Fitness' },
  { to: '/workout', nama: 'Workout', apa: 'Guided sessions with movement-form demo videos', kw: 'workout exercise session movement demo', grup: 'Fitness' },
  { to: '/training-plan', nama: 'AI Program', apa: 'A structured, adaptive training plan', kw: 'training plan program ai schedule periodization', grup: 'Fitness' },
  { to: '/lari-sepeda-renang', nama: 'Lari, Sepeda, Renang', apa: 'Power zones, swim CSS, speed work and posture across three sports', kw: 'lari sepeda renang cycling swimming triathlon ftp watt power zone css critical swim speed cadence bike fit kecepatan speed', grup: 'Fitness' },
  { to: '/teknik-lari', nama: 'Running Technique', apa: 'Irama langkah, jangkauan kaki, ayunan lengan, napas, start dan aerodinamis', kw: 'teknik lari running form cadence irama langkah spm stride panjang langkah overstriding postur posisi badan lean condong gerakan kaki foot strike pendaratan tumit midfoot forefoot lengan arm swing napas pernapasan breathing diafragma start pemanasan aerodinamis drafting angin endurance daya tahan volume intensitas 80/20', grup: 'Fitness' },
  { to: '/peregangan', nama: 'Stretching & Posture', apa: 'Rutinitas per situasi — sebelum lari, sesudah sepeda, jeda kerja duduk', kw: 'peregangan stretching stretch dinamis statis yoga pilates postur posture mobilitas mobility pemanasan warm up pendinginan cooldown hamstring betis bahu pinggul leher fleksor lari renang sepeda', grup: 'Fitness' },
  { to: '/crossfit', nama: 'CrossFit & AMRAP', apa: 'Workout formats, named benchmarks, and how to scale them safely', kw: 'crossfit amrap emom wod tabata chipper couplet triplet ladder hyrox cindy mary angie barbara chelsea annie fran helen grace karen murph chad jt benchmark girls hero rabdomiolisis rhabdo skala scaling pemula', grup: 'Fitness' },
  { to: '/alat-fitness', nama: 'Gym Equipment & Hyrox', apa: 'Gym equipment guide and Hyrox-style workout formats', kw: 'alat fitness gym equipment hyrox mesin beban dumbbell barbell kettlebell', grup: 'Fitness' },
  { to: '/sports-lab', nama: 'Sports Lab', apa: 'Sport-specific testing and performance breakdowns', kw: 'sports lab tes olahraga performa cabang', grup: 'Fitness' },
  { to: '/health-data', nama: 'Sambungkan Perangkat', apa: 'Sinkronisasi Apple Watch, unggah ekspor Garmin/WHOOP/InBody', kw: 'connect sambungkan perangkat device wearable apple watch garmin whoop inbody sinkron sync impor import', grup: 'Fitness' },
  { to: '/analisis-gerak', nama: 'Movement Analysis', apa: 'Walking asymmetry, gait quality, running form and heart-rate recovery, read from your watch export', kw: 'gait berjalan asimetri asymmetry langkah step length double support cadence irama ground contact vertical oscillation running form bentuk lari hrr cardio recovery pemulihan stair speed tangga daylight cahaya headphone audio', grup: 'Fitness' },
  { to: '/riwayat-latihan', nama: 'Session History', apa: 'Every imported session with its per-minute heart-rate curve, zone split and recovery', kw: 'workout latihan riwayat history sesi heart rate curve kurva zona zone 80/20 easy pace hrr recovery pemulihan apple watch import notification peringatan denyut', grup: 'Fitness' },
  { to: '/log-detak-jantung', nama: 'Heart Rate Log', apa: 'Every heart-rate sample your watch pushes, with how dense the data really is', kw: 'heart rate log detak jantung real time realtime live monitor sampel webhook auto export apple watch bpm', grup: 'Fitness' },
  { to: '/pola-tidur', nama: 'Sleep Pattern', apa: 'Sleep by stage per night — deep, REM, core, awake — plus bedtime regularity', kw: 'tidur sleep pola stage deep rem core awake tahapan malam jam tidur keteraturan regularity apple watch jaga shift', grup: 'Fitness' },
  { to: '/analisis-pro', nama: 'Pro Analysis', apa: 'Kebugaran & kesegaran, upaya relatif, usaha terbaik, zona pace, log latihan dan target', kw: 'analisis pro strava fitness freshness ctl atl tsb kebugaran kesegaran relative effort upaya relatif training log best efforts usaha terbaik rekor pr goals target zona pace gap grade adjusted', grup: 'Fitness' },
  { to: '/body-battery', nama: 'Body Battery', apa: 'Cadangan energi 0-100 sepanjang hari dan tingkat stres, dari deret denyut', kw: 'body battery baterai energi cadangan stres stress sepanjang hari all day pemulihan recovery garmin hrv denyut istirahat', grup: 'Fitness' },
  { to: '/fisiologi-latihan', nama: 'Training Physiology', apa: 'Training load, status, recovery time, training effect, readiness and threshold — computed from your watch', kw: 'training load beban acute chronic acwr epoc trimp status recovery pemulihan readiness kesiapan training effect lthr ambang laktat performance condition endurance ketahanan garmin firstbeat suggested workout', grup: 'Fitness' },
  { to: '/alat-endurance', nama: 'Endurance Tools', apa: 'Fuelling plan, sweat rate, cycling FTP and zones, course power guide, heat and altitude acclimation', kw: 'fueling bahan bakar karbohidrat carb sweat rate keringat natrium sodium hidrasi ftp watt wkg power zone coggan power guide pacing tanjakan gradien acclimation aklimatisasi panas heat altitude ketinggian sepeda cycling', grup: 'Fitness' },
  { to: '/pelacak-klinis', nama: 'Clinical Trackers', apa: 'SpO2 log, ECG result diary, jet lag plan, pregnancy activity, wheelchair physiology', kw: 'spo2 saturasi pulse ox oksigen ekg ecg afib fibrilasi atrium jet lag jetlag circadian kehamilan hamil pregnancy trimester kursi roda wheelchair paraplegi disrefleksia bahu shoulder', grup: 'Fitness' },
  { to: '/latihan-dasar', nama: 'Foundation Training & Postur', apa: 'Running pace zones, push/pull/sit-up progressions, posture correction', kw: 'lari run pace easy tempo interval long push up pull up sit up kalistenik calisthenics postur posture vdot', grup: 'Fitness' },
  { to: '/fitness-test', nama: 'Fitness Test', apa: 'AI form & posture check from a photo of your movement', kw: 'fitness test form posture ai photo injury risk', grup: 'Fitness' },
  { to: '/readiness', nama: 'Recovery & Strain', apa: 'Is today a push day or a rest day?', kw: 'recovery strain readiness hrv fatigue', grup: 'Fitness' },
  { to: '/assessment', nama: 'Initial Assessment', apa: 'Baseline fitness & movement screening', kw: 'initial assessment baseline screening onboarding', grup: 'Fitness' },
  { to: '/body', nama: 'Body Composition', apa: 'InBody-style visual breakdown of your composition', kw: 'body composition inbody fat muscle scale', grup: 'Fitness' },
  { to: '/lab', nama: 'Performance Lab', apa: 'Load management, VO2max, and performance metrics', kw: 'performance lab vo2max load management', grup: 'Fitness' },
  { to: '/sports-science', nama: 'Science & KPIs', apa: 'The evidence and key metrics behind your numbers', kw: 'sports science kpi evidence metrics', grup: 'Fitness' },
  { to: '/shape-forming', nama: 'Shape Forming', apa: 'A structured body-recomposition program', kw: 'shape forming body recomposition program', grup: 'Fitness' },
  { to: '/sports-scores', nama: 'Live Scores', apa: 'Real-time scores for your favorite teams & leagues', kw: 'live scores sports scoreboard football f1 motogp', grup: 'Fitness' },
  { to: '/chatbot', nama: 'AI Chatbot', apa: 'Ask a health question and get a sourced, plain-language answer', kw: 'chatbot ai tanya chat asisten pertanyaan kesehatan', grup: 'Learn & Look Up' },
  { to: '/evidence', nama: 'Clinical Evidence', apa: 'The published evidence behind a treatment or claim', kw: 'evidence bukti klinis jurnal studi penelitian guideline pedoman', grup: 'Learn & Look Up' },
  { to: '/trials', nama: 'Clinical Trials Finder', apa: 'Find trials you may be eligible to join', kw: 'clinical trials uji klinis penelitian rekrutmen eligible peserta', grup: 'Learn & Look Up' },
  { to: '/emr', nama: 'AI-EMR', apa: 'Electronic records with AI-assisted note writing', kw: 'emr rekam medis elektronik catatan note soap dokter', grup: 'Learn & Look Up' },
  { to: '/clinical', nama: 'Clinical Data', apa: 'Your patient panel and their clinical numbers', kw: 'clinical data pasien panel klinis dokter', grup: 'Learn & Look Up' },
  { to: '/planning', nama: 'Planning', apa: 'Schedule and plan patient care', kw: 'planning jadwal rencana perawatan dokter', grup: 'Learn & Look Up' },
  { to: '/clinical-calculators', nama: 'Clinical Calculators', apa: 'Scores and risk calculators used at the bedside', kw: 'kalkulator klinis skor risiko score calculator gcs curb wells', grup: 'Learn & Look Up' },
  { to: '/sexual-health', nama: 'Sexual Health & OB-GYN', apa: 'Reproductive, sexual and obstetric health topics', kw: 'sexual health seksual obgyn kandungan kebidanan reproduksi kehamilan kontrasepsi ims sti', grup: 'Learn & Look Up' },
  { to: '/longevity-curriculum', nama: 'Longevity Curriculum', apa: 'Structured teaching material on longevity medicine', kw: 'longevity curriculum kurikulum kuliah materi ajar penuaan aging', grup: 'Learn & Look Up' },
  { to: '/stroke-risk', nama: 'CHA₂DS₂-VASc', apa: 'Stroke risk in atrial fibrillation → anticoagulation decision', kw: 'af atrial fibrillation stroke anticoagulation', grup: 'Calculators & Labs' },
  { to: '/has-bled-score', nama: 'HAS-BLED', apa: 'Bleeding risk on anticoagulation (pairs with CHA₂DS₂-VASc)', kw: 'bleeding anticoagulation warfarin', grup: 'Calculators & Labs' },
  { to: '/timi-risk-score', nama: 'TIMI Risk Score', apa: '14-day risk in unstable angina / NSTEMI', kw: 'acs nstemi unstable angina chest pain', grup: 'Calculators & Labs' },
  { to: '/grace-score', nama: 'GRACE Score', apa: 'In-hospital mortality across the full ACS spectrum', kw: 'acs stemi nstemi mortality invasive', grup: 'Calculators & Labs' },
  { to: '/qtc-calculator', nama: 'QTc Calculator', apa: 'Corrected QT — drug-safety screening, 4 formulas + serial trend', kw: 'qt torsades ecg drug antipsychotic methadone', grup: 'Calculators & Labs' },
  { to: '/duke-criteria', nama: 'Duke Criteria', apa: 'Infective endocarditis diagnostic classification', kw: 'endocarditis ie vegetation blood culture', grup: 'Calculators & Labs' },
  { to: '/ldl-calculator', nama: 'LDL (Friedewald)', apa: 'Calculated LDL + non-HDL cholesterol', kw: 'cholesterol lipid friedewald', grup: 'Calculators & Labs' },
  { to: '/risk', nama: 'Framingham CVD (Risk Calculators)', apa: '10-year cardiovascular risk, FIB-4, OST', kw: 'framingham cardiovascular 10-year fibrosis osteoporosis', grup: 'Calculators & Labs' },
  { to: '/wells-score', nama: 'Wells Score', apa: 'DVT and PE pretest probability, with D-dimer strategy', kw: 'dvt pe embolism thrombosis d-dimer', grup: 'Calculators & Labs' },
  { to: '/perc-rule', nama: 'PERC Rule', apa: 'Rule out PE without testing in low-risk patients', kw: 'pe embolism rule out low risk', grup: 'Calculators & Labs' },
  { to: '/aa-gradient', nama: 'A-a Gradient', apa: 'Localize hypoxemia: lung problem vs hypoventilation', kw: 'hypoxemia abg oxygen alveolar shunt', grup: 'Calculators & Labs' },
  { to: '/lights-criteria', nama: 'Light’s Criteria', apa: 'Pleural effusion: exudate vs transudate', kw: 'pleural effusion exudate transudate tap', grup: 'Calculators & Labs' },
  { to: '/sofa-score', nama: 'SOFA Score', apa: 'Full 6-organ ICU severity + serial trend', kw: 'sepsis icu organ failure', grup: 'Calculators & Labs' },
  { to: '/news2-score', nama: 'NEWS2', apa: 'Ward vital-signs early warning + serial trend', kw: 'vital signs deterioration early warning ward', grup: 'Calculators & Labs' },
  { to: '/meld-score', nama: 'MELD-Na', apa: 'Liver disease severity / transplant priority + serial trend', kw: 'liver cirrhosis transplant meld', grup: 'Calculators & Labs' },
  { to: '/maddrey-score', nama: 'Maddrey’s Discriminant Function', apa: 'Severe alcoholic hepatitis — the corticosteroid decision', kw: 'alcoholic hepatitis steroid prednisolone maddrey liver', grup: 'Calculators & Labs' },
  { to: '/child-pugh-score', nama: 'Child-Pugh', apa: 'Cirrhosis class A/B/C, surgical risk + serial trend', kw: 'liver cirrhosis ascites surgical risk', grup: 'Calculators & Labs' },
  { to: '/glasgow-blatchford-score', nama: 'Glasgow-Blatchford', apa: 'Upper GI bleed: who needs admission (pre-endoscopy)', kw: 'gi bleed bleeding hematemesis melena admission', grup: 'Calculators & Labs' },
  { to: '/rockall-score', nama: 'Rockall Score', apa: 'Upper GI bleed: rebleeding/mortality (post-endoscopy)', kw: 'gi bleed endoscopy rebleeding mortality', grup: 'Calculators & Labs' },
  { to: '/ranson-criteria', nama: 'Ranson’s Criteria', apa: 'Pancreatitis severity (admission + 48h)', kw: 'pancreatitis amylase lipase severity', grup: 'Calculators & Labs' },
  { to: '/bisap-score', nama: 'BISAP', apa: 'Pancreatitis severity — usable within 24h', kw: 'pancreatitis bedside early severity', grup: 'Calculators & Labs' },
  { to: '/creatinine-clearance', nama: 'Creatinine Clearance', apa: 'Cockcroft-Gault CrCl for renal drug dosing', kw: 'renal kidney dosing cockcroft gault crcl', grup: 'Calculators & Labs' },
  { to: '/fena-calculator', nama: 'FeNa', apa: 'AKI: prerenal vs intrinsic (ATN)', kw: 'aki acute kidney injury prerenal atn urine sodium', grup: 'Calculators & Labs' },
  { to: '/pediatric-dka-calculator', nama: 'Pediatric DKA Calculator', apa: 'Bolus, deficit, maintenance, potassium & insulin infusion for pediatric DKA', kw: 'pediatric dka diabetic ketoacidosis fluid insulin holliday segar maintenance rehydration anak', grup: 'Calculators & Labs' },
  { to: '/corrected-calcium', nama: 'Corrected Calcium', apa: 'Adjust total calcium for low albumin', kw: 'calcium albumin hypocalcemia', grup: 'Calculators & Labs' },
  { to: '/serum-osmolality', nama: 'Serum Osmolality & Gap', apa: 'Osmolal gap — toxic alcohol screen', kw: 'osmolality toxic alcohol methanol ethylene glycol overdose', grup: 'Calculators & Labs' },
  { to: '/lab-decoder', nama: 'Lab Result Decoder', apa: 'Plain-language explanation of common lab panels', kw: 'lab results panel explain', grup: 'Calculators & Labs' },
  { to: '/4ts-score', nama: '4Ts Score', apa: 'Heparin-induced thrombocytopenia pretest probability', kw: 'hit heparin thrombocytopenia platelets', grup: 'Calculators & Labs' },
  { to: '/padua-score', nama: 'Padua Score', apa: 'VTE prophylaxis decision — medical inpatients', kw: 'vte prophylaxis medical inpatient lmwh', grup: 'Calculators & Labs' },
  { to: '/caprini-score', nama: 'Caprini Score', apa: 'VTE prophylaxis decision — surgical patients', kw: 'vte prophylaxis surgery surgical', grup: 'Calculators & Labs' },
  { to: '/braden-scale', nama: 'Braden Scale', apa: 'Pressure injury (ulcer) risk with intervention tiers', kw: 'pressure ulcer decubitus nursing skin', grup: 'Calculators & Labs' },
  { to: '/charlson-index', nama: 'Charlson Index', apa: 'Comorbidity burden → estimated 10-year survival', kw: 'comorbidity survival prognosis burden', grup: 'Calculators & Labs' },
  { to: '/child-growth', nama: 'Child Growth Tracker', apa: 'Longitudinal WHO growth chart (0-60 months)', kw: 'pediatric growth who anthropometry stunting', grup: 'Calculators & Labs' },
  { to: '/ottawa-ankle', nama: 'Ottawa Ankle Rules', apa: 'Does this ankle/foot injury need an X-ray?', kw: 'ankle foot xray fracture injury', grup: 'Calculators & Labs' },
  { to: '/reality-check', nama: 'Habit Reality Check', apa: 'CAGE alcohol screen + smoking pack-years', kw: 'alcohol smoking cage pack years screening', grup: 'Calculators & Labs' },
  { to: '/data-lab', nama: 'Data Lab', apa: 'Upload a CSV of your own health data and chart it', kw: 'csv upload chart data', grup: 'Calculators & Labs' },
  { to: '/fluid-calculators', nama: 'Fluid & Electrolyte Calculators', apa: 'Maintenance, resuscitation (sepsis/PALS/Parkland) & electrolyte correction', kw: 'cairan maintenance rumatan resusitasi cairan elektrolit holliday segar parkland sepsis pals fluid resuscitation electrolyte', grup: 'Calculators & Labs' },
  { to: '/neonatal-resuscitation-guide', nama: 'Neonatal Resuscitation (NRP) Guide', apa: 'Initial-steps algorithm + Golden Minute timer', kw: 'resusitasi neonatus neonatal nrp golden minute newborn edukasi', grup: 'Calculators & Labs' },
  { to: '/empiric-therapy-reference', nama: 'Empiric Therapy Reference', apa: 'First-line drug classes by diagnosis — searchable quick reference', kw: 'pemilihan obat berdasarkan diagnosis empiric therapy antibiotic first line drug class', grup: 'Calculators & Labs' },
  { to: '/dermatology-lesion-mapper', nama: 'Dermatology Status & Lesion Mapper', apa: 'Morphology + predilection site → classic teaching differential', kw: 'status dermatologis predileksi lesi dermatology skin lesion morphology differential', grup: 'Calculators & Labs' },
  { to: '/psychiatric-status-exam', nama: 'Psychiatric Status Exam', apa: 'Structured Mental Status Exam (MSE) documentation', kw: 'status psikiatri mental status exam mse psychiatric', grup: 'Calculators & Labs' },
]
