export type WealthDomain = 'Time' | 'Health' | 'Money' | 'Knowledge' | 'Social' | 'Family' | 'Career'

export interface LifeReading {
  id: string
  domain: WealthDomain
  title: string
  by: string
  year?: number
  kind: 'book' | 'classic' | 'research-guide' | 'practice'
  summary: string
  tryThis: string
}

/**
 * Panacea Life Library.
 *
 * Summaries are original descriptions, not quotations or substitutes for the
 * source works. They are intentionally short: enough to decide what to explore
 * next, while the actual work remains the primary source.
 *
 * Seven domains mirror the Life OS wealth model: time, health, money,
 * knowledge, social connection, family and career. No domain is treated as a
 * master score for a person's worth.
 */
export const LIFE_LIBRARY: LifeReading[] = [
  // ── TIME ────────────────────────────────────────────────────────────────
  { id: 'time-4000-weeks', domain: 'Time', title: 'Four Thousand Weeks', by: 'Oliver Burkeman', year: 2021, kind: 'book', summary: 'A finite life makes prioritization unavoidable. The useful move is not squeezing everything in, but choosing what deserves a limited number of weeks and accepting what will remain undone.', tryThis: 'Name one worthwhile thing you will protect this week and one thing you will deliberately not optimize.' },
  { id: 'time-deep-work', domain: 'Time', title: 'Deep Work', by: 'Cal Newport', year: 2016, kind: 'book', summary: 'High-value cognitive work benefits from long periods without switching. The practical lesson is to schedule focus as a real appointment rather than waiting for motivation.', tryThis: 'Block one 45-minute period with notifications off and one clearly defined outcome.' },
  { id: 'time-make-time', domain: 'Time', title: 'Make Time', by: 'Jake Knapp & John Zeratsky', year: 2018, kind: 'book', summary: 'A day feels different when one highlight is chosen before the inbox chooses for you. Energy, attention and environment matter as much as a task list.', tryThis: 'Choose today’s single highlight before opening your highest-noise app.' },
  { id: 'time-seneca', domain: 'Time', title: 'On the Shortness of Life', by: 'Seneca', year: 49, kind: 'classic', summary: 'Seneca argues that time is not merely lost by idleness; it is also lost by living according to other people’s agendas without noticing.', tryThis: 'Review yesterday and mark one hour that did not serve a value you actually chose.' },
  { id: 'time-essentialism', domain: 'Time', title: 'Essentialism', by: 'Greg McKeown', year: 2014, kind: 'book', summary: 'Doing fewer things can be a strategy for doing the right things better. The hard part is not discovering priorities but creating boundaries around them.', tryThis: 'Turn one vague obligation into a clear yes, a clear no, or a smaller commitment.' },
  { id: 'time-attention-audit', domain: 'Time', title: 'Attention Audit', by: 'Panacea Practice', kind: 'practice', summary: 'Time and attention are related but not identical: an hour spent fragmented may deliver far less value than an hour spent deliberately. The audit focuses on where attention actually went.', tryThis: 'For one day, record only three categories: chosen focus, necessary maintenance, and unplanned capture.' },
  { id: 'time-week-design', domain: 'Time', title: 'Design the Week Before It Designs You', by: 'Panacea Practice', kind: 'practice', summary: 'Weekly planning works best when commitments are placed around energy and relationships, not only around deadlines. It makes trade-offs visible before they become emergencies.', tryThis: 'Place sleep, exercise, family and one deep-work block on the calendar before optional tasks.' },

  // ── HEALTH ──────────────────────────────────────────────────────────────
  { id: 'health-exercised', domain: 'Health', title: 'Exercised', by: 'Daniel Lieberman', year: 2020, kind: 'book', summary: 'Human bodies evolved for movement but not for modern exercise culture. The book is useful for understanding why physical activity often needs social, environmental and practical support rather than moral pressure.', tryThis: 'Make one form of movement easier to start by reducing setup time to under two minutes.' },
  { id: 'health-why-we-sleep', domain: 'Health', title: 'Why We Sleep', by: 'Matthew Walker', year: 2017, kind: 'book', summary: 'Sleep affects many biological systems, although some popular claims around exact effect sizes deserve caution. The durable lesson is that sleep is a physiological process, not disposable idle time.', tryThis: 'Keep wake time more consistent for one week before changing multiple sleep variables at once.' },
  { id: 'health-outlive', domain: 'Health', title: 'Outlive', by: 'Peter Attia with Bill Gifford', year: 2023, kind: 'book', summary: 'The book reframes prevention around long-term function, metabolic health and physical capacity. Its strongest use is as a map of questions to discuss, not a personalized prescription.', tryThis: 'Choose one capacity you want to preserve decades from now and identify what you can measure safely today.' },
  { id: 'health-peak-performance', domain: 'Health', title: 'Peak Performance', by: 'Brad Stulberg & Steve Magness', year: 2017, kind: 'book', summary: 'Adaptation depends on a cycle of stress and recovery. Training, study and work all become fragile when the loading phase grows while recovery is treated as optional.', tryThis: 'After one demanding session, schedule the recovery behavior at the same time you schedule the effort.' },
  { id: 'health-who-guidelines', domain: 'Health', title: 'WHO Physical Activity Guidelines', by: 'World Health Organization', year: 2020, kind: 'research-guide', summary: 'The guideline synthesizes evidence on movement, sedentary time and health across age groups. It is a population-level reference and should be adapted to medical context and ability.', tryThis: 'Compare your current week with the guideline ranges, then choose the smallest realistic gap to close.' },
  { id: 'health-n-of-1', domain: 'Health', title: 'N-of-1 Habit Experiment', by: 'Panacea Practice', kind: 'practice', summary: 'Personal experiments are most useful when one variable changes at a time and the outcome is defined before the change. They are poor substitutes for medical diagnosis or treatment trials.', tryThis: 'Pick one low-risk behavior, one outcome and a review date; avoid changing five things at once.' },
  { id: 'health-capacity-not-aesthetic', domain: 'Health', title: 'Capacity Over Appearance', by: 'Panacea Practice', kind: 'practice', summary: 'A Life OS can track what the body can do without reducing health to appearance. Strength, endurance, mobility, sleep and daily function each describe a different dimension.', tryThis: 'Track one capability metric that matters to your real life rather than adding another appearance score.' },

  // ── MONEY ───────────────────────────────────────────────────────────────
  { id: 'money-psychology', domain: 'Money', title: 'The Psychology of Money', by: 'Morgan Housel', year: 2020, kind: 'book', summary: 'Financial outcomes are shaped by behavior, time horizon and the ability to stay in the game, not only by technical knowledge. Enough is a strategic concept, not merely a moral one.', tryThis: 'Write what “enough” means for one spending category so comparison does not define it for you.' },
  { id: 'money-random-walk', domain: 'Money', title: 'A Random Walk Down Wall Street', by: 'Burton Malkiel', year: 1973, kind: 'book', summary: 'Markets make persistent outperformance difficult, especially after costs. The book is a useful counterweight to stories that make hindsight look like skill.', tryThis: 'Separate the part of your financial plan that depends on prediction from the part that works even when prediction fails.' },
  { id: 'money-little-book', domain: 'Money', title: 'The Little Book of Common Sense Investing', by: 'John C. Bogle', year: 2007, kind: 'book', summary: 'Costs compound in the same direction as returns: a small recurring drag becomes large over long horizons. Simplicity can be a risk-control feature.', tryThis: 'List every recurring fee attached to one investment or subscription before comparing headline returns.' },
  { id: 'money-your-money-life', domain: 'Money', title: 'Your Money or Your Life', by: 'Vicki Robin & Joe Dominguez', year: 1992, kind: 'book', summary: 'Spending can be translated into life energy: time used to earn, maintain and recover from the work that paid for it. That lens makes some purchases look very different.', tryThis: 'Convert one discretionary purchase into hours of take-home work rather than currency alone.' },
  { id: 'money-antifragile-budget', domain: 'Money', title: 'Financial Buffer Design', by: 'Panacea Practice', kind: 'practice', summary: 'A resilient financial system is designed for bad months, not only average months. Buffers create time to make better decisions under pressure.', tryThis: 'Estimate essential monthly outflow and calculate how many months your accessible buffer currently covers.' },
  { id: 'money-recurring-cost', domain: 'Money', title: 'Recurring-Cost Audit', by: 'Panacea Practice', kind: 'practice', summary: 'Small subscriptions are not automatically bad, but recurring commitments deserve a recurring review. The goal is to align money with actual use and values.', tryThis: 'Review three recurring expenses and label each keep, renegotiate, replace or stop.' },
  { id: 'money-decision-journal', domain: 'Money', title: 'Financial Decision Journal', by: 'Panacea Practice', kind: 'practice', summary: 'Writing the assumptions behind a financial decision makes hindsight less seductive. Later, you can judge the process separately from luck.', tryThis: 'Before one meaningful money decision, write the thesis, biggest risk and condition that would change your mind.' },

  // ── KNOWLEDGE ───────────────────────────────────────────────────────────
  { id: 'knowledge-make-it-stick', domain: 'Knowledge', title: 'Make It Stick', by: 'Brown, Roediger & McDaniel', year: 2014, kind: 'book', summary: 'Retrieval practice, spacing and interleaving often feel harder than rereading because they expose forgetting. That difficulty is part of why they improve durable learning.', tryThis: 'Close the notes and retrieve five facts before rereading anything.' },
  { id: 'knowledge-ultralearning', domain: 'Knowledge', title: 'Ultralearning', by: 'Scott Young', year: 2019, kind: 'book', summary: 'Intense self-directed learning improves when practice resembles the real skill, feedback is fast and weaknesses are isolated deliberately.', tryThis: 'Replace one passive study block with a task that resembles the exam, conversation or output you actually want to perform.' },
  { id: 'knowledge-range', domain: 'Knowledge', title: 'Range', by: 'David Epstein', year: 2019, kind: 'book', summary: 'In many uncertain domains, broad experience and analogical thinking can complement specialization. The lesson is not that depth is bad, but that transfer between domains is a real skill.', tryThis: 'Explain one current problem using an analogy from a completely different field.' },
  { id: 'knowledge-thinking-fast-slow', domain: 'Knowledge', title: 'Thinking, Fast and Slow', by: 'Daniel Kahneman', year: 2011, kind: 'book', summary: 'The book popularized a large body of work on judgment and bias; some specific studies have since faced replication problems. Its durable value is the habit of questioning intuitive certainty.', tryThis: 'For one high-stakes judgment, list what evidence would make the opposite conclusion more plausible.' },
  { id: 'knowledge-feynman', domain: 'Knowledge', title: 'Feynman Explanation Test', by: 'Panacea Practice', kind: 'practice', summary: 'A concept that cannot be explained simply may still contain gaps. Simplification is not dumbing down; it is a test of structure.', tryThis: 'Explain one concept in five sentences without jargon, then mark the sentence where you become vague.' },
  { id: 'knowledge-question-bank', domain: 'Knowledge', title: 'Question-First Reading', by: 'Panacea Practice', kind: 'practice', summary: 'Reading becomes more active when a question comes before the text. The brain has a target for relevance instead of treating every paragraph equally.', tryThis: 'Before a chapter or guideline, write three questions you want it to answer.' },
  { id: 'knowledge-teachback', domain: 'Knowledge', title: 'Teach-Back Loop', by: 'Panacea Practice', kind: 'practice', summary: 'Teaching reveals missing links quickly because the explanation must survive another person’s questions. It also converts private knowledge into social value.', tryThis: 'Teach one concept to a peer or to an empty room in under three minutes, then revise the weakest transition.' },

  // ── SOCIAL ──────────────────────────────────────────────────────────────
  { id: 'social-bowling-alone', domain: 'Social', title: 'Bowling Alone', by: 'Robert Putnam', year: 2000, kind: 'book', summary: 'Putnam documents the decline of many forms of civic participation and social capital in the United States. The larger lesson is that connection is also infrastructure, not just mood.', tryThis: 'Identify one recurring group, club or community where showing up repeatedly would matter more than one-off networking.' },
  { id: 'social-together', domain: 'Social', title: 'Together', by: 'Vivek Murthy', year: 2020, kind: 'book', summary: 'Loneliness and social connection are treated as health-relevant experiences without pretending every form of solitude is pathological. Quality and reciprocity matter more than contact counts.', tryThis: 'Send one message that contains real curiosity instead of a reaction emoji or logistical request.' },
  { id: 'social-give-take', domain: 'Social', title: 'Give and Take', by: 'Adam Grant', year: 2013, kind: 'book', summary: 'Helping others can build strong networks, but indiscriminate giving can also exhaust. Sustainable generosity needs boundaries and attention to how help is delivered.', tryThis: 'Offer one specific form of help that has a clear limit rather than a vague “anything you need.”' },
  { id: 'social-nonviolent', domain: 'Social', title: 'Nonviolent Communication', by: 'Marshall Rosenberg', year: 1999, kind: 'book', summary: 'The method separates observations, feelings, needs and requests so conflict is less likely to collapse into accusation. It is a communication tool, not a guarantee that every relationship can be repaired.', tryThis: 'Rewrite one complaint as an observation plus a concrete request.' },
  { id: 'social-weak-ties', domain: 'Social', title: 'The Strength of Weak Ties', by: 'Mark Granovetter', year: 1973, kind: 'research-guide', summary: 'Social networks often transmit new information through acquaintances who connect otherwise separate groups. Close friends and weak ties serve different functions.', tryThis: 'Reconnect with one acquaintance whose world differs from your immediate circle.' },
  { id: 'social-reciprocity', domain: 'Social', title: 'Reciprocity Map', by: 'Panacea Practice', kind: 'practice', summary: 'Healthy networks are not perfectly balanced transaction by transaction, but over time they usually contain both giving and receiving. Chronic one-way relationships deserve attention.', tryThis: 'List three people you support and three people you can honestly ask for help.' },
  { id: 'social-presence', domain: 'Social', title: 'Ten Minutes of Presence', by: 'Panacea Practice', kind: 'practice', summary: 'Connection often improves through undivided attention rather than longer total contact. A short conversation without task-switching can feel different from an hour of partial presence.', tryThis: 'Give one person ten phone-free minutes today.' },

  // ── FAMILY ──────────────────────────────────────────────────────────────
  { id: 'family-seven-principles', domain: 'Family', title: 'The Seven Principles for Making Marriage Work', by: 'John Gottman & Nan Silver', year: 1999, kind: 'book', summary: 'The book translates long-running relationship research into patterns around friendship, conflict and repair. It is most useful as a language for noticing interactions, not as a score that predicts an individual marriage with certainty.', tryThis: 'Ask one question about your partner or family member’s current inner world that you do not already know the answer to.' },
  { id: 'family-all-about-love', domain: 'Family', title: 'All About Love', by: 'bell hooks', year: 2000, kind: 'book', summary: 'hooks treats love as an active practice involving care, commitment, knowledge, responsibility, respect and trust, rather than only an emotion.', tryThis: 'Choose one relationship and name a concrete behavior that would make care more visible this week.' },
  { id: 'family-adult-children', domain: 'Family', title: 'Adult Children of Emotionally Immature Parents', by: 'Lindsay C. Gibson', year: 2015, kind: 'book', summary: 'The book offers a framework for understanding emotionally limited family dynamics and setting boundaries. Readers should use it as a lens, not a remote diagnosis of relatives.', tryThis: 'Identify one boundary you can state as your own action rather than a demand that another person change.' },
  { id: 'family-legacy-interview', domain: 'Family', title: 'Legacy Interview', by: 'Panacea Practice', kind: 'practice', summary: 'Families lose knowledge when stories are never recorded: migration, work, illness, traditions, failures and turning points. A short interview can preserve context that later records cannot reconstruct.', tryThis: 'Ask an older relative one question about a decision that changed the family’s direction and record the answer with permission.' },
  { id: 'family-care-map', domain: 'Family', title: 'Family Care Map', by: 'Panacea Practice', kind: 'practice', summary: 'Care work is often invisible until one person can no longer do it. Mapping who depends on whom makes resilience and overload easier to see.', tryThis: 'Write the names of people who give and receive care in your family, then mark any single point of failure.' },
  { id: 'family-ritual', domain: 'Family', title: 'Small Family Rituals', by: 'Panacea Practice', kind: 'practice', summary: 'Repeated rituals create predictability and shared identity without requiring grand events. The value comes from recurrence more than expense.', tryThis: 'Choose one weekly ritual that takes under thirty minutes and can survive a busy month.' },
  { id: 'family-repair', domain: 'Family', title: 'Repair After Conflict', by: 'Panacea Practice', kind: 'practice', summary: 'Families do not need an absence of conflict to be functional; they need ways to return to safety, accountability and connection after conflict.', tryThis: 'Use one repair sentence that owns your part without immediately adding a defense.' },

  // ── CAREER ──────────────────────────────────────────────────────────────
  { id: 'career-so-good', domain: 'Career', title: 'So Good They Can’t Ignore You', by: 'Cal Newport', year: 2012, kind: 'book', summary: 'Career satisfaction can grow from rare and valuable skills, autonomy and meaningful contribution rather than from discovering a single pre-existing passion.', tryThis: 'Name one skill that compounds across several possible careers and schedule deliberate practice for it.' },
  { id: 'career-designing-life', domain: 'Career', title: 'Designing Your Life', by: 'Bill Burnett & Dave Evans', year: 2016, kind: 'book', summary: 'Career decisions can be prototyped instead of solved entirely in the head. Small experiments generate information that abstract rumination cannot.', tryThis: 'Design one low-cost prototype: a conversation, shadowing day, project or application that tests a career assumption.' },
  { id: 'career-working-identity', domain: 'Career', title: 'Working Identity', by: 'Herminia Ibarra', year: 2003, kind: 'book', summary: 'Career transitions often happen by trying possible selves in practice, building new networks and revising the story of who you are. Identity can follow action rather than precede it.', tryThis: 'Do one small piece of the role you are considering before deciding whether you “are” that kind of person.' },
  { id: 'career-range', domain: 'Career', title: 'Range for Careers', by: 'David Epstein', year: 2019, kind: 'book', summary: 'Sampling different environments can build transfer skills and reveal fit, especially in uncertain fields. Early specialization is not automatically superior outside stable rule-based domains.', tryThis: 'List three experiences that looked unrelated but taught the same underlying skill.' },
  { id: 'career-skill-stack', domain: 'Career', title: 'Skill-Stack Map', by: 'Panacea Practice', kind: 'practice', summary: 'A distinctive career can emerge from a combination of several strong skills even when none is world-class alone. The combination matters when it solves a real problem.', tryThis: 'Write five skills you already have and circle the pair whose combination is least common in your field.' },
  { id: 'career-optionality', domain: 'Career', title: 'Career Optionality', by: 'Panacea Practice', kind: 'practice', summary: 'Some career moves increase future choices while others narrow them. Salary, prestige and learning are only part of the decision; reversibility and network effects also matter.', tryThis: 'For one opportunity, score learning, network, autonomy, reversibility and financial runway separately before choosing.' },
  { id: 'career-contribution', domain: 'Career', title: 'Contribution Ledger', by: 'Panacea Practice', kind: 'practice', summary: 'A career is easier to evaluate when output and contribution are recorded, not only titles and effort. Evidence of useful work compounds into confidence, negotiation and future opportunities.', tryThis: 'Record one concrete result from this week: what changed, for whom, and what evidence shows it changed.' },
]

export const WEALTH_DOMAINS: WealthDomain[] = ['Time', 'Health', 'Money', 'Knowledge', 'Social', 'Family', 'Career']

export function readingsFor(domain: WealthDomain): LifeReading[] {
  return LIFE_LIBRARY.filter((item) => item.domain === domain)
}
