// ─────────────────────────────────────────────────────────────────────────────
// Mekanisme obat — mengapa obat ini, dan ia mengatasi apa.
//
// MASALAH YANG DIPECAHKAN. Daftar tatalaksana memberi tahu obat APA dan
// BERAPA, tetapi tidak memberi tahu MENGAPA. Nama dan angka yang dihafal tanpa
// alasannya akan tertukar di bawah tekanan ujian, dan yang lebih buruk, ia
// tidak dapat dipakai menalar kasus yang sedikit berbeda dari yang dihafal.
// Orang yang tahu nitrat menurunkan preload dan statin menstabilkan plak tidak
// perlu menghafal mana yang dihentikan saat pasien tidak nyeri — ia dapat
// menyimpulkannya.
//
// SATU KAMUS UNTUK SELURUH ENTRI. Menuliskan mekanisme pada tiap entri
// tatalaksana berarti menyalin penjelasan aspirin ke belasan tempat, dan
// salinan yang tersebar pasti berbeda-beda setelah beberapa kali diperbaiki.
// Di sini ia ditulis SEKALI, lalu dicocokkan otomatis dengan nama obat yang
// disebut di dalam teks tatalaksana.
//
// EMPAT MEDAN, DAN URUTANNYA DISENGAJA:
//   golongan   — tempat obat ini berdiri di antara obat lain
//   mekanisme  — dari molekul sampai efek yang terlihat, bukan istilah saja
//   mengatasi  — gejala atau masalah APA yang hilang karenanya
//   ingat      — satu kalimat yang membuatnya melekat
//   awas       — satu hal yang paling berbahaya bila terlupa
//
// "Mengatasi" ditulis terpisah dari "mekanisme" dengan sengaja: itulah yang
// membedakan nitrat yang meredakan nyeri dari statin yang mencegah kematian,
// dan pasien berhenti minum statin justru karena perbedaan itu tidak pernah
// dijelaskan kepadanya.
// ─────────────────────────────────────────────────────────────────────────────

export interface MekanismeObat {
  /** Nama baku yang ditampilkan. */
  nama: string
  /** Ejaan lain yang muncul di dalam teks tatalaksana. Dipakai mencocokkan. */
  alias?: string[]
  golongan: string
  /**
   * Mekanisme sebagai RANTAI PANAH, satu langkah satu ruas.
   *
   * Bentuk inilah yang dibaca lebih dahulu, dan paragraf di bawahnya hanya
   * untuk yang ingin menelusuri. Alasannya bukan selera: rantai pendek dapat
   * DIULANG DALAM HATI dan diucapkan, sedangkan paragraf harus dibaca ulang
   * dari awal setiap kali satu mata rantai terlupa. Menjelang ujian, yang
   * dibutuhkan adalah urutan yang dapat disebutkan, bukan penjelasan yang
   * dapat dipahami sekali lalu hilang.
   *
   * Ditulis sebagai daftar, bukan satu kalimat berisi panah, supaya barisnya
   * dapat dipatahkan mengikuti lebar layar tanpa memutus rantainya di tempat
   * yang keliru.
   */
  rantai?: string[]
  mekanisme: string
  /** Gejala atau masalah yang diatasinya — bukan pengulangan mekanismenya. */
  mengatasi: string
  ingat?: string
  awas?: string
}

export const MEKANISME_OBAT: MekanismeObat[] = [
  {
    nama: 'Aspirin',
    alias: ['asetosal', 'acetosal', 'asam asetilsalisilat'],
    rantai: [
      'Plak pecah',
      'trombosit aktif',
      'TXA₂ ↑',
      'agregasi',
      'trombus',
      'sumbatan koroner',
      'INFARK',
      '',
      'Aspirin ⊣ COX-1',
      'TXA₂ ↓',
      'agregasi ↓',
      'Irreversibel → 7-10 hari',
    ],
    golongan: 'Antiplatelet (dosis rendah) / NSAID (dosis tinggi)',
    mekanisme: 'Menghambat COX-1 trombosit secara IRREVERSIBEL sehingga tromboksan A2 tidak terbentuk dan agregasi trombosit menurun. Karena trombosit tidak berinti, ia tidak dapat membuat enzim baru — efeknya bertahan sepanjang umur trombosit, 7-10 hari.',
    mengatasi: 'MENCEGAH pembentukan trombus (infark, stroke), bukan menghilangkan nyeri angina.',
    ingat: 'Irreversibel = 7-10 hari. Itu sebabnya aspirin dihentikan seminggu sebelum operasi.',
    awas: 'Perdarahan saluran cerna; hindari pada anak dengan infeksi virus (sindrom Reye).',
  },
  {
    nama: 'Klopidogrel',
    alias: ['clopidogrel'],
    golongan: 'Antiplatelet penghambat P2Y12',
    mekanisme: 'Menghambat reseptor ADP P2Y12 pada trombosit secara irreversibel sehingga aktivasi glikoprotein IIb/IIIa dan agregasi terhambat. Bekerja pada jalur BERBEDA dari aspirin — itulah dasar terapi antiplatelet ganda.',
    mengatasi: 'Mencegah trombus pada sindrom koroner akut dan setelah pemasangan cincin; pengganti aspirin bila alergi.',
    ingat: 'Jalur ADP, bukan COX — dua jalur berbeda menutup dua pintu.',
    awas: 'Perdarahan; hentikan 5-7 hari sebelum operasi besar.',
  },
  {
    nama: 'Statin',
    alias: ['atorvastatin', 'rosuvastatin', 'simvastatin'],
    rantai: [
      'Statin ⊣ HMG-CoA reduktase',
      'kolesterol hati ↓',
      'reseptor LDL ↑',
      'LDL darah ↓',
      '+ radang plak ↓',
      'tudung plak MENEBAL',
      'plak tidak mudah pecah',
    ],
    golongan: 'Penghambat HMG-CoA reduktase',
    mekanisme: 'Menghambat HMG-CoA reduktase, enzim penentu laju sintesis kolesterol di hati; reseptor LDL hati bertambah sehingga LDL darah ditarik masuk. Selain itu bersifat PLEIOTROPIK: meredam radang dinding pembuluh dan MENEBALKAN tudung plak sehingga tidak mudah pecah.',
    mengatasi: 'Memodifikasi penyakit dan MENCEGAH infark maupun stroke — bukan meredakan nyeri dada.',
    ingat: 'Statin menstabilkan plak, bukan melebarkan pembuluh. Itu sebabnya ia tetap diminum meski tidak ada keluhan.',
    awas: 'Nyeri otot sampai rabdomiolisis; periksa CK bila nyeri otot berat. Naikkan kewaspadaan bila bersama fibrat.',
  },
  {
    nama: 'Nitrat',
    alias: ['nitrogliserin', 'isosorbid', 'isdn', 'ismn', 'gliseril trinitrat'],
    rantai: [
      'Nitrat',
      'NO ↑',
      'cGMP ↑',
      'otot polos VENA melemas',
      'aliran balik (preload) ↓',
      'kerja jantung ↓',
      'kebutuhan O₂ ↓',
      'NYERI REDA',
    ],
    golongan: 'Vasodilator donor nitrit oksida',
    mekanisme: 'Melepaskan nitrit oksida yang mengaktifkan guanilat siklase sehingga cGMP naik dan otot polos pembuluh melemas. Terutama melebarkan VENA sehingga aliran balik ke jantung (preload) berkurang, dan dengan demikian kebutuhan oksigen miokardium turun.',
    mengatasi: 'MEREDAKAN nyeri angina saat itu juga — tidak memperpanjang hidup.',
    ingat: 'Nitrat = pereda gejala. Aspirin dan statin = penyelamat nyawa.',
    awas: 'Hipotensi berat bila bersama sildenafil/tadalafil (24-48 jam) dan pada infark ventrikel kanan. Toleransi timbul tanpa jeda bebas nitrat 8-12 jam.',
  },
  {
    nama: 'Penyekat beta',
    alias: ['bisoprolol', 'metoprolol', 'propranolol', 'atenolol', 'carvedilol', 'karvedilol'],
    rantai: [
      '⊣ reseptor beta-1 jantung',
      'nadi ↓ + kontraktilitas ↓',
      'kebutuhan O₂ ↓',
      '+ diastol memanjang',
      'pengisian koroner ↑',
      'angina ↓',
    ],
    golongan: 'Penghambat reseptor beta-adrenergik',
    mekanisme: 'Menghambat reseptor beta-1 di jantung sehingga laju denyut, kontraktilitas, dan konduksi AV menurun — kerja jantung dan kebutuhan oksigennya berkurang, sekaligus waktu pengisian koroner saat diastol memanjang. Propranolol juga menghambat perubahan T4 menjadi T3 di perifer.',
    mengatasi: 'Mengurangi frekuensi angina, mengendalikan laju pada fibrilasi atrium, menurunkan kematian pada gagal jantung dan pascainfark, serta meredakan berdebar dan tremor pada tirotoksikosis.',
    ingat: 'Dosisnya ditentukan SASARAN NADI istirahat 55-60, bukan angka mg yang dihafal.',
    awas: 'Jangan dihentikan mendadak (angina rebound). Hati-hati pada asma berat, blok AV, dan bradikardia; menutupi gejala hipoglikemia.',
  },
  {
    nama: 'Penghambat kanal kalsium',
    alias: ['amlodipin', 'nifedipin', 'diltiazem', 'verapamil'],
    rantai: [
      '⊣ kanal Ca otot polos',
      'vasodilatasi',
      'afterload ↓',
      '(non-dihidropiridin juga ⊣ nodus SA/AV → nadi ↓)',
    ],
    golongan: 'Penghambat kanal kalsium',
    mekanisme: 'Menghambat masuknya kalsium ke otot polos pembuluh (golongan dihidropiridin: amlodipin, nifedipin) sehingga terjadi vasodilatasi dan afterload turun; golongan non-dihidropiridin (diltiazem, verapamil) juga menekan nodus SA dan AV sehingga laju denyut turun.',
    mengatasi: 'Menurunkan tekanan darah, meredakan angina, mengendalikan laju pada takiaritmia supraventrikel, dan MENCEGAH SPASME pada angina Prinzmetal.',
    ingat: 'Dihidropiridin ke PEMBULUH, non-dihidropiridin ke JANTUNG.',
    awas: 'Verapamil dan diltiazem JANGAN digabung dengan penyekat beta (bradikardia dan blok berat). Amlodipin sering menimbulkan edema tungkai.',
  },
  {
    nama: 'ACE-inhibitor',
    alias: ['kaptopril', 'captopril', 'lisinopril', 'ramipril', 'enalapril'],
    rantai: [
      '⊣ ACE',
      'Angiotensin II ↓',
      'vasokonstriksi ↓ + aldosteron ↓',
      'TD ↓ + retensi Na ↓',
      'remodeling ↓',
      '',
      'Bradikinin ↑',
      'BATUK KERING',
    ],
    golongan: 'Penghambat enzim pengubah angiotensin',
    mekanisme: 'Menghambat perubahan angiotensin I menjadi angiotensin II sehingga vasokonstriksi dan sekresi aldosteron berkurang: tekanan darah turun, retensi natrium berkurang, dan remodeling jantung serta ginjal dihambat. Bradikinin ikut menumpuk — dari sinilah batuk keringnya.',
    mengatasi: 'Menurunkan tekanan darah, memperpanjang hidup pada gagal jantung dan pascainfark, dan MELINDUNGI GINJAL pada proteinuria diabetik.',
    ingat: 'Batuk kering = bradikinin. Ganti ke ARB bila mengganggu.',
    awas: 'KONTRAINDIKASI pada kehamilan. Awas hiperkalemia, gagal ginjal akut pada stenosis arteri renalis bilateral, dan angioedema.',
  },
  {
    nama: 'Furosemid',
    alias: ['furosemide', 'lasix'],
    rantai: [
      '⊣ Na-K-2Cl di ansa Henle',
      'reabsorpsi Na ↓',
      'diuresis kuat',
      'cairan ↓',
      '+ venodilatasi → sesak reda LEBIH DULU',
    ],
    golongan: 'Diuretik kuat (loop)',
    mekanisme: 'Menghambat kotransporter Na-K-2Cl pada ansa Henle asendens tebal sehingga reabsorpsi natrium besar-besaran dihambat dan diuresis kuat terjadi. Pada edema paru ia juga bersifat venodilator, meredakan sesak SEBELUM diuresisnya mulai.',
    mengatasi: 'Mengeluarkan kelebihan cairan: sesak pada edema paru, bengkak tungkai, dan asites.',
    ingat: 'Loop = mengurangi CAIRAN, bukan memperbaiki pompa jantungnya.',
    awas: 'Hipokalemia, hiponatremia, dehidrasi, gangguan pendengaran pada dosis besar cepat.',
  },
  {
    nama: 'Spironolakton',
    alias: ['spironolactone', 'aldakton'],
    rantai: [
      '⊣ reseptor aldosteron',
      'Na keluar, KALIUM DITAHAN',
      'cairan ↓',
      '+ fibrosis miokard ↓',
    ],
    golongan: 'Antagonis aldosteron (diuretik hemat kalium)',
    mekanisme: 'Menghambat reseptor aldosteron di tubulus distal sehingga natrium dikeluarkan tetapi KALIUM DITAHAN; pada gagal jantung ia juga menghambat fibrosis miokardium.',
    mengatasi: 'Mengurangi cairan pada gagal jantung dan asites sirosis, serta memperpanjang hidup pada gagal jantung.',
    ingat: 'Perbandingan 100:40 dengan furosemid pada asites — supaya kalium tidak jatuh.',
    awas: 'HIPERKALEMIA, terutama bersama ACE-inhibitor; ginekomastia.',
  },
  {
    nama: 'Parasetamol',
    alias: ['paracetamol', 'asetaminofen', 'acetaminophen'],
    rantai: [
      '⊣ prostaglandin di HIPOTALAMUS',
      'titik setel suhu ↓',
      'DEMAM TURUN',
      '(di jaringan hampir tanpa efek radang)',
    ],
    golongan: 'Analgetik-antipiretik',
    mekanisme: 'Bekerja terutama di susunan saraf pusat, menghambat sintesis prostaglandin di hipotalamus sehingga titik setel suhu diturunkan; efek antiradangnya di jaringan hampir tidak ada.',
    mengatasi: 'Menurunkan demam dan meredakan nyeri ringan-sedang.',
    ingat: 'Aman untuk lambung dan untuk ibu hamil — itulah keunggulannya atas NSAID.',
    awas: 'Overdosis merusak HATI (metabolit NAPQI); batas dewasa 4 g/hari, lebih rendah pada peminum alkohol dan penyakit hati.',
  },
  {
    nama: 'NSAID',
    alias: ['ibuprofen', 'natrium diklofenak', 'diklofenak', 'meloksikam', 'asam mefenamat', 'ketorolak', 'naproksen', 'indometasin', 'piroksikam'],
    rantai: [
      '⊣ COX-1 & COX-2',
      'prostaglandin ↓',
      'radang ↓ nyeri ↓ demam ↓',
      '',
      'COX-1 juga ⊣',
      'PG pelindung lambung ↓',
      'TUKAK',
      'aliran darah ginjal ↓',
    ],
    golongan: 'Antiinflamasi nonsteroid',
    mekanisme: 'Menghambat COX-1 dan COX-2 sehingga prostaglandin berkurang: radang, nyeri, dan demam menurun. Penghambatan COX-1 juga menghilangkan prostaglandin pelindung mukosa lambung dan menurunkan aliran darah ginjal — dari situlah efek sampingnya.',
    mengatasi: 'Meredakan NYERI DENGAN RADANG: artritis, kolik ureter, nyeri haid, cedera jaringan.',
    ingat: 'COX-1 = pelindung lambung dan ginjal; COX-2 = radang. Itu sebabnya khasiat dan efek sampingnya satu paket.',
    awas: 'Ulkus dan perdarahan lambung, gangguan ginjal, retensi cairan. Hindari pada dengue, gagal ginjal, dan trimester ketiga kehamilan.',
  },
  {
    nama: 'Kortikosteroid',
    alias: ['prednison', 'prednisolon', 'metilprednisolon', 'deksametason', 'hidrokortison', 'betametason'],
    rantai: [
      'Masuk inti sel → ubah transkripsi',
      '⊣ fosfolipase A₂',
      'asam arakidonat ↓',
      'prostaglandin DAN leukotrien ↓ sekaligus',
      '+ sitokin ↓',
      'RADANG PADAM',
      '(butuh jam — bekerja lewat gen)',
    ],
    golongan: 'Glukokortikoid',
    mekanisme: 'Masuk ke inti sel dan mengubah transkripsi gen: menekan fosfolipase A2 (sehingga seluruh jalur prostaglandin dan leukotrien terputus sekaligus), menurunkan sitokin, dan menstabilkan membran sel radang. Karena bekerja di tingkat gen, efeknya baru penuh dalam hitungan jam.',
    mengatasi: 'Menekan PERADANGAN dan reaksi imun: asma, PPOK eksaserbasi, penyakit autoimun, reaksi alergi berat, edema otak.',
    ingat: 'Bekerja di HULU — satu obat memutus banyak jalur sekaligus. Karena itu kuat, dan karena itu pula efek sampingnya luas.',
    awas: 'Pemakaian lama: gula darah naik, osteoporosis, infeksi, supresi adrenal. JANGAN dihentikan mendadak setelah pemakaian panjang.',
  },
  {
    nama: 'Salbutamol',
    alias: ['salbutamol', 'albuterol', 'ventolin', 'terbutalin'],
    rantai: [
      'Rangsang beta-2 bronkus',
      'cAMP ↑',
      'otot polos melemas',
      'BRONKUS MELEBAR (menit)',
    ],
    golongan: 'Agonis beta-2 kerja pendek',
    mekanisme: 'Merangsang reseptor beta-2 pada otot polos bronkus sehingga cAMP naik dan otot melemas — bronkus melebar dalam hitungan menit.',
    mengatasi: 'MEMBUKA jalan napas yang menyempit: sesak dan mengi pada asma serta PPOK.',
    ingat: 'Beta-2 = pelega. Steroid inhalasi = pengendali. Pelega tanpa pengendali adalah kesalahan tersering pada asma.',
    awas: 'Tremor, berdebar, dan HIPOKALEMIA pada dosis besar.',
  },
  {
    nama: 'Ipratropium',
    alias: ['ipratropium', 'atrovent'],
    rantai: [
      '⊣ reseptor muskarinik',
      'tonus vagus bronkus ↓',
      'bronkus melebar',
      '(jalur BEDA dari salbutamol → digabung makin kuat)',
    ],
    golongan: 'Antikolinergik inhalasi',
    mekanisme: 'Menghambat reseptor muskarinik pada otot polos bronkus sehingga tonus parasimpatis yang menyempitkan jalan napas berkurang. Jalurnya BERBEDA dari salbutamol, sehingga digabung efeknya bertambah.',
    mengatasi: 'Menambah pelebaran jalan napas pada serangan asma berat dan eksaserbasi PPOK.',
    ingat: 'Pada PPOK, tonus kolinergik justru komponen yang paling reversibel.',
    awas: 'Mulut kering; hati-hati pada glaukoma sudut sempit bila terkena mata.',
  },
  {
    nama: 'Adrenalin',
    alias: ['epinefrin', 'epinephrine', 'adrenalin'],
    rantai: [
      'Alfa-1',
      'vasokonstriksi',
      'TD ↑ + edema mukosa ↓',
      '',
      'Beta-1',
      'nadi & kontraktilitas ↑',
      '',
      'Beta-2',
      'bronkus melebar + sel mast stabil',
      '',
      'Tiga sekaligus → tak tergantikan pada anafilaksis',
    ],
    golongan: 'Agonis adrenergik alfa dan beta',
    mekanisme: 'Alfa-1 menyempitkan pembuluh sehingga tekanan darah naik dan edema mukosa berkurang; beta-1 menaikkan denyut dan kontraktilitas; beta-2 melebarkan bronkus dan menstabilkan sel mast. Ketiganya bekerja bersamaan — inilah sebabnya tidak ada obat lain yang dapat menggantikannya pada anafilaksis.',
    mengatasi: 'Anafilaksis, henti jantung, croup berat (nebulisasi), dan syok.',
    ingat: 'Anafilaksis = ADRENALIN INTRAMUSKULAR di paha lateral. Antihistamin dan steroid hanya pelengkap dan tidak pernah menggantikan.',
    awas: 'Jalur IM pada anafilaksis, bukan IV (risiko aritmia). Awas pada penyakit jantung iskemik.',
  },
  {
    nama: 'Antihistamin',
    alias: ['setirizin', 'cetirizine', 'loratadin', 'klorfeniramin', 'ctm', 'difenhidramin', 'dimenhidrinat'],
    rantai: [
      '⊣ reseptor H1',
      'gatal ↓ bentol ↓ permeabilitas kapiler ↓',
      '(generasi lama menembus otak → MENGANTUK)',
    ],
    golongan: 'Antagonis reseptor H1',
    mekanisme: 'Menghambat reseptor histamin H1 sehingga gatal, bentol, bersin, dan permeabilitas kapiler berkurang. Golongan lama (klorfeniramin, difenhidramin) menembus sawar darah-otak sehingga mengantuk; golongan baru (setirizin, loratadin) tidak.',
    mengatasi: 'Meredakan GATAL dan bentol pada urtikaria, rinitis alergi, dan gigitan serangga; golongan lama juga meredakan mual akibat vertigo.',
    ingat: 'Antihistamin tidak pernah cukup untuk anafilaksis — yang menyelamatkan adalah adrenalin.',
    awas: 'Mengantuk dan efek antikolinergik pada golongan lama; hati-hati pada usia lanjut dan pekerjaan yang menuntut kewaspadaan.',
  },
  {
    nama: 'Amoksisilin',
    alias: ['amoxicillin', 'amoksisilin', 'amoksisilin-klavulanat', 'co-amoxiclav'],
    rantai: [
      '⊣ protein pengikat penisilin',
      'ikatan silang peptidoglikan gagal',
      'dinding sel tak terbentuk',
      'bakteri LISIS',
      '',
      'Klavulanat ⊣ beta-laktamase → melindungi amoksisilin',
    ],
    golongan: 'Antibiotik beta-laktam (penisilin spektrum luas)',
    mekanisme: 'Mengikat protein pengikat penisilin dan menghambat pembentukan ikatan silang peptidoglikan sehingga dinding sel bakteri gagal terbentuk dan bakteri lisis. Penambahan klavulanat menghambat enzim beta-laktamase sehingga kuman penghasil enzim itu kembali peka.',
    mengatasi: 'Infeksi saluran napas, telinga, gigi, saluran kemih, dan kulit oleh kuman yang peka.',
    ingat: 'Klavulanat bukan antibiotik — ia PENJAGA yang melindungi amoksisilin dari enzim perusak.',
    awas: 'Alergi penisilin (sampai anafilaksis); ruam pada mononukleosis; diare, terutama dengan klavulanat.',
  },
  {
    nama: 'Seftriakson',
    alias: ['ceftriaxone', 'seftriakson', 'sefiksim', 'cefixime', 'sefaleksin', 'cephalexin', 'sefadroksil'],
    golongan: 'Antibiotik sefalosporin',
    mekanisme: 'Sama seperti penisilin, menghambat sintesis dinding sel bakteri, tetapi lebih tahan terhadap beta-laktamase. Generasi makin tinggi makin kuat terhadap kuman gram negatif; seftriakson menembus cairan serebrospinal dengan baik.',
    mengatasi: 'Infeksi berat: meningitis, pielonefritis, demam tifoid, gonore, dan pneumonia yang perlu dirawat.',
    ingat: 'Generasi naik = gram negatif naik, gram positif menurun.',
    awas: 'Reaksi silang pada alergi penisilin berat. Seftriakson JANGAN dicampur cairan mengandung kalsium pada neonatus.',
  },
  {
    nama: 'Metronidazol',
    alias: ['metronidazole', 'metronidazol'],
    rantai: [
      'Masuk kuman ANAEROB',
      'gugus nitro direduksi',
      'radikal bebas',
      'DNA kuman putus',
      '(aerob tak bisa mereduksi → selektif)',
    ],
    golongan: 'Antibiotik nitroimidazol',
    mekanisme: 'Di dalam kuman ANAEROB dan protozoa, gugus nitronya direduksi menjadi radikal bebas yang memutus untai DNA. Kuman aerob tidak mampu mereduksinya — itulah sebabnya kerjanya sangat selektif pada anaerob.',
    mengatasi: 'Infeksi anaerob (abses, peritonitis, infeksi panggul), amubiasis, giardiasis, trikomoniasis, dan vaginosis bakterialis.',
    ingat: 'Metronidazol = anaerob dan protozoa. Kalau baunya busuk, ingat metronidazol.',
    awas: 'REAKSI DISULFIRAM dengan alkohol — larang alkohol selama terapi dan 48 jam sesudahnya; rasa logam di mulut.',
  },
  {
    nama: 'Doksisiklin',
    alias: ['doxycycline', 'doksisiklin', 'tetrasiklin'],
    rantai: [
      '⊣ ribosom 30S',
      'tRNA tak menempel',
      'sintesis protein berhenti',
      'bakteriostatik',
      '(menembus sel → kuman INTRASELULER)',
    ],
    golongan: 'Antibiotik tetrasiklin',
    mekanisme: 'Mengikat subunit ribosom 30S sehingga tRNA tidak dapat menempel dan sintesis protein bakteri terhenti (bakteriostatik). Menembus sel dengan baik sehingga efektif terhadap kuman INTRASELULER.',
    mengatasi: 'Klamidia, riketsia, leptospirosis, akne, dan profilaksis malaria.',
    ingat: 'Kuman yang bersembunyi DI DALAM sel = tetrasiklin atau makrolid.',
    awas: 'KONTRAINDIKASI pada kehamilan dan anak <8 tahun (mewarnai gigi dan mengganggu tulang). Fotosensitivitas; jangan berbaring 30 menit setelah minum (esofagitis).',
  },
  {
    nama: 'Azitromisin',
    alias: ['azithromycin', 'azitromisin', 'eritromisin', 'erythromycin', 'klaritromisin'],
    rantai: [
      '⊣ ribosom 50S',
      'translokasi peptida berhenti',
      'sintesis protein berhenti',
      '(terkumpul di jaringan → dosis pendek cukup)',
    ],
    golongan: 'Antibiotik makrolid',
    mekanisme: 'Mengikat subunit ribosom 50S dan menghambat translokasi rantai peptida sehingga sintesis protein bakteri terhenti. Terkumpul di dalam jaringan dan sel radang, sehingga kadarnya di tempat infeksi jauh melebihi kadar dalam darah.',
    mengatasi: 'Infeksi napas, klamidia, pertusis, difteri, dan pilihan pengganti pada alergi penisilin.',
    ingat: 'Waktu paruh panjang: azitromisin 3-5 hari sudah setara terapi 10 hari obat lain.',
    awas: 'Memanjangkan interval QT; banyak interaksi obat lewat enzim hati (eritromisin dan klaritromisin).',
  },
  {
    nama: 'Siprofloksasin',
    alias: ['ciprofloxacin', 'siprofloksasin', 'levofloksasin', 'levofloxacin', 'ofloksasin', 'fluorokuinolon'],
    rantai: [
      '⊣ DNA girase & topoisomerase IV',
      'DNA tak dapat dipilin',
      'replikasi gagal',
      'BAKTERISID',
      '(larut lemak → menembus PROSTAT & tulang)',
    ],
    golongan: 'Antibiotik fluorokuinolon',
    mekanisme: 'Menghambat DNA girase dan topoisomerase IV sehingga DNA bakteri tidak dapat dipilin dan direplikasi — bersifat bakterisid. Larut lemak sehingga menembus prostat dan tulang dengan baik.',
    mengatasi: 'Infeksi saluran kemih berkomplikasi, prostatitis, infeksi usus, dan infeksi Pseudomonas.',
    ingat: 'Menembus PROSTAT — itulah sebabnya prostatitis diobati dengan golongan ini selama 2-4 minggu.',
    awas: 'Ruptur tendon Achilles, neuropati, perpanjangan QT, dan disglikemia. Hindari pada anak dan kehamilan kecuali indikasi kuat; jangan bersama antasida, kalsium, atau besi.',
  },
  {
    nama: 'Kotrimoksazol',
    alias: ['cotrimoxazole', 'kotrimoksazol', 'trimetoprim', 'sulfametoksazol'],
    rantai: [
      'Sulfametoksazol ⊣ dihidropteroat sintase',
      '↓',
      'Trimetoprim ⊣ dihidrofolat reduktase',
      'folat bakteri ↓↓',
      'DNA bakteri gagal dibuat',
      '(manusia ambil folat dari makanan → aman)',
    ],
    golongan: 'Antibiotik sulfa (kombinasi)',
    mekanisme: 'Menghambat DUA langkah berurutan pada sintesis asam folat bakteri: sulfametoksazol menghambat dihidropteroat sintase dan trimetoprim menghambat dihidrofolat reduktase. Hambatan berurutan inilah yang membuat kombinasinya jauh lebih kuat daripada masing-masing sendiri. Manusia tidak membuat folat sendiri melainkan mengambil dari makanan, sehingga tidak terganggu.',
    mengatasi: 'Infeksi saluran kemih, profilaksis dan terapi pneumonia Pneumocystis, serta beberapa infeksi kulit.',
    ingat: 'Dua pisau pada satu jalur — itu sebabnya disebut kombinasi sinergistik.',
    awas: 'Sindrom Stevens-Johnson, hiperkalemia, gangguan ginjal. Hindari pada trimester pertama dan ketiga; interaksi kuat dengan metotreksat dan warfarin.',
  },
  {
    nama: 'Insulin',
    alias: ['insulin', 'novorapid', 'levemir', 'lantus'],
    rantai: [
      'Insulin → reseptor',
      'GLUT4 ke membran',
      'glukosa MASUK sel',
      'gula darah ↓',
      '',
      '+ lipolisis ⊣',
      'asam lemak bebas ↓',
      'KETON BERHENTI dibuat',
      '',
      '+ KALIUM ikut masuk sel → hipokalemia',
    ],
    golongan: 'Hormon anabolik',
    mekanisme: 'Mengikat reseptor insulin sehingga transporter GLUT4 dipindahkan ke membran sel otot dan lemak: glukosa masuk ke dalam sel, glikogenesis dan lipogenesis meningkat, sedangkan produksi glukosa hati serta lipolisis ditekan. Penekanan lipolisis inilah yang menghentikan pembentukan badan keton.',
    mengatasi: 'Menurunkan gula darah, dan pada ketoasidosis MENGHENTIKAN produksi keton — itulah sasaran sesungguhnya, bukan sekadar angka gula.',
    ingat: 'Insulin mendorong KALIUM masuk sel bersama glukosa. Karena itu kalium diperiksa sebelum insulin dimulai.',
    awas: 'Hipoglikemia dan hipokalemia. Pada KAD, kalium <3,3 mEq/L berarti TUNDA insulin.',
  },
  {
    nama: 'Metformin',
    alias: ['metformin'],
    rantai: [
      'Aktifkan AMPK di hati',
      'glukoneogenesis ↓',
      'produksi gula hati ↓',
      '+ sensitivitas insulin otot ↑',
      '(tak memeras pankreas → tak hipoglikemia)',
    ],
    golongan: 'Biguanid',
    mekanisme: 'Mengaktifkan AMPK di hati sehingga GLUKONEOGENESIS ditekan; sensitivitas insulin di otot meningkat. Tidak merangsang sekresi insulin, karena itu hampir tidak menyebabkan hipoglikemia bila dipakai sendiri.',
    mengatasi: 'Menurunkan gula darah pada diabetes tipe 2 dan menjadi obat lini pertama.',
    ingat: 'Metformin menekan pabrik gula di HATI, bukan memeras pankreas.',
    awas: 'Gangguan saluran cerna (minum sesudah makan, naikkan bertahap); asidosis laktat pada gagal ginjal — hentikan bila eGFR sangat rendah dan sebelum pemberian kontras.',
  },
  {
    nama: 'Levotiroksin',
    alias: ['levotiroksin', 'levothyroxine', 'euthyrox'],
    rantai: [
      'T4 → T3 di jaringan',
      'ubah transkripsi gen',
      'laju metabolisme ↑',
      'gejala hipotiroid hilang',
    ],
    golongan: 'Hormon tiroid pengganti',
    mekanisme: 'Menggantikan T4, yang di jaringan diubah menjadi T3 aktif dan mengatur transkripsi gen sehingga laju metabolisme basal, kepekaan reseptor beta, dan pertumbuhan kembali normal.',
    mengatasi: 'Hipotiroid: lelah, tidak tahan dingin, sembelit, kulit kering, dan lambat berpikir.',
    ingat: 'Diminum PAGI perut kosong, berjarak 4 jam dari kalsium, besi, dan antasida — semuanya menghalangi penyerapannya.',
    awas: 'Dosis berlebih menimbulkan tirotoksikosis iatrogenik, fibrilasi atrium, dan osteoporosis. Mulai kecil pada usia lanjut dan penyakit jantung.',
  },
  {
    nama: 'Tiamazol',
    alias: ['tiamazol', 'metimazol', 'methimazole', 'propiltiourasil', 'PTU'],
    rantai: [
      '⊣ tiroid peroksidase',
      'iodinasi tirosin gagal',
      'hormon BARU tak dibuat',
      '',
      'Hormon SIMPANAN masih ada',
      '→ efek baru terasa 2-6 MINGGU',
      '(itu sebabnya penyekat beta dulu)',
    ],
    golongan: 'Obat antitiroid (tionamid)',
    mekanisme: 'Menghambat enzim tiroid peroksidase sehingga iodinasi tirosin dan penggabungannya menjadi hormon terhenti. PTU juga menghambat perubahan T4 menjadi T3 di perifer — kelebihan yang membuatnya dipilih pada krisis tiroid.',
    mengatasi: 'Menurunkan produksi hormon pada hipertiroid dan penyakit Graves.',
    ingat: 'Efek baru terasa 2-6 MINGGU karena hormon yang sudah tersimpan di kelenjar harus habis dahulu. Itu sebabnya penyekat beta diberikan lebih dahulu.',
    awas: 'AGRANULOSITOSIS: demam atau nyeri tenggorokan berarti hentikan obat dan periksa darah hari itu juga. PTU berisiko gagal hati fulminan.',
  },
  {
    nama: 'Omeprazol',
    alias: ['omeprazol', 'omeprazole', 'lansoprazol', 'pantoprazol', 'esomeprazol'],
    rantai: [
      '⊣ pompa H⁺/K⁺-ATPase (irreversibel)',
      'sekresi asam berhenti',
      '(pompa = keran TERAKHIR → apa pun rangsangannya tetap tertutup)',
    ],
    golongan: 'Penghambat pompa proton',
    mekanisme: 'Menghambat pompa H+/K+-ATPase pada sel parietal lambung secara irreversibel — pompa terakhir pada jalur sekresi asam, sehingga apa pun rangsangannya asam tetap tertekan.',
    mengatasi: 'Nyeri ulu hati, refluks, tukak lambung, dan pencegahan tukak akibat NSAID.',
    ingat: 'Pompa proton = keran terakhir. Menutup di ujung lebih tuntas daripada menutup salah satu rangsangan.',
    awas: 'Diminum 30-60 menit SEBELUM makan. Pemakaian lama: defisiensi B12 dan magnesium, risiko patah tulang, dan infeksi Clostridioides difficile.',
  },
  {
    nama: 'Ranitidin',
    alias: ['ranitidin', 'famotidin', 'simetidin'],
    golongan: 'Penghambat reseptor H2',
    mekanisme: 'Menghambat reseptor histamin H2 pada sel parietal sehingga rangsangan histamin terhadap sekresi asam berkurang. Hanya menutup satu dari tiga rangsangan, sehingga lebih lemah daripada penghambat pompa proton.',
    mengatasi: 'Nyeri ulu hati dan dispepsia ringan.',
    ingat: 'H2 menutup satu keran; pompa proton menutup keran terakhir.',
    awas: 'Simetidin banyak berinteraksi lewat enzim hati.',
  },
  {
    nama: 'Oralit',
    alias: ['oralit', 'cairan rehidrasi', 'ORS', 'rehidrasi oral'],
    rantai: [
      'Glukosa + Na masuk lewat SGLT1',
      'Na ditarik masuk',
      'AIR ikut masuk',
      'rehidrasi berhasil',
      '(SGLT1 tetap bekerja meski usus radang)',
    ],
    golongan: 'Larutan rehidrasi oral',
    mekanisme: 'Memanfaatkan kotransporter natrium-glukosa (SGLT1) di usus halus yang TETAP BEKERJA meski usus meradang: glukosa menarik natrium masuk, dan natrium menarik air ikut masuk. Karena itu rehidrasi oral tetap berhasil pada diare hebat.',
    mengatasi: 'Mengganti cairan dan elektrolit yang hilang pada diare dan muntah.',
    ingat: 'Harus ada GULA agar garam terserap. Air putih saja tidak menggantikan oralit.',
    awas: 'Formula rendah osmolaritas lebih baik. Dehidrasi berat tetap memerlukan cairan intravena.',
  },
  {
    nama: 'Zinc',
    alias: ['zinc', 'zink', 'seng'],
    golongan: 'Mikronutrien',
    mekanisme: 'Memperbaiki epitel usus yang rusak, mengembalikan fungsi enzim pembawa, dan memperkuat kekebalan mukosa sehingga durasi dan beratnya diare berkurang.',
    mengatasi: 'Mempersingkat diare pada anak dan menurunkan kekambuhan dalam 2-3 bulan berikutnya.',
    ingat: 'Zinc 10 hari PENUH meski diare berhenti di hari kedua — manfaat pencegahannya justru datang dari lama pemberiannya.',
    awas: 'Dosis 10 mg (<6 bulan) dan 20 mg (>6 bulan) selama 10-14 hari.',
  },
  {
    nama: 'Albendazol',
    alias: ['albendazol', 'albendazole', 'mebendazol', 'mebendazole', 'pirantel'],
    rantai: [
      '⊣ beta-tubulin cacing',
      'mikrotubulus gagal',
      'ambilan glukosa cacing ↓',
      'cacing kehabisan tenaga',
      'MATI & keluar',
    ],
    golongan: 'Antihelmintik benzimidazol',
    mekanisme: 'Mengikat beta-tubulin cacing sehingga mikrotubulus tidak terbentuk; cacing kehilangan kemampuan menyerap glukosa, kehabisan tenaga, lalu mati dan keluar bersama tinja.',
    mengatasi: 'Askariasis, cacing tambang, cacing kremi, dan trikuriasis.',
    ingat: 'Cacing kremi diulang 2 minggu kemudian dan SELURUH rumah diobati — memutus daur telur.',
    awas: 'Hindari pada trimester pertama kehamilan.',
  },
  {
    nama: 'Asiklovir',
    alias: ['asiklovir', 'acyclovir', 'valasiklovir'],
    rantai: [
      'Diaktifkan timidin kinase VIRUS',
      '(hanya ada di sel terinfeksi)',
      '⊣ DNA polimerase virus',
      'rantai DNA berhenti',
      'replikasi virus berhenti',
    ],
    golongan: 'Antivirus analog nukleosida',
    mekanisme: 'Diaktifkan oleh timidin kinase VIRUS — enzim yang hanya ada pada sel terinfeksi — lalu menghambat DNA polimerase virus dan menghentikan pemanjangan rantai DNA. Selektivitas inilah yang membuatnya hampir tidak mengganggu sel sehat.',
    mengatasi: 'Herpes simpleks, herpes zoster, dan varisela.',
    ingat: 'Harus dimulai dalam 72 JAM pertama; sesudah itu virus sudah selesai bereplikasi dan obatnya tidak banyak menolong.',
    awas: 'Jaga hidrasi (nefrotoksik pada dosis intravena tinggi); sesuaikan dosis pada gangguan ginjal.',
  },
  {
    nama: 'Ketokonazol',
    alias: ['ketokonazol', 'mikonazol', 'flukonazol', 'itrakonazol', 'klotrimazol'],
    rantai: [
      '⊣ lanosterol 14-α-demetilase',
      'ERGOSTEROL tak terbentuk',
      'membran jamur bocor',
      'jamur mati',
    ],
    golongan: 'Antijamur azol',
    mekanisme: 'Menghambat enzim lanosterol 14-alfa-demetilase sehingga ERGOSTEROL — komponen utama membran sel jamur — tidak terbentuk; membran menjadi bocor dan jamur mati.',
    mengatasi: 'Dermatofitosis (tinea), pitiriasis versikolor, dan kandidiasis.',
    ingat: 'Ergosterol pada jamur setara kolesterol pada kita — itu sebabnya azol selektif.',
    awas: 'Ketokonazol oral hepatotoksik dan jarang dipakai sistemik; azol banyak berinteraksi lewat enzim CYP.',
  },
  {
    nama: 'Terbinafin',
    alias: ['terbinafin', 'terbinafine'],
    golongan: 'Antijamur alilamin',
    mekanisme: 'Menghambat skualen epoksidase pada langkah yang lebih awal daripada azol, sehingga ergosterol tidak terbentuk sekaligus skualen menumpuk dan meracuni jamur — bersifat fungisid, bukan sekadar menghambat.',
    mengatasi: 'Tinea, terutama tinea unguium dan tinea kapitis.',
    ingat: 'Terbinafin membunuh; azol umumnya menghambat.',
    awas: 'Pantau fungsi hati pada terapi oral yang panjang.',
  },
  {
    nama: 'Kloroquin',
    alias: ['klorokuin', 'chloroquine', 'dihidroartemisinin', 'artesunat', 'piperakuin', 'primakuin', 'DHP'],
    golongan: 'Antimalaria',
    mekanisme: 'Artemisinin dan turunannya diaktifkan oleh besi heme di dalam parasit dan menghasilkan radikal bebas yang merusak protein parasit — kerjanya paling cepat di antara semua antimalaria. Primakuin membunuh bentuk HIPNOZOIT yang tidur di hati.',
    mengatasi: 'Malaria falsiparum dan vivaks; primakuin mencegah kekambuhan dari hati.',
    ingat: 'Tanpa primakuin, vivaks akan kambuh dari hati meski darahnya sudah bersih.',
    awas: 'Primakuin menimbulkan hemolisis berat pada defisiensi G6PD dan tidak diberikan pada kehamilan.',
  },
  {
    nama: 'Diazepam',
    alias: ['diazepam', 'lorazepam', 'midazolam', 'benzodiazepin'],
    rantai: [
      'Ikat reseptor GABA-A',
      'FREKUENSI kanal Cl⁻ terbuka ↑',
      'Cl⁻ masuk',
      'hiperpolarisasi',
      'letupan neuron teredam',
      'KEJANG BERHENTI',
    ],
    golongan: 'Benzodiazepin',
    mekanisme: 'Mengikat tempat khusus pada reseptor GABA-A dan meningkatkan FREKUENSI terbukanya kanal klorida bila GABA hadir; klorida masuk, neuron mengalami hiperpolarisasi, dan letupan listrik teredam.',
    mengatasi: 'Menghentikan kejang, meredakan agitasi dan spasme otot, serta sedasi jangka pendek.',
    ingat: 'Benzodiazepin memperkuat GABA yang ada — ia tidak bekerja tanpa GABA. Itu sebabnya relatif aman dibanding barbiturat.',
    awas: 'Depresi napas, terutama bersama opioid; toleransi dan ketergantungan pada pemakaian >2-4 minggu. Penawarnya flumazenil.',
  },
  {
    nama: 'Fenitoin',
    alias: ['fenitoin', 'phenytoin'],
    rantai: [
      '⊣ kanal Na⁺ (keadaan tidak aktif)',
      'letupan CEPAT BERULANG dihambat',
      '(letupan normal tetap jalan)',
      'kejang berhenti',
    ],
    golongan: 'Antikonvulsan penstabil kanal natrium',
    mekanisme: 'Menghambat kanal natrium bergerbang voltase pada keadaan tidak aktif sehingga neuron tidak dapat melepas rentetan letupan cepat, tetapi letupan normal tetap berjalan.',
    mengatasi: 'Status epileptikus setelah benzodiazepin, dan epilepsi fokal maupun tonik-klonik.',
    ingat: 'JANGAN dicampur DEKSTROSA — mengendap. Larutkan dalam NaCl 0,9%.',
    awas: 'Diberikan pelan <50 mg/menit (dewasa) karena risiko hipotensi dan aritmia; hipertrofi gusi, hirsutisme, ataksia. Kinetiknya orde nol — kenaikan dosis kecil dapat melonjakkan kadar.',
  },
  {
    nama: 'Asam valproat',
    alias: ['asam valproat', 'valproat', 'depakote'],
    golongan: 'Antikonvulsan spektrum luas',
    mekanisme: 'Meningkatkan GABA, menghambat kanal natrium, dan menghambat kanal kalsium tipe T — kombinasi inilah yang membuatnya bekerja pada hampir semua jenis bangkitan.',
    mengatasi: 'Bangkitan umum, absans, mioklonik, dan pencegahan migren.',
    ingat: 'Valproat = spektrum luas. Karbamazepin justru MEMPERBERAT absans dan mioklonik.',
    awas: 'TERATOGENIK berat (defek tabung saraf, gangguan kognitif) — hindari pada perempuan usia subur; hepatotoksik pada anak <2 tahun.',
  },
  {
    nama: 'Karbamazepin',
    alias: ['karbamazepin', 'carbamazepin', 'carbamazepine', 'okskarbazepin'],
    golongan: 'Antikonvulsan penstabil kanal natrium',
    mekanisme: 'Menghambat kanal natrium bergerbang voltase dan menstabilkan membran neuron yang mudah melepas letupan berulang.',
    mengatasi: 'Bangkitan fokal dan NEURALGIA TRIGEMINAL, tempat ia menjadi obat pilihan pertama.',
    ingat: 'Neuralgia trigeminal = karbamazepin. Jangan pada absans.',
    awas: 'Sindrom Stevens-Johnson (periksa HLA-B*1502 pada keturunan Asia bila memungkinkan), hiponatremia, dan menginduksi enzim hati sehingga banyak obat lain melemah.',
  },
  {
    nama: 'Haloperidol',
    alias: ['haloperidol', 'risperidon', 'risperidone', 'olanzapin', 'klorpromazin'],
    rantai: [
      '⊣ reseptor D2 mesolimbik',
      'waham & halusinasi ↓',
      '',
      '⊣ D2 nigrostriatal (tak diinginkan)',
      'EFEK EKSTRAPIRAMIDAL',
    ],
    golongan: 'Antipsikotik',
    mekanisme: 'Menghambat reseptor dopamin D2 pada jalur mesolimbik sehingga waham dan halusinasi berkurang. Antipsikotik atipikal juga menghambat serotonin 5-HT2A, yang mengurangi gejala ekstrapiramidal dan memperbaiki gejala negatif.',
    mengatasi: 'Gejala POSITIF skizofrenia (waham, halusinasi), agitasi berat, dan delirium.',
    ingat: 'D2 di mesolimbik = manfaat; D2 di nigrostriatal = efek ekstrapiramidal. Satu reseptor, dua jalur.',
    awas: 'Distonia akut (atasi dengan difenhidramin), parkinsonisme, akatisia, diskinesia tardif, sindrom neuroleptik maligna, dan pemanjangan QT.',
  },
  {
    nama: 'Sertralin',
    alias: ['sertralin', 'sertraline', 'fluoksetin', 'fluoxetine', 'escitalopram', 'SSRI'],
    rantai: [
      '⊣ transporter serotonin',
      'serotonin di celah sinaps ↑ (jam)',
      'reseptor beradaptasi (minggu)',
      'GEJALA MEMBAIK 4-6 minggu',
      '(1-2 minggu awal cemas bisa MEMBURUK)',
    ],
    golongan: 'Penghambat ambilan kembali serotonin',
    mekanisme: 'Menghambat transporter serotonin pada celah sinaps sehingga serotonin bertahan lebih lama. Kadar naik dalam hitungan jam, tetapi perbaikan gejala baru muncul setelah reseptor beradaptasi — itulah sebabnya efeknya tertunda 4-6 minggu.',
    mengatasi: 'Depresi, gangguan cemas menyeluruh, panik, obsesif-kompulsif, dan PTSD.',
    ingat: 'Beritahu di awal: cemas dapat MEMBURUK 1-2 minggu pertama. Tanpa penjelasan ini pasien berhenti sendiri.',
    awas: 'Sindrom serotonin bila digabung obat serotonergik lain; disfungsi seksual; hiponatremia pada usia lanjut; jangan dihentikan mendadak.',
  },
  {
    nama: 'Amitriptilin',
    alias: ['amitriptilin', 'amitriptyline'],
    rantai: [
      'Dosis RENDAH',
      'perkuat jalur penghambat nyeri desendens',
      'sinyal nyeri di kornu dorsalis ⊣',
      'NYERI NEUROPATIK ↓',
      '(bukan lewat efek antidepresannya)',
    ],
    golongan: 'Antidepresan trisiklik',
    mekanisme: 'Menghambat ambilan kembali serotonin dan noradrenalin; pada dosis RENDAH efek analgetiknya bekerja lewat jalur penghambat nyeri desendens di medula spinalis, bukan lewat efek antidepresannya.',
    mengatasi: 'Nyeri neuropatik, pencegahan migren dan tension headache, serta membantu tidur.',
    ingat: 'Dosis nyeri (10-25 mg malam) jauh lebih kecil daripada dosis depresi — dan bekerja lebih cepat.',
    awas: 'Efek antikolinergik (mulut kering, retensi urin, konstipasi, kebingungan pada usia lanjut); aritmia pada overdosis.',
  },
  {
    nama: 'Gabapentin',
    alias: ['gabapentin', 'pregabalin'],
    rantai: [
      'Ikat subunit α2δ kanal Ca presinaps',
      'pelepasan glutamat & substansi P ↓',
      'letupan berlebih neuron ↓',
      'nyeri neuropatik ↓',
      '(BUKAN lewat reseptor GABA)',
    ],
    golongan: 'Ligan subunit alfa-2-delta',
    mekanisme: 'Mengikat subunit alfa-2-delta kanal kalsium presinaps sehingga pelepasan neurotransmiter perangsang (glutamat, substansi P) berkurang pada neuron yang tereksitasi berlebihan. Meski namanya menyerupai GABA, ia TIDAK bekerja pada reseptor GABA.',
    mengatasi: 'Nyeri NEUROPATIK: neuropati diabetik, neuralgia pascaherpes, dan radikulopati.',
    ingat: 'Nyeri neuropatik tidak berespons pada parasetamol dan NSAID — itulah sebabnya golongan ini diperlukan.',
    awas: 'Mengantuk dan pusing; naikkan dosis bertahap dan sesuaikan pada gangguan ginjal.',
  },
  {
    nama: 'Morfin',
    alias: ['morfin', 'morphine', 'petidin', 'fentanil', 'opioid', 'kodein'],
    rantai: [
      'Aktifkan reseptor mu',
      'hantaran nyeri kornu dorsalis ⊣',
      'persepsi nyeri di otak berubah',
      '',
      '+ venodilatasi & cemas ↓',
      'kerja napas ↓ pada edema paru',
    ],
    golongan: 'Analgetik opioid',
    mekanisme: 'Mengaktifkan reseptor mu di susunan saraf pusat sehingga hantaran nyeri di kornu dorsalis dihambat dan persepsi nyeri di otak berubah. Pada edema paru ia juga melebarkan vena dan menurunkan kecemasan sehingga kerja napas berkurang.',
    mengatasi: 'Nyeri berat, edema paru akut, dan sesak pada perawatan paliatif.',
    ingat: 'Opioid mengubah PERSEPSI nyeri; NSAID mengurangi SUMBER nyeri. Itu sebabnya keduanya bersinergi.',
    awas: 'Depresi napas, hipotensi, mual, konstipasi (selalu resepkan pencahar), dan ketergantungan. Penawarnya nalokson.',
  },
  {
    nama: 'Asam traneksamat',
    alias: ['asam traneksamat', 'tranexamic', 'kalnex'],
    rantai: [
      '⊣ tempat ikat lisin pada plasminogen',
      'plasmin tak menempel pada fibrin',
      'bekuan TIDAK dilarutkan',
      'perdarahan berhenti',
      '(menjaga bekuan yang ADA → harus <3 jam)',
    ],
    golongan: 'Antifibrinolitik',
    mekanisme: 'Menghambat tempat pengikatan lisin pada plasminogen sehingga plasmin tidak dapat menempel pada fibrin — bekuan yang sudah terbentuk tidak dilarutkan.',
    mengatasi: 'Perdarahan: trauma, perdarahan pascapersalinan, dan perdarahan haid berlebihan.',
    ingat: 'Ia MENJAGA bekuan yang ada, bukan membuat bekuan baru. Karena itu harus diberikan dalam 3 JAM pertama pada trauma.',
    awas: 'Hati-hati pada riwayat tromboemboli; setelah 3 jam pada trauma justru merugikan.',
  },
  {
    nama: 'Vitamin K',
    alias: ['vitamin k', 'fitomenadion', 'phytomenadione'],
    golongan: 'Kofaktor sintesis faktor pembekuan',
    mekanisme: 'Menjadi kofaktor karboksilasi faktor II, VII, IX, dan X di hati sehingga faktor-faktor itu dapat mengikat kalsium dan bekerja. Tanpa vitamin K, faktor tetap dibuat tetapi tidak berfungsi.',
    mengatasi: 'Perdarahan akibat defisiensi vitamin K, penyakit hati, dan kelebihan warfarin; profilaksis perdarahan pada bayi baru lahir.',
    ingat: '1972 = faktor II, VII, IX, X.',
    awas: 'Efek oral maupun suntik baru terlihat setelah beberapa jam; perdarahan mengancam nyawa memerlukan plasma atau konsentrat faktor.',
  },
  {
    nama: 'MgSO4',
    alias: ['magnesium sulfat', 'mgso4', 'mgso 4'],
    rantai: [
      '⊣ reseptor NMDA + saingi Ca²⁺',
      'eksitabilitas neuron ↓',
      '+ vasospasme serebral ↓',
      'KEJANG DICEGAH',
      '',
      'Overdosis: refleks patela hilang → napas ↓',
      'Penawar: KALSIUM GLUKONAS',
    ],
    golongan: 'Antikonvulsan dan penstabil membran',
    mekanisme: 'Menghambat reseptor NMDA dan bersaing dengan kalsium pada terminal saraf sehingga eksitabilitas neuron menurun dan vasospasme serebral berkurang.',
    mengatasi: 'MENCEGAH dan mengatasi kejang pada preeklamsia berat dan eklamsia — obat pilihan, mengungguli diazepam maupun fenitoin.',
    ingat: 'Pantau tiga hal sebelum dosis berikutnya: refleks patela ADA, napas >=16 kali/menit, dan urin >=25-30 mL/jam.',
    awas: 'Keracunan: refleks hilang lalu depresi napas. Penawarnya KALSIUM GLUKONAS 1 g intravena.',
  },
  {
    nama: 'Kalsium glukonas',
    alias: ['kalsium glukonas', 'calcium gluconate', 'ca glukonas'],
    rantai: [
      'Naikkan selisih ambang–istirahat miokard',
      'membran STABIL terhadap kalium tinggi',
      'aritmia dicegah',
      '',
      '(kalium darah TIDAK turun sama sekali)',
      'Lindungi → Pindahkan → Buang',
    ],
    golongan: 'Penstabil membran miokardium',
    mekanisme: 'Menaikkan selisih antara potensial ambang dan potensial istirahat pada sel miokardium sehingga membran menjadi stabil terhadap efek kalium yang tinggi. Ia TIDAK menurunkan kadar kalium sama sekali.',
    mengatasi: 'Melindungi jantung pada hiperkalemia dengan perubahan EKG, dan menjadi penawar keracunan magnesium.',
    ingat: 'Kalsium MELINDUNGI, insulin dan salbutamol MEMINDAHKAN, resin dan dialisis MEMBUANG. Tiga langkah berbeda, jangan tertukar.',
    awas: 'Efeknya hanya 30-60 menit — harus disusul terapi yang benar-benar menurunkan kalium.',
  },
  {
    nama: 'Atropin',
    alias: ['atropin', 'atropine'],
    golongan: 'Antikolinergik (antagonis muskarinik)',
    mekanisme: 'Menghambat reseptor muskarinik sehingga pengaruh saraf vagus pada nodus SA dan AV berkurang dan laju denyut naik; juga mengeringkan sekret dan melebarkan pupil.',
    mengatasi: 'Bradikardia bergejala dan keracunan organofosfat.',
    ingat: 'Pada keracunan organofosfat, sasarannya adalah PARU KERING — dosis dinaikkan sampai sekret berhenti, bukan sampai nadi tertentu.',
    awas: 'Mulut kering, retensi urin, kebingungan pada usia lanjut, dan glaukoma sudut sempit.',
  },
  {
    nama: 'Oksitosin',
    alias: ['oksitosin', 'oxytocin'],
    rantai: [
      'Ikat reseptor oksitosin miometrium',
      'Ca²⁺ intrasel ↑',
      'rahim KONTRAKSI',
      'pembuluh spiralis terjepit',
      'PERDARAHAN BERHENTI',
    ],
    golongan: 'Hormon uterotonika',
    mekanisme: 'Mengikat reseptor oksitosin pada miometrium sehingga kalsium intrasel naik dan otot rahim berkontraksi kuat; kontraksi itu menjepit pembuluh spiralis di bekas tempat melekatnya plasenta — inilah yang menghentikan perdarahan.',
    mengatasi: 'Manajemen aktif kala III dan perdarahan pascapersalinan akibat atonia uteri.',
    ingat: 'Rahim yang berkontraksi adalah tourniquet alami. Karena itu masase fundus dikerjakan bersama obatnya.',
    awas: 'Pemberian intravena cepat menimbulkan hipotensi; cairan berlebih berisiko intoksikasi air.',
  },
  {
    nama: 'Misoprostol',
    alias: ['misoprostol'],
    golongan: 'Analog prostaglandin E1',
    mekanisme: 'Merangsang reseptor prostaglandin pada miometrium sehingga rahim berkontraksi dan serviks melunak; pada lambung ia menggantikan prostaglandin pelindung mukosa.',
    mengatasi: 'Perdarahan pascapersalinan bila oksitosin tidak tersedia, evakuasi sisa konsepsi, dan pencegahan tukak akibat NSAID.',
    ingat: 'Tahan suhu ruangan — itu keunggulannya di tempat tanpa lemari pendingin, tempat oksitosin cepat rusak.',
    awas: 'Demam dan menggigil setelah pemberian; KONTRAINDIKASI pada kehamilan yang ingin dipertahankan.',
  },
  {
    nama: 'Besi',
    alias: ['sulfas ferosus', 'ferro', 'fe', 'besi', 'ferrous'],
    rantai: [
      'Fe → sumsum tulang',
      'sintesis heme',
      'eritropoiesis pulih',
      'Hb ↑',
      '',
      'Retikulosit hari 5-7 → Hb +2 g/dL dalam 3-4 minggu',
    ],
    golongan: 'Mineral pembentuk hemoglobin',
    mekanisme: 'Menyediakan besi untuk sintesis heme di sumsum tulang sehingga eritropoiesis kembali berjalan dan hemoglobin terbentuk.',
    mengatasi: 'Anemia defisiensi besi: lelah, pucat, dan sesak saat aktivitas.',
    ingat: 'Retikulosit naik hari ke-5-7, Hb naik ~2 g/dL dalam 3-4 minggu, dan terapi DILANJUTKAN 3 bulan setelah Hb normal untuk mengisi cadangan.',
    awas: 'Mual dan tinja hitam; penyerapan turun bersama teh, kopi, kalsium, dan antasida, naik bersama vitamin C.',
  },
  {
    nama: 'Asam folat',
    alias: ['asam folat', 'folat', 'folic acid'],
    golongan: 'Vitamin B9',
    mekanisme: 'Menjadi kofaktor pemindahan satu atom karbon pada sintesis purin dan timidin — bahan dasar DNA. Tanpa folat, pembelahan sel terhenti pada sel yang paling cepat membelah: sumsum tulang dan tabung saraf janin.',
    mengatasi: 'Anemia megaloblastik, pencegahan defek tabung saraf pada kehamilan, dan mengurangi efek samping metotreksat.',
    ingat: 'Pada anemia megaloblastik, PERIKSA B12 dahulu — folat memperbaiki darahnya tetapi membiarkan kerusakan saraf akibat defisiensi B12 berjalan terus.',
    awas: 'Diberikan pada hari SELAIN hari metotreksat.',
  },
  {
    nama: 'Metotreksat',
    alias: ['metotreksat', 'methotrexate', 'MTX'],
    rantai: [
      '⊣ dihidrofolat reduktase',
      'sintesis purin & timidin ↓',
      '',
      'Dosis rendah mingguan:',
      'adenosin ↑',
      'RADANG SENDI ↓',
      'erosi diperlambat',
    ],
    golongan: 'Antimetabolit (antagonis folat)',
    mekanisme: 'Menghambat dihidrofolat reduktase sehingga sintesis purin dan timidin terganggu; pada dosis rendah mingguan, efek antiradangnya justru terutama lewat penumpukan adenosin.',
    mengatasi: 'DMARD lini pertama pada artritis reumatoid — memperlambat kerusakan sendi, bukan sekadar meredakan nyeri.',
    ingat: 'DIMINUM SEKALI SEMINGGU. Dosis harian mematikan — tulis di resep dan pastikan pasien mengulanginya.',
    awas: 'Supresi sumsum tulang, hepatotoksik, dan pneumonitis. KONTRAINDIKASI pada kehamilan; hindari bersama kotrimoksazol.',
  },
  {
    nama: 'Hidroksiklorokuin',
    alias: ['hidroksiklorokuin', 'hydroxychloroquine', 'HCQ'],
    golongan: 'Antimalaria dengan efek imunomodulator',
    mekanisme: 'Menaikkan pH di dalam lisosom sel penyaji antigen sehingga pemrosesan antigen dan pensinyalan reseptor Toll-like terganggu, dan respons autoimun mereda.',
    mengatasi: 'Dasar terapi lupus untuk SEMUA pasien; juga dipakai pada artritis reumatoid.',
    ingat: 'Satu-satunya obat lupus yang terbukti menurunkan kekambuhan, kerusakan organ, sekaligus kematian — karena itu tidak boleh dihentikan meski penyakit tenang.',
    awas: 'Retinopati pada pemakaian lama — pemeriksaan mata berkala wajib.',
  },
  {
    nama: 'Allopurinol',
    alias: ['allopurinol', 'alopurinol'],
    rantai: [
      '⊣ xantin oksidase',
      'hipoxantin → xantin → asam urat TERPUTUS',
      'asam urat ↓',
      'kristal larut kembali',
      '(mencegah, BUKAN meredakan serangan)',
    ],
    golongan: 'Penghambat xantin oksidase',
    mekanisme: 'Menghambat xantin oksidase sehingga hipoxantin dan xantin tidak diubah menjadi asam urat; kadar asam urat turun dan kristal yang sudah mengendap perlahan larut kembali.',
    mengatasi: 'MENCEGAH serangan gout berulang dan mengecilkan tofus — bukan meredakan serangan yang sedang berlangsung.',
    ingat: 'Jangan memulai maupun menghentikan allopurinol saat serangan akut: perubahan kadar mendadak justru mencetuskan serangan.',
    awas: 'Sindrom hipersensitivitas allopurinol yang berat; sesuaikan dosis pada gangguan ginjal; interaksi berbahaya dengan azatioprin.',
  },
  {
    nama: 'Kolkisin',
    alias: ['kolkisin', 'colchicine'],
    rantai: [
      'Ikat tubulin',
      'mikrotubulus neutrofil gagal',
      'neutrofil tak bergerak ke kristal',
      'sitokin ↓',
      'RADANG PADAM',
      '(asam urat TIDAK turun)',
    ],
    golongan: 'Antiradang penghambat mikrotubulus',
    mekanisme: 'Mengikat tubulin sehingga mikrotubulus neutrofil tidak terbentuk; neutrofil tidak dapat bergerak menuju kristal urat maupun melepaskan sitokin, sehingga radangnya padam.',
    mengatasi: 'Serangan gout akut dan profilaksis selama memulai allopurinol.',
    ingat: 'Kolkisin melumpuhkan NEUTROFIL, bukan menurunkan asam urat. Dua pekerjaan berbeda.',
    awas: 'Diare adalah tanda dosis berlebih; toksisitas berat pada gangguan ginjal dan bersama makrolid.',
  },
  {
    nama: 'Bifosfonat',
    alias: ['alendronat', 'bifosfonat', 'asam zoledronat'],
    golongan: 'Penghambat resorpsi tulang',
    mekanisme: 'Menempel pada hidroksiapatit tulang dan ditelan osteoklas, lalu mengganggu jalur mevalonat sehingga osteoklas kehilangan fungsi dan mengalami apoptosis — resorpsi tulang berhenti.',
    mengatasi: 'Osteoporosis dan pencegahan patah tulang, termasuk akibat kortikosteroid jangka panjang.',
    ingat: 'Diminum perut kosong dengan air putih dan TETAP TEGAK 30 menit — bila berbaring, tablet dapat melukai esofagus.',
    awas: 'Esofagitis, osteonekrosis rahang (periksa gigi sebelum memulai), dan patah tulang femur atipikal pada pemakaian sangat lama.',
  },
  {
    nama: 'Kalsium dan vitamin D',
    alias: ['kalsium', 'vitamin d', 'kolekalsiferol'],
    golongan: 'Mineral dan hormon pengatur kalsium',
    mekanisme: 'Vitamin D dihidroksilasi di hati lalu di ginjal menjadi kalsitriol, yang meningkatkan penyerapan kalsium dan fosfat di usus sehingga mineralisasi tulang berjalan.',
    mengatasi: 'Mencegah dan mengobati rakitis, osteomalasia, dan osteoporosis; menjadi dasar terapi bersama bifosfonat.',
    ingat: 'Bifosfonat tanpa kalsium dan vitamin D yang cukup dapat menimbulkan hipokalsemia.',
    awas: 'Kelebihan menimbulkan hiperkalsemia dan batu ginjal.',
  },
  {
    nama: 'Tamsulosin',
    alias: ['tamsulosin', 'alfuzosin', 'terazosin', 'doksazosin'],
    rantai: [
      '⊣ reseptor α1A leher buli & prostat',
      'tonus otot polos ↓',
      'aliran urin membaik',
      '(komponen DINAMIS → efek dalam HARI)',
    ],
    golongan: 'Penghambat reseptor alfa-1',
    mekanisme: 'Menghambat reseptor alfa-1A pada otot polos leher kandung kemih dan prostat sehingga tonusnya menurun dan aliran urin membaik — ini mengurusi komponen DINAMIS obstruksi, bukan ukuran prostatnya.',
    mengatasi: 'Keluhan berkemih pada pembesaran prostat, dan meningkatkan keberhasilan pelepasan kateter setelah retensi.',
    ingat: 'Efek terasa dalam hitungan HARI. Finasterid yang mengecilkan prostat baru terasa setelah berbulan-bulan.',
    awas: 'Hipotensi ortostatik pada dosis pertama (minum malam hari); ejakulasi retrograd; floppy iris syndrome saat operasi katarak — beritahu dokter mata.',
  },
  {
    nama: 'Finasterid',
    alias: ['finasterid', 'finasteride', 'dutasterid'],
    rantai: [
      '⊣ 5-α-reduktase',
      'testosteron → DHT terputus',
      'rangsang tumbuh prostat ↓',
      'volume prostat MENGECIL',
      '(komponen STATIS → efek dalam BULAN)',
      '+ PSA turun setengahnya',
    ],
    golongan: 'Penghambat 5-alfa-reduktase',
    mekanisme: 'Menghambat perubahan testosteron menjadi dihidrotestosteron sehingga rangsangan pertumbuhan pada prostat berkurang dan volumenya mengecil sampai seperempatnya.',
    mengatasi: 'Mengecilkan prostat pada BPH dengan kelenjar besar, mengurangi risiko retensi dan kebutuhan operasi.',
    ingat: 'Ia menurunkan PSA sekitar SETENGAHNYA — nilai PSA harus dikalikan dua saat menafsirkan skrining.',
    awas: 'Butuh 6 bulan untuk efek penuh; penurunan libido; perempuan hamil tidak boleh menyentuh tablet yang pecah.',
  },
  {
    nama: 'Betahistin',
    alias: ['betahistin', 'betahistine'],
    golongan: 'Analog histamin',
    mekanisme: 'Bekerja sebagai agonis lemah H1 dan antagonis H3 sehingga aliran darah mikrosirkulasi telinga dalam meningkat dan tekanan endolimf diduga berkurang; ia juga mempercepat kompensasi vestibular di batang otak.',
    mengatasi: 'Mengurangi frekuensi serangan vertigo pada penyakit Meniere.',
    ingat: 'Betahistin untuk PENCEGAHAN; antihistamin sedatif untuk serangan akut. Terbalik memakainya membuat keduanya tampak tidak berguna.',
    awas: 'Hati-hati pada tukak lambung dan asma.',
  },
  {
    nama: 'Ondansetron',
    alias: ['ondansetron'],
    golongan: 'Antagonis reseptor 5-HT3',
    mekanisme: 'Menghambat reseptor serotonin 5-HT3 di zona pencetus kemoreseptor dan pada ujung saraf vagus di usus, sehingga sinyal muntah tidak sampai ke pusat muntah.',
    mengatasi: 'Mual dan muntah hebat, termasuk pascaoperasi dan akibat kemoterapi.',
    ingat: '5-HT3 berada di USUS dan di batang otak — itu sebabnya obat ini bekerja pada mual yang berasal dari saluran cerna.',
    awas: 'Memanjangkan interval QT; konstipasi dan nyeri kepala.',
  },
  {
    nama: 'Domperidon',
    alias: ['domperidon', 'metoklopramid', 'metoclopramide'],
    golongan: 'Antagonis dopamin (prokinetik)',
    mekanisme: 'Menghambat reseptor dopamin D2 di zona pencetus kemoreseptor dan di saluran cerna sehingga pengosongan lambung dipercepat dan rasa mual berkurang. Domperidon hampir tidak menembus sawar darah-otak, metoklopramid menembusnya.',
    mengatasi: 'Mual, muntah, dan rasa penuh akibat pengosongan lambung yang lambat.',
    ingat: 'METOKLOPRAMID adalah penyebab parkinsonisme akibat obat yang paling sering terlewat — selalu periksa daftar obat pada pasien dengan tremor dan kaku.',
    awas: 'Reaksi distonia akut, terutama pada anak dan dewasa muda; keduanya memanjangkan QT.',
  },
  {
    nama: 'Laktulosa',
    alias: ['laktulosa', 'lactulose'],
    rantai: [
      'Tak diserap usus halus',
      'difermentasi bakteri kolon',
      'asam laktat & asetat',
      'pH kolon ↓',
      'NH₃ → NH₄⁺ (tak terserap)',
      'amonia darah ↓',
      'ensefalopati membaik',
    ],
    golongan: 'Laksatif osmotik dan pengikat amonia',
    mekanisme: 'Tidak diserap di usus halus; di kolon difermentasi bakteri menjadi asam laktat dan asetat. Air tertarik ke lumen (efek pencahar) dan pH kolon turun sehingga amonia (NH3) berubah menjadi amonium (NH4+) yang tidak dapat diserap kembali lalu dibuang bersama tinja.',
    mengatasi: 'Konstipasi, dan ENSEFALOPATI HEPATIK dengan menurunkan amonia darah.',
    ingat: 'Dititrasi sampai 2-3 kali buang air besar lembek per hari — bukan sampai diare.',
    awas: 'Kembung dan kram; diare berlebihan justru dapat mencetuskan ensefalopati karena dehidrasi.',
  },
  {
    nama: 'Salin hipertonik',
    alias: ['salin hipertonik', 'nacl 3%', 'manitol'],
    golongan: 'Agen osmotik',
    mekanisme: 'Menaikkan osmolaritas plasma sehingga air ditarik keluar dari jaringan otak melewati sawar darah-otak yang utuh, dan tekanan intrakranial turun.',
    mengatasi: 'Menurunkan tekanan intrakranial pada edema serebri.',
    ingat: 'Bekerja hanya bila sawar darah-otak masih utuh.',
    awas: 'Manitol dapat menimbulkan hipovolemia dan gangguan ginjal; pantau osmolaritas dan natrium.',
  },
  {
    nama: 'Antitoksin difteri',
    alias: ['antitoksin difteri', 'ADS', 'antitoksin'],
    rantai: [
      'Netralkan toksin yang masih BEBAS di darah',
      'toksin tak sampai ke jantung & saraf',
      'miokarditis dicegah',
      '',
      'Toksin yang SUDAH terikat → tak bisa dinetralkan',
      '→ tiap jam menentukan',
    ],
    golongan: 'Imunisasi pasif (antibodi siap pakai)',
    mekanisme: 'Menetralkan toksin difteri yang masih BEBAS di dalam darah sebelum ia terikat pada sel jantung dan saraf. Toksin yang sudah terikat tidak dapat dinetralkan lagi — dan itulah sebabnya keterlambatan beberapa jam sangat menentukan.',
    mengatasi: 'Mencegah miokarditis dan kelumpuhan pada difteri.',
    ingat: 'Diberikan berdasarkan KLINIS, tanpa menunggu hasil kultur.',
    awas: 'Uji sensitivitas dahulu (serum kuda); siapkan penanganan anafilaksis.',
  },
  {
    nama: 'Oksigen',
    alias: ['oksigen', 'o2'],
    rantai: [
      'PaO₂ alveolus ↑',
      'selisih tekanan ke kapiler ↑',
      'hantaran O₂ ke jaringan ↑',
      '',
      'PPOK: O₂ berlebih ⊣ vasokonstriksi hipoksik',
      'V/Q memburuk + efek Haldane',
      'RETENSI CO₂',
    ],
    golongan: 'Terapi gas medis',
    mekanisme: 'Meningkatkan tekanan parsial oksigen alveolus sehingga selisih tekanan menuju kapiler membesar dan hantaran oksigen ke jaringan meningkat.',
    mengatasi: 'Hipoksemia dan iskemia jaringan; pada cluster headache oksigen aliran tinggi menghentikan serangan.',
    ingat: 'Pada PPOK, sasarannya 88-92%. Oksigen berlebihan menghilangkan vasokonstriksi hipoksik dan memperberat retensi CO2.',
    awas: 'Bukan obat tanpa risiko: pantau saturasi dan sesuaikan, jangan diberikan maksimal secara membuta.',
  },
  {
    nama: 'OAT (rifampisin, INH, pirazinamid, etambutol)',
    alias: ['rifampisin', 'isoniazid', 'inh', 'pirazinamid', 'etambutol', 'OAT', 'FDC', 'streptomisin'],
    rantai: [
      'Rifampisin ⊣ RNA polimerase → basil cepat & setengah tidur',
      'Isoniazid ⊣ asam mikolat → basil aktif membelah',
      'Pirazinamid → basil DALAM makrofag (suasana asam)',
      'Etambutol ⊣ arabinosil transferase → tahan resistensi',
      '',
      'Satu obat sendiri = PASTI kebal',
    ],
    golongan: 'Antituberkulosis kombinasi',
    mekanisme: 'Empat obat dipakai bersama karena masing-masing menyerang populasi basil yang berbeda dan mencegah munculnya kekebalan. Rifampisin membunuh basil yang membelah cepat maupun yang setengah tidur dengan menghambat RNA polimerase; isoniazid menghambat sintesis asam mikolat dinding sel pada basil yang aktif membelah; pirazinamid bekerja pada basil di dalam makrofag yang bersuasana asam; etambutol menghambat arabinosil transferase dan terutama menahan timbulnya resistensi.',
    mengatasi: 'Menyembuhkan tuberkulosis dan memutus penularan; dahak umumnya menjadi negatif setelah 2 bulan fase intensif.',
    ingat: 'Satu obat sendirian PASTI menghasilkan kuman kebal. Itulah alasan tunggal mengapa selalu empat, bukan satu.',
    awas: 'Rifampisin mewarnai urin dan air mata JINGGA — beritahu di awal, atau pasien berhenti sendiri karena takut. Isoniazid menimbulkan neuropati (cegah dengan piridoksin 10-25 mg/hari); etambutol mengganggu penglihatan warna; semua berisiko hepatotoksik.',
  },
  {
    nama: 'Kloramfenikol',
    alias: ['kloramfenikol', 'chloramphenicol'],
    golongan: 'Antibiotik penghambat ribosom 50S',
    mekanisme: 'Menghambat enzim peptidil transferase pada subunit ribosom 50S sehingga rantai peptida bakteri tidak dapat disambung.',
    mengatasi: 'Demam tifoid, dan sediaan tetes atau salep untuk infeksi mata luar.',
    ingat: 'Masih menjadi pilihan tifoid di Indonesia karena murah dan efektif, sementara di banyak negara sudah ditinggalkan.',
    awas: 'Anemia aplastik (jarang tetapi fatal) dan sindrom bayi kelabu pada neonatus.',
  },
  {
    nama: 'Penisilin benzatin',
    alias: ['benzatin', 'penisilin prokain', 'penicillin', 'penisilin'],
    golongan: 'Antibiotik beta-laktam kerja panjang',
    mekanisme: 'Sama seperti penisilin lain menghambat sintesis dinding sel, tetapi bentuk garamnya melepaskan obat perlahan dari tempat suntikan sehingga kadar terapeutik bertahan berminggu-minggu dari satu kali suntikan.',
    mengatasi: 'Faringitis streptokokus, sifilis, dan PROFILAKSIS SEKUNDER demam reumatik.',
    ingat: 'Satu suntikan tiap 3-4 minggu selama bertahun-tahun — kepatuhan itulah yang mencegah kerusakan katup jantung.',
    awas: 'Suntikkan INTRAMUSKULAR dalam, jangan intravena. Reaksi Jarisch-Herxheimer pada sifilis.',
  },
  {
    nama: 'Klindamisin',
    alias: ['klindamisin', 'clindamycin'],
    golongan: 'Antibiotik linkosamid',
    mekanisme: 'Mengikat subunit ribosom 50S dan menghambat sintesis protein; menembus tulang dan abses dengan baik, serta menekan produksi toksin pada infeksi streptokokus dan stafilokokus berat.',
    mengatasi: 'Infeksi kulit dan jaringan lunak, abses gigi, osteomielitis, dan alternatif pada alergi penisilin.',
    ingat: 'Menekan TOKSIN — karena itu ditambahkan pada fasiitis nekrotikans dan sindrom syok toksik.',
    awas: 'Kolitis akibat Clostridioides difficile adalah efek samping klasiknya.',
  },
  {
    nama: 'Gentamisin',
    alias: ['gentamisin', 'gentamicin', 'amikasin', 'aminoglikosida'],
    golongan: 'Antibiotik aminoglikosida',
    mekanisme: 'Mengikat subunit ribosom 30S secara irreversibel sehingga pembacaan kode genetik menjadi keliru dan protein yang cacat merusak membran bakteri — bersifat bakterisid dan bergantung pada kadar puncak.',
    mengatasi: 'Infeksi gram negatif berat, sepsis neonatorum, dan dikombinasikan pada endokarditis.',
    ingat: 'Efeknya bergantung PUNCAK, bukan lama paparan — itu sebabnya kini diberikan sekali sehari dosis besar.',
    awas: 'Nefrotoksik dan ototoksik (tuli menetap dan gangguan keseimbangan); pantau fungsi ginjal, sesuaikan dosis.',
  },
  {
    nama: 'Vankomisin',
    alias: ['vankomisin', 'vancomycin'],
    golongan: 'Antibiotik glikopeptida',
    mekanisme: 'Mengikat ujung D-alanil-D-alanin prekursor peptidoglikan sehingga penyambungan dinding sel terhalang — jalur berbeda dari beta-laktam, sehingga tetap bekerja pada kuman yang menghasilkan beta-laktamase maupun MRSA.',
    mengatasi: 'Infeksi MRSA, sepsis terkait kateter, dan kolitis Clostridioides difficile berat (per oral).',
    ingat: 'Untuk kolitis C. difficile diberikan ORAL justru karena TIDAK diserap — obat bertahan di lumen usus tempat kumannya berada.',
    awas: 'Sindrom red man bila infus terlalu cepat (perlambat, bukan hentikan); nefrotoksik; pantau kadar.',
  },
  {
    nama: 'Praziquantel',
    alias: ['praziquantel'],
    golongan: 'Antihelmintik untuk cacing pipih',
    mekanisme: 'Meningkatkan permeabilitas membran cacing terhadap kalsium sehingga terjadi kontraksi otot yang hebat dan kelumpuhan, sekaligus merusak tegumen sehingga cacing terbuka terhadap serangan kekebalan pejamu.',
    mengatasi: 'Skistosomiasis, taeniasis, dan sistiserkosis.',
    ingat: 'Kalsium masuk = cacing kejang lalu lumpuh.',
    awas: 'Pada neurosistiserkosis dapat mencetuskan radang otak — berikan bersama kortikosteroid dan antikonvulsan.',
  },
  {
    nama: 'Dietilkarbamazin',
    alias: ['dietilkarbamazin', 'DEC', 'ivermektin', 'ivermectin'],
    golongan: 'Antifilaria',
    mekanisme: 'DEC mengubah permukaan mikrofilaria sehingga mudah dihancurkan sistem imun pejamu. Ivermektin mengikat kanal klorida bergerbang glutamat yang hanya dimiliki invertebrata sehingga parasit lumpuh — itulah dasar keamanannya pada manusia.',
    mengatasi: 'Filariasis limfatik, skabies (ivermektin oral), dan strongiloidiasis.',
    ingat: 'Kanal glutamat-klorida tidak ada pada mamalia — selektivitasnya berasal dari situ.',
    awas: 'Reaksi Mazzotti akibat matinya mikrofilaria secara serentak; DEC BERBAHAYA pada koinfeksi Loa loa dan onkoserkiasis.',
  },
  {
    nama: 'Antiretroviral',
    alias: ['tenofovir', 'lamivudin', 'dolutegravir', 'efavirenz', 'zidovudin', 'ARV', 'antiretroviral'],
    golongan: 'Terapi antiretroviral kombinasi',
    mekanisme: 'Menghambat tiga tahap daur hidup HIV sekaligus: penghambat reverse transcriptase menghentikan penyalinan RNA virus menjadi DNA, penghambat integrase mencegah penyisipan DNA virus ke kromosom pejamu, dan penghambat protease menggagalkan pematangan virion.',
    mengatasi: 'Menekan jumlah virus sampai tidak terdeteksi, memulihkan CD4, dan MEMUTUS PENULARAN.',
    ingat: 'Tidak terdeteksi = tidak menularkan. Itu pesan yang mengubah hidup pasien dan pasangannya.',
    awas: 'Tiga obat sekaligus, seumur hidup, tanpa jeda — putus obat menimbulkan kekebalan virus. Awas sindrom pemulihan imun pada bulan-bulan pertama.',
  },
  {
    nama: 'Dapson',
    alias: ['dapson', 'dapsone', 'klofazimin', 'rifampicin kusta', 'MDT'],
    golongan: 'Antikusta (multidrug therapy)',
    mekanisme: 'Dapson menghambat sintesis folat basil kusta; rifampisin membunuhnya dengan cepat lewat penghambatan RNA polimerase; klofazimin bekerja pada DNA basil sekaligus meredam radang. Kombinasi tiga obat mencegah kekebalan.',
    mengatasi: 'Menyembuhkan kusta dan memutus penularan; pasien tidak menular lagi setelah dosis pertama rifampisin.',
    ingat: 'PB 6 bulan, MB 12 bulan. Reaksi kusta bukan berarti terapi gagal dan obat TIDAK dihentikan.',
    awas: 'Dapson menimbulkan hemolisis pada defisiensi G6PD dan methemoglobinemia; klofazimin menggelapkan kulit.',
  },
  {
    nama: 'Permetrin',
    alias: ['permetrin', 'permethrin', 'gameksan', 'lindan', 'sulfur presipitatum'],
    golongan: 'Skabisida topikal',
    mekanisme: 'Mengganggu kanal natrium pada saraf tungau sehingga terjadi depolarisasi berkepanjangan, kelumpuhan, dan kematian parasit.',
    mengatasi: 'Skabies dan pedikulosis.',
    ingat: 'Dioleskan ke SELURUH tubuh dari leher ke bawah, didiamkan 8-10 jam, dan SELURUH anggota rumah diobati bersamaan meski belum gatal.',
    awas: 'Gatal dapat bertahan 2-4 minggu setelah tungau mati (reaksi alergi terhadap sisa tungau) — itu bukan tanda gagal terapi dan jangan diulang terus-menerus.',
  },
  {
    nama: 'Heparin',
    alias: ['heparin', 'enoksaparin', 'enoxaparin', 'fondaparinuks', 'fondaparinux', 'LMWH'],
    rantai: [
      'Percepat antitrombin III ×1000',
      'faktor Xa & trombin dinonaktifkan',
      'bekuan tak membesar',
      '(MENCEGAH, tidak melarutkan)',
    ],
    golongan: 'Antikoagulan',
    mekanisme: 'Mempercepat kerja antitrombin III ribuan kali lipat sehingga faktor Xa dan trombin dinonaktifkan; heparin berat molekul rendah lebih selektif terhadap faktor Xa sehingga efeknya lebih dapat diramalkan tanpa pemantauan rutin.',
    mengatasi: 'Mencegah pembesaran trombus pada sindrom koroner akut, trombosis vena dalam, dan emboli paru.',
    ingat: 'Antikoagulan MENCEGAH bekuan membesar; ia tidak melarutkan bekuan yang sudah ada — itu pekerjaan trombolitik.',
    awas: 'Perdarahan dan trombositopenia akibat heparin; penawarnya protamin sulfat.',
  },
  {
    nama: 'Warfarin',
    alias: ['warfarin'],
    rantai: [
      '⊣ vitamin K epoksida reduktase',
      'faktor II, VII, IX, X tak dikarboksilasi',
      'tak berfungsi',
      '',
      'Faktor lama harus habis → efek penuh 3-5 HARI',
      'Protein C habis duluan → awalnya PROTROMBOTIK',
    ],
    golongan: 'Antikoagulan antagonis vitamin K',
    mekanisme: 'Menghambat enzim vitamin K epoksida reduktase sehingga faktor II, VII, IX, dan X tidak dapat dikarboksilasi dan menjadi tidak berfungsi. Karena faktor yang sudah beredar harus habis lebih dahulu, efek penuhnya baru tercapai setelah 3-5 hari.',
    mengatasi: 'Mencegah stroke pada fibrilasi atrium dan mencegah kekambuhan trombosis vena.',
    ingat: 'Awalnya PROTROMBOTIK karena protein C yang antikoagulan justru habis lebih dahulu — itu sebabnya ditumpangkan dengan heparin pada awal terapi.',
    awas: 'Perdarahan; sangat banyak interaksi obat dan makanan (sayuran hijau); pantau INR; penawarnya vitamin K dan konsentrat faktor.',
  },
  {
    nama: 'Streptokinase',
    alias: ['streptokinase', 'alteplase', 'fibrinolitik', 'trombolitik'],
    rantai: [
      'Plasminogen → PLASMIN',
      'jaring fibrin dilarutkan',
      'bekuan hancur',
      'arteri terbuka',
      'miokardium selamat',
    ],
    golongan: 'Trombolitik',
    mekanisme: 'Mengubah plasminogen menjadi plasmin yang MELARUTKAN jaring fibrin, sehingga bekuan yang sudah menyumbat pembuluh terbuka kembali dan aliran darah pulih.',
    mengatasi: 'Membuka kembali arteri koroner pada STEMI bila tindakan kateterisasi tidak terjangkau dalam waktu yang ditentukan.',
    ingat: 'Waktu adalah otot jantung: makin cepat diberikan, makin banyak miokardium yang selamat.',
    awas: 'Perdarahan intrakranial adalah risiko utamanya; kontraindikasi mutlak antara lain riwayat stroke perdarahan, stroke iskemik <6 bulan, dan perdarahan aktif.',
  },
  {
    nama: 'Digoksin',
    alias: ['digoksin', 'digoxin'],
    rantai: [
      '⊣ Na-K-ATPase',
      'Na intrasel ↑',
      'pertukaran Na-Ca melambat',
      'Ca intrasel ↑',
      'KONTRAKSI MENGUAT',
      '',
      '+ tonus vagus ↑ → konduksi AV ↓ → laju ↓',
    ],
    golongan: 'Glikosida jantung',
    mekanisme: 'Menghambat pompa Na-K-ATPase sehingga natrium intrasel naik, pertukaran natrium-kalsium melambat, dan kalsium intrasel meningkat — kontraksi menguat. Ia juga meningkatkan tonus vagus sehingga konduksi melalui nodus AV melambat.',
    mengatasi: 'Mengendalikan laju pada fibrilasi atrium (terutama bila disertai gagal jantung) dan memperbaiki gejala gagal jantung.',
    ingat: 'Digoksin memperbaiki GEJALA, tidak memperpanjang hidup.',
    awas: 'Jendela terapi sempit: mual, penglihatan kuning, dan aritmia. HIPOKALEMIA meningkatkan toksisitasnya — itu sebabnya berbahaya bersama furosemid tanpa pemantauan kalium.',
  },
  {
    nama: 'Amiodaron',
    alias: ['amiodaron', 'amiodarone'],
    golongan: 'Antiaritmia kelas III',
    mekanisme: 'Memperpanjang masa refrakter dengan menghambat kanal kalium, sekaligus memiliki sifat kelas I, II, dan IV — itulah sebabnya ia bekerja pada aritmia atrium maupun ventrikel.',
    mengatasi: 'Fibrilasi atrium, takikardia ventrikel, dan henti jantung dengan irama yang dapat dikejut.',
    ingat: 'Satu obat empat kelas — kuat, tetapi harganya adalah efek samping di banyak organ.',
    awas: 'Toksisitas tiroid (dapat hipo maupun hipertiroid), fibrosis paru, endapan kornea, dan hepatotoksik. Pantau tiroid dan foto toraks berkala.',
  },
  {
    nama: 'Adenosin',
    alias: ['adenosin', 'adenosine'],
    golongan: 'Antiaritmia kerja sangat singkat',
    mekanisme: 'Mengaktifkan reseptor A1 di nodus AV sehingga konduksi terhenti sesaat dan sirkuit masuk-ulang terputus. Waktu paruhnya kurang dari 10 detik karena langsung diambil sel darah merah dan endotel.',
    mengatasi: 'Menghentikan takikardia supraventrikel yang stabil, dan membantu mengungkap irama atrium yang tersembunyi.',
    ingat: 'Suntikkan CEPAT lewat vena besar lalu bilas dengan NaCl — bila pelan, obat sudah habis sebelum sampai ke jantung.',
    awas: 'Pasien merasa dada seperti tertekan dan takut sesaat — beritahu sebelumnya. Terjadi henti sinus beberapa detik yang normal.',
  },
  {
    nama: 'Norepinefrin',
    alias: ['norepinefrin', 'noradrenalin', 'dobutamin', 'dopamin', 'vasopresor'],
    golongan: 'Vasopresor dan inotropik',
    mekanisme: 'Norepinefrin bekerja terutama pada reseptor alfa-1 sehingga pembuluh menyempit dan tekanan perfusi naik. Dobutamin bekerja pada beta-1 sehingga kontraktilitas meningkat tanpa banyak menaikkan tahanan pembuluh.',
    mengatasi: 'Mempertahankan tekanan perfusi organ pada syok septik (norepinefrin) dan memperbaiki curah jantung pada syok kardiogenik (dobutamin).',
    ingat: 'Vasopresor MENJEPIT pembuluh; inotropik MEMOMPA lebih kuat. Pilih menurut apa yang rusak.',
    awas: 'Berikan lewat vena besar — kebocoran norepinefrin ke jaringan menyebabkan nekrosis. Vasopresor pada pasien yang masih kekurangan cairan hanya menyembunyikan hipovolemia.',
  },
  {
    nama: 'Kortikosteroid inhalasi',
    alias: ['budesonid', 'flutikason', 'beklometason', 'ICS'],
    rantai: [
      'Langsung ke mukosa jalan napas',
      'radang eosinofilik ↓',
      'hiperresponsivitas bronkus ↓',
      'SERANGAN BERKURANG',
      '(pengendali, BUKAN pelega)',
    ],
    golongan: 'Glukokortikoid inhalasi',
    mekanisme: 'Bekerja langsung pada mukosa jalan napas: menekan radang eosinofilik, menurunkan hiperresponsivitas bronkus, dan mengurangi sekresi — dengan dosis jauh lebih kecil daripada steroid sistemik sehingga efek samping seluruh tubuh minimal.',
    mengatasi: 'MENGENDALIKAN asma: mengurangi serangan, bukan melegakan serangan yang sedang terjadi.',
    ingat: 'Pengendali harian, bukan pelega. Pasien yang hanya memakai salbutamol tanpa ini akan terus masuk gawat darurat.',
    awas: 'Kandidiasis mulut dan suara serak — KUMUR setelah pemakaian; gunakan spacer pada anak.',
  },
  {
    nama: 'Montelukast',
    alias: ['montelukast'],
    golongan: 'Antagonis reseptor leukotrien',
    mekanisme: 'Menghambat reseptor CysLT1 sehingga leukotrien — mediator yang jauh lebih kuat daripada histamin dalam menyempitkan bronkus dan menarik eosinofil — tidak dapat bekerja.',
    mengatasi: 'Asma, terutama yang dipicu latihan fisik, dan rinitis alergi penyerta.',
    ingat: 'Jalur leukotrien tidak dipengaruhi antihistamin — itu sebabnya ia menjadi tambahan, bukan pengganti.',
    awas: 'Gangguan suasana hati dan mimpi buruk, termasuk pada anak — tanyakan secara aktif.',
  },
  {
    nama: 'Oksimetazolin',
    alias: ['oksimetazolin', 'pseudoefedrin', 'efedrin', 'dekongestan', 'fenilefrin'],
    golongan: 'Dekongestan agonis alfa-adrenergik',
    mekanisme: 'Merangsang reseptor alfa-1 pada pembuluh mukosa hidung sehingga terjadi vasokonstriksi, mukosa mengempis, dan jalan napas hidung terbuka.',
    mengatasi: 'Hidung tersumbat pada rinitis dan sinusitis, serta melapangkan lapangan pandang saat mengeluarkan benda asing.',
    ingat: 'Topikal MAKSIMAL 3-5 HARI — lebih lama menimbulkan rinitis medikamentosa, tersumbat yang justru disebabkan obatnya.',
    awas: 'Sediaan oral menaikkan tekanan darah dan menimbulkan insomnia; hati-hati pada hipertensi, penyakit jantung, dan glaukoma.',
  },
  {
    nama: 'Timolol',
    alias: ['timolol', 'asetazolamid', 'acetazolamide', 'latanoprost', 'pilokarpin'],
    golongan: 'Obat penurun tekanan intraokular',
    mekanisme: 'Penyekat beta topikal (timolol) dan asetazolamid menurunkan PRODUKSI humor akuos oleh badan siliar; analog prostaglandin (latanoprost) dan pilokarpin meningkatkan PENGELUARANNYA.',
    mengatasi: 'Menurunkan tekanan bola mata pada glaukoma, dan pada glaukoma akut menyelamatkan penglihatan yang dapat hilang dalam hitungan jam.',
    ingat: 'Dua cara menurunkan tekanan: kurangi produksi atau perlancar pengeluaran. Pada serangan akut keduanya dipakai bersama.',
    awas: 'Timolol dapat diserap sistemik dan menimbulkan bradikardia serta bronkospasme — tanyakan asma sebelum meresepkan; tekan sudut mata dalam setelah meneteskan.',
  },
  {
    nama: 'Air mata buatan',
    alias: ['air mata buatan', 'artificial tear', 'lubrikan mata', 'hidroksipropil metilselulosa'],
    golongan: 'Lubrikan permukaan mata',
    mekanisme: 'Menggantikan lapisan air mata yang kurang sehingga permukaan kornea tetap basah dan epitelnya terlindung dari kekeringan serta gesekan kelopak.',
    mengatasi: 'Mata kering, dan PERLINDUNGAN KORNEA pada mata yang tidak dapat menutup sempurna (Bell\'s palsy, eksoftalmus).',
    ingat: 'Pada Bell\'s palsy, perlindungan mata sama pentingnya dengan steroidnya — kebutaan akibat kornea kering tidak dapat dikembalikan.',
    awas: 'Pilih sediaan tanpa pengawet bila dipakai lebih dari 4-6 kali sehari.',
  },
  {
    nama: 'Karbo adsorben',
    alias: ['norit', 'karbo adsorben', 'arang aktif', 'activated charcoal'],
    golongan: 'Adsorben saluran cerna',
    mekanisme: 'Permukaannya yang sangat luas dan berpori mengikat molekul racun di dalam lumen saluran cerna sehingga tidak terserap dan dibuang bersama tinja.',
    mengatasi: 'Keracunan obat dan zat kimia yang tertelan.',
    ingat: 'Paling berguna dalam 1 JAM pertama; sesudah itu sebagian besar racun sudah terserap.',
    awas: 'Tidak mengikat besi, litium, alkohol, dan asam maupun basa kuat. Jangan diberikan pada penurunan kesadaran tanpa jalan napas terlindung — risiko aspirasi.',
  },
  {
    nama: 'Nalokson',
    alias: ['nalokson', 'naloxone'],
    golongan: 'Antagonis reseptor opioid',
    mekanisme: 'Bersaing dengan opioid pada reseptor mu dan mengusirnya dari reseptor sehingga depresi napas segera pulih.',
    mengatasi: 'Keracunan opioid dengan depresi napas.',
    ingat: 'Waktu paruh nalokson LEBIH PENDEK daripada sebagian besar opioid — pasien dapat kembali tidak bernapas, jadi harus tetap dipantau.',
    awas: 'Menimbulkan gejala putus obat mendadak pada pemakai kronik: agitasi, nyeri, dan muntah.',
  },
  {
    nama: 'Diazepam rektal',
    alias: ['stesolid', 'diazepam rektal'],
    golongan: 'Benzodiazepin sediaan rektal',
    mekanisme: 'Zat yang sama dengan diazepam suntik, tetapi diserap melalui pleksus vena hemoroidalis yang sebagian melewati hati, sehingga kadar terapeutik tercapai dalam 5-10 menit tanpa perlu jalur intravena.',
    mengatasi: 'Menghentikan kejang pada anak ketika jalur intravena belum terpasang atau di rumah.',
    ingat: '5 mg untuk berat <10 kg, 10 mg untuk >10 kg. Ini yang diajarkan kepada ORANG TUA supaya kejang berhenti sebelum sampai rumah sakit.',
    awas: 'Depresi napas bila diulang berlebihan; boleh diulang satu kali.',
  },
  {
    nama: 'Asam salisilat',
    alias: ['asam salisilat', 'urea topikal', 'keratolitik'],
    golongan: 'Keratolitik topikal',
    mekanisme: 'Melarutkan semen antar-sel pada stratum korneum sehingga lapisan tanduk yang menebal terlepas dan obat lain dapat menembus lebih dalam.',
    mengatasi: 'Menipiskan sisik pada psoriasis, kalus, dan veruka.',
    ingat: 'Dipakai sebagai PEMBUKA JALAN bagi obat aktif — bukan obat utamanya.',
    awas: 'Iritasi; hindari pemakaian luas pada anak (keracunan salisilat).',
  },
  {
    nama: 'Benzoil peroksida',
    alias: ['benzoil peroksida', 'tretinoin', 'adapalen', 'retinoid'],
    golongan: 'Antiakne topikal',
    mekanisme: 'Benzoil peroksida melepaskan radikal oksigen yang membunuh Cutibacterium acnes sekaligus melarutkan komedo. Retinoid menormalkan pematangan keratinosit sehingga sumbatan folikel — akar seluruh proses akne — tidak terbentuk.',
    mengatasi: 'Akne: retinoid mengurusi komedo, benzoil peroksida mengurusi bakteri dan radangnya.',
    ingat: 'Akne dimulai dari SUMBATAN, bukan dari kuman. Itu sebabnya retinoid menjadi tulang punggung terapi.',
    awas: 'Iritasi dan kulit kering pada awal pemakaian (mulai selang-seling); retinoid KONTRAINDIKASI pada kehamilan; benzoil peroksida memutihkan kain.',
  },
  {
    nama: 'Antasida',
    alias: ['antasida', 'aluminium hidroksida', 'magnesium hidroksida', 'sukralfat'],
    golongan: 'Penetral asam dan pelindung mukosa',
    mekanisme: 'Antasida menetralkan asam lambung yang sudah ada secara langsung. Sukralfat, dalam suasana asam, membentuk lapisan lekat yang menutupi dasar tukak sehingga terlindung dari asam dan pepsin.',
    mengatasi: 'Meredakan nyeri ulu hati dengan CEPAT, dan sukralfat melindungi tukak selama penyembuhan.',
    ingat: 'Antasida meredakan dalam hitungan menit tetapi tidak menyembuhkan; penghambat pompa proton lambat tetapi menyembuhkan.',
    awas: 'Antasida menghalangi penyerapan banyak obat — beri jarak 2 jam. Aluminium menyebabkan sembelit, magnesium menyebabkan diare.',
  },
  {
    nama: 'Loperamid',
    alias: ['loperamid', 'loperamide'],
    golongan: 'Antimotilitas opioid perifer',
    mekanisme: 'Mengaktifkan reseptor opioid mu pada pleksus mienterikus usus sehingga gerak peristaltik melambat dan waktu penyerapan air memanjang; hampir tidak menembus sawar darah-otak sehingga tidak menimbulkan efek pusat.',
    mengatasi: 'Diare tanpa infeksi invasif, misalnya diare wisatawan tanpa demam.',
    ingat: 'JANGAN pada disentri, diare berdarah, atau diare dengan demam — memperlambat pengeluaran kuman dan toksinnya. TIDAK BOLEH pada anak.',
    awas: 'Megakolon toksik pada kolitis; pada anak menimbulkan ileus dan depresi napas.',
  },
  {
    nama: 'Piridoksin',
    alias: ['piridoksin', 'vitamin b6'],
    golongan: 'Vitamin B6',
    mekanisme: 'Menjadi kofaktor pada sintesis neurotransmiter dan metabolisme asam amino; isoniazid mengikatnya sehingga terjadi defisiensi fungsional pada saraf tepi.',
    mengatasi: 'Mencegah dan mengobati neuropati akibat isoniazid; penawar kejang pada keracunan isoniazid.',
    ingat: 'Setiap resep isoniazid sebaiknya disertai piridoksin, terutama pada gizi kurang, hamil, diabetes, dan HIV.',
    awas: 'Dosis sangat besar jangka panjang justru menimbulkan neuropati sensorik.',
  },
  {
    nama: 'Vitamin A',
    alias: ['vitamin a', 'retinol'],
    golongan: 'Vitamin larut lemak',
    mekanisme: 'Menjadi bahan rodopsin pada sel batang retina dan mempertahankan keutuhan epitel serta fungsi kekebalan mukosa.',
    mengatasi: 'Xeroftalmia dan buta senja; menurunkan keparahan campak dan angka kematiannya.',
    ingat: 'Diberikan hari ke-1, ke-2, dan ke-15 — bukan sekali saja.',
    awas: 'Dosis besar KONTRAINDIKASI pada kehamilan (teratogenik).',
  },
  {
    nama: 'Cairan kristaloid',
    alias: ['ringer laktat', 'nacl 0,9%', 'kristaloid', 'ringer asetat', 'dekstrosa'],
    rantai: [
      'Isi ruang intravaskular',
      'preload ↑',
      'isi sekuncup ↑',
      'curah jantung ↑',
      'perfusi jaringan pulih',
    ],
    golongan: 'Cairan resusitasi',
    mekanisme: 'Mengisi kembali ruang intravaskular sehingga preload, isi sekuncup, dan curah jantung naik; kandungan elektrolitnya menyerupai plasma sehingga tidak menimbulkan pergeseran cairan yang mencolok.',
    mengatasi: 'Mengembalikan perfusi jaringan pada syok hipovolemik, dehidrasi, dan sepsis.',
    ingat: 'Pada perdarahan, kristaloid hanya menunda — yang dibutuhkan adalah DARAH dan penghentian sumber perdarahannya.',
    awas: 'Berlebihan menimbulkan edema paru dan asidosis hiperkloremik (NaCl 0,9%); pada syok kardiogenik justru berbahaya.',
  },
]

/**
 * Obat yang disebut di dalam satu teks tatalaksana.
 *
 * Pencocokan memakai BATAS KATA, bukan sekadar potongan teks: tanpa itu "Fe"
 * cocok dengan "Fenitoin" dan "besi" muncul pada setiap entri yang menyebut
 * "pembesian". Nama terpanjang diuji lebih dahulu supaya "asam traneksamat"
 * tidak keburu tertangkap oleh "asam folat".
 */
export function obatDalam(teks: string): MekanismeObat[] {
  const t = teks.toLowerCase()
  const keluar: MekanismeObat[] = []
  for (const o of MEKANISME_OBAT) {
    const nama = [o.nama, ...(o.alias ?? [])].sort((a, b) => b.length - a.length)
    const ketemu = nama.some((n) => {
      const k = n.toLowerCase()
      const i = t.indexOf(k)
      if (i < 0) return false
      const sebelum = i === 0 ? ' ' : t[i - 1]
      const sesudah = i + k.length >= t.length ? ' ' : t[i + k.length]
      return !/[a-z0-9]/.test(sebelum) && !/[a-z0-9]/.test(sesudah)
    })
    if (ketemu) keluar.push(o)
  }
  return keluar
}
