// DIBANGKITKAN oleh scripts/molekul.py — jangan disunting tangan.
//
// Konformer 3D dihitung RDKit (ETKDG + MMFF94) dari SMILES yang tercatat di
// skrip itu, dan tiap molekul hanya ditulis setelah rumus serta massa
// molekulnya cocok dengan nilai rujukannya. Sifat fisikokimia di bawah ini
// dihitung dari struktur yang sama, bukan diketik ulang.
export interface MoleculeMeta {
  id: string
  name: string
  smiles: string
  formula: string
  mass: number
  atoms: number
  heavyAtoms: number
  rings: number
  /** Lipofilisitas terhitung (Crippen logP). */
  logP: number
  hbd: number
  hba: number
  /** Luas permukaan polar topologis (Å²) — penentu penembusan sawar. */
  tpsa: number
}

export const MOLECULES: MoleculeMeta[] = [
  {
    "id": "aspirin",
    "name": "Aspirin",
    "smiles": "CC(=O)Oc1ccccc1C(=O)O",
    "formula": "C9H8O4",
    "mass": 180.16,
    "atoms": 21,
    "heavyAtoms": 13,
    "rings": 1,
    "logP": 1.31,
    "hbd": 1,
    "hba": 3,
    "tpsa": 63.6
  },
  {
    "id": "paracetamol",
    "name": "Paracetamol",
    "smiles": "CC(=O)Nc1ccc(O)cc1",
    "formula": "C8H9NO2",
    "mass": 151.16,
    "atoms": 20,
    "heavyAtoms": 11,
    "rings": 1,
    "logP": 1.35,
    "hbd": 2,
    "hba": 2,
    "tpsa": 49.3
  },
  {
    "id": "ibuprofen",
    "name": "Ibuprofen",
    "smiles": "CC(C)Cc1ccc(cc1)C(C)C(=O)O",
    "formula": "C13H18O2",
    "mass": 206.28,
    "atoms": 33,
    "heavyAtoms": 15,
    "rings": 1,
    "logP": 3.07,
    "hbd": 1,
    "hba": 1,
    "tpsa": 37.3
  },
  {
    "id": "metformin",
    "name": "Metformin",
    "smiles": "CN(C)C(=N)NC(=N)N",
    "formula": "C4H11N5",
    "mass": 129.17,
    "atoms": 20,
    "heavyAtoms": 9,
    "rings": 0,
    "logP": -1.03,
    "hbd": 4,
    "hba": 2,
    "tpsa": 89.0
  },
  {
    "id": "atorvastatin",
    "name": "Atorvastatin",
    "smiles": "CC(C)c1c(C(=O)Nc2ccccc2)c(-c2ccccc2)c(-c2ccc(F)cc2)n1CC[C@@H](O)C[C@@H](O)CC(=O)O",
    "formula": "C33H35FN2O5",
    "mass": 558.65,
    "atoms": 76,
    "heavyAtoms": 41,
    "rings": 4,
    "logP": 6.31,
    "hbd": 4,
    "hba": 4,
    "tpsa": 111.8
  },
  {
    "id": "simvastatin",
    "name": "Simvastatin",
    "smiles": "CC[C](C)(C)C(=O)O[C@H]1C[C@H](C)C=C2C=C[C@H](C)[C@H](CC[C@@H]3C[C@@H](O)CC(=O)O3)[C@@H]12",
    "formula": "C25H38O5",
    "mass": 418.57,
    "atoms": 68,
    "heavyAtoms": 30,
    "rings": 3,
    "logP": 4.59,
    "hbd": 1,
    "hba": 5,
    "tpsa": 72.8
  },
  {
    "id": "amlodipine",
    "name": "Amlodipine",
    "smiles": "CCOC(=O)C1=C(COCCN)NC(C)=C(C(=O)OC)C1c1ccccc1Cl",
    "formula": "C20H25ClN2O5",
    "mass": 408.88,
    "atoms": 53,
    "heavyAtoms": 28,
    "rings": 2,
    "logP": 2.27,
    "hbd": 2,
    "hba": 7,
    "tpsa": 99.9
  },
  {
    "id": "lisinopril",
    "name": "Lisinopril",
    "smiles": "NCCCC[C@H](N[C@@H](CCc1ccccc1)C(=O)O)C(=O)N1CCC[C@H]1C(=O)O",
    "formula": "C21H31N3O5",
    "mass": 405.5,
    "atoms": 60,
    "heavyAtoms": 29,
    "rings": 2,
    "logP": 1.24,
    "hbd": 4,
    "hba": 5,
    "tpsa": 133.0
  },
  {
    "id": "captopril",
    "name": "Captopril",
    "smiles": "CC(CS)C(=O)N1CCC[C@H]1C(=O)O",
    "formula": "C9H15NO3S",
    "mass": 217.29,
    "atoms": 29,
    "heavyAtoms": 14,
    "rings": 1,
    "logP": 0.63,
    "hbd": 2,
    "hba": 3,
    "tpsa": 57.6
  },
  {
    "id": "losartan",
    "name": "Losartan",
    "smiles": "CCCCc1nc(Cl)c(CO)n1Cc1ccc(-c2ccccc2-c2nnn[nH]2)cc1",
    "formula": "C22H23ClN6O",
    "mass": 422.92,
    "atoms": 53,
    "heavyAtoms": 30,
    "rings": 4,
    "logP": 4.27,
    "hbd": 2,
    "hba": 5,
    "tpsa": 92.5
  },
  {
    "id": "furosemide",
    "name": "Furosemide",
    "smiles": "NS(=O)(=O)c1cc(C(=O)O)c(NCc2ccco2)cc1Cl",
    "formula": "C12H11ClN2O5S",
    "mass": 330.75,
    "atoms": 32,
    "heavyAtoms": 21,
    "rings": 2,
    "logP": 1.89,
    "hbd": 3,
    "hba": 5,
    "tpsa": 122.6
  },
  {
    "id": "hct",
    "name": "Hydrochlorothiazide",
    "smiles": "NS(=O)(=O)c1cc2c(cc1Cl)NCNS2(=O)=O",
    "formula": "C7H8ClN3O4S2",
    "mass": 297.75,
    "atoms": 25,
    "heavyAtoms": 17,
    "rings": 2,
    "logP": -0.35,
    "hbd": 3,
    "hba": 5,
    "tpsa": 118.4
  },
  {
    "id": "spironolactone",
    "name": "Spironolactone",
    "smiles": "CC(=O)S[C@@H]1CC2=CC(=O)CC[C@]2(C)[C@H]2CC[C@]3(C)[C@@H](CC[C@]34CCC(=O)O4)[C@@H]12",
    "formula": "C24H32O4S",
    "mass": 416.58,
    "atoms": 61,
    "heavyAtoms": 29,
    "rings": 5,
    "logP": 4.85,
    "hbd": 0,
    "hba": 5,
    "tpsa": 60.4
  },
  {
    "id": "bisoprolol",
    "name": "Bisoprolol",
    "smiles": "CC(C)NCC(O)COc1ccc(COCCOC(C)C)cc1",
    "formula": "C18H31NO4",
    "mass": 325.45,
    "atoms": 54,
    "heavyAtoms": 23,
    "rings": 1,
    "logP": 2.37,
    "hbd": 2,
    "hba": 5,
    "tpsa": 60.0
  },
  {
    "id": "propranolol",
    "name": "Propranolol",
    "smiles": "CC(C)NCC(O)COc1cccc2ccccc12",
    "formula": "C16H21NO2",
    "mass": 259.35,
    "atoms": 40,
    "heavyAtoms": 19,
    "rings": 2,
    "logP": 2.58,
    "hbd": 2,
    "hba": 3,
    "tpsa": 41.5
  },
  {
    "id": "warfarin",
    "name": "Warfarin",
    "smiles": "CC(=O)CC(c1ccccc1)c1c(O)c2ccccc2oc1=O",
    "formula": "C19H16O4",
    "mass": 308.33,
    "atoms": 39,
    "heavyAtoms": 23,
    "rings": 3,
    "logP": 3.61,
    "hbd": 1,
    "hba": 4,
    "tpsa": 67.5
  },
  {
    "id": "clopidogrel",
    "name": "Clopidogrel",
    "smiles": "COC(=O)[C@@H](c1ccccc1Cl)N1CCc2sccc2C1",
    "formula": "C16H16ClNO2S",
    "mass": 321.83,
    "atoms": 37,
    "heavyAtoms": 21,
    "rings": 3,
    "logP": 3.67,
    "hbd": 0,
    "hba": 4,
    "tpsa": 29.5
  },
  {
    "id": "salbutamol",
    "name": "Salbutamol",
    "smiles": "CC(C)(C)NCC(O)c1ccc(O)c(CO)c1",
    "formula": "C13H21NO3",
    "mass": 239.31,
    "atoms": 38,
    "heavyAtoms": 17,
    "rings": 1,
    "logP": 1.31,
    "hbd": 4,
    "hba": 4,
    "tpsa": 72.7
  },
  {
    "id": "prednisolone",
    "name": "Prednisolone",
    "smiles": "C[C@]12CC(O)[C@H]3[C@@H](CCC4=CC(=O)C=C[C@]43C)[C@@H]1CC[C@@]2(O)C(=O)CO",
    "formula": "C21H28O5",
    "mass": 360.45,
    "atoms": 54,
    "heavyAtoms": 26,
    "rings": 4,
    "logP": 1.56,
    "hbd": 3,
    "hba": 5,
    "tpsa": 94.8
  },
  {
    "id": "dexamethasone",
    "name": "Dexamethasone",
    "smiles": "C[C@@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(O)C(=O)CO",
    "formula": "C22H29FO5",
    "mass": 392.47,
    "atoms": 57,
    "heavyAtoms": 28,
    "rings": 4,
    "logP": 1.9,
    "hbd": 3,
    "hba": 5,
    "tpsa": 94.8
  },
  {
    "id": "omeprazole",
    "name": "Omeprazole",
    "smiles": "COc1ccc2[nH]c(S(=O)Cc3ncc(C)c(OC)c3C)nc2c1",
    "formula": "C17H19N3O3S",
    "mass": 345.42,
    "atoms": 43,
    "heavyAtoms": 24,
    "rings": 3,
    "logP": 2.9,
    "hbd": 1,
    "hba": 5,
    "tpsa": 77.1
  },
  {
    "id": "amoxicillin",
    "name": "Amoxicillin",
    "smiles": "CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O",
    "formula": "C16H19N3O5S",
    "mass": 365.41,
    "atoms": 44,
    "heavyAtoms": 25,
    "rings": 3,
    "logP": 0.02,
    "hbd": 4,
    "hba": 6,
    "tpsa": 133.0
  },
  {
    "id": "ciprofloxacin",
    "name": "Ciprofloxacin",
    "smiles": "O=C(O)c1cn(C2CC2)c2cc(N3CCNCC3)c(F)cc2c1=O",
    "formula": "C17H18FN3O3",
    "mass": 331.35,
    "atoms": 42,
    "heavyAtoms": 24,
    "rings": 4,
    "logP": 1.58,
    "hbd": 2,
    "hba": 4,
    "tpsa": 74.6
  },
  {
    "id": "metronidazole",
    "name": "Metronidazole",
    "smiles": "Cc1ncc([N+](=O)[O-])n1CCO",
    "formula": "C6H9N3O3",
    "mass": 171.16,
    "atoms": 21,
    "heavyAtoms": 12,
    "rings": 1,
    "logP": 0.09,
    "hbd": 1,
    "hba": 4,
    "tpsa": 81.2
  },
  {
    "id": "isoniazid",
    "name": "Isoniazid",
    "smiles": "NNC(=O)c1ccncc1",
    "formula": "C6H7N3O",
    "mass": 137.14,
    "atoms": 17,
    "heavyAtoms": 10,
    "rings": 1,
    "logP": -0.31,
    "hbd": 2,
    "hba": 3,
    "tpsa": 68.0
  },
  {
    "id": "allopurinol",
    "name": "Allopurinol",
    "smiles": "O=c1[nH]cnc2[nH]ncc12",
    "formula": "C5H4N4O",
    "mass": 136.11,
    "atoms": 14,
    "heavyAtoms": 10,
    "rings": 2,
    "logP": -0.35,
    "hbd": 2,
    "hba": 3,
    "tpsa": 74.4
  },
  {
    "id": "levodopa",
    "name": "Levodopa",
    "smiles": "N[C@@H](Cc1ccc(O)c(O)c1)C(=O)O",
    "formula": "C9H11NO4",
    "mass": 197.19,
    "atoms": 25,
    "heavyAtoms": 14,
    "rings": 1,
    "logP": 0.05,
    "hbd": 4,
    "hba": 4,
    "tpsa": 103.8
  },
  {
    "id": "diazepam",
    "name": "Diazepam",
    "smiles": "CN1c2ccc(Cl)cc2C(c2ccccc2)=NCC1=O",
    "formula": "C16H13ClN2O",
    "mass": 284.75,
    "atoms": 33,
    "heavyAtoms": 20,
    "rings": 3,
    "logP": 3.15,
    "hbd": 0,
    "hba": 2,
    "tpsa": 32.7
  },
  {
    "id": "haloperidol",
    "name": "Haloperidol",
    "smiles": "O=C(CCCN1CCC(O)(c2ccc(Cl)cc2)CC1)c1ccc(F)cc1",
    "formula": "C21H23ClFNO2",
    "mass": 375.87,
    "atoms": 49,
    "heavyAtoms": 26,
    "rings": 3,
    "logP": 4.43,
    "hbd": 1,
    "hba": 3,
    "tpsa": 40.5
  },
  {
    "id": "sertraline",
    "name": "Sertraline",
    "smiles": "CN[C@H]1CC[C@@H](c2ccc(Cl)c(Cl)c2)c2ccccc21",
    "formula": "C17H17Cl2N",
    "mass": 306.24,
    "atoms": 37,
    "heavyAtoms": 20,
    "rings": 3,
    "logP": 5.18,
    "hbd": 1,
    "hba": 1,
    "tpsa": 12.0
  },
  {
    "id": "phenytoin",
    "name": "Phenytoin",
    "smiles": "O=C1NC(=O)C(c2ccccc2)(c2ccccc2)N1",
    "formula": "C15H12N2O2",
    "mass": 252.27,
    "atoms": 31,
    "heavyAtoms": 19,
    "rings": 3,
    "logP": 1.77,
    "hbd": 2,
    "hba": 2,
    "tpsa": 58.2
  },
  {
    "id": "morphine",
    "name": "Morphine",
    "smiles": "CN1CC[C@]23c4c5ccc(O)c4O[C@H]2[C@H](O)C=C[C@H]3[C@H]1C5",
    "formula": "C17H19NO3",
    "mass": 285.34,
    "atoms": 40,
    "heavyAtoms": 21,
    "rings": 5,
    "logP": 1.2,
    "hbd": 2,
    "hba": 4,
    "tpsa": 52.9
  },
  {
    "id": "cetirizine",
    "name": "Cetirizine",
    "smiles": "OC(=O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1",
    "formula": "C21H25ClN2O3",
    "mass": 388.9,
    "atoms": 52,
    "heavyAtoms": 27,
    "rings": 3,
    "logP": 3.15,
    "hbd": 1,
    "hba": 4,
    "tpsa": 53.0
  },
  {
    "id": "ondansetron",
    "name": "Ondansetron",
    "smiles": "Cc1nccn1CC1CCc2c(c3ccccc3n2C)C1=O",
    "formula": "C18H19N3O",
    "mass": 293.37,
    "atoms": 41,
    "heavyAtoms": 22,
    "rings": 4,
    "logP": 3.13,
    "hbd": 0,
    "hba": 2,
    "tpsa": 39.8
  }
]

export const MOLECULE_BY_ID: Record<string, MoleculeMeta> = Object.fromEntries(
  MOLECULES.map((m) => [m.id, m]),
)
