// ─────────────────────────────────────────────────────────────────────────────
// Penjelasan fungsi tiap fitur, dalam bahasa sehari-hari.
//
// DITULIS DALAM BAHASA INGGRIS sejak putaran ini, mengikuti aturan pokok di
// CLAUDE.md: bahasa dasar aplikasi ini Inggris, dan layar yang masih berbahasa
// Indonesia adalah pekerjaan yang belum selesai. Sebelumnya 192 kalimat di
// sini berbahasa Indonesia, dan karena halaman "All Features" menampilkannya
// pada TIAP BARIS, satu halaman yang paling sering dibuka orang terbaca
// setengah Inggris setengah Indonesia.
//
// Halaman "Semua Fitur" berbentuk tabel: satu baris satu fitur, dengan kolom
// kedua berisi APA GUNANYA. Tanpa kolom itu, tabel hanya menjadi daftar nama
// yang tidak lebih berguna daripada deretan keping sebelumnya — nama seperti
// "VitaPulse" dan "Braden Scale" tidak memberi tahu siapa pun apa isinya.
//
// ATURAN PENULISAN — dipegang tanpa kecuali:
//
//   * SATU KALIMAT, dan sependek mungkin. Kolom ini dibaca sambil menggulir,
//     bukan dipelajari.
//   * MULAI DENGAN KATA KERJA yang menjawab "saya bisa apa di sini", bukan
//     "halaman ini adalah…". Yang dicari orang adalah kegiatannya.
//   * TANPA ISTILAH TEKNIS bila ada padanan sehari-hari. "Tekanan darah",
//     bukan "tensi arterial". Sasarannya harus terbaca oleh orang yang bukan
//     tenaga kesehatan.
//   * TIDAK MENJANJIKAN LEBIH DARI ISINYA. Kalimat yang melebih-lebihkan
//     membuat orang membuka halaman lalu merasa tertipu, dan itu lebih buruk
//     daripada nama yang membosankan.
//
// Kunci peta ini adalah alamat halamannya, bukan namanya — nama berubah saat
// disunting, alamat tidak.
// ─────────────────────────────────────────────────────────────────────────────

export const PENJELASAN_FITUR: Record<string, string> = {
  '/': 'See today at a glance: your numbers, what is due, and shortcuts to what you use most',
  '/tutorial': 'Walk through six short steps if this is your first time here',
  '/profile': 'Keep your own details, height, weight, and health history',
  '/settings': 'Change the look, language, notifications, and the technical bits',
  '/search': 'Search anything in the app from one box',
  '/latihan-beban': 'Log sets, reps, and load; see weekly volume and your best per movement',
  '/cari': 'Search features, conditions, drugs, OSCE stations, and calculators from one box',
  '/harian': 'Look back at any day: what the device measured and what you felt',
  '/ikhtisar': 'See every body number with charts and averages, over a range you choose',
  '/tubuh': 'Energy, heart, sleep, and movement on one page',
  '/latihan': 'Your coach, analysis, physiology, and endurance in one place',
  '/recovery': 'See how recovered you are today, and whether to train hard',
  '/logs': 'Read back your daily notes and the numbers that built up over time',
  '/vitapulse': 'Track heart rate, blood pressure, and other vitals over time',
  '/med-reminders': 'Set reminders so no dose gets missed',
  '/emergency': 'Carry a card with your blood type, allergies, and who to call',
  '/med-study': 'Practise questions, OSCE cases, condition notes, and mnemonics for exams',
  '/osce-ukmppd': 'See which cases have actually come up in OSCE exams since 2016',
  '/education': 'Read health material written for everyone, not for medical exams',
  '/drug-info': 'Look up a drug: what it treats, its dose, side effects, and cautions',
  '/my-materials': 'Find the material you wrote and the material you saved',
  '/editor': 'Write and edit material to share',
  '/feed': 'See what your friends have been up to',
  '/community': 'Talk with other people using the app',
  '/messages': 'Message other people privately',
  '/clubs': 'Join sports clubs and group activities',
  '/jelajah': 'Find people and posts across the app',
  '/scripture': 'Read scripture, with the source named every time',
  '/hadith': 'Read hadith collections with their translations',
  '/prayer-times': 'Check prayer times and the qibla direction where you are',
  '/wellness-hub': 'Open every wellbeing and longevity tool from one door',
  '/calculator-hub': 'Open every clinical calculator, searchable',
  '/fitness-hub': 'Open every fitness and training tool from one door',
  '/clinical-hub': 'Open every clinical and AI-assisted tool from one door',
  '/ringkasan-karya': 'Read one-paragraph summaries of 131 self-development books and films',
  '/semua-fitur': 'Browse every page in the app and what each one is for',
  '/consult': 'Book a consultation with a health professional',
  '/hospitals': 'Find hospitals, clinics, and health centres near you',
  '/pharmacy': 'Order medicines from a pharmacy',
  '/orders': 'Review your orders and purchases',
  '/marketplace': 'Buy and sell material, notes, and items with other users',
  '/pricing': 'Compare subscription plans and prices',
  '/billing': 'Manage your invoices and payment methods',
  '/keuangan': 'Track the money you spend and receive around your health',
  '/atur-fitur': 'Choose which features show up and which stay hidden',
  '/verification': 'Prove you are a health professional to unlock clinician features',
  '/notifications': 'Read everything that has been sent to you',
  '/architecture': 'See how this app is built, if you are curious how it works',
  '/legal': 'Read the terms, the privacy policy, and the limits of liability',
  '/change': 'See what changed and what was added in each version',
  '/learn': 'Learn how to use this app and what is in it',
  '/dek-connect': 'Manage your profile card for finding friends and partners',
  '/verifikasi-connect': 'Ask to have your profile marked as genuine',
  '/tinjau-connect': 'Review other people’s profile verification requests',
  '/admin': 'Use the admin tools for running the app',
  '/owner': 'See the owner overview',
  '/owner-analytics': 'See usage and growth numbers for the owner',
  '/health-simulator': 'See how today’s choices change your disease risk ten years out',
  '/findrisc': 'Work out your ten-year diabetes risk, and how to bring it down',
  '/biological-age': 'Estimate how old your body actually is from your health data',
  '/longevity': 'Build a personal plan to stay well longer, not just live longer',
  '/organ-vitality': 'See how each organ is doing, organ by organ, in one picture',
  '/supplements': 'Find out which supplements have real evidence behind them, and which do not',
  '/family-health': 'Record illness in your family so you know what to check for earlier',
  '/gene-info': 'Look up what a gene does and why it matters',
  '/connect': 'Find friends or a partner who match how you want to live',
  '/breathwork': 'Follow a paced breathing exercise that calms you in a few minutes',
  '/gratitude': 'Write down three good things a day — simple, and it holds up in trials',
  '/mental-health-screen': 'Check yourself for signs of depression and anxiety with standard questionnaires',
  '/substance-use-screen': 'Check your own drinking and smoking habits',
  '/ikigai': 'Work out what makes life feel worth it for you',
  '/harada': 'Break one big goal into eight supports and 64 concrete steps',
  '/life-compass': 'Set out your aims, your direction, and the next step',
  '/resilience-stories': 'Read how real people came back from hard places',
  '/sleep-debt': 'Work out the gap between the sleep you need and the sleep you get',
  '/chronotype': 'Find out whether you are an early riser or a night owl',
  '/epworth-sleepiness': 'Measure how sleepy you actually are during the day',
  '/sleep-apnea-screen': 'Check your risk of stopping breathing during sleep',
  '/sleep-toolkit': 'Use a cycle alarm, nap timer, dream journal, and sleep sounds',
  '/log-detak-jantung': 'See every heart-rate sample your watch sent, and how often it sampled',
  '/pola-tidur': 'See each night in stages — deep, REM, core, awake — and how regular your hours are',
  '/fasting': 'Set your eating window and see which metabolic stage you are in',
  '/thermal-therapy': 'Follow sauna and cold-water guidance, with the evidence beside it',
  '/macro-lab': 'Work out your carbohydrate, protein, and fat targets',
  '/sehat-sibuk': 'Fit healthy habits into a schedule that is already full',
  '/carbon-diet': 'Weigh food choices by their carbon footprint',
  '/nutrition': 'Count calories and nutrients, and see how fast you burn them',
  '/hydration': 'Work out how much water you need in a day',
  '/alcohol': 'Count standard drinks and estimate your blood alcohol level',
  '/caffeine': 'See how late today’s coffee will still be keeping you awake tonight',
  '/nutrition-toolkit': 'Use a Mediterranean diet checklist, sugar log, and plant-diversity count',
  '/air-quality': 'Check the air around you and what it means for your lungs',
  '/aesthetic': 'Follow guidance on caring for your skin and face',
  '/sun-exposure': 'Get enough sun for vitamin D without damaging your skin',
  '/toxin-checklist': 'Cut everyday exposure from plastics, cleaning products, and dirty air',
  '/body-toolkit': 'Build a skincare routine, map your symptoms, and note daily movement',
  '/first-aid': 'Follow first-aid steps in plain words: choking, cardiac arrest, bleeding',
  '/vaccine-tracker': 'Record your last immunisations and when the next ones are due',
  '/allergy-tracker': 'Record allergies to food, drink, drugs, and things that touch your skin',
  '/blood-donation': 'Check whether you can donate blood, and when you can again',
  '/organ-donor': 'Record your wish to donate organs, then talk to your family about it',
  '/visit-prep': 'Prepare what to bring and what to ask before seeing a doctor',
  '/posture-breaks': 'Get nudged to stand, stretch, and rest your eyes',
  '/pain-diary': 'Track pain day by day — useful for you, and for your doctor',
  '/second-opinion': 'Get a draft written by AI, then reviewed and approved by a real doctor',
  '/movement-toolkit': 'Test grip strength, balance, zone 2, and short daily drills',
  '/mind-toolkit': 'Train your brain with memory games, reaction time, and a stress measure',
  '/longevity-science': 'Read what is known about ageing: hallmarks, NAD+, sirtuins, rapamycin',
  '/self-assessment-toolkit': 'Try the telomere quiz, inflammation score, and waist-to-height ratio',
  '/longevity-game-center': 'Play habit bingo, share a report card, and read a daily quote',
  '/predictive-models-toolkit': 'Estimate autophagy timing, cortisol curves, and glycaemic load',
  '/data-lab-advanced': 'Forecast blood trends, compute PhenoAge, and use an encrypted data vault',
  '/bio-simulators': 'See mTOR/AMPK, daily rhythm, and telomeres drawn as illustrations',
  '/rppg-heart-rate': 'Estimate your pulse from the camera, without a smartwatch',
  '/vocal-biomarkers': 'Analyse pitch and tremor from a five-second voice recording',
  '/snp-profiler': 'Upload raw DNA data — processed in your own browser, sent nowhere',
  '/data-lab': 'Upload your own health data files and turn them into charts',
  '/athlete': 'Watch your training board: heart-rate zones, load, and GPS runs',
  '/workout': 'Follow guided sessions with video for each movement',
  '/training-plan': 'Follow a structured programme that adapts as you progress',
  '/lari-sepeda-renang': 'Work on power zones, swim pace, speed work, and form across all three sports',
  '/teknik-lari': 'Work on cadence, foot strike, arm swing, breathing, starts, and wind resistance',
  '/peregangan': 'Stretch for the situation — before a run, after a ride, or a break from sitting',
  '/crossfit': 'Learn CrossFit movements, the named benchmarks, and how to scale them safely',
  '/alat-fitness': 'Learn gym equipment and Hyrox-style workouts',
  '/sports-lab': 'Test and break down performance for your sport',
  '/analisis-gerak': 'Read stride asymmetry, walking quality, running form, and heart-rate recovery from your watch',
  '/riwayat-latihan': 'See every imported session with its minute-by-minute heart rate, zones, and recovery',
  '/analisis-pro': 'Track fitness and freshness, relative effort, best efforts, pace zones, and targets',
  '/body-battery': 'Watch your energy reserve from 0 to 100 through the day, read from heart rate',
  '/fisiologi-latihan': 'See training load, status, recovery time, and readiness computed from your watch',
  '/alat-endurance': 'Plan fuelling, sweat rate, cycling FTP, power guidance, and heat adjustment',
  '/pelacak-klinis': 'Log SpO₂, ECG results, jet-lag plans, pregnancy activity, and wheelchair physiology',
  '/latihan-dasar': 'Work through run pace zones and push-up, pull-up, sit-up, and posture progressions',
  '/fitness-test': 'Check your movement and posture from a photo',
  '/readiness': 'Find out whether today is for training hard or for resting',
  '/assessment': 'Take a starting measure of your fitness and movement patterns',
  '/body': 'Break down your body composition: muscle, fat, and water',
  '/lab': 'Manage training load, VO₂max, and performance measures',
  '/sports-science': 'Read the science and the key measures behind your numbers',
  '/shape-forming': 'Follow a structured programme to reshape your body composition',
  '/sports-scores': 'Follow live scores for your teams and leagues',
  '/health-data': 'Connect Apple Watch, or upload exports from Garmin, WHOOP, and InBody',
  '/chatbot': 'Ask a health question and get a plain-language answer with its sources',
  '/evidence': 'See the published evidence behind a treatment or a claim',
  '/trials': 'Find clinical trials you might be able to join',
  '/emr': 'Keep electronic records with help writing the notes',
  '/clinical': 'See your patient list with their clinical numbers',
  '/planning': 'Plan patient schedules and care',
  '/clinical-calculators': 'Use the scores and risk calculators used at the bedside',
  '/sexual-health': 'Read about reproductive, sexual, and maternity health',
  '/longevity-curriculum': 'Study a structured course in longevity medicine',
  '/lab-decoder': 'Get plain-language explanations of common lab results',
  '/reality-check': 'Take the CAGE alcohol screen and count your smoking pack-years',
  '/empiric-therapy-reference': 'Look up first-line drug classes by diagnosis — a quick, searchable reference',
  '/dermatology-lesion-mapper': 'Go from lesion shape and favoured site to a standard differential',
  '/psychiatric-status-exam': 'Write up a mental state examination in a structured way',
  '/neonatal-resuscitation-guide': 'Follow the newborn resuscitation steps with a Golden Minute timer',
  '/fluid-calculators': 'Calculate maintenance fluid, sepsis resuscitation, PALS, Parkland, and electrolyte correction',
  '/child-growth': 'Plot child growth on WHO charts, from 0 to 60 months',
  '/stroke-risk': 'Work out stroke risk in atrial fibrillation to decide about blood thinners',
  '/has-bled-score': 'Work out bleeding risk on blood thinners — the partner to CHA₂DS₂-VASc',
  '/timi-risk-score': 'Work out 14-day risk in unstable angina and non-ST-elevation heart attack',
  '/grace-score': 'Estimate in-hospital death risk across the whole acute coronary spectrum',
  '/qtc-calculator': 'Calculate corrected QT to screen drug safety, with four formulas and a trend',
  '/duke-criteria': 'Apply the criteria for diagnosing heart valve infection',
  '/ldl-calculator': 'Calculate LDL by the Friedewald formula, plus non-HDL cholesterol',
  '/risk': 'Calculate ten-year heart disease risk, FIB-4, and OST',
  '/wells-score': 'Estimate the chance of a leg or lung clot before testing',
  '/perc-rule': 'Rule out a lung clot without testing in low-risk patients',
  '/aa-gradient': 'Locate the cause of low oxygen: a lung problem, or breathing too slowly',
  '/lights-criteria': 'Tell exudate from transudate in fluid around the lung',
  '/sofa-score': 'Score failure across six organs in intensive care, with the trend',
  '/news2-score': 'Get early warning from ward vital signs, with the trend',
  '/meld-score': 'Score liver disease severity and transplant priority',
  '/maddrey-score': 'Decide whether steroids are needed in severe alcoholic hepatitis',
  '/child-pugh-score': 'Grade cirrhosis as A, B, or C, with the surgical risk that comes with it',
  '/glasgow-blatchford-score': 'Decide who needs admission for upper GI bleeding, before endoscopy',
  '/rockall-score': 'Estimate rebleeding and death risk after endoscopy',
  '/ranson-criteria': 'Score pancreatitis severity on admission and at 48 hours',
  '/bisap-score': 'Score pancreatitis severity within the first 24 hours',
  '/creatinine-clearance': 'Calculate creatinine clearance to adjust doses in kidney impairment',
  '/fena-calculator': 'Tell pre-renal acute kidney injury from tubular damage',
  '/pediatric-dka-calculator': 'Calculate bolus, deficit, maintenance, potassium, and insulin in paediatric DKA',
  '/corrected-calcium': 'Correct the calcium level when albumin is low',
  '/serum-osmolality': 'Calculate the osmolal gap to screen for toxic alcohol poisoning',
  '/4ts-score': 'Estimate the chance that heparin caused the low platelets',
  '/padua-score': 'Decide whether a medical patient needs clot prevention',
  '/caprini-score': 'Decide whether a surgical patient needs clot prevention',
  '/braden-scale': 'Score pressure-injury risk and the level of prevention it calls for',
  '/charlson-index': 'Score comorbidity burden and estimate ten-year survival',
  '/ottawa-ankle': 'Decide whether this ankle injury needs an X-ray at all',
}

/**
 * Ambil penjelasan untuk sebuah alamat.
 *
 * Urutannya: penjelasan di berkas ini lebih dahulu, lalu keterangan bawaan
 * dari hub sebagai cadangan. Bila keduanya tidak ada, dikembalikan teks kosong
 * dan pemanggilnya yang memutuskan apa yang ditampilkan — MENGARANG kalimat
 * penjelasan secara otomatis dari nama fitur akan menghasilkan keterangan yang
 * terdengar meyakinkan namun bisa saja keliru, dan keterangan keliru pada
 * halaman berisi dosis obat lebih berbahaya daripada kolom yang dikosongkan.
 */
export function penjelasan(to: string, cadangan?: string): string {
  return PENJELASAN_FITUR[to] ?? cadangan ?? ''
}
