// AUTO-GENERATED reference data — SKDI 2012 (Konsil Kedokteran Indonesia), official disease competency list
export type SkdiDiseaseSystem =
  | 'Saraf (Neurologi)'
  | 'Psikiatri'
  | 'Indera'
  | 'Respirasi'
  | 'Kardiovaskular'
  | 'Gastrointestinal & Hepatobilier'
  | 'Ginjal & Saluran Kemih'
  | 'Reproduksi & Obstetri'
  | 'Endokrin & Metabolik'
  | 'Hematologi & Imunologi'
  | 'Muskuloskeletal'
  | 'Integumen'
  | 'Forensik & Medikolegal'

export interface SkdiDiseaseEntry {
  system: SkdiDiseaseSystem
  disease: string
  level: string
  subsection: string | null
}

export const SKDI_DISEASE_LIST: SkdiDiseaseEntry[] = [
  { system: 'Saraf (Neurologi)', disease: 'Spina bifida', level: '2', subsection: 'Genetik dan Kongenital' },
  { system: 'Saraf (Neurologi)', disease: 'Fenilketonuria', level: '1', subsection: 'Genetik dan Kongenital' },
  { system: 'Saraf (Neurologi)', disease: 'Duchene muscular dystrophy', level: '1', subsection: 'Gangguan Neurologik Paediatrik' },
  { system: 'Saraf (Neurologi)', disease: 'Kejang demam', level: '4A', subsection: 'Gangguan Neurologik Paediatrik' },
  { system: 'Saraf (Neurologi)', disease: 'Infeksi sitomegalovirus', level: '2', subsection: 'Infeksi' },
  { system: 'Saraf (Neurologi)', disease: 'Meningitis', level: '3B', subsection: 'Infeksi' },
  { system: 'Saraf (Neurologi)', disease: 'Ensefalitis', level: '3B', subsection: 'Infeksi' },
  { system: 'Saraf (Neurologi)', disease: 'Malaria serebral', level: '3B', subsection: 'Infeksi' },
  { system: 'Saraf (Neurologi)', disease: 'Tetanus', level: '4A', subsection: 'Infeksi' },
  { system: 'Saraf (Neurologi)', disease: 'Tetanus neonatorum', level: '3B', subsection: 'Infeksi' },
  { system: 'Saraf (Neurologi)', disease: 'Toksoplasmosis serebral', level: '2', subsection: 'Infeksi' },
  { system: 'Saraf (Neurologi)', disease: 'Abses otak', level: '2', subsection: 'Infeksi' },
  { system: 'Saraf (Neurologi)', disease: 'HIV AIDS tanpa komplikasi', level: '4A', subsection: 'Infeksi' },
  { system: 'Saraf (Neurologi)', disease: 'AIDS dengan komplikasi', level: '3A', subsection: 'Infeksi' },
  { system: 'Saraf (Neurologi)', disease: 'Hidrosefalus', level: '2', subsection: 'Infeksi' },
  { system: 'Saraf (Neurologi)', disease: 'Poliomielitis', level: '3B', subsection: 'Infeksi' },
  { system: 'Saraf (Neurologi)', disease: 'Rabies', level: '3B', subsection: 'Infeksi' },
  { system: 'Saraf (Neurologi)', disease: 'Spondilitis TB', level: '3A', subsection: 'Infeksi' },
  { system: 'Saraf (Neurologi)', disease: 'Tumor primer', level: '2', subsection: 'Tumor Sistem Saraf Pusat' },
  { system: 'Saraf (Neurologi)', disease: 'Tumor sekunder', level: '2', subsection: 'Tumor Sistem Saraf Pusat' },
  { system: 'Saraf (Neurologi)', disease: 'Ensefalopati', level: '3B', subsection: 'Penurunan Kesadaran' },
  { system: 'Saraf (Neurologi)', disease: 'Koma', level: '3B', subsection: 'Penurunan Kesadaran' },
  { system: 'Saraf (Neurologi)', disease: 'Mati batang otak', level: '2', subsection: 'Penurunan Kesadaran' },
  { system: 'Saraf (Neurologi)', disease: 'Tension headache', level: '4A', subsection: 'Nyeri Kepala' },
  { system: 'Saraf (Neurologi)', disease: 'Migren', level: '4A', subsection: 'Nyeri Kepala' },
  { system: 'Saraf (Neurologi)', disease: 'Arteritis kranial', level: '1', subsection: 'Nyeri Kepala' },
  { system: 'Saraf (Neurologi)', disease: 'Neuralgia trigeminal', level: '3A', subsection: 'Nyeri Kepala' },
  { system: 'Saraf (Neurologi)', disease: 'Cluster headache', level: '3A', subsection: 'Nyeri Kepala' },
  { system: 'Saraf (Neurologi)', disease: 'TIA', level: '3B', subsection: 'Penyakit Neurovaskular' },
  { system: 'Saraf (Neurologi)', disease: 'Infark serebral', level: '3B', subsection: 'Penyakit Neurovaskular' },
  { system: 'Saraf (Neurologi)', disease: 'Hematom intraserebral', level: '3B', subsection: 'Penyakit Neurovaskular' },
  { system: 'Saraf (Neurologi)', disease: 'Perdarahan subarakhnoid', level: '3B', subsection: 'Penyakit Neurovaskular' },
  { system: 'Saraf (Neurologi)', disease: 'Ensefalopati hipertensi', level: '3B', subsection: 'Penyakit Neurovaskular' },
  { system: 'Saraf (Neurologi)', disease: 'Bells’ palsy', level: '4A', subsection: 'Lesi Kranial dan Batang Otak' },
  { system: 'Saraf (Neurologi)', disease: 'Lesi batang otak', level: '2', subsection: 'Lesi Kranial dan Batang Otak' },
  { system: 'Saraf (Neurologi)', disease: 'Meniere\'s disease', level: '3A', subsection: 'Gangguan Sistem Vaskular' },
  { system: 'Saraf (Neurologi)', disease: 'Vertigo (Benign paroxysmal positional vertigo)', level: '4A', subsection: 'Gangguan Sistem Vaskular' },
  { system: 'Saraf (Neurologi)', disease: 'Cerebral palsy', level: '2', subsection: 'Gangguan Sistem Vaskular' },
  { system: 'Saraf (Neurologi)', disease: 'Demensia', level: '3A', subsection: 'Defisit Memori' },
  { system: 'Saraf (Neurologi)', disease: 'Penyakit Alzheimer', level: '2', subsection: 'Defisit Memori' },
  { system: 'Saraf (Neurologi)', disease: 'Parkinson', level: '3A', subsection: 'Gangguan Pergerakan' },
  { system: 'Saraf (Neurologi)', disease: 'Gangguan pergerakan lainnya', level: '1', subsection: 'Gangguan Pergerakan' },
  { system: 'Saraf (Neurologi)', disease: 'Kejang', level: '3B', subsection: 'Epilepsi dan Kejang Lainnya' },
  { system: 'Saraf (Neurologi)', disease: 'Epilepsi', level: '3A', subsection: 'Epilepsi dan Kejang Lainnya' },
  { system: 'Saraf (Neurologi)', disease: 'Status epileptikus', level: '3B', subsection: 'Epilepsi dan Kejang Lainnya' },
  { system: 'Saraf (Neurologi)', disease: 'Sklerosis multipel', level: '1', subsection: 'Penyakit Demielinisasi' },
  { system: 'Saraf (Neurologi)', disease: 'Amyotrophic lateral sclerosis (ALS)', level: '1', subsection: 'Penyakit pada Tulang Belakang dan Sumsum Tulang Belakang' },
  { system: 'Saraf (Neurologi)', disease: 'Complete spinal transaction', level: '3B', subsection: 'Penyakit pada Tulang Belakang dan Sumsum Tulang Belakang' },
  { system: 'Saraf (Neurologi)', disease: 'Sindrom kauda equine', level: '2', subsection: 'Penyakit pada Tulang Belakang dan Sumsum Tulang Belakang' },
  { system: 'Saraf (Neurologi)', disease: 'Neurogenic bladder', level: '3A', subsection: 'Penyakit pada Tulang Belakang dan Sumsum Tulang Belakang' },
  { system: 'Saraf (Neurologi)', disease: 'Siringomielia', level: '2', subsection: 'Penyakit pada Tulang Belakang dan Sumsum Tulang Belakang' },
  { system: 'Saraf (Neurologi)', disease: 'Mielopati', level: '2', subsection: 'Penyakit pada Tulang Belakang dan Sumsum Tulang Belakang' },
  { system: 'Saraf (Neurologi)', disease: 'Dorsal root syndrome', level: '2', subsection: 'Penyakit pada Tulang Belakang dan Sumsum Tulang Belakang' },
  { system: 'Saraf (Neurologi)', disease: 'Acute medulla compression', level: '3B', subsection: 'Penyakit pada Tulang Belakang dan Sumsum Tulang Belakang' },
  { system: 'Saraf (Neurologi)', disease: 'Radicular syndrome', level: '3A', subsection: 'Penyakit pada Tulang Belakang dan Sumsum Tulang Belakang' },
  { system: 'Saraf (Neurologi)', disease: 'Hernia nucleus pulposus (HNP)', level: '3A', subsection: 'Penyakit pada Tulang Belakang dan Sumsum Tulang Belakang' },
  { system: 'Saraf (Neurologi)', disease: 'Hematom epidural', level: '2', subsection: 'Trauma' },
  { system: 'Saraf (Neurologi)', disease: 'Hematom subdural', level: '2', subsection: 'Trauma' },
  { system: 'Saraf (Neurologi)', disease: 'Trauma Medula Spinalis', level: '2', subsection: 'Trauma' },
  { system: 'Saraf (Neurologi)', disease: 'Reffered pain', level: '3A', subsection: 'Trauma' },
  { system: 'Saraf (Neurologi)', disease: 'Nyeri neuropatik', level: '3A', subsection: 'Trauma' },
  { system: 'Saraf (Neurologi)', disease: 'Sindrom Horner', level: '2', subsection: 'Penyakit Neuromuskular dan Neuropati' },
  { system: 'Saraf (Neurologi)', disease: 'Carpal tunnel syndrome', level: '3A', subsection: 'Penyakit Neuromuskular dan Neuropati' },
  { system: 'Saraf (Neurologi)', disease: 'Tarsal tunnel syndrome', level: '3A', subsection: 'Penyakit Neuromuskular dan Neuropati' },
  { system: 'Saraf (Neurologi)', disease: 'Neuropati', level: '3A', subsection: 'Penyakit Neuromuskular dan Neuropati' },
  { system: 'Saraf (Neurologi)', disease: 'Peroneal palsy', level: '3A', subsection: 'Penyakit Neuromuskular dan Neuropati' },
  { system: 'Saraf (Neurologi)', disease: 'Guillain Barre syndrome', level: '3B', subsection: 'Penyakit Neuromuskular dan Neuropati' },
  { system: 'Saraf (Neurologi)', disease: 'Miastenia gravis', level: '3B', subsection: 'Penyakit Neuromuskular dan Neuropati' },
  { system: 'Saraf (Neurologi)', disease: 'Polimiositis', level: '1', subsection: 'Penyakit Neuromuskular dan Neuropati' },
  { system: 'Saraf (Neurologi)', disease: 'Neurofibromatosis (Von Recklaing Hausen disease)', level: '2', subsection: 'Penyakit Neuromuskular dan Neuropati' },
  { system: 'Saraf (Neurologi)', disease: 'Amnesia pascatrauma', level: '3A', subsection: 'Gangguan Neurobehaviour' },
  { system: 'Saraf (Neurologi)', disease: 'Afasia', level: '2', subsection: 'Gangguan Neurobehaviour' },
  { system: 'Saraf (Neurologi)', disease: 'Mild Cognitive Impairment (MCI)', level: '2', subsection: 'Gangguan Neurobehaviour' },
  { system: 'Psikiatri', disease: 'Intoksikasi akut zat psikoaktif', level: '3B', subsection: '1 Delirium yang tidak diinduksi oleh alkohol atau zat' },
  { system: 'Psikiatri', disease: 'Adiksi/ketergantungan Narkoba', level: '3A', subsection: '1 Delirium yang tidak diinduksi oleh alkohol atau zat' },
  { system: 'Psikiatri', disease: 'Skizofrenia', level: '3A', subsection: '4 Delirium yang diinduksi oleh alkohol atau zat psikoaktif' },
  { system: 'Psikiatri', disease: 'Gangguan waham', level: '3A', subsection: '4 Delirium yang diinduksi oleh alkohol atau zat psikoaktif' },
  { system: 'Psikiatri', disease: 'Gangguan psikotik', level: '3A', subsection: '4 Delirium yang diinduksi oleh alkohol atau zat psikoaktif' },
  { system: 'Psikiatri', disease: 'Gangguan skizoafektif', level: '3A', subsection: '4 Delirium yang diinduksi oleh alkohol atau zat psikoaktif' },
  { system: 'Psikiatri', disease: 'Gangguan bipolar, episode manik', level: '3A', subsection: '4 Delirium yang diinduksi oleh alkohol atau zat psikoaktif' },
  { system: 'Psikiatri', disease: 'Gangguan bipolar, episode depresif', level: '3A', subsection: '4 Delirium yang diinduksi oleh alkohol atau zat psikoaktif' },
  { system: 'Psikiatri', disease: 'Gangguan siklotimia', level: '2', subsection: '4 Delirium yang diinduksi oleh alkohol atau zat psikoaktif' },
  { system: 'Psikiatri', disease: 'Depresi endogen, episode tunggal dan rekuran', level: '2', subsection: '4 Delirium yang diinduksi oleh alkohol atau zat psikoaktif' },
  { system: 'Psikiatri', disease: 'Gangguan distimia (depresi neurosis)', level: '2', subsection: '4 Delirium yang diinduksi oleh alkohol atau zat psikoaktif' },
  { system: 'Psikiatri', disease: 'Gangguan depresif yang tidak terklasifikasikan', level: '2', subsection: '4 Delirium yang diinduksi oleh alkohol atau zat psikoaktif' },
  { system: 'Psikiatri', disease: 'Baby blues (post-partum depression)', level: '3A', subsection: '4 Delirium yang diinduksi oleh alkohol atau zat psikoaktif' },
  { system: 'Psikiatri', disease: 'Agorafobia dengan/tanpa panik', level: '2', subsection: '4 Delirium yang diinduksi oleh alkohol atau zat psikoaktif' },
  { system: 'Psikiatri', disease: 'Fobia sosial', level: '2', subsection: '4 Delirium yang diinduksi oleh alkohol atau zat psikoaktif' },
  { system: 'Psikiatri', disease: 'Fobia spesifik', level: '2', subsection: '4 Delirium yang diinduksi oleh alkohol atau zat psikoaktif' },
  { system: 'Psikiatri', disease: 'Gangguan panik', level: '3A', subsection: 'Gangguan Cemas Lainnya' },
  { system: 'Psikiatri', disease: 'Gangguan cemas menyeluruh', level: '3A', subsection: 'Gangguan Cemas Lainnya' },
  { system: 'Psikiatri', disease: 'Gangguan campuran cemas depresi', level: '3A', subsection: 'Gangguan Cemas Lainnya' },
  { system: 'Psikiatri', disease: 'Gangguan obsesif-kompulsif', level: '2', subsection: 'Gangguan Cemas Lainnya' },
  { system: 'Psikiatri', disease: 'Reaksi terhadap stres yg berat, & gangguan penyesuaian', level: '2', subsection: 'Gangguan Cemas Lainnya' },
  { system: 'Psikiatri', disease: 'Post traumatic stress disorder', level: '3A', subsection: 'Gangguan Cemas Lainnya' },
  { system: 'Psikiatri', disease: 'Gangguan disosiasi (konversi)', level: '2', subsection: 'Gangguan Cemas Lainnya' },
  { system: 'Psikiatri', disease: 'Gangguan somatoform', level: '4A', subsection: 'Gangguan Cemas Lainnya' },
  { system: 'Psikiatri', disease: 'Trikotilomania', level: '3A', subsection: 'Gangguan Cemas Lainnya' },
  { system: 'Psikiatri', disease: 'Gangguan kepribadian', level: '2', subsection: 'Gangguan Kepribadian dan Perilaku Masa Dewasa' },
  { system: 'Psikiatri', disease: 'Gangguan identitas gender', level: '2', subsection: 'Gangguan Kepribadian dan Perilaku Masa Dewasa' },
  { system: 'Psikiatri', disease: 'Gangguan preferensi seksual', level: '2', subsection: 'Gangguan Kepribadian dan Perilaku Masa Dewasa' },
  { system: 'Psikiatri', disease: 'Gangguan perkembangan pervasif', level: '2', subsection: 'Gangguan Emosional dan Perilaku dengan Onset Khusus pada Masa Anak dan Remaja' },
  { system: 'Psikiatri', disease: 'Retardasi mental', level: '3A', subsection: 'Gangguan Emosional dan Perilaku dengan Onset Khusus pada Masa Anak dan Remaja' },
  { system: 'Psikiatri', disease: '34 Gangguan tingkah laku (conduct disorder)', level: '2', subsection: '33 Gangguan pemusatan perhatian dan hiperaktif' },
  { system: 'Psikiatri', disease: 'Anoreksia nervosa', level: '2', subsection: 'Gangguan Makam' },
  { system: 'Psikiatri', disease: 'Bulimia', level: '2', subsection: 'Gangguan Makam' },
  { system: 'Psikiatri', disease: 'Pica', level: '2', subsection: 'Gangguan Makam' },
  { system: 'Psikiatri', disease: 'Gilles de la tourette syndrome', level: '2', subsection: 'Gangguan Makam' },
  { system: 'Psikiatri', disease: 'Chronic motor of vocal tics disorder', level: '2', subsection: 'Gangguan Makam' },
  { system: 'Psikiatri', disease: 'Transient tics disorder', level: '3A', subsection: 'Gangguan Makam' },
  { system: 'Psikiatri', disease: 'Functional encoperasis', level: '2', subsection: 'Gangguan Ekskresi' },
  { system: 'Psikiatri', disease: 'Functional enuresis', level: '2', subsection: 'Gangguan Ekskresi' },
  { system: 'Psikiatri', disease: 'Uncoordinated speech', level: '2', subsection: 'Gangguan Bicara' },
  { system: 'Psikiatri', disease: 'Parafilia', level: '2', subsection: 'Kelainan dan Disfungsi Seksual' },
  { system: 'Psikiatri', disease: 'Gangguan keinginan dan gairah seksual', level: '3A', subsection: 'Kelainan dan Disfungsi Seksual' },
  { system: 'Psikiatri', disease: 'Insomnia', level: '4A', subsection: 'diparenia) 3A Gangguan Tidur' },
  { system: 'Psikiatri', disease: 'Hipersomnia', level: '3A', subsection: 'diparenia) 3A Gangguan Tidur' },
  { system: 'Psikiatri', disease: 'Sleep-wake cycle disturbance', level: '2', subsection: 'diparenia) 3A Gangguan Tidur' },
  { system: 'Psikiatri', disease: 'Nightmare', level: '2', subsection: 'diparenia) 3A Gangguan Tidur' },
  { system: 'Psikiatri', disease: 'Sleep walking', level: '2', subsection: 'diparenia) 3A Gangguan Tidur' },
  { system: 'Indera', disease: 'Benda asing di konjungtiva', level: '4A', subsection: 'Konjunctiva' },
  { system: 'Indera', disease: 'Konjungtivitis', level: '4A', subsection: 'Konjunctiva' },
  { system: 'Indera', disease: 'Pterigium', level: '3A', subsection: 'Konjunctiva' },
  { system: 'Indera', disease: 'Perdarahan subkonjungtiva', level: '4A', subsection: 'Konjunctiva' },
  { system: 'Indera', disease: 'Mata kering', level: '4A', subsection: 'Konjunctiva' },
  { system: 'Indera', disease: 'Blefaritis', level: '4A', subsection: 'Kelopak Mata' },
  { system: 'Indera', disease: 'Hordeolum', level: '4A', subsection: 'Kelopak Mata' },
  { system: 'Indera', disease: 'Chalazion', level: '3A', subsection: 'Kelopak Mata' },
  { system: 'Indera', disease: 'Laserasi kelopak mata', level: '3B', subsection: 'Kelopak Mata' },
  { system: 'Indera', disease: 'Entropion', level: '2', subsection: 'Kelopak Mata' },
  { system: 'Indera', disease: 'Trikiasis', level: '4A', subsection: 'Kelopak Mata' },
  { system: 'Indera', disease: 'Lagoftalmus', level: '2', subsection: 'Kelopak Mata' },
  { system: 'Indera', disease: 'Epikantus', level: '2', subsection: 'Kelopak Mata' },
  { system: 'Indera', disease: 'Ptosis', level: '2', subsection: 'Kelopak Mata' },
  { system: 'Indera', disease: 'Retraksi kelopak mata', level: '2', subsection: 'Kelopak Mata' },
  { system: 'Indera', disease: 'Xanthelasma', level: '2', subsection: 'Kelopak Mata' },
  { system: 'Indera', disease: 'Dakrioadenitis', level: '3A', subsection: 'Aparatus Lakrimalis' },
  { system: 'Indera', disease: 'Dakriosistitis', level: '3A', subsection: 'Aparatus Lakrimalis' },
  { system: 'Indera', disease: 'Dakriostenosis', level: '2', subsection: 'Aparatus Lakrimalis' },
  { system: 'Indera', disease: 'Laserasi duktus lakrimal', level: '2', subsection: 'Aparatus Lakrimalis' },
  { system: 'Indera', disease: 'Skleritis', level: '3A', subsection: 'Aparatus Lakrimalis' },
  { system: 'Indera', disease: 'Episkleritis', level: '4A', subsection: 'Aparatus Lakrimalis' },
  { system: 'Indera', disease: 'Erosi', level: '2', subsection: 'Kornea' },
  { system: 'Indera', disease: 'Benda asing di kornea', level: '2', subsection: 'Kornea' },
  { system: 'Indera', disease: 'Luka bakar kornea', level: '2', subsection: 'Kornea' },
  { system: 'Indera', disease: 'Keratitis', level: '3A', subsection: 'Kornea' },
  { system: 'Indera', disease: 'Kerato-konjungtivitis sicca', level: '2', subsection: 'Kornea' },
  { system: 'Indera', disease: 'Edema kornea', level: '2', subsection: 'Kornea' },
  { system: 'Indera', disease: 'Keratokonus', level: '2', subsection: 'Kornea' },
  { system: 'Indera', disease: 'Xerophtalmia', level: '3A', subsection: 'Kornea' },
  { system: 'Indera', disease: 'Endoftalmitis', level: '2', subsection: 'Bola Mata' },
  { system: 'Indera', disease: 'Mikroftalmos', level: '2', subsection: 'Bola Mata' },
  { system: 'Indera', disease: 'Hifema', level: '3A', subsection: 'Anterior Chamber' },
  { system: 'Indera', disease: 'Hipopion', level: '3A', subsection: 'Anterior Chamber' },
  { system: 'Indera', disease: 'Perdarahan Vitreous', level: '1', subsection: 'Cairan Vitreous' },
  { system: 'Indera', disease: 'Iridosisklitis, iritis', level: '3A', subsection: 'Iris dan Badan Silier' },
  { system: 'Indera', disease: 'Tumor iris', level: '2', subsection: 'Iris dan Badan Silier' },
  { system: 'Indera', disease: 'Katarak', level: '2', subsection: 'Iris dan Badan Silier' },
  { system: 'Indera', disease: 'Afakia kongenital', level: '2', subsection: 'Iris dan Badan Silier' },
  { system: 'Indera', disease: 'Dislokasi lensa', level: '2', subsection: 'Iris dan Badan Silier' },
  { system: 'Indera', disease: 'Hipermetropia ringan', level: '4A', subsection: 'Akomodasi dan Refraksi' },
  { system: 'Indera', disease: 'Miopia ringan', level: '4A', subsection: 'Akomodasi dan Refraksi' },
  { system: 'Indera', disease: 'Astigmatism ringan', level: '4A', subsection: 'Akomodasi dan Refraksi' },
  { system: 'Indera', disease: 'Presbiopia', level: '4A', subsection: 'Akomodasi dan Refraksi' },
  { system: 'Indera', disease: 'Anisometropia pada dewasa', level: '3A', subsection: 'Akomodasi dan Refraksi' },
  { system: 'Indera', disease: 'Anisometropia pada anak', level: '2', subsection: 'Akomodasi dan Refraksi' },
  { system: 'Indera', disease: 'Ambliopia', level: '2', subsection: 'Akomodasi dan Refraksi' },
  { system: 'Indera', disease: 'Diplopia binokuler', level: '2', subsection: 'Akomodasi dan Refraksi' },
  { system: 'Indera', disease: 'Buta senja', level: '4A', subsection: 'Akomodasi dan Refraksi' },
  { system: 'Indera', disease: 'Skotoma', level: '2', subsection: 'Akomodasi dan Refraksi' },
  { system: 'Indera', disease: 'Hemianopia, bitemporal, and homonymous', level: '2', subsection: 'Akomodasi dan Refraksi' },
  { system: 'Indera', disease: 'Gangguan lapang pandang', level: '2', subsection: 'Akomodasi dan Refraksi' },
  { system: 'Indera', disease: 'Ablasio retina', level: '2', subsection: 'Akomodasi dan Refraksi' },
  { system: 'Indera', disease: 'Perdarahan retina, oklusi pembuluh darah retina', level: '2', subsection: 'Akomodasi dan Refraksi' },
  { system: 'Indera', disease: 'Degenerasi makula karena usia', level: '2', subsection: 'Akomodasi dan Refraksi' },
  { system: 'Indera', disease: 'Retinopati (diabetik, hipertensi, prematur)', level: '2', subsection: 'Akomodasi dan Refraksi' },
  { system: 'Indera', disease: 'Korioretinitis', level: '1', subsection: 'Akomodasi dan Refraksi' },
  { system: 'Indera', disease: 'Optic disc cupping', level: '2', subsection: 'Diskus Optik dan Saraf Mata' },
  { system: 'Indera', disease: 'Edema papil', level: '2', subsection: 'Diskus Optik dan Saraf Mata' },
  { system: 'Indera', disease: 'Atrofi optik', level: '2', subsection: 'Diskus Optik dan Saraf Mata' },
  { system: 'Indera', disease: 'Neuropati optik', level: '2', subsection: 'Diskus Optik dan Saraf Mata' },
  { system: 'Indera', disease: 'Neuritis optik', level: '2', subsection: 'Diskus Optik dan Saraf Mata' },
  { system: 'Indera', disease: 'Glaukoma akut', level: '3B', subsection: 'Glaukoma' },
  { system: 'Indera', disease: 'Glaukoma lainnya', level: '3A', subsection: 'Glaukoma' },
  { system: 'Indera', disease: 'Tuli (kongenital, perseptif, konduktif)', level: '2', subsection: 'Telinga, Pendengaran, dan Keseimbangan' },
  { system: 'Indera', disease: 'Inflamasi pada aurikular', level: '3A', subsection: 'Telinga, Pendengaran, dan Keseimbangan' },
  { system: 'Indera', disease: 'Herpes zoster pada telinga', level: '3A', subsection: 'Telinga, Pendengaran, dan Keseimbangan' },
  { system: 'Indera', disease: 'Fistula pre-aurikular', level: '3A', subsection: 'Telinga, Pendengaran, dan Keseimbangan' },
  { system: 'Indera', disease: 'Labirintitis', level: '2', subsection: 'Telinga, Pendengaran, dan Keseimbangan' },
  { system: 'Indera', disease: 'Otitis eksterna', level: '4A', subsection: 'Telinga, Pendengaran, dan Keseimbangan' },
  { system: 'Indera', disease: 'Otitis media akut', level: '4A', subsection: 'Telinga, Pendengaran, dan Keseimbangan' },
  { system: 'Indera', disease: 'Otitis media serosa', level: '3A', subsection: 'Telinga, Pendengaran, dan Keseimbangan' },
  { system: 'Indera', disease: 'Otitis media kronik', level: '3A', subsection: 'Telinga, Pendengaran, dan Keseimbangan' },
  { system: 'Indera', disease: 'Mastoiditis', level: '3A', subsection: 'Telinga, Pendengaran, dan Keseimbangan' },
  { system: 'Indera', disease: 'Miringitis bullosa', level: '3A', subsection: 'Telinga, Pendengaran, dan Keseimbangan' },
  { system: 'Indera', disease: 'Benda asing', level: '3A', subsection: 'Telinga, Pendengaran, dan Keseimbangan' },
  { system: 'Indera', disease: 'Perforasi membran timpani', level: '3A', subsection: 'Telinga, Pendengaran, dan Keseimbangan' },
  { system: 'Indera', disease: 'Otosklerosis', level: '3A', subsection: 'Telinga, Pendengaran, dan Keseimbangan' },
  { system: 'Indera', disease: 'Timpanosklerosis', level: '2', subsection: 'Telinga, Pendengaran, dan Keseimbangan' },
  { system: 'Indera', disease: 'Kolesteatoma', level: '1', subsection: 'Telinga, Pendengaran, dan Keseimbangan' },
  { system: 'Indera', disease: 'Presbiakusis', level: '3A', subsection: 'Telinga, Pendengaran, dan Keseimbangan' },
  { system: 'Indera', disease: 'Serumen prop', level: '4A', subsection: 'Telinga, Pendengaran, dan Keseimbangan' },
  { system: 'Indera', disease: 'Mabuk perjalanan', level: '4A', subsection: 'Telinga, Pendengaran, dan Keseimbangan' },
  { system: 'Indera', disease: 'Trauma akustik akut', level: '3A', subsection: 'Telinga, Pendengaran, dan Keseimbangan' },
  { system: 'Indera', disease: 'Trauma aurikular', level: '3B', subsection: 'Telinga, Pendengaran, dan Keseimbangan' },
  { system: 'Indera', disease: 'Deviasi septum hidung', level: '2', subsection: 'HIDUNG Hidung dan Sinus Hidung' },
  { system: 'Indera', disease: 'Furunkel pada hidung', level: '4A', subsection: 'HIDUNG Hidung dan Sinus Hidung' },
  { system: 'Indera', disease: 'Rhinitis akut', level: '4A', subsection: 'HIDUNG Hidung dan Sinus Hidung' },
  { system: 'Indera', disease: 'Rhinitis vasomotor', level: '4A', subsection: 'HIDUNG Hidung dan Sinus Hidung' },
  { system: 'Indera', disease: 'Rhinitis alergika', level: '4A', subsection: 'HIDUNG Hidung dan Sinus Hidung' },
  { system: 'Indera', disease: 'Rhinitis kronik', level: '3A', subsection: 'HIDUNG Hidung dan Sinus Hidung' },
  { system: 'Indera', disease: 'Rhinitis medikamentosa', level: '3A', subsection: 'HIDUNG Hidung dan Sinus Hidung' },
  { system: 'Indera', disease: 'Sinusitis', level: '3A', subsection: 'HIDUNG Hidung dan Sinus Hidung' },
  { system: 'Indera', disease: 'Sinusitis frontal akut', level: '2', subsection: 'HIDUNG Hidung dan Sinus Hidung' },
  { system: 'Indera', disease: 'Sinusitis maksilaris akut', level: '2', subsection: 'HIDUNG Hidung dan Sinus Hidung' },
  { system: 'Indera', disease: 'Sinusitis kronik', level: '3A', subsection: 'HIDUNG Hidung dan Sinus Hidung' },
  { system: 'Indera', disease: 'Benda asing', level: '4A', subsection: 'HIDUNG Hidung dan Sinus Hidung' },
  { system: 'Indera', disease: 'Epistaksis', level: '4A', subsection: 'HIDUNG Hidung dan Sinus Hidung' },
  { system: 'Indera', disease: 'Etmoiditis akut', level: '1', subsection: 'HIDUNG Hidung dan Sinus Hidung' },
  { system: 'Indera', disease: 'Polip', level: '2', subsection: 'HIDUNG Hidung dan Sinus Hidung' },
  { system: 'Indera', disease: 'Fistula dan kista brankial lateral dan medial', level: '2', subsection: 'Kepala dan Leher' },
  { system: 'Indera', disease: 'Higroma kistik', level: '2', subsection: 'Kepala dan Leher' },
  { system: 'Indera', disease: 'Tortikolis', level: '3A', subsection: 'Kepala dan Leher' },
  { system: 'Indera', disease: 'Abses Bezold', level: '3A', subsection: 'Kepala dan Leher' },
  { system: 'Respirasi', disease: 'Influenza', level: '4A', subsection: null },
  { system: 'Respirasi', disease: 'Pertusis', level: '4A', subsection: null },
  { system: 'Respirasi', disease: 'Acute Respiratory distress syndrome (ARDS)', level: '3B', subsection: null },
  { system: 'Respirasi', disease: 'SARS', level: '3B', subsection: null },
  { system: 'Respirasi', disease: 'Flu burung', level: '3B', subsection: null },
  { system: 'Respirasi', disease: 'Faringitis', level: '4A', subsection: 'Laring dan Faring' },
  { system: 'Respirasi', disease: 'Tonsilitis', level: '4A', subsection: 'Laring dan Faring' },
  { system: 'Respirasi', disease: 'Laringitis', level: '4A', subsection: 'Laring dan Faring' },
  { system: 'Respirasi', disease: 'Hipertrofi adenoid', level: '2', subsection: 'Laring dan Faring' },
  { system: 'Respirasi', disease: 'Abses peritonsilar', level: '3A', subsection: 'Laring dan Faring' },
  { system: 'Respirasi', disease: 'Pseudo-croop acute epiglotitis', level: '3A', subsection: 'Laring dan Faring' },
  { system: 'Respirasi', disease: 'Difteria (THT)', level: '3B', subsection: 'Laring dan Faring' },
  { system: 'Respirasi', disease: 'Karsinoma laring', level: '2', subsection: 'Laring dan Faring' },
  { system: 'Respirasi', disease: 'Karsinoma nasofaring', level: '2', subsection: 'Laring dan Faring' },
  { system: 'Respirasi', disease: 'Trakeitis', level: '2', subsection: 'Trakea' },
  { system: 'Respirasi', disease: 'Aspirasi', level: '3B', subsection: 'Trakea' },
  { system: 'Respirasi', disease: 'Benda asing', level: '2', subsection: 'Trakea' },
  { system: 'Respirasi', disease: 'Asma bronkial', level: '4A', subsection: 'Trakea' },
  { system: 'Respirasi', disease: 'Status asmatikus (asma akut berat)', level: '3B', subsection: 'Trakea' },
  { system: 'Respirasi', disease: 'Bronkitis akut', level: '4A', subsection: 'Trakea' },
  { system: 'Respirasi', disease: 'Bronkiolitis akut', level: '3B', subsection: 'Trakea' },
  { system: 'Respirasi', disease: 'Bronkiektasis', level: '3A', subsection: 'Trakea' },
  { system: 'Respirasi', disease: 'Displasia bronkopulmonar', level: '1', subsection: 'Trakea' },
  { system: 'Respirasi', disease: 'Karsinoma paru', level: '2', subsection: 'Trakea' },
  { system: 'Respirasi', disease: 'Pneumonia, bronkopneumonia', level: '4A', subsection: 'Trakea' },
  { system: 'Respirasi', disease: 'Pneumonia aspirasi', level: '3B', subsection: 'Trakea' },
  { system: 'Respirasi', disease: 'Tuberkulosis paru tanpa komplikasi', level: '4A', subsection: 'Trakea' },
  { system: 'Respirasi', disease: 'Tuberkulosis dengan HIV', level: '3A', subsection: 'Trakea' },
  { system: 'Respirasi', disease: 'Multi Drug Resistance (MDR) TB', level: '2', subsection: 'Trakea' },
  { system: 'Respirasi', disease: 'Pneumothorax ventil', level: '3A', subsection: 'Trakea' },
  { system: 'Respirasi', disease: 'Pneumothorax', level: '3A', subsection: 'Trakea' },
  { system: 'Respirasi', disease: 'Efusi pleura', level: '2', subsection: 'Trakea' },
  { system: 'Respirasi', disease: 'Efusi pleura masif', level: '3B', subsection: 'Trakea' },
  { system: 'Respirasi', disease: 'Emfisema paru', level: '3A', subsection: 'Trakea' },
  { system: 'Respirasi', disease: 'Atelektasis', level: '2', subsection: 'KONSIL KEDOKTERAN INDONESIA' },
  { system: 'Respirasi', disease: 'Edema paru', level: '3B', subsection: '36 Penyakit Paru Obstruksi Kronik (PPOK) eksaserbasi' },
  { system: 'Respirasi', disease: 'Infark paru', level: '1', subsection: '36 Penyakit Paru Obstruksi Kronik (PPOK) eksaserbasi' },
  { system: 'Respirasi', disease: 'Abses paru', level: '3A', subsection: '36 Penyakit Paru Obstruksi Kronik (PPOK) eksaserbasi' },
  { system: 'Respirasi', disease: 'Emboli paru', level: '1', subsection: '36 Penyakit Paru Obstruksi Kronik (PPOK) eksaserbasi' },
  { system: 'Respirasi', disease: 'Kistik fibrosis', level: '1', subsection: '36 Penyakit Paru Obstruksi Kronik (PPOK) eksaserbasi' },
  { system: 'Respirasi', disease: 'Haematothorax', level: '3B', subsection: '36 Penyakit Paru Obstruksi Kronik (PPOK) eksaserbasi' },
  { system: 'Respirasi', disease: 'Tumor mediastinum', level: '2', subsection: '36 Penyakit Paru Obstruksi Kronik (PPOK) eksaserbasi' },
  { system: 'Respirasi', disease: 'Pnemokoniasis', level: '2', subsection: '36 Penyakit Paru Obstruksi Kronik (PPOK) eksaserbasi' },
  { system: 'Respirasi', disease: 'Penyakit paru intersisial', level: '1', subsection: '36 Penyakit Paru Obstruksi Kronik (PPOK) eksaserbasi' },
  { system: 'Respirasi', disease: 'Obstructive Sleep Apnea (OSA)', level: '1', subsection: '36 Penyakit Paru Obstruksi Kronik (PPOK) eksaserbasi' },
  { system: 'Kardiovaskular', disease: '3 Syok (septik, hipovolemik, kardiogenik, neurogenik)', level: '3B', subsection: '2 Radang pada dinding jantung (Endokarditis,' },
  { system: 'Kardiovaskular', disease: 'Angina pektoris', level: '3B', subsection: '2 Radang pada dinding jantung (Endokarditis,' },
  { system: 'Kardiovaskular', disease: 'Infark miokard', level: '3B', subsection: '2 Radang pada dinding jantung (Endokarditis,' },
  { system: 'Kardiovaskular', disease: 'Gagal jantung akut', level: '3B', subsection: '2 Radang pada dinding jantung (Endokarditis,' },
  { system: 'Kardiovaskular', disease: 'Gagal jantung kronik', level: '3A', subsection: '2 Radang pada dinding jantung (Endokarditis,' },
  { system: 'Kardiovaskular', disease: 'Takikardi: supraventrikular, ventrikular', level: '3B', subsection: '2' },
  { system: 'Kardiovaskular', disease: 'Fibrilasi atrial', level: '3A', subsection: '2' },
  { system: 'Kardiovaskular', disease: 'Fibrilasi ventrikular', level: '3B', subsection: '2' },
  { system: 'Kardiovaskular', disease: 'Atrial flutter', level: '3B', subsection: '2' },
  { system: 'Kardiovaskular', disease: 'Ekstrasistol supraventrikular, ventrikular', level: '3A', subsection: '2' },
  { system: 'Kardiovaskular', disease: 'Bundle Branch Block', level: '2', subsection: '2' },
  { system: 'Kardiovaskular', disease: 'Aritmia lainnya', level: '2', subsection: '2' },
  { system: 'Kardiovaskular', disease: 'Kardiomiopati', level: '2', subsection: '2' },
  { system: 'Kardiovaskular', disease: 'Kor pulmonale akut', level: '3B', subsection: '2' },
  { system: 'Kardiovaskular', disease: 'Kor pulmonale kronik', level: '3A', subsection: '2' },
  { system: 'Kardiovaskular', disease: 'Hipertensi esensial', level: '4A', subsection: 'Gangguan Aorta dan Arteri' },
  { system: 'Kardiovaskular', disease: 'Hipertensi sekunder', level: '3A', subsection: 'Gangguan Aorta dan Arteri' },
  { system: 'Kardiovaskular', disease: 'Hipertensi pulmoner', level: '1', subsection: 'Gangguan Aorta dan Arteri' },
  { system: 'Kardiovaskular', disease: 'Penyakit Raynaud', level: '2', subsection: 'Gangguan Aorta dan Arteri' },
  { system: 'Kardiovaskular', disease: 'Trombosis arteri', level: '2', subsection: 'Gangguan Aorta dan Arteri' },
  { system: 'Kardiovaskular', disease: 'Koarktasio aorta', level: '1', subsection: 'Gangguan Aorta dan Arteri' },
  { system: 'Kardiovaskular', disease: 'Penyakit Buerger\'s (Thromboangiitis Obliterans)', level: '2', subsection: 'Gangguan Aorta dan Arteri' },
  { system: 'Kardiovaskular', disease: 'Emboli arteri', level: '1', subsection: 'Gangguan Aorta dan Arteri' },
  { system: 'Kardiovaskular', disease: 'Aterosklerosis', level: '1', subsection: 'Gangguan Aorta dan Arteri' },
  { system: 'Kardiovaskular', disease: 'Subclavian steal syndrome', level: '1', subsection: 'Gangguan Aorta dan Arteri' },
  { system: 'Kardiovaskular', disease: 'Aneurisma Aorta', level: '1', subsection: 'Gangguan Aorta dan Arteri' },
  { system: 'Kardiovaskular', disease: 'Aneurisma diseksi', level: '1', subsection: 'Gangguan Aorta dan Arteri' },
  { system: 'Kardiovaskular', disease: 'Klaudikasio', level: '2', subsection: 'Gangguan Aorta dan Arteri' },
  { system: 'Kardiovaskular', disease: 'Penyakit jantung reumatik', level: '2', subsection: 'Gangguan Aorta dan Arteri' },
  { system: 'Kardiovaskular', disease: 'Tromboflebitis', level: '3A', subsection: 'Vena dan Pembuluh Limfe' },
  { system: 'Kardiovaskular', disease: 'Limfangitis', level: '3A', subsection: 'Vena dan Pembuluh Limfe' },
  { system: 'Kardiovaskular', disease: 'Varises (primer, sekunder)', level: '2', subsection: 'Vena dan Pembuluh Limfe' },
  { system: 'Kardiovaskular', disease: 'Obstructed venous return', level: '2', subsection: 'Vena dan Pembuluh Limfe' },
  { system: 'Kardiovaskular', disease: 'Trombosis vena dalam', level: '2', subsection: 'Vena dan Pembuluh Limfe' },
  { system: 'Kardiovaskular', disease: 'Emboli vena', level: '2', subsection: 'Vena dan Pembuluh Limfe' },
  { system: 'Kardiovaskular', disease: 'Limfedema (primer, sekunder)', level: '3A', subsection: 'Vena dan Pembuluh Limfe' },
  { system: 'Kardiovaskular', disease: 'Insufisiensi vena kronik', level: '3A', subsection: 'Vena dan Pembuluh Limfe' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Sumbing pada bibir dan palatum', level: '2', subsection: null },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Micrognatia and macrognatia', level: '2', subsection: null },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Kandidiasis mulut', level: '4A', subsection: null },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Ulkus mulut (aptosa, herpes)', level: '4A', subsection: null },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Glositis', level: '3A', subsection: null },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Leukoplakia', level: '2', subsection: null },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Angina Ludwig', level: '3A', subsection: null },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Parotitis', level: '4A', subsection: null },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Karies gigi', level: '3A', subsection: null },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Atresia esofagus', level: '2', subsection: 'Esofagus' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Akalasia', level: '2', subsection: 'Esofagus' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Esofagitis refluks', level: '3A', subsection: 'Esofagus' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Lesi korosif pada esofagus', level: '3B', subsection: 'Esofagus' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Varises esofagus', level: '2', subsection: 'Esofagus' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Ruptur esofagus', level: '1', subsection: 'Esofagus' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Hernia (diaframatika, hiatus)', level: '2', subsection: 'irreponibilis 2 17 Hernia (inguinalis, femoralis, skrotalis) strangulata,' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Hernia umbilikalis', level: '3A', subsection: 'irreponibilis 2 17 Hernia (inguinalis, femoralis, skrotalis) strangulata,' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Peritonitis', level: '3B', subsection: 'irreponibilis 2 17 Hernia (inguinalis, femoralis, skrotalis) strangulata,' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Perforasi usus', level: '2', subsection: 'irreponibilis 2 17 Hernia (inguinalis, femoralis, skrotalis) strangulata,' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Malrotasi traktus gastro-intestinal', level: '2', subsection: 'irreponibilis 2 17 Hernia (inguinalis, femoralis, skrotalis) strangulata,' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Infeksi pada umbilikus', level: '4A', subsection: 'irreponibilis 2 17 Hernia (inguinalis, femoralis, skrotalis) strangulata,' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Sindrom Reye', level: '1', subsection: 'irreponibilis 2 17 Hernia (inguinalis, femoralis, skrotalis) strangulata,' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Gastritis', level: '4A', subsection: 'Lambung, Duodenum, Jejunum, Ileum' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Gastroenteritis (termasuk kolera, giardiasis)', level: '4A', subsection: 'Lambung, Duodenum, Jejunum, Ileum' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Refluks gastroesofagus', level: '4A', subsection: 'Lambung, Duodenum, Jejunum, Ileum' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Ulkus (gaster, duodenum)', level: '3A', subsection: 'Lambung, Duodenum, Jejunum, Ileum' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Stenosis pilorik', level: '2', subsection: 'Lambung, Duodenum, Jejunum, Ileum' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Atresia intestinal', level: '2', subsection: 'Lambung, Duodenum, Jejunum, Ileum' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Divertikulum Meckel', level: '2', subsection: 'Lambung, Duodenum, Jejunum, Ileum' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Fistula umbilikal, omphalocoele-gastroschisis', level: '2', subsection: 'Lambung, Duodenum, Jejunum, Ileum' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Apendisitis akut', level: '3B', subsection: 'Lambung, Duodenum, Jejunum, Ileum' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Abses apendiks', level: '3B', subsection: 'KONSIL KEDOKTERAN INDONESIA' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Demam tifoid', level: '4A', subsection: 'KONSIL KEDOKTERAN INDONESIA' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Perdarahan gastrointestinal', level: '3B', subsection: 'KONSIL KEDOKTERAN INDONESIA' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Ileus', level: '2', subsection: 'KONSIL KEDOKTERAN INDONESIA' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Malabsorbsi', level: '3A', subsection: 'KONSIL KEDOKTERAN INDONESIA' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Intoleransi makanan', level: '4A', subsection: 'KONSIL KEDOKTERAN INDONESIA' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Alergi makanan', level: '4A', subsection: 'KONSIL KEDOKTERAN INDONESIA' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Keracunan makanan', level: '4A', subsection: 'KONSIL KEDOKTERAN INDONESIA' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Botulisme', level: '3B', subsection: 'KONSIL KEDOKTERAN INDONESIA' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Penyakit cacing tambang', level: '4A', subsection: 'Infestasi Cacing dan Lainnya' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Strongiloidiasis', level: '4A', subsection: 'Infestasi Cacing dan Lainnya' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Askariasis', level: '4A', subsection: 'Infestasi Cacing dan Lainnya' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Skistosomiasis', level: '4A', subsection: 'Infestasi Cacing dan Lainnya' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Taeniasis', level: '4A', subsection: 'Infestasi Cacing dan Lainnya' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Pes', level: '1', subsection: 'Infestasi Cacing dan Lainnya' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Hepatitis A', level: '4A', subsection: 'Infestasi Cacing dan Lainnya' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Hepatitis B', level: '3A', subsection: 'Infestasi Cacing dan Lainnya' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Hepatitis C', level: '2', subsection: 'Infestasi Cacing dan Lainnya' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Abses hepar amoeba', level: '3A', subsection: 'Infestasi Cacing dan Lainnya' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Perlemakan hepar', level: '3A', subsection: 'Infestasi Cacing dan Lainnya' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Sirosis hepatis', level: '2', subsection: 'Infestasi Cacing dan Lainnya' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Gagal hepar', level: '2', subsection: 'Infestasi Cacing dan Lainnya' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Neoplasma hepar', level: '2', subsection: 'Infestasi Cacing dan Lainnya' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Kolesistitis', level: '3B', subsection: 'Kandung Empedu, Saluran Empedu, dan Pankreas' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Kole(doko)litiasis', level: '2', subsection: 'Kandung Empedu, Saluran Empedu, dan Pankreas' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Empiema dan hidrops kandung empedu', level: '2', subsection: 'Kandung Empedu, Saluran Empedu, dan Pankreas' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Atresia biliaris', level: '2', subsection: 'Kandung Empedu, Saluran Empedu, dan Pankreas' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Pankreatitis', level: '2', subsection: 'Kandung Empedu, Saluran Empedu, dan Pankreas' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Karsinoma pankreas', level: '2', subsection: 'Kandung Empedu, Saluran Empedu, dan Pankreas' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Divertikulosis/divertikulitis', level: '3A', subsection: 'Kandung Empedu, Saluran Empedu, dan Pankreas' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Kolitis', level: '3A', subsection: 'Kandung Empedu, Saluran Empedu, dan Pankreas' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Disentri basiler, disentri amuba', level: '4A', subsection: 'Kandung Empedu, Saluran Empedu, dan Pankreas' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Penyakit Crohn', level: '1', subsection: 'Kandung Empedu, Saluran Empedu, dan Pankreas' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Kolitis ulseratif', level: '1', subsection: 'Kandung Empedu, Saluran Empedu, dan Pankreas' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Irritable Bowel Syndrome', level: '3A', subsection: 'Kandung Empedu, Saluran Empedu, dan Pankreas' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Polip/adenoma', level: '2', subsection: 'Kandung Empedu, Saluran Empedu, dan Pankreas' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Karsinoma kolon', level: '2', subsection: 'Kandung Empedu, Saluran Empedu, dan Pankreas' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Penyakit Hirschsprung', level: '2', subsection: 'Kandung Empedu, Saluran Empedu, dan Pankreas' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Enterokolitis nekrotik', level: '1', subsection: 'Kandung Empedu, Saluran Empedu, dan Pankreas' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Intususepsi atau invaginasi', level: '3B', subsection: 'Kandung Empedu, Saluran Empedu, dan Pankreas' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Atresia anus', level: '2', subsection: 'Kandung Empedu, Saluran Empedu, dan Pankreas' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Proktitis', level: '3A', subsection: 'Kandung Empedu, Saluran Empedu, dan Pankreas' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Abses (peri)anal', level: '3A', subsection: 'Kandung Empedu, Saluran Empedu, dan Pankreas' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Hemoroid grade 1-2', level: '4A', subsection: 'Kandung Empedu, Saluran Empedu, dan Pankreas' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Hemoroid grade 3-4', level: '3A', subsection: 'Kandung Empedu, Saluran Empedu, dan Pankreas' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Fistula', level: '2', subsection: 'Kandung Empedu, Saluran Empedu, dan Pankreas' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Fisura anus', level: '2', subsection: 'Kandung Empedu, Saluran Empedu, dan Pankreas' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Prolaps rektum, anus', level: '3A', subsection: 'Kandung Empedu, Saluran Empedu, dan Pankreas' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Limfoma', level: '2', subsection: 'Neoplasma Gastrointestinal' },
  { system: 'Gastrointestinal & Hepatobilier', disease: 'Gastrointestinal Stromal Tumor (GIST)', level: '2', subsection: 'Neoplasma Gastrointestinal' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Infeksi saluran kemih', level: '4A', subsection: null },
  { system: 'Ginjal & Saluran Kemih', disease: 'Glomerulonefritis akut', level: '3A', subsection: null },
  { system: 'Ginjal & Saluran Kemih', disease: 'Glomerulonefritis kronik', level: '3A', subsection: null },
  { system: 'Ginjal & Saluran Kemih', disease: 'Gonore', level: '4A', subsection: null },
  { system: 'Ginjal & Saluran Kemih', disease: 'Karsinoma sel renal', level: '2', subsection: null },
  { system: 'Ginjal & Saluran Kemih', disease: 'Tumor Wilms', level: '2', subsection: null },
  { system: 'Ginjal & Saluran Kemih', disease: 'Acute kidney injury', level: '2', subsection: null },
  { system: 'Ginjal & Saluran Kemih', disease: 'Penyakit ginjal kronik', level: '2', subsection: null },
  { system: 'Ginjal & Saluran Kemih', disease: 'Sindrom nefrotik', level: '2', subsection: null },
  { system: 'Ginjal & Saluran Kemih', disease: 'Kolik renal', level: '3A', subsection: null },
  { system: 'Ginjal & Saluran Kemih', disease: 'Ginjal polikistik simtomatik', level: '2', subsection: '11 Batu saluran kemih (vesika urinaria, ureter, uretra )' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Ginjal tapal kuda', level: '1', subsection: '11 Batu saluran kemih (vesika urinaria, ureter, uretra )' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Pielonefritis tanpa komplikasi', level: '4A', subsection: '11 Batu saluran kemih (vesika urinaria, ureter, uretra )' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Nekrosis tubular akut', level: '2', subsection: '11 Batu saluran kemih (vesika urinaria, ureter, uretra )' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Hipospadia', level: '2', subsection: 'Alat Kelamin Pria' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Epispadia', level: '2', subsection: 'Alat Kelamin Pria' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Testis tidak turun/ kriptorkidismus', level: '2', subsection: 'Alat Kelamin Pria' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Rectratile testis', level: '2', subsection: 'Alat Kelamin Pria' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Varikokel', level: '2', subsection: 'Alat Kelamin Pria' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Hidrokel', level: '2', subsection: 'Alat Kelamin Pria' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Fimosis', level: '4A', subsection: 'Alat Kelamin Pria' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Parafimosis', level: '4A', subsection: 'Alat Kelamin Pria' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Spermatokel', level: '2', subsection: 'Alat Kelamin Pria' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Epididimitis', level: '2', subsection: 'Alat Kelamin Pria' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Prostatitis', level: '3A', subsection: 'Alat Kelamin Pria' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Torsio testis', level: '3B', subsection: 'Alat Kelamin Pria' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Ruptur uretra', level: '3B', subsection: 'Alat Kelamin Pria' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Ruptur kandung kencing', level: '3B', subsection: 'Alat Kelamin Pria' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Ruptur ginjal', level: '3B', subsection: 'Alat Kelamin Pria' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Karsinoma uroterial', level: '2', subsection: 'Alat Kelamin Pria' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Seminoma testis', level: '1', subsection: 'Alat Kelamin Pria' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Teratoma testis', level: '1', subsection: 'Alat Kelamin Pria' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Hiperplasia prostat jinak', level: '2', subsection: 'Alat Kelamin Pria' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Karsinoma prostat', level: '2', subsection: 'Alat Kelamin Pria' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Striktura uretra', level: '2', subsection: 'Alat Kelamin Pria' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Priapismus', level: '3B', subsection: 'Alat Kelamin Pria' },
  { system: 'Ginjal & Saluran Kemih', disease: 'Chancroid', level: '3A', subsection: 'Alat Kelamin Pria' },
  { system: 'Reproduksi & Obstetri', disease: 'Sifilis', level: '3A', subsection: 'Infeksi' },
  { system: 'Reproduksi & Obstetri', disease: 'Toksoplasmosis', level: '2', subsection: 'Infeksi' },
  { system: 'Reproduksi & Obstetri', disease: 'Infeksi virus Herpes tipe', level: '2', subsection: '3 Sindrom duh (discharge) genital (gonore dan' },
  { system: 'Reproduksi & Obstetri', disease: '5 Infeksi saluran kemih bagian bawah', level: '4A', subsection: '3 Sindrom duh (discharge) genital (gonore dan' },
  { system: 'Reproduksi & Obstetri', disease: 'Vulvitis', level: '4A', subsection: '3 Sindrom duh (discharge) genital (gonore dan' },
  { system: 'Reproduksi & Obstetri', disease: 'Kondiloma akuminatum', level: '3A', subsection: '3 Sindrom duh (discharge) genital (gonore dan' },
  { system: 'Reproduksi & Obstetri', disease: 'Vaginitis', level: '4A', subsection: '3 Sindrom duh (discharge) genital (gonore dan' },
  { system: 'Reproduksi & Obstetri', disease: 'Vaginosis bakterialis', level: '4A', subsection: '3 Sindrom duh (discharge) genital (gonore dan' },
  { system: 'Reproduksi & Obstetri', disease: 'Servisitis', level: '3A', subsection: '3 Sindrom duh (discharge) genital (gonore dan' },
  { system: 'Reproduksi & Obstetri', disease: 'Salpingitis', level: '4A', subsection: '3 Sindrom duh (discharge) genital (gonore dan' },
  { system: 'Reproduksi & Obstetri', disease: 'Abses tubo-ovarium', level: '3B', subsection: '3 Sindrom duh (discharge) genital (gonore dan' },
  { system: 'Reproduksi & Obstetri', disease: 'Penyakit radang panggul', level: '3A', subsection: '3 Sindrom duh (discharge) genital (gonore dan' },
  { system: 'Reproduksi & Obstetri', disease: 'Kehamilan normal', level: '4A', subsection: 'Kehamilan' },
  { system: 'Reproduksi & Obstetri', disease: 'Infeksi intra-uterin: korioamnionitis', level: '3A', subsection: 'Gangguan pada Kehamilan' },
  { system: 'Reproduksi & Obstetri', disease: 'Infeksi pada kehamilan: TORCH, hepatitis B, malaria', level: '3B', subsection: 'Gangguan pada Kehamilan' },
  { system: 'Reproduksi & Obstetri', disease: 'Aborsi mengancam', level: '3B', subsection: 'Gangguan pada Kehamilan' },
  { system: 'Reproduksi & Obstetri', disease: 'Aborsi spontan inkomplit', level: '3B', subsection: 'Gangguan pada Kehamilan' },
  { system: 'Reproduksi & Obstetri', disease: 'Aborsi spontan komplit', level: '4A', subsection: 'Gangguan pada Kehamilan' },
  { system: 'Reproduksi & Obstetri', disease: 'Hiperemesis gravidarum', level: '3B', subsection: 'Gangguan pada Kehamilan' },
  { system: 'Reproduksi & Obstetri', disease: 'Inkompatibilitas darah', level: '2', subsection: 'Gangguan pada Kehamilan' },
  { system: 'Reproduksi & Obstetri', disease: 'Mola hidatidosa', level: '2', subsection: 'Gangguan pada Kehamilan' },
  { system: 'Reproduksi & Obstetri', disease: 'Hipertensi pada kehamilan', level: '2', subsection: 'Gangguan pada Kehamilan' },
  { system: 'Reproduksi & Obstetri', disease: 'Preeklampsia', level: '3B', subsection: 'Gangguan pada Kehamilan' },
  { system: 'Reproduksi & Obstetri', disease: 'Eklampsia', level: '3B', subsection: 'Gangguan pada Kehamilan' },
  { system: 'Reproduksi & Obstetri', disease: 'Diabetes gestasional', level: '2', subsection: 'Gangguan pada Kehamilan' },
  { system: 'Reproduksi & Obstetri', disease: 'Kehamilan posterm', level: '2', subsection: 'Gangguan pada Kehamilan' },
  { system: 'Reproduksi & Obstetri', disease: 'Insufisiensi plasenta', level: '2', subsection: 'Gangguan pada Kehamilan' },
  { system: 'Reproduksi & Obstetri', disease: 'Plasenta previa', level: '2', subsection: 'Gangguan pada Kehamilan' },
  { system: 'Reproduksi & Obstetri', disease: 'Vasa previa', level: '2', subsection: 'Gangguan pada Kehamilan' },
  { system: 'Reproduksi & Obstetri', disease: 'Abrupsio plasenta', level: '2', subsection: 'Gangguan pada Kehamilan' },
  { system: 'Reproduksi & Obstetri', disease: 'Inkompeten serviks', level: '2', subsection: 'Gangguan pada Kehamilan' },
  { system: 'Reproduksi & Obstetri', disease: 'Polihidramnion', level: '2', subsection: 'Gangguan pada Kehamilan' },
  { system: 'Reproduksi & Obstetri', disease: 'Kelainan letak janin setelah 36 minggu', level: '2', subsection: 'Gangguan pada Kehamilan' },
  { system: 'Reproduksi & Obstetri', disease: 'Kehamilan ganda', level: '2', subsection: 'Gangguan pada Kehamilan' },
  { system: 'Reproduksi & Obstetri', disease: 'Janin tumbuh lambat', level: '3A', subsection: 'Gangguan pada Kehamilan' },
  { system: 'Reproduksi & Obstetri', disease: 'Kelainan janin', level: '2', subsection: 'Gangguan pada Kehamilan' },
  { system: 'Reproduksi & Obstetri', disease: 'Diproporsi kepala panggul', level: '2', subsection: 'Gangguan pada Kehamilan' },
  { system: 'Reproduksi & Obstetri', disease: 'Anemia defisiensi besi pada kehamilan', level: '4A', subsection: 'Gangguan pada Kehamilan' },
  { system: 'Reproduksi & Obstetri', disease: 'Intra-Uterine Fetal Death (IUFD)', level: '2', subsection: 'Persalinan dan Nifas' },
  { system: 'Reproduksi & Obstetri', disease: 'Persalinan preterm', level: '3A', subsection: 'Persalinan dan Nifas' },
  { system: 'Reproduksi & Obstetri', disease: 'Ruptur uteri', level: '2', subsection: 'Persalinan dan Nifas' },
  { system: 'Reproduksi & Obstetri', disease: 'Bayi post matur', level: '3A', subsection: 'Persalinan dan Nifas' },
  { system: 'Reproduksi & Obstetri', disease: 'Ketuban pecah dini (KPD)', level: '3A', subsection: 'Persalinan dan Nifas' },
  { system: 'Reproduksi & Obstetri', disease: 'Distosia', level: '3B', subsection: 'Persalinan dan Nifas' },
  { system: 'Reproduksi & Obstetri', disease: 'Malpresentasi', level: '2', subsection: 'Persalinan dan Nifas' },
  { system: 'Reproduksi & Obstetri', disease: 'Partus lama', level: '3B', subsection: 'Persalinan dan Nifas' },
  { system: 'Reproduksi & Obstetri', disease: 'Prolaps tali pusat', level: '3B', subsection: 'Persalinan dan Nifas' },
  { system: 'Reproduksi & Obstetri', disease: 'Hipoksia janin', level: '3B', subsection: 'Persalinan dan Nifas' },
  { system: 'Reproduksi & Obstetri', disease: 'Ruptur serviks', level: '3B', subsection: 'Persalinan dan Nifas' },
  { system: 'Reproduksi & Obstetri', disease: 'Ruptur perineum tingkat 1-2', level: '4A', subsection: 'Persalinan dan Nifas' },
  { system: 'Reproduksi & Obstetri', disease: 'Ruptur perineum tingkat 3-4', level: '3B', subsection: 'Persalinan dan Nifas' },
  { system: 'Reproduksi & Obstetri', disease: 'Retensi plasenta', level: '3B', subsection: 'Persalinan dan Nifas' },
  { system: 'Reproduksi & Obstetri', disease: 'Inversio uterus', level: '3B', subsection: 'Persalinan dan Nifas' },
  { system: 'Reproduksi & Obstetri', disease: 'Perdarahan post partum', level: '3B', subsection: 'Persalinan dan Nifas' },
  { system: 'Reproduksi & Obstetri', disease: 'Tromboemboli', level: '2', subsection: 'Persalinan dan Nifas' },
  { system: 'Reproduksi & Obstetri', disease: 'Endometritis', level: '3B', subsection: 'Persalinan dan Nifas' },
  { system: 'Reproduksi & Obstetri', disease: 'Inkontinensia urine', level: '2', subsection: 'Persalinan dan Nifas' },
  { system: 'Reproduksi & Obstetri', disease: 'Inkontinensia feses', level: '2', subsection: 'Persalinan dan Nifas' },
  { system: 'Reproduksi & Obstetri', disease: 'Trombosis vena dalam', level: '2', subsection: 'Persalinan dan Nifas' },
  { system: 'Reproduksi & Obstetri', disease: 'Tromboflebitis', level: '2', subsection: 'Persalinan dan Nifas' },
  { system: 'Reproduksi & Obstetri', disease: 'Subinvolusio uterus', level: '3B', subsection: 'Persalinan dan Nifas' },
  { system: 'Reproduksi & Obstetri', disease: 'Kista dan abses kelenjar bartolini', level: '3A', subsection: 'Kelainan Organ Genital' },
  { system: 'Reproduksi & Obstetri', disease: 'Abses folikel rambut atau kelenjar sebasea', level: '4A', subsection: 'Kelainan Organ Genital' },
  { system: 'Reproduksi & Obstetri', disease: 'Malformasi kongenital', level: '1', subsection: 'Kelainan Organ Genital' },
  { system: 'Reproduksi & Obstetri', disease: 'Kistokel', level: '1', subsection: 'Kelainan Organ Genital' },
  { system: 'Reproduksi & Obstetri', disease: 'Rektokel', level: '1', subsection: 'Kelainan Organ Genital' },
  { system: 'Reproduksi & Obstetri', disease: 'Corpus alienum vaginae', level: '3A', subsection: 'Kelainan Organ Genital' },
  { system: 'Reproduksi & Obstetri', disease: 'Kista Gartner', level: '3A', subsection: 'Kelainan Organ Genital' },
  { system: 'Reproduksi & Obstetri', disease: 'Fistula (vesiko-vaginal, uretero-vagina, rektovagina)', level: '2', subsection: 'Kelainan Organ Genital' },
  { system: 'Reproduksi & Obstetri', disease: 'Kista Nabotian', level: '3A', subsection: 'Kelainan Organ Genital' },
  { system: 'Reproduksi & Obstetri', disease: 'Polip serviks', level: '3A', subsection: 'Kelainan Organ Genital' },
  { system: 'Reproduksi & Obstetri', disease: 'Malformasi kongenital uterus', level: '1', subsection: 'Kelainan Organ Genital' },
  { system: 'Reproduksi & Obstetri', disease: 'Prolaps uterus, sistokel, rektokel', level: '3A', subsection: 'Kelainan Organ Genital' },
  { system: 'Reproduksi & Obstetri', disease: 'Hematokolpos', level: '2', subsection: 'Kelainan Organ Genital' },
  { system: 'Reproduksi & Obstetri', disease: 'Endometriosis', level: '2', subsection: 'Kelainan Organ Genital' },
  { system: 'Reproduksi & Obstetri', disease: 'Hiperplasia endometrium', level: '1', subsection: 'Kelainan Organ Genital' },
  { system: 'Reproduksi & Obstetri', disease: 'Menopause, perimenopausal syndome', level: '2', subsection: 'Kelainan Organ Genital' },
  { system: 'Reproduksi & Obstetri', disease: 'Polikistik ovarium', level: '1', subsection: 'Kelainan Organ Genital' },
  { system: 'Reproduksi & Obstetri', disease: 'Kehamilan ektopik', level: '2', subsection: 'Kelainan Organ Genital' },
  { system: 'Reproduksi & Obstetri', disease: 'Karsinoma serviks', level: '2', subsection: 'Tumor dan Keganasan pada Organ Genital' },
  { system: 'Reproduksi & Obstetri', disease: 'Karsinoma endometrium', level: '1', subsection: 'Tumor dan Keganasan pada Organ Genital' },
  { system: 'Reproduksi & Obstetri', disease: 'Karsinoma ovarium', level: '1', subsection: 'Tumor dan Keganasan pada Organ Genital' },
  { system: 'Reproduksi & Obstetri', disease: 'Teratoma ovarium (kista dermoid)', level: '2', subsection: 'Tumor dan Keganasan pada Organ Genital' },
  { system: 'Reproduksi & Obstetri', disease: 'Kista ovarium', level: '2', subsection: 'Tumor dan Keganasan pada Organ Genital' },
  { system: 'Reproduksi & Obstetri', disease: 'Torsi dan ruptur kista', level: '3B', subsection: 'Tumor dan Keganasan pada Organ Genital' },
  { system: 'Reproduksi & Obstetri', disease: 'Koriokarsinoma Adenomiosis, mioma', level: '1', subsection: 'Tumor dan Keganasan pada Organ Genital' },
  { system: 'Reproduksi & Obstetri', disease: 'Malpresentasi', level: '2', subsection: 'Tumor dan Keganasan pada Organ Genital' },
  { system: 'Reproduksi & Obstetri', disease: 'Inflamasi, abses', level: '2', subsection: 'Payudara' },
  { system: 'Reproduksi & Obstetri', disease: 'Mastitis', level: '4A', subsection: 'Payudara' },
  { system: 'Reproduksi & Obstetri', disease: 'Cracked nipple', level: '4A', subsection: 'Payudara' },
  { system: 'Reproduksi & Obstetri', disease: 'Inverted nipple', level: '4A', subsection: 'Payudara' },
  { system: 'Reproduksi & Obstetri', disease: 'Fibrokista', level: '2', subsection: 'Payudara' },
  { system: 'Reproduksi & Obstetri', disease: 'Fibroadenoma mammae (FAM)', level: '2', subsection: 'Payudara' },
  { system: 'Reproduksi & Obstetri', disease: 'Tumor Filoides', level: '1', subsection: 'Payudara' },
  { system: 'Reproduksi & Obstetri', disease: 'Karsinoma payudara', level: '2', subsection: 'Payudara' },
  { system: 'Reproduksi & Obstetri', disease: 'Penyakit Paget', level: '1', subsection: 'Payudara' },
  { system: 'Reproduksi & Obstetri', disease: 'Ginekomastia', level: '2', subsection: 'Payudara' },
  { system: 'Reproduksi & Obstetri', disease: 'Infertilitas', level: '3A', subsection: 'Masalah Reproduksi Pria' },
  { system: 'Reproduksi & Obstetri', disease: 'Gangguan ereksi', level: '2', subsection: 'Masalah Reproduksi Pria' },
  { system: 'Reproduksi & Obstetri', disease: 'Gangguan ejakulasi', level: '2', subsection: 'Masalah Reproduksi Pria' },
  { system: 'Endokrin & Metabolik', disease: 'Diabetes melitus tipe 1', level: '3A', subsection: 'Kelenjar Endokrin' },
  { system: 'Endokrin & Metabolik', disease: 'Diabetes melitus tipe 2', level: '4A', subsection: 'Kelenjar Endokrin' },
  { system: 'Endokrin & Metabolik', disease: 'Ketoasidosis diabetikum nonketotik', level: '3B', subsection: 'Kelenjar Endokrin' },
  { system: 'Endokrin & Metabolik', disease: 'Hiperglikemi hiperosmolar', level: '3B', subsection: 'Kelenjar Endokrin' },
  { system: 'Endokrin & Metabolik', disease: 'Hipoglikemia ringan', level: '4A', subsection: 'Kelenjar Endokrin' },
  { system: 'Endokrin & Metabolik', disease: 'Hipoglikemia berat', level: '3B', subsection: 'Kelenjar Endokrin' },
  { system: 'Endokrin & Metabolik', disease: 'Diabetes insipidus', level: '1', subsection: 'Kelenjar Endokrin' },
  { system: 'Endokrin & Metabolik', disease: 'Akromegali, gigantisme', level: '1', subsection: 'Kelenjar Endokrin' },
  { system: 'Endokrin & Metabolik', disease: 'Defisiensi hormon pertumbuhan', level: '1', subsection: 'Kelenjar Endokrin' },
  { system: 'Endokrin & Metabolik', disease: 'Hiperparatiroid', level: '1', subsection: 'Kelenjar Endokrin' },
  { system: 'Endokrin & Metabolik', disease: 'Hipoparatiroid', level: '3A', subsection: 'Kelenjar Endokrin' },
  { system: 'Endokrin & Metabolik', disease: 'Hipertiroid', level: '3A', subsection: 'Kelenjar Endokrin' },
  { system: 'Endokrin & Metabolik', disease: 'Tirotoksikosis', level: '3B', subsection: 'Kelenjar Endokrin' },
  { system: 'Endokrin & Metabolik', disease: 'Hipotiroid', level: '2', subsection: 'Kelenjar Endokrin' },
  { system: 'Endokrin & Metabolik', disease: 'Goiter', level: '3A', subsection: 'Kelenjar Endokrin' },
  { system: 'Endokrin & Metabolik', disease: 'Tiroiditis', level: '2', subsection: 'Kelenjar Endokrin' },
  { system: 'Endokrin & Metabolik', disease: 'Cushing\'s disease', level: '3B', subsection: 'Kelenjar Endokrin' },
  { system: 'Endokrin & Metabolik', disease: 'Krisis adrenal', level: '3B', subsection: 'Kelenjar Endokrin' },
  { system: 'Endokrin & Metabolik', disease: 'Addison\'s disease', level: '1', subsection: 'Kelenjar Endokrin' },
  { system: 'Endokrin & Metabolik', disease: 'Pubertas prekoks', level: '2', subsection: 'Kelenjar Endokrin' },
  { system: 'Endokrin & Metabolik', disease: 'Hipogonadisme', level: '2', subsection: 'Kelenjar Endokrin' },
  { system: 'Endokrin & Metabolik', disease: 'Prolaktinemia', level: '1', subsection: 'Kelenjar Endokrin' },
  { system: 'Endokrin & Metabolik', disease: 'Adenoma tiroid', level: '2', subsection: 'Kelenjar Endokrin' },
  { system: 'Endokrin & Metabolik', disease: 'Karsinoma tiroid', level: '2', subsection: 'Kelenjar Endokrin' },
  { system: 'Endokrin & Metabolik', disease: 'Malnutrisi energi-protein', level: '4A', subsection: 'Gizi dan Metabollisme' },
  { system: 'Endokrin & Metabolik', disease: 'Defisiensi vitamin', level: '4A', subsection: 'Gizi dan Metabollisme' },
  { system: 'Endokrin & Metabolik', disease: 'Defisiensi mineral', level: '4A', subsection: 'Gizi dan Metabollisme' },
  { system: 'Endokrin & Metabolik', disease: 'Dislipidemia', level: '4A', subsection: 'Gizi dan Metabollisme' },
  { system: 'Endokrin & Metabolik', disease: 'Porfiria', level: '1', subsection: 'Gizi dan Metabollisme' },
  { system: 'Endokrin & Metabolik', disease: 'Hiperurisemia', level: '4A', subsection: 'Gizi dan Metabollisme' },
  { system: 'Endokrin & Metabolik', disease: 'Obesitas', level: '4A', subsection: 'Gizi dan Metabollisme' },
  { system: 'Endokrin & Metabolik', disease: 'Sindrom metabolik', level: '3B', subsection: 'Gizi dan Metabollisme' },
  { system: 'Hematologi & Imunologi', disease: 'Anemia aplastik', level: '2', subsection: null },
  { system: 'Hematologi & Imunologi', disease: 'Anemia defisiensi besi', level: '4A', subsection: null },
  { system: 'Hematologi & Imunologi', disease: 'Anemia hemolitik', level: '3A', subsection: null },
  { system: 'Hematologi & Imunologi', disease: 'Anemia makrositik', level: '3A', subsection: null },
  { system: 'Hematologi & Imunologi', disease: 'Anemia megaloblastik', level: '2', subsection: null },
  { system: 'Hematologi & Imunologi', disease: 'Hemoglobinopati', level: '2', subsection: null },
  { system: 'Hematologi & Imunologi', disease: 'Polisitemia', level: '2', subsection: null },
  { system: 'Hematologi & Imunologi', disease: '9 DIC', level: '2', subsection: '8 Gangguan pembekuan darah (trombositopenia,' },
  { system: 'Hematologi & Imunologi', disease: 'Agranulositosis', level: '2', subsection: '8 Gangguan pembekuan darah (trombositopenia,' },
  { system: 'Hematologi & Imunologi', disease: 'Inkompatibilitas golongan darah', level: '2', subsection: '8 Gangguan pembekuan darah (trombositopenia,' },
  { system: 'Hematologi & Imunologi', disease: 'Timoma', level: '1', subsection: '8 Gangguan pembekuan darah (trombositopenia,' },
  { system: 'Hematologi & Imunologi', disease: 'Limfoma non-Hodgkin\'s, Hodgkin\'s', level: '1', subsection: 'Kelenjar Limfe dan Darah' },
  { system: 'Hematologi & Imunologi', disease: 'Leukemia akut, kronik', level: '2', subsection: 'Kelenjar Limfe dan Darah' },
  { system: 'Hematologi & Imunologi', disease: 'Mieloma multipel', level: '1', subsection: 'Kelenjar Limfe dan Darah' },
  { system: 'Hematologi & Imunologi', disease: 'Limfadenopati', level: '3A', subsection: 'Kelenjar Limfe dan Darah' },
  { system: 'Hematologi & Imunologi', disease: 'Limfadenitis', level: '4A', subsection: 'Kelenjar Limfe dan Darah' },
  { system: 'Hematologi & Imunologi', disease: 'Bakteremia', level: '3B', subsection: 'Infeksi' },
  { system: 'Hematologi & Imunologi', disease: 'Demam dengue, DHF', level: '4A', subsection: 'Infeksi' },
  { system: 'Hematologi & Imunologi', disease: 'Dengue shock syndrome', level: '3B', subsection: 'Infeksi' },
  { system: 'Hematologi & Imunologi', disease: 'Malaria', level: '4A', subsection: 'Infeksi' },
  { system: 'Hematologi & Imunologi', disease: 'Leishmaniasis dan tripanosomiasis', level: '2', subsection: 'Infeksi' },
  { system: 'Hematologi & Imunologi', disease: 'Toksoplasmosis', level: '3A', subsection: 'Infeksi' },
  { system: 'Hematologi & Imunologi', disease: 'Leptospirosis (tanpa komplikasi)', level: '4A', subsection: 'Infeksi' },
  { system: 'Hematologi & Imunologi', disease: 'Sepsis', level: '3B', subsection: 'Infeksi' },
  { system: 'Hematologi & Imunologi', disease: 'Lupus eritematosus sistemik', level: '3A', subsection: 'Penyakit Autoimun' },
  { system: 'Hematologi & Imunologi', disease: 'Poliarteritis nodosa', level: '1', subsection: 'Penyakit Autoimun' },
  { system: 'Hematologi & Imunologi', disease: 'Polimialgia reumatik', level: '3A', subsection: 'Penyakit Autoimun' },
  { system: 'Hematologi & Imunologi', disease: 'Reaksi anafilaktik', level: '4A', subsection: 'Penyakit Autoimun' },
  { system: 'Hematologi & Imunologi', disease: 'Demam reumatik', level: '3A', subsection: 'Penyakit Autoimun' },
  { system: 'Hematologi & Imunologi', disease: 'Artritis reumatoid', level: '3A', subsection: 'Penyakit Autoimun' },
  { system: 'Hematologi & Imunologi', disease: 'Juvenile chronic arthritis', level: '2', subsection: 'Penyakit Autoimun' },
  { system: 'Hematologi & Imunologi', disease: 'Henoch-schoenlein purpura', level: '2', subsection: 'Penyakit Autoimun' },
  { system: 'Hematologi & Imunologi', disease: 'Eritema multiformis', level: '2', subsection: 'Penyakit Autoimun' },
  { system: 'Hematologi & Imunologi', disease: 'Imunodefisiensi', level: '2', subsection: 'Penyakit Autoimun' },
  { system: 'Muskuloskeletal', disease: 'Artritis, osteoarthritis', level: '3A', subsection: 'Tulang dan Sendi' },
  { system: 'Muskuloskeletal', disease: 'Fraktur terbuka, tertutup', level: '3B', subsection: 'Tulang dan Sendi' },
  { system: 'Muskuloskeletal', disease: 'Fraktur klavikula', level: '3A', subsection: 'Tulang dan Sendi' },
  { system: 'Muskuloskeletal', disease: 'Fraktur patologis,', level: '2', subsection: 'Tulang dan Sendi' },
  { system: 'Muskuloskeletal', disease: 'Fraktur dan dislokasi tulang belakang', level: '2', subsection: 'Tulang dan Sendi' },
  { system: 'Muskuloskeletal', disease: 'Dislokasi pada sendi ekstremitas', level: '2', subsection: 'Tulang dan Sendi' },
  { system: 'Muskuloskeletal', disease: 'Osteogenesis imperfekta', level: '1', subsection: 'Tulang dan Sendi' },
  { system: 'Muskuloskeletal', disease: 'Ricketsia, osteomalasia', level: '1', subsection: 'Tulang dan Sendi' },
  { system: 'Muskuloskeletal', disease: 'Osteoporosis', level: '3A', subsection: 'Tulang dan Sendi' },
  { system: 'Muskuloskeletal', disease: 'Akondroplasia', level: '1', subsection: 'Tulang dan Sendi' },
  { system: 'Muskuloskeletal', disease: 'Displasia fibrosa', level: '1', subsection: 'Tulang dan Sendi' },
  { system: 'Muskuloskeletal', disease: 'Tenosinovitis supuratif', level: '3A', subsection: 'Tulang dan Sendi' },
  { system: 'Muskuloskeletal', disease: 'Tumor tulang primer, sekunder', level: '2', subsection: 'Tulang dan Sendi' },
  { system: 'Muskuloskeletal', disease: 'Osteosarkoma', level: '1', subsection: 'Tulang dan Sendi' },
  { system: 'Muskuloskeletal', disease: 'Sarcoma Ewing', level: '1', subsection: 'Tulang dan Sendi' },
  { system: 'Muskuloskeletal', disease: 'Kista ganglion', level: '2', subsection: 'Tulang dan Sendi' },
  { system: 'Muskuloskeletal', disease: 'Trauma sendi', level: '3A', subsection: 'Tulang dan Sendi' },
  { system: 'Muskuloskeletal', disease: '19 Spondilitis, spondilodisitis', level: '2', subsection: '18 Kelainan bentuk tulang belakang (skoliosis, kifosis,' },
  { system: 'Muskuloskeletal', disease: 'Teratoma sakrokoksigeal', level: '2', subsection: '18 Kelainan bentuk tulang belakang (skoliosis, kifosis,' },
  { system: 'Muskuloskeletal', disease: 'Spondilolistesis', level: '1', subsection: '18 Kelainan bentuk tulang belakang (skoliosis, kifosis,' },
  { system: 'Muskuloskeletal', disease: 'Spondilolisis', level: '1', subsection: '18 Kelainan bentuk tulang belakang (skoliosis, kifosis,' },
  { system: 'Muskuloskeletal', disease: 'Lesi pada ligamentosa panggul', level: '1', subsection: '18 Kelainan bentuk tulang belakang (skoliosis, kifosis,' },
  { system: 'Muskuloskeletal', disease: 'Displasia panggul', level: '2', subsection: '18 Kelainan bentuk tulang belakang (skoliosis, kifosis,' },
  { system: 'Muskuloskeletal', disease: 'Nekrosis kaput femoris', level: '1', subsection: '18 Kelainan bentuk tulang belakang (skoliosis, kifosis,' },
  { system: 'Muskuloskeletal', disease: 'Tendinitis Achilles', level: '1', subsection: '18 Kelainan bentuk tulang belakang (skoliosis, kifosis,' },
  { system: 'Muskuloskeletal', disease: 'Ruptur tendon Achilles', level: '3A', subsection: '18 Kelainan bentuk tulang belakang (skoliosis, kifosis,' },
  { system: 'Muskuloskeletal', disease: 'Lesi meniskus, medial, dan lateral', level: '3A', subsection: '18 Kelainan bentuk tulang belakang (skoliosis, kifosis,' },
  { system: 'Muskuloskeletal', disease: 'Instabilitas sendi tumit', level: '2', subsection: '18 Kelainan bentuk tulang belakang (skoliosis, kifosis,' },
  { system: 'Muskuloskeletal', disease: '31 Claw foot, drop foot', level: '2', subsection: '30 Malformasi kongenital (genovarum, genovalgum, club' },
  { system: 'Muskuloskeletal', disease: 'Claw hand, drop hand', level: '2', subsection: '30 Malformasi kongenital (genovarum, genovalgum, club' },
  { system: 'Muskuloskeletal', disease: 'Ulkus pada tungkai', level: '4A', subsection: 'Otot dan Jaringan Lunak' },
  { system: 'Muskuloskeletal', disease: 'Osteomielitis', level: '3B', subsection: 'Otot dan Jaringan Lunak' },
  { system: 'Muskuloskeletal', disease: 'Rhabdomiosarkoma', level: '1', subsection: 'Otot dan Jaringan Lunak' },
  { system: 'Muskuloskeletal', disease: 'Leiomioma, leiomiosarkoma, liposarkoma', level: '1', subsection: 'Otot dan Jaringan Lunak' },
  { system: 'Muskuloskeletal', disease: 'Lipoma', level: '4A', subsection: 'Otot dan Jaringan Lunak' },
  { system: 'Muskuloskeletal', disease: 'Fibromatosis, fibroma, fibrosarkoma', level: '1', subsection: 'Otot dan Jaringan Lunak' },
  { system: 'Integumen', disease: 'Veruka vulgaris', level: '4A', subsection: 'KULIT Infeksi Virus' },
  { system: 'Integumen', disease: 'Kondiloma akuminatum', level: '3A', subsection: 'KULIT Infeksi Virus' },
  { system: 'Integumen', disease: 'Moluskum kontagiosum', level: '4A', subsection: 'KULIT Infeksi Virus' },
  { system: 'Integumen', disease: 'Herpes zoster tanpa komplikasi', level: '4A', subsection: 'KULIT Infeksi Virus' },
  { system: 'Integumen', disease: 'Morbili tanpa komplikasi', level: '4A', subsection: 'KULIT Infeksi Virus' },
  { system: 'Integumen', disease: 'Varisela tanpa komplikasi', level: '4A', subsection: 'KULIT Infeksi Virus' },
  { system: 'Integumen', disease: 'Herpes simpleks tanpa komplikasi', level: '4A', subsection: 'KULIT Infeksi Virus' },
  { system: 'Integumen', disease: 'Impetigo', level: '4A', subsection: 'Infeksi Bakteri' },
  { system: 'Integumen', disease: 'Impetigo ulseratif (ektima)', level: '4A', subsection: 'Infeksi Bakteri' },
  { system: 'Integumen', disease: 'Folikulitis superfisialis', level: '4A', subsection: 'Infeksi Bakteri' },
  { system: 'Integumen', disease: 'Furunkel, karbunkel', level: '4A', subsection: 'Infeksi Bakteri' },
  { system: 'Integumen', disease: 'Eritrasma', level: '4A', subsection: 'Infeksi Bakteri' },
  { system: 'Integumen', disease: 'Erisipelas', level: '4A', subsection: 'Infeksi Bakteri' },
  { system: 'Integumen', disease: 'Skrofuloderma', level: '4A', subsection: 'Infeksi Bakteri' },
  { system: 'Integumen', disease: 'Lepra', level: '4A', subsection: 'Infeksi Bakteri' },
  { system: 'Integumen', disease: 'Reaksi lepra', level: '3A', subsection: 'Infeksi Bakteri' },
  { system: 'Integumen', disease: 'Sifilis stadium', level: '1', subsection: 'Infeksi Bakteri' },
  { system: 'Integumen', disease: 'Tinea kapitis', level: '4A', subsection: 'dan 2 4A Infeksi Jamur' },
  { system: 'Integumen', disease: 'Tinea barbe', level: '4A', subsection: 'dan 2 4A Infeksi Jamur' },
  { system: 'Integumen', disease: 'Tinea fasialis', level: '4A', subsection: 'dan 2 4A Infeksi Jamur' },
  { system: 'Integumen', disease: 'Tinea korporis', level: '4A', subsection: 'dan 2 4A Infeksi Jamur' },
  { system: 'Integumen', disease: 'Tinea manus', level: '4A', subsection: 'dan 2 4A Infeksi Jamur' },
  { system: 'Integumen', disease: 'Tinea unguium', level: '4A', subsection: 'dan 2 4A Infeksi Jamur' },
  { system: 'Integumen', disease: 'Tinea kruris', level: '4A', subsection: 'dan 2 4A Infeksi Jamur' },
  { system: 'Integumen', disease: 'Tinea pedis', level: '4A', subsection: 'dan 2 4A Infeksi Jamur' },
  { system: 'Integumen', disease: 'Pitiriasis vesikolor', level: '4A', subsection: 'dan 2 4A Infeksi Jamur' },
  { system: 'Integumen', disease: 'Kandidosis mukokutan ringan', level: '4A', subsection: 'dan 2 4A Infeksi Jamur' },
  { system: 'Integumen', disease: 'Cutaneus larva migran', level: '4A', subsection: 'Gigitan Serangga dan Infestasi Parasit' },
  { system: 'Integumen', disease: 'Filariasis', level: '4A', subsection: 'Gigitan Serangga dan Infestasi Parasit' },
  { system: 'Integumen', disease: 'Pedikulosis kapitis', level: '4A', subsection: 'Gigitan Serangga dan Infestasi Parasit' },
  { system: 'Integumen', disease: 'Pedikulosis pubis', level: '4A', subsection: 'Gigitan Serangga dan Infestasi Parasit' },
  { system: 'Integumen', disease: 'Skabies', level: '4A', subsection: 'Gigitan Serangga dan Infestasi Parasit' },
  { system: 'Integumen', disease: 'Reaksi gigitan serangga', level: '4A', subsection: 'Gigitan Serangga dan Infestasi Parasit' },
  { system: 'Integumen', disease: 'Dermatitis kontak iritan', level: '4A', subsection: 'Dermatitis Eksim' },
  { system: 'Integumen', disease: 'Dermatitis kontak alergika', level: '3A', subsection: 'Dermatitis Eksim' },
  { system: 'Integumen', disease: 'Dermatitis atopik (kecuali recalcitrant)', level: '4A', subsection: 'Dermatitis Eksim' },
  { system: 'Integumen', disease: 'Dermatitis numularis', level: '4A', subsection: 'Dermatitis Eksim' },
  { system: 'Integumen', disease: 'Liken simpleks kronik/neurodermatitis', level: '3A', subsection: 'Dermatitis Eksim' },
  { system: 'Integumen', disease: 'Napkin eczema', level: '4A', subsection: 'Dermatitis Eksim' },
  { system: 'Integumen', disease: 'Psoriasis vulgaris', level: '3A', subsection: 'Lesi Eritro-Squamosa' },
  { system: 'Integumen', disease: 'Dermatitis seboroik', level: '4A', subsection: 'Lesi Eritro-Squamosa' },
  { system: 'Integumen', disease: 'Pitiriasis rosea', level: '4A', subsection: 'Lesi Eritro-Squamosa' },
  { system: 'Integumen', disease: 'Akne vulgaris ringan', level: '4A', subsection: 'Kelainan Kelenjar Sebasea dan Ekrin' },
  { system: 'Integumen', disease: 'Akne vulgaris sedang-berat', level: '3A', subsection: 'Kelainan Kelenjar Sebasea dan Ekrin' },
  { system: 'Integumen', disease: 'Hidradenitis supuratif', level: '4A', subsection: 'Kelainan Kelenjar Sebasea dan Ekrin' },
  { system: 'Integumen', disease: 'Dermatitis perioral', level: '4A', subsection: 'Kelainan Kelenjar Sebasea dan Ekrin' },
  { system: 'Integumen', disease: 'Miliaria', level: '4A', subsection: 'Kelainan Kelenjar Sebasea dan Ekrin' },
  { system: 'Integumen', disease: 'Toxic epidermal necrolysis', level: '3B', subsection: 'Penyakit Vesikobulosa' },
  { system: 'Integumen', disease: 'Sindrom Stevens-Johnson', level: '3B', subsection: 'Penyakit Vesikobulosa' },
  { system: 'Integumen', disease: 'Urtikaria akut', level: '4A', subsection: 'Penyakit Kulit Alergi' },
  { system: 'Integumen', disease: 'Urtikaria kronis', level: '3A', subsection: 'Penyakit Kulit Alergi' },
  { system: 'Integumen', disease: 'Angioedema', level: '3B', subsection: 'Penyakit Kulit Alergi' },
  { system: 'Integumen', disease: 'Lupus eritematosis kulit', level: '2', subsection: 'Penyakit Autoimun' },
  { system: 'Integumen', disease: 'Ichthyosis vulgaris', level: '3A', subsection: 'Gangguan Keratinisasi' },
  { system: 'Integumen', disease: 'Exanthematous drug eruption, fixed drug eruption', level: '4A', subsection: 'Reaksi Obat' },
  { system: 'Integumen', disease: 'Vitiligo', level: '3A', subsection: 'Kelainan Pigmentasi' },
  { system: 'Integumen', disease: 'Melasma', level: '3A', subsection: 'Kelainan Pigmentasi' },
  { system: 'Integumen', disease: 'Albino', level: '2', subsection: 'Kelainan Pigmentasi' },
  { system: 'Integumen', disease: 'Hiperpigmentasi pascainflamasi', level: '3A', subsection: 'Kelainan Pigmentasi' },
  { system: 'Integumen', disease: 'Hipopigmentasi pascainflamasi', level: '3A', subsection: 'Kelainan Pigmentasi' },
  { system: 'Integumen', disease: 'Keratosis seboroik', level: '2', subsection: 'Neoplasma' },
  { system: 'Integumen', disease: 'Kista epitel', level: '3A', subsection: 'Neoplasma' },
  { system: 'Integumen', disease: 'Squamous cell carcinoma (Karsinoma sel skuamosa)', level: '2', subsection: 'Tumor Epitel Premaligna dan Maligna' },
  { system: 'Integumen', disease: 'Basal cell carcinoma (Karsinoma sel basal)', level: '2', subsection: 'Tumor Epitel Premaligna dan Maligna' },
  { system: 'Integumen', disease: 'Xanthoma', level: '2', subsection: 'Tumor Dermis' },
  { system: 'Integumen', disease: 'Hemangioma', level: '2', subsection: 'Tumor Dermis' },
  { system: 'Integumen', disease: 'Lentigo', level: '2', subsection: 'Tumor Sel Melanosit' },
  { system: 'Integumen', disease: 'Nevus pigmentosus', level: '2', subsection: 'Tumor Sel Melanosit' },
  { system: 'Integumen', disease: 'Melanoma maligna', level: '1', subsection: 'Tumor Sel Melanosit' },
  { system: 'Integumen', disease: 'Alopesia areata', level: '2', subsection: 'Rambut' },
  { system: 'Integumen', disease: 'Alopesia androgenik', level: '2', subsection: 'Rambut' },
  { system: 'Integumen', disease: 'Telogen eflluvium', level: '2', subsection: 'Rambut' },
  { system: 'Integumen', disease: 'Psoriasis vulgaris', level: '2', subsection: 'Rambut' },
  { system: 'Integumen', disease: 'Vulnus laseratum, punctum', level: '4A', subsection: 'Trauma' },
  { system: 'Integumen', disease: 'Vulnus perforatum, penetratum', level: '3B', subsection: 'Trauma' },
  { system: 'Integumen', disease: 'Luka bakar derajat', level: '1', subsection: 'Trauma' },
  { system: 'Integumen', disease: '4A 77 Luka bakar derajat', level: '3', subsection: 'Trauma' },
  { system: 'Integumen', disease: '3B 78 Luka akibat bahan kimia', level: '3B', subsection: 'Trauma' },
  { system: 'Integumen', disease: 'Luka akibat sengatan listrik', level: '3B', subsection: 'Trauma' },
  { system: 'Forensik & Medikolegal', disease: 'Kekerasan tumpul', level: '4A', subsection: null },
  { system: 'Forensik & Medikolegal', disease: 'Kekerasan tajam', level: '4A', subsection: null },
  { system: 'Forensik & Medikolegal', disease: 'Trauma kimia', level: '3A', subsection: null },
  { system: 'Forensik & Medikolegal', disease: 'Luka tembak', level: '3A', subsection: null },
  { system: 'Forensik & Medikolegal', disease: 'Luka listrik dan petir', level: '2', subsection: null },
  { system: 'Forensik & Medikolegal', disease: 'Barotrauma', level: '2', subsection: null },
  { system: 'Forensik & Medikolegal', disease: 'Trauma suhu', level: '2', subsection: null },
  { system: 'Forensik & Medikolegal', disease: 'Asfiksia', level: '3A', subsection: null },
  { system: 'Forensik & Medikolegal', disease: 'Tenggelam', level: '3A', subsection: null },
  { system: 'Forensik & Medikolegal', disease: 'Pembunuhan anak sendiri', level: '3A', subsection: null },
  { system: 'Forensik & Medikolegal', disease: 'Pengguguran kandungan', level: '3A', subsection: null },
  { system: 'Forensik & Medikolegal', disease: 'Kematian mendadak', level: '3B', subsection: null },
  { system: 'Forensik & Medikolegal', disease: 'Toksikologi forensik', level: '3A', subsection: null },
]

export const SKDI_DISEASE_SYSTEMS: SkdiDiseaseSystem[] = [
  'Saraf (Neurologi)',
  'Psikiatri',
  'Indera',
  'Respirasi',
  'Kardiovaskular',
  'Gastrointestinal & Hepatobilier',
  'Ginjal & Saluran Kemih',
  'Reproduksi & Obstetri',
  'Endokrin & Metabolik',
  'Hematologi & Imunologi',
  'Muskuloskeletal',
  'Integumen',
  'Forensik & Medikolegal',
]