// ─────────────────────────────────────────────────────────────────────────────
// SKDI Therapy Reference — a curated tatalaksana (therapy) compendium by
// system → diagnosis → classification/subtype → farmakoterapi, transcribed
// from a real SKDI-aligned UKMPPD study reference, used with the content
// owner's confirmed permission. This is study material for board-exam
// preparation, NOT a prescribing tool — always cross-check current dosing
// against PIONAS/Pharmacology references, your institution's formulary, and
// a supervising clinician before any real clinical use. Some entries in the
// source carry an explicit "(?)" or shorthand — these are preserved as-is
// rather than silently resolved, since guessing at a dose would be unsafe.
// ─────────────────────────────────────────────────────────────────────────────

export type SkdiSystem =
  | 'Infeksi Tropis'
  | 'Rheumatologi'
  | 'Ginjal & Saluran Kemih'
  | 'Endokrin & Metabolik'
  | 'Gastroenterologi'
  | 'Hepatobilier'
  | 'Hematologi & Onkologi Medik'
  | 'Anak — Respirasi'
  | 'Anak — Neuro'
  | 'Anak — Kardio'
  | 'Anak — Digestif & Ginjal'
  | 'Anak — Endokrin & Gizi'
  | 'Anak — Infeksi & NICU'
  | 'Kardiovaskular'
  | 'Respirasi'
  | 'Neurologi'
  | 'Psikiatri'
  | 'Mata'
  | 'THT'

export interface SkdiEntry {
  system: SkdiSystem
  diagnosis: string
  classification?: string
  therapy: string
}

export const SKDI_ENTRIES: SkdiEntry[] = [
  // Infeksi Tropis
  { system: 'Infeksi Tropis', diagnosis: 'Leptospirosis', classification: 'Ringan', therapy: 'Doksisiklin 2x100 mg / Ampisilin 4x500 mg / Amoksisilin 4x500 mg' },
  { system: 'Infeksi Tropis', diagnosis: 'Leptospirosis', classification: 'Berat', therapy: 'Penicillin G 1.5 jt unit/6 jam IV / Ampisilin 1gr/6 jam IV / Ceftriaxon 1gr/hari IV' },
  { system: 'Infeksi Tropis', diagnosis: 'Leptospirosis', classification: 'Profilaksis', therapy: 'Doksisiklin 200 mg/minggu' },
  { system: 'Infeksi Tropis', diagnosis: 'Demam Tifoid', therapy: 'Kloramfenikol 4x500 mg 10 hari / Ampisilin 2gr/hr 10 hari (aman bumil) / Ciprofloxacin 2x500 mg 7 hari (kontraindikasi anak)' },
  { system: 'Infeksi Tropis', diagnosis: 'Demam Tifoid', classification: 'Carrier / Rawat inap', therapy: 'Ceftriaxon 1gr/hari IV' },
  { system: 'Infeksi Tropis', diagnosis: 'HIV tanpa komplikasi', therapy: 'ARV (2 NRTI + 1 NNRTI) — NNRTI: Efavirenz, Nevirapine; NRTI: Zidovudine, Lamivudine, Stavudine' },
  { system: 'Infeksi Tropis', diagnosis: 'HIV', classification: 'Profilaksis', therapy: 'Dewasa: Kotrimoksazol 960 mg u/AIDS, CD4<200; Anak: Kotrimoksazol 4-6 mg/kgBB' },
  { system: 'Infeksi Tropis', diagnosis: 'Profilaksis bayi dari ibu HIV+', therapy: 'ASI: Zidovudin + Nevirapin 6 minggu; Tanpa ASI: Zidovudin 6 minggu' },
  { system: 'Infeksi Tropis', diagnosis: 'Helminthiasis (Ascaris/Ankylostoma)', therapy: 'Albendazol 400 mg SD, atau Mebendazol 500 mg SD/2x100 3hr, atau Pirantel Pamoat 3x10 mg/kgBB (u/<1 thn & bumil)' },
  { system: 'Infeksi Tropis', diagnosis: 'Enterobius Vermicularis', therapy: 'Pirantel Pamoat / Mebendazol / Albendazol' },
  { system: 'Infeksi Tropis', diagnosis: 'Trichuris Trichiura', therapy: 'Mebendazol / Albendazol' },
  { system: 'Infeksi Tropis', diagnosis: 'Strongyloides', therapy: 'Albendazol 400 mg 3 hari' },
  { system: 'Infeksi Tropis', diagnosis: 'Taeniasis', therapy: 'Praziquantel 10 mg/kgBB SD, atau Albendazol 400 mg 3 hari, atau Mebendazol 3x100 mg 2-4 minggu' },
  { system: 'Infeksi Tropis', diagnosis: 'Taeniasis + Neurosistiserkosis', therapy: 'Albendazol 2x400 mg 8-30 hari + steroid' },
  { system: 'Infeksi Tropis', diagnosis: 'Schistosomiasis Japonicum', therapy: 'Praziquantel 3x20 mg/kgBB/hr (60 mg total)' },
  { system: 'Infeksi Tropis', diagnosis: 'Schistosomiasis Mansoni/Haematobium', therapy: 'Praziquantel 2x20 mg/kgBB/hr (40 mg total)' },
  { system: 'Infeksi Tropis', diagnosis: 'Filariasis', classification: 'Akut', therapy: 'DEC (Dietilkarbamazin) 6 mg/kgBB (3x100 mg) 12 hari' },
  { system: 'Infeksi Tropis', diagnosis: 'Filariasis + koinfeksi Loa loa', therapy: 'Tambah Ivermectin 150 mcg/kgBB SD' },
  { system: 'Infeksi Tropis', diagnosis: 'Filariasis Kronik / Profilaksis massal', therapy: 'Albendazol 400 mg SD + DEC/Ivermektin per tahun selama 5 tahun' },
  { system: 'Infeksi Tropis', diagnosis: 'Malaria Falciparum', therapy: 'Lini 1: ACT 3 hari + Primakuin 1 hari; Lini 2: Kina + Doksi/Tetra 7 hari + Primakuin 1 hari' },
  { system: 'Infeksi Tropis', diagnosis: 'Malaria Vivax/Ovale', therapy: 'Lini 1: ACT 3 hari + Primakuin 14 hari; Lini 2: Kina + Doksi/Tetra 7 hari + Primakuin 14 hari' },
  { system: 'Infeksi Tropis', diagnosis: 'Malaria Malariae', therapy: 'Lini 1: ACT 3 hari; Lini 2: Kina + Doksi/Tetra 7 hari' },
  { system: 'Infeksi Tropis', diagnosis: 'ACT (kombinasi)', therapy: 'Artesunat + Amodiakuin, atau Dihidroartemisin + Piperakuin' },
  { system: 'Infeksi Tropis', diagnosis: 'Malaria Berat', therapy: 'Artesunat IV hari 1: 2.4 mg/kgBB jam 0,12,24, lanjut 2.4 mg/24 jam sampai sadar. Bila tak bisa infus/RS perifer: Artemeter IM hari 1: 3.2 mg/kgBB dalam 2 dosis, lanjut 1.6 mg/kgBB/24 jam selama 4 hari. Alternatif: Kina HCl 10 mg/kgBB dalam 500cc D5% selama 8 jam' },
  { system: 'Infeksi Tropis', diagnosis: 'Malaria Profilaksis', classification: 'Maks. 3 bulan', therapy: 'Doksisiklin 100 mg/hari (2 hari sebelum - 4 minggu setelah)' },
  { system: 'Infeksi Tropis', diagnosis: 'Malaria Profilaksis', classification: 'Bumil/Anak', therapy: 'Klorokuin 500 mg/minggu (1 minggu sebelum - 4 minggu setelah); jika resisten klorokuin: Meflokuin 250 mg' },
  { system: 'Infeksi Tropis', diagnosis: 'DBD (resusitasi cairan)', classification: 'Derajat 1', therapy: '3-5 mL/kgBB/jam' },
  { system: 'Infeksi Tropis', diagnosis: 'DBD (resusitasi cairan)', classification: 'Derajat 2', therapy: '6-7 mL/kgBB/jam' },
  { system: 'Infeksi Tropis', diagnosis: 'DBD (resusitasi cairan)', classification: 'Derajat 3', therapy: '10-20 mL/kgBB dalam 30 menit' },
  { system: 'Infeksi Tropis', diagnosis: 'DBD (resusitasi cairan)', classification: 'Derajat 4 (syok)', therapy: '20-30 mL/kgBB bolus' },

  // Rheumatologi
  { system: 'Rheumatologi', diagnosis: 'Gout Arthritis', classification: 'Akut <3 hari', therapy: 'Kolkisin 0.6-1.2 mg/jam (maks. 8 mg)' },
  { system: 'Rheumatologi', diagnosis: 'Gout Arthritis', classification: 'Akut >3 hari', therapy: 'Indometasin 150-200 mg/hari' },
  { system: 'Rheumatologi', diagnosis: 'Gout Arthritis', classification: 'Kronik', therapy: 'Allopurinol 3x100 mg, atau Probenesid' },
  { system: 'Rheumatologi', diagnosis: 'Osteoarthritis', classification: 'Grade 1', therapy: 'NSAID' },
  { system: 'Rheumatologi', diagnosis: 'Osteoarthritis', classification: 'Grade 2/3', therapy: 'Injeksi kortikosteroid + asam hialuronat intraartikular' },
  { system: 'Rheumatologi', diagnosis: 'Osteoarthritis', classification: 'Grade 4', therapy: 'Total Knee Arthroplasty' },
  { system: 'Rheumatologi', diagnosis: 'Rheumatoid Arthritis', classification: 'Awal', therapy: 'NSAID (Meloksikam, Na. Diklofenak)' },
  { system: 'Rheumatologi', diagnosis: 'Rheumatoid Arthritis', classification: 'Definitif', therapy: 'DMARDS (Metotreksat/Klorokuin/Sulfasalazin)' },
  { system: 'Rheumatologi', diagnosis: 'SLE', classification: 'Awal/Induksi', therapy: 'Metilprednisolon 8 mg (high dose)' },
  { system: 'Rheumatologi', diagnosis: 'SLE', classification: 'Definitif', therapy: 'DMARDS (Metotreksat/Klorokuin)' },
  { system: 'Rheumatologi', diagnosis: 'Polimialgia Rheumatica', therapy: 'Kortikosteroid dosis rendah (Prednison 15 mg/hari)' },

  // Ginjal & Saluran Kemih
  { system: 'Ginjal & Saluran Kemih', diagnosis: 'Sistitis Non-Komplikata', classification: 'Wanita tidak hamil', therapy: 'Kotrimoksazol 2x960 / Ciprofloxacin 2x250 mg 3 hari, atau Amoksiklav 2x625 mg 7 hari' },
  { system: 'Ginjal & Saluran Kemih', diagnosis: 'Sistitis Komplikata', therapy: 'Ciprofloxacin 2x500 mg 7 hari' },
  { system: 'Ginjal & Saluran Kemih', diagnosis: 'Sistitis', classification: 'Anak', therapy: 'Kotrimoksazol 10 mg/kgBB' },
  { system: 'Ginjal & Saluran Kemih', diagnosis: 'Sistitis', classification: 'Bumil', therapy: 'Nitrofurantoin 2x100 mg, atau Amoksisilin 3x500 mg 3 hari' },
  { system: 'Ginjal & Saluran Kemih', diagnosis: 'Pielonefritis', classification: 'IV 10-14 hari', therapy: 'Fluorokuinolon (Ciprofloxacin/Levofloxacin), atau TMP-SMX' },
  { system: 'Ginjal & Saluran Kemih', diagnosis: 'Pielonefritis', classification: 'Bumil', therapy: 'Cefadroxil 2x500 mg 7 hari' },
  { system: 'Ginjal & Saluran Kemih', diagnosis: 'Sindrom Nefrotik', therapy: 'Prednison continuous 2 mg/kgBB (maks. 60 mg) 1 bulan, lanjut alternating dose 1.5 mg/kgBB (selang-seling) 1 bulan' },
  { system: 'Ginjal & Saluran Kemih', diagnosis: 'Acute Kidney Injury (AKI)', classification: 'Uremia berat / uremic syndrome', therapy: 'Rehidrasi, koreksi elektrolit + hemodialisis cito' },

  // Endokrin & Metabolik
  { system: 'Endokrin & Metabolik', diagnosis: 'Diabetes Melitus Tipe 2 (kelas obat)', therapy: 'Sulfonilurea (Glibenklamid/Glimepirid, atau Gliclazide/Glipizide/Gliquidone bila perlu aman ginjal); Non-sulfonilurea (Glinid); Biguanid (Metformin 3x500 mg); Tiazolidindion (Pioglitazon); Alfa-glukosidase inhibitor (Acarbose); SGLT2i (Canagliflozin); Agonis GLP-1 (Liraglutide); DPP4i (Sitagliptin); Insulin sesuai indikasi 0.5 IU/kgBB (60% prandial-40% basal)' },
  { system: 'Endokrin & Metabolik', diagnosis: 'KAD / HHS (HONK)', therapy: 'Insulin drip 0.1 IU/kgBB. Prandial (analog): Novorapid/Aspart atau Apidra/Glulisin. Basal (analog): Lantus/Glargine atau Levemir/Detemir' },
  { system: 'Endokrin & Metabolik', diagnosis: 'Neuropati Diabetik', classification: 'Awal/simptomatik', therapy: 'Pregabalin (Lyrica) 2x75 mg PO, naik bertahap' },
  { system: 'Endokrin & Metabolik', diagnosis: 'Neuropati Diabetik', classification: 'Terapi tepat sasaran', therapy: 'Mecobalamin (Vit B12)' },
  { system: 'Endokrin & Metabolik', diagnosis: 'Hipoglikemia', classification: 'Ringan', therapy: 'Larutan gula 15-20 gr dalam 15 menit (2-3 sdm)' },
  { system: 'Endokrin & Metabolik', diagnosis: 'Hipoglikemia', classification: 'Berat', therapy: 'Bolus D40% 1 flakon (25cc) atau D10% 150cc, lanjut D10% 100cc/jam' },
  { system: 'Endokrin & Metabolik', diagnosis: 'Dislipidemia', classification: 'Hiperkolesterolemia', therapy: 'Statin (malam hari)' },
  { system: 'Endokrin & Metabolik', diagnosis: 'Dislipidemia', classification: 'Trigliserida >500', therapy: 'Gemfibrozil 2x600 mg, atau Fenofibrat 300 mg' },
  { system: 'Endokrin & Metabolik', diagnosis: 'Dislipidemia', classification: 'HDL <40 saja', therapy: 'Asam Nikotinat (Niasin) 500-750 mg' },
  { system: 'Endokrin & Metabolik', diagnosis: 'Obesitas', classification: 'Non-farmako', therapy: 'Defisit kalori 500-1000 kkal/hari + aktivitas fisik' },
  { system: 'Endokrin & Metabolik', diagnosis: 'Obesitas', classification: 'Farmako', therapy: 'Orlistat' },
  { system: 'Endokrin & Metabolik', diagnosis: 'Obesitas', classification: 'Bedah (IMT >35)', therapy: 'Restrictive/Hybrid Bariatric Surgery' },
  { system: 'Endokrin & Metabolik', diagnosis: 'Hipertiroid', classification: 'Mild', therapy: 'Metimazol 3x5 mg/hari' },
  { system: 'Endokrin & Metabolik', diagnosis: 'Hipertiroid', classification: 'Moderate', therapy: 'Metimazol 3x10 mg/hari' },
  { system: 'Endokrin & Metabolik', diagnosis: 'Hipertiroid', classification: 'Severe', therapy: 'Metimazol 3x20 mg/hari' },
  { system: 'Endokrin & Metabolik', diagnosis: 'Hipertiroid', classification: 'Bumil trimester 1', therapy: 'PTU 3x100-200 mg (300-600 mg/hari)' },
  { system: 'Endokrin & Metabolik', diagnosis: 'Krisis Tiroid', therapy: 'PTU 600-1000 mg atau Metimazol 6x20 mg + loading cairan, Lugol/iodide 6-8 tetes/jam, Propranolol IV/60 mg oral' },
  { system: 'Endokrin & Metabolik', diagnosis: 'Hipertiroid (radioterapi pre-op)', therapy: 'Radioaktif Iodine-131' },
  { system: 'Endokrin & Metabolik', diagnosis: 'Hipotiroid', therapy: 'Levotiroksin 1x25-50 mcg/hari' },
  { system: 'Endokrin & Metabolik', diagnosis: 'Koma Miksedema', therapy: 'Levotiroksin 1x200-500 mcg IV, lanjut 100 mcg/hari sampai stabil' },
  { system: 'Endokrin & Metabolik', diagnosis: 'Hipoparatiroid', therapy: 'Ca Glukonas 1000 mg + Vit D' },
  { system: 'Endokrin & Metabolik', diagnosis: 'Addison Disease (Hipoadrenal)', therapy: 'Hidrokortison 10-25 mg' },
  { system: 'Endokrin & Metabolik', diagnosis: 'Krisis Adrenal', therapy: 'Awal: infus NaCl; Hidrokortison 100 mg bolus, lanjut 100 mg/4-6 jam' },

  // Gastroenterologi
  { system: 'Gastroenterologi', diagnosis: 'Dispepsia', classification: 'Step-up', therapy: 'Antasida/Ranitidin → PPI' },
  { system: 'Gastroenterologi', diagnosis: 'Dispepsia dengan Epigastric Pain', therapy: 'PPI (mnemonik ROLE-P): Rabeprazole 10mg, Omeprazole 20mg, Lansoprazole 30mg, Esomeprazole 40mg, Pantoprazole 40mg' },
  { system: 'Gastroenterologi', diagnosis: 'Dispepsia dengan Post-Prandial Fullness', therapy: 'Prokinetik: Domperidone/Metoklopramid 3x10 mg' },
  { system: 'Gastroenterologi', diagnosis: 'Dispepsia', classification: 'Bumil', therapy: 'Antasida/Ranitidin saja' },
  { system: 'Gastroenterologi', diagnosis: 'Dispepsia (naikkan faktor defensif)', therapy: 'Sukralfat, Misoprostol' },
  { system: 'Gastroenterologi', diagnosis: 'GERD', classification: 'PPI test', therapy: 'PPI dosis ganda' },
  { system: 'Gastroenterologi', diagnosis: 'GERD', classification: 'Step-down', therapy: 'PPI dosis tunggal → Antasida/Ranitidin' },
  { system: 'Gastroenterologi', diagnosis: 'Ulkus Gaster/Peptikum/Duodenal', classification: 'Step-down', therapy: 'PPI → Antasida/Ranitidin' },
  { system: 'Gastroenterologi', diagnosis: 'Gastritis (H. pylori)', classification: 'Triple therapy (lini 1)', therapy: 'O-K-A: Omeprazole 2x20 + Klaritromisin 2x500 + Amoksisilin 2x1000' },
  { system: 'Gastroenterologi', diagnosis: 'Gastritis (H. pylori)', classification: 'Quadruple (lini 2)', therapy: 'Ter-Bom: Tetrasiklin 4x250 + Bismuth 2x2 + Omeprazole + Metronidazol' },
  { system: 'Gastroenterologi', diagnosis: 'Gastritis (H. pylori)', classification: 'Lini 3', therapy: 'M-OKA: Metronidazol 3x500 + OKA' },
  { system: 'Gastroenterologi', diagnosis: 'IBS', classification: 'Tipe diare', therapy: 'Loperamid (agonis opioid); jika ada infeksi/berdarah: Atapulgit 600mg' },
  { system: 'Gastroenterologi', diagnosis: 'IBS', classification: 'Tipe konstipasi', therapy: 'Bisacodyl (Dulcolax), Polietilen glikol (PEG), Sodium bifosfat enema' },
  { system: 'Gastroenterologi', diagnosis: 'IBS', classification: 'Tipe nyeri perut', therapy: 'Papaverin, Hyoscine Butylbromide' },
  { system: 'Gastroenterologi', diagnosis: 'Diare — Giardiasis', therapy: 'Metronidazol 3x250 mg 5 hari' },
  { system: 'Gastroenterologi', diagnosis: 'Diare — Kolera', therapy: 'Tetrasiklin 3x500 mg 2 hari, atau Doksisiklin 300mg SD, atau Azitromisin 1gr SD (anak: 15 mg/kgBB hari 1, lanjut 7.5 mg/kgBB hari 2-5)' },
  { system: 'Gastroenterologi', diagnosis: 'Diare — ETEC/EPEC', therapy: 'Ciprofloxacin 2x500 5 hari' },
  { system: 'Gastroenterologi', diagnosis: 'Disentri — EHEC/EIEC/Shigellosis', therapy: 'Ciprofloxacin 2x500 5 hari' },
  { system: 'Gastroenterologi', diagnosis: 'Disentri — Amoebiasis', therapy: 'Metronidazol 4x500 mg 5 hari' },
  { system: 'Gastroenterologi', diagnosis: 'Disentri — Balantidiasis', therapy: 'Tetrasiklin 4x500 mg, atau Metronidazol 3x500 mg 5 hari' },
  { system: 'Gastroenterologi', diagnosis: 'Infeksi Clostridium botulinum', therapy: 'Human Botulism Immunoglobulin 50 mg/kg SD' },
  { system: 'Gastroenterologi', diagnosis: 'Infeksi Clostridium perfringens', therapy: 'Penicillin G 2-4 jt unit/6 jam IV' },
  { system: 'Gastroenterologi', diagnosis: 'C. difficile / kolitis pseudomembran', therapy: 'Stop antibiotik pemicu, Metronidazol 4x250-500 mg 7-14 hari' },
  { system: 'Gastroenterologi', diagnosis: 'Appendisitis akut', therapy: 'Tatalaksana bedah (apendektomi) — terapi definitif, bukan farmakologis' },

  // Hepatobilier
  { system: 'Hepatobilier', diagnosis: 'Kolelitiasis', therapy: 'Ursodeoxycholic Acid (Urdafalk) 250 mg' },
  { system: 'Hepatobilier', diagnosis: 'Hepatitis (hepatoprotektor)', therapy: 'Curcuma' },
  { system: 'Hepatobilier', diagnosis: 'Hepatitis A', therapy: 'Simptomatik (self-limiting)' },
  { system: 'Hepatobilier', diagnosis: 'Hepatitis B', therapy: 'Antivirus: Lamivudin' },
  { system: 'Hepatobilier', diagnosis: 'Hepatitis C', therapy: 'Ribavirin + Interferon' },
  { system: 'Hepatobilier', diagnosis: 'Abses Hepar — Piogenik', therapy: 'Penicillin; aspirasi abses jika >5cm' },
  { system: 'Hepatobilier', diagnosis: 'Abses Hepar — Amoebik', therapy: 'Metronidazol 3x750 mg' },
  { system: 'Hepatobilier', diagnosis: 'Sirosis Hepatis — hematemesis/melena', therapy: 'Somatostatin' },
  { system: 'Hepatobilier', diagnosis: 'Sirosis Hepatis — profilaksis ensefalopati', therapy: 'Laktulosa (turunkan kadar amonia)' },
  { system: 'Hepatobilier', diagnosis: 'Sirosis Hepatis — profilaksis ruptur varises esofagus', therapy: 'Propranolol' },

  // Hematologi & Onkologi Medik
  { system: 'Hematologi & Onkologi Medik', diagnosis: 'Anemia Mikrositik — defisiensi Fe', therapy: 'Fe elemental 3x60 mg, atau Ferro glukonat 4x1 tab (12% elemental), Ferro sulfat 3x1 tab (20%), Ferro suksinat 3x1 tab (22%), Ferro fumarat 2x1 tab (33%)' },
  { system: 'Hematologi & Onkologi Medik', diagnosis: 'Thalassemia', therapy: 'PRC: (Hb target − Hb sekarang) x 3 x BB; Deferoxamin untuk kelasi besi' },
  { system: 'Hematologi & Onkologi Medik', diagnosis: 'Anemia Normositik — Hemolitik', therapy: 'Steroid' },
  { system: 'Hematologi & Onkologi Medik', diagnosis: 'Anemia Megaloblastik — defisiensi B12', therapy: 'Vit B12 (Cyanocobalamin) IM' },
  { system: 'Hematologi & Onkologi Medik', diagnosis: 'Anemia Megaloblastik — defisiensi asam folat', therapy: 'Asam folat (B9) 1 mg/hari' },
  { system: 'Hematologi & Onkologi Medik', diagnosis: 'Polisitemia Vera', therapy: 'Flebotomi (target Ht <45%), Aspirin 40-80 mg/hari, Hidroksiurea 2x500 mg' },
  { system: 'Hematologi & Onkologi Medik', diagnosis: 'Von Willebrand Disease', therapy: 'Desmopressin 0.3 mcg/kg IV, konsentrat vWF, kriopresipitat' },

  // Anak — Respirasi
  { system: 'Anak — Respirasi', diagnosis: 'Pertusis', therapy: 'Eritromisin 40-50 mg/kgBB dalam 4 dosis, atau Azitromisin 10 mg/kgBB 5 hari. Alternatif: Kotrimoksazol 8 mg/kgBB TMP dalam 2 dosis 14 hari' },
  { system: 'Anak — Respirasi', diagnosis: 'Bronkiolitis', therapy: 'Simptomatik (oksigen, parasetamol dsb.)' },
  { system: 'Anak — Respirasi', diagnosis: 'Bronkiolitis — profilaksis', therapy: 'Kotrimoksazol 4 mg/kgBB/kali 2x1, atau Amoksisilin 25 mg/kgBB' },
  { system: 'Anak — Respirasi', diagnosis: 'Pneumonia (anak)', therapy: 'Ampisilin 50 mg/kgBB/6 jam + Gentamisin 7.5 mg/kgBB/24 jam' },
  { system: 'Anak — Respirasi', diagnosis: 'TB Anak', therapy: '2 RHZ + 4 RH (tanpa Etambutol). Dosis FDC — 5-9kg: 1 FDC; 10-14kg: 2 FDC; 15-19kg: 3 FDC; 20-32kg: 4 FDC. Profilaksis: INH 10 mg/kgBB selama 6 bulan (kontak + <5 thn/HIV)' },
  { system: 'Anak — Respirasi', diagnosis: 'Asma anak (6-11 thn)', classification: 'Step 1 Intermiten / Step 2 Persisten ringan', therapy: 'ICS dosis rendah' },
  { system: 'Anak — Respirasi', diagnosis: 'Asma anak (6-11 thn)', classification: 'Step 3 Persisten sedang', therapy: 'ICS dosis rendah + LABA, atau ICS dosis sedang' },
  { system: 'Anak — Respirasi', diagnosis: 'Asma anak (6-11 thn)', classification: 'Step 4 Persisten berat', therapy: 'ICS dosis sedang + LABA' },

  // Anak — Neuro
  { system: 'Anak — Neuro', diagnosis: 'Kejang Demam', classification: 'Pre-hospital', therapy: 'Diazepam rektal 5mg (<12kg) / 10mg (>12kg), bisa diulang 2x' },
  { system: 'Anak — Neuro', diagnosis: 'Kejang Demam', classification: 'Di rumah sakit', therapy: 'Diazepam IV 0.2-0.5 mg/kgBB, atau Midazolam 0.2 mg/kgBB IM/bukal, lanjut Fenitoin+NaCl atau Fenobarbital 20 mg/kgBB' },
  { system: 'Anak — Neuro', diagnosis: 'Kejang Demam', classification: 'ICU', therapy: 'Midazolam, Fenobarbital' },
  { system: 'Anak — Neuro', diagnosis: 'Profilaksis Kejang Demam', classification: 'Rumatan', therapy: 'Asam valproat 15-40 mg, atau Fenobarbital 3-4 mg/kgBB' },
  { system: 'Anak — Neuro', diagnosis: 'Profilaksis Kejang Demam', classification: 'Intermiten (tiap demam)', therapy: 'Diazepam oral 0.3 mg/kgBB, atau Diazepam rektal 0.5 mg/kgBB' },

  // Anak — Kardio
  { system: 'Anak — Kardio', diagnosis: 'Penyakit Jantung Bawaan (simptomatik, rujuk!)', therapy: 'Oksigen, infus, morfin' },
  { system: 'Anak — Kardio', diagnosis: 'Patent Ductus Arteriosus (PDA)', therapy: 'Indometasin 0.1-0.2 mg/kg' },

  // Anak — Digestif & Ginjal
  { system: 'Anak — Digestif & Ginjal', diagnosis: 'Diare tanpa dehidrasi', therapy: '<1 thn: 50-100 mL oralit/BAB; >1 thn: 100 mL oralit/BAB' },
  { system: 'Anak — Digestif & Ginjal', diagnosis: 'Diare dehidrasi ringan-sedang', therapy: 'Oralit 75 mL/kgBB/3 jam; Zink <6 bulan: 10 mg, >6 bulan: 20 mg' },
  { system: 'Anak — Digestif & Ginjal', diagnosis: 'Diare dehidrasi berat', therapy: '<1 thn: 30 mL/kgBB (1 jam) + 70 mL/kgBB (5 jam); >1 thn: 30 mL/kgBB (30 menit) + 70 mL/kgBB (2.5 jam); bila tak bisa infus: rujuk + NGT 20 cc/kgBB/jam selama 6 jam' },
  { system: 'Anak — Digestif & Ginjal', diagnosis: 'Syok Hipovolemik (anak)', therapy: 'Guyur RL 20 cc/kgBB secepatnya' },
  { system: 'Anak — Digestif & Ginjal', diagnosis: 'Sindrom Nefritik (anak)', therapy: 'Eritromisin 30 mg/kgBB dalam 3 dosis; awal: diuretik' },
  { system: 'Anak — Digestif & Ginjal', diagnosis: 'Sindrom Nefrotik (anak)', therapy: 'Prednison continuous 2 mg/kgBB (maks. 60mg) 1 bulan, lanjut alternating dose 1.5 mg/kgBB' },

  // Anak — Endokrin & Gizi
  { system: 'Anak — Endokrin & Gizi', diagnosis: 'Hipoglikemia (anak)', classification: 'Sadar', therapy: 'Larutan gula oral (D10% 50cc)' },
  { system: 'Anak — Endokrin & Gizi', diagnosis: 'Hipoglikemia (anak)', classification: 'Tidak sadar', therapy: 'Bolus Dextrose 2 cc/kgBB (selain gizi buruk) — <2 thn: D10%, 2-12 thn: D25%, >12 thn: D50%' },
  { system: 'Anak — Endokrin & Gizi', diagnosis: 'Gizi Buruk — atasi hipoglikemia', therapy: 'Sadar: Dextrose oral (D10% 50cc); Tidak sadar: NGT + bolus D10% 5cc/kgBB' },
  { system: 'Anak — Endokrin & Gizi', diagnosis: 'Gizi Buruk — atasi hipotermia', therapy: 'Lampu 40W jarak 50cm, Perawatan Metode Kanguru' },
  { system: 'Anak — Endokrin & Gizi', diagnosis: 'Gizi Buruk — atasi dehidrasi', therapy: 'ReSoMal (Rehydration Solution for Malnutrition) 5 cc/kgBB/30 menit selama 2 jam' },
  { system: 'Anak — Endokrin & Gizi', diagnosis: 'Alergi susu sapi', therapy: 'Susu terhidrolisat sempurna ekstensif, atau susu asam amino' },
  { system: 'Anak — Endokrin & Gizi', diagnosis: 'Profilaksis alergi susu', therapy: 'Susu terhidrolisat parsial' },
  { system: 'Anak — Endokrin & Gizi', diagnosis: 'Intoleransi laktosa', therapy: 'Susu bebas laktosa' },

  // Anak — Infeksi & NICU
  { system: 'Anak — Infeksi & NICU', diagnosis: 'Campak', therapy: 'Simptomatik + Vit A — <6 bulan: 50.000 IU, <1 thn: 100.000 IU, >1 thn: 200.000 IU' },
  { system: 'Anak — Infeksi & NICU', diagnosis: 'Kawasaki Disease', therapy: 'Aspirin 30 mg/kg/hari terbagi 4 dosis, + IVIG' },
  { system: 'Anak — Infeksi & NICU', diagnosis: 'Scarlet Fever', therapy: 'Penicillin, atau Eritromisin' },
  { system: 'Anak — Infeksi & NICU', diagnosis: 'Hyaline Membrane Disease (prematur)', therapy: 'Injeksi surfaktan' },
  { system: 'Anak — Infeksi & NICU', diagnosis: 'Transient Tachypnea of Newborn (SC elektif)', therapy: 'Laringoskopi direct, suction intratrakeal' },
  { system: 'Anak — Infeksi & NICU', diagnosis: 'Meconium Aspiration Syndrome', therapy: 'Meropenem' },
  { system: 'Anak — Infeksi & NICU', diagnosis: 'Pneumonia Kongenital', therapy: 'Ampisilin 50 mg/kgBB/6 jam + Gentamisin 7.5 mg/kgBB/24 jam' },

  // Kardiovaskular (dewasa)
  { system: 'Kardiovaskular', diagnosis: 'SVT (HR>150), stabil', therapy: 'Manuver vagal 10 menit (cek kontraindikasi dulu); Adenosin 6mg IV → 12mg IV; atau CCB (Verapamil 80-120mg/Diltiazem 10mg) atau BB (Bisoprolol 5-10mg PO/bolus IV)' },
  { system: 'Kardiovaskular', diagnosis: 'SVT, tidak stabil', therapy: 'Kardioversi 50-100J (narrow regular)' },
  { system: 'Kardiovaskular', diagnosis: 'Sinus Bradikardi (HR<60), reguler', therapy: 'Observasi (stabil) / Atropin 1mg IV (tidak stabil)' },
  { system: 'Kardiovaskular', diagnosis: 'PEA (tanpa nadi)', therapy: 'RJP + Epinefrin' },
  { system: 'Kardiovaskular', diagnosis: 'AV Blok derajat I-IIa', therapy: 'Observasi (stabil) / Atropin 1mg IV (tidak stabil)' },
  { system: 'Kardiovaskular', diagnosis: 'AV Blok derajat IIb-III', therapy: 'Pacemaker' },
  { system: 'Kardiovaskular', diagnosis: 'Sinus Takikardi (HR>100), stabil', therapy: 'Amiodaron 300mg IV 10-20 menit → 150mg (atasi penyakit dasar!)' },
  { system: 'Kardiovaskular', diagnosis: 'Sinus Takikardi, tidak stabil', therapy: 'Kardioversi 50-100J (narrow regular)' },
  { system: 'Kardiovaskular', diagnosis: 'Atrial Fibrilasi, stabil', therapy: 'Mnemonik ABCD: BB → CCB → Digoxin. Bila AF+CHF (pulsus defisit): langsung Digoxin 0.125-0.5mg' },
  { system: 'Kardiovaskular', diagnosis: 'Atrial Fibrilasi, tidak stabil', therapy: 'Kardioversi 120-200J (narrow irregular)' },
  { system: 'Kardiovaskular', diagnosis: 'Atrial Fibrilasi — profilaksis emboli (CHA2DS2-VASc)', therapy: 'Bila ada gangguan katup/mitral stenosis: Warfarin (AVK); tanpa itu: Rivaroxaban/Dabigatran/Apixaban (antikoagulan oral baru)' },
  { system: 'Kardiovaskular', diagnosis: 'Atrial Flutter, stabil', therapy: 'BB selektif (Bisoprolol 5-10mg PO/Atenolol 25-50mg PO/Metoprolol 2x50-100mg PO), atau CCB (Verapamil 2x40/Diltiazem 3x30)' },
  { system: 'Kardiovaskular', diagnosis: 'Atrial Flutter, tidak stabil', therapy: 'Kardioversi 50-100J (narrow regular)' },
  { system: 'Kardiovaskular', diagnosis: 'Ventricular Tachycardia (VT), stabil', therapy: 'Amiodaron 300mg, atau Prokainamid 20-50mg' },
  { system: 'Kardiovaskular', diagnosis: 'VT, tidak stabil + nadi', therapy: 'Kardioversi 100J (wide regular)' },
  { system: 'Kardiovaskular', diagnosis: 'Torsade de Pointes, stabil', therapy: 'MgSO4 20% 1-2g IV' },
  { system: 'Kardiovaskular', diagnosis: 'Torsade / polimorfik tanpa nadi', therapy: 'Defibrilasi 200J (bifasik)/360J (monofasik)' },
  { system: 'Kardiovaskular', diagnosis: 'Cardiac Arrest — VF/VT tanpa nadi (shockable)', therapy: 'Defibrilasi 200J (bifasik)/360J (monofasik) tiap sebelum RJP; Epinefrin mulai di RJP ke-2, alternating dengan Amiodaron 300→150' },
  { system: 'Kardiovaskular', diagnosis: 'Cardiac Arrest — Asistol/PEA (non-shockable)', therapy: 'RJP + Epinefrin 1mg segera, ulangi tiap siklus RJP' },
  { system: 'Kardiovaskular', diagnosis: 'PVC/PAC (premature complex)', therapy: 'BB, atau CCB non-dihidropiridin (Verapamil)' },
  { system: 'Kardiovaskular', diagnosis: 'Hipokalemia (gelombang U, K<3.5)', therapy: 'KCl IV 20 mEq/jam' },
  { system: 'Kardiovaskular', diagnosis: 'Hiperkalemia (T tall, K>5.5)', therapy: 'Ca Glukonas 10% 20mL IV 10 menit, atau Insulin 10 IU dalam 50mL D40% (bila EKG masih normal)' },
  { system: 'Kardiovaskular', diagnosis: 'Hipokalsemia (Long QT interval)', therapy: 'Ca Glukonas 10% 20mL IV 10 menit' },
  { system: 'Kardiovaskular', diagnosis: 'ACS — tatalaksana awal', therapy: 'Oksigen (bila SpO2<95%), Aspirin 160-320mg, Nitrat sublingual 5mg maks 3x (cek KI dulu), Clopidogrel 300mg, Morfin (injeksi 2-4mg/oral 5-10mg)' },
  { system: 'Kardiovaskular', diagnosis: 'STEMI definitif', therapy: '<12 jam: Primary PCI (jika jarak rujuk PCI >2 jam, fibrinolitik dulu). Fibrinolitik: Streptokinase 1.5jt 30-60 menit, atau Alteplase 15mg IV bolus (KI: riwayat stroke <6 bulan). >12 jam: antikoagulan' },
  { system: 'Kardiovaskular', diagnosis: 'NSTEMI/UAP definitif', therapy: 'Antikoagulan LMWH 5 hari — Fondaparinux 2.5mg SC (KI: CKD), atau Enoxaparin 1mg/kg 2x1' },
  { system: 'Kardiovaskular', diagnosis: 'Angina Prinzmetal', therapy: 'CCB (untuk kontrol)' },
  { system: 'Kardiovaskular', diagnosis: 'ACS profilaksis', therapy: 'Aspirin 80mg' },
  { system: 'Kardiovaskular', diagnosis: 'Edema Paru Akut', therapy: 'Oksigen/intubasi, Nitrat sublingual/Nitrogliserin, Furosemid IV 0.5-1mg/kgBB, Morfin IV 2-4mg' },
  { system: 'Kardiovaskular', diagnosis: 'CHF — sesak/udem', therapy: 'Furosemid IV 0.5-1mg/kgBB. Mnemonik ABSD: ACE-i/ARB, Beta-blocker, Spironolakton, stop semua ganti Digoksin bila AF+CHF' },
  { system: 'Kardiovaskular', diagnosis: 'Intoksikasi Digoksin', therapy: 'Charcoal, Kolestiramin, anti-aritmia' },
  { system: 'Kardiovaskular', diagnosis: 'Hipertensi Primer/Esensial', therapy: 'HCT (tiazid 12.5-50mg), ACE-i/ARB (Captopril 2x25/Candesartan 8mg), BB (Bisoprolol/Propranolol), CCB (Amlodipin 5-10mg/Verapamil/Diltiazem)' },
  { system: 'Kardiovaskular', diagnosis: 'Hipertensi Urgency', therapy: 'Captopril sublingual' },
  { system: 'Kardiovaskular', diagnosis: 'Hipertensi Emergency', therapy: 'Nicardipin IV 0.5 mcg/kg/menit, atau Diltiazem IV 5-15 mcg/kg/menit' },
  { system: 'Kardiovaskular', diagnosis: 'Penyakit Jantung Rematik', therapy: 'Penisilin (Eritromisin bila alergi); profilaksis: Penisilin 1x/bulan selama 5 tahun (10 tahun bila ada tanda karditis)' },
  { system: 'Kardiovaskular', diagnosis: 'PAD → TAO/ALI/CLI, awal', therapy: 'Cilostazol 2x100mg PO' },
  { system: 'Kardiovaskular', diagnosis: 'PAD, definitif', therapy: 'Revaskularisasi (stent)' },
  { system: 'Kardiovaskular', diagnosis: 'CVI (insufisiensi vena kronis), awal', therapy: 'Stocking compression / injeksi skleroterapi' },
  { system: 'Kardiovaskular', diagnosis: 'DVT', therapy: 'Heparin 5000 unit IV' },
  { system: 'Kardiovaskular', diagnosis: 'Syok Kardiogenik (berdasarkan hemodinamik/TD & suhu kulit)', therapy: 'TD>100: Nitrogliserin 10-20 mcg/menit IV. TD 70-100 hangat: Dobutamin 2-20 mcg/kg/menit IV. TD 70-100 dingin: Dopamin 5-15 mcg/kg/menit IV. TD<70: Norepinefrin 0.5-30 mcg/kg/menit IV' },

  // Respirasi (dewasa)
  { system: 'Respirasi', diagnosis: 'Asma (kontrol jangka panjang)', classification: 'Intermiten', therapy: 'Step 1: ICS 200-400 mcg + LABA/SABA bila perlu' },
  { system: 'Respirasi', diagnosis: 'Asma', classification: 'Persisten ringan', therapy: 'Step 2: ICS 200-400 mcg + LABA bila perlu' },
  { system: 'Respirasi', diagnosis: 'Asma', classification: 'Persisten sedang', therapy: 'Step 3: ICS 200-400 mcg + LABA harian' },
  { system: 'Respirasi', diagnosis: 'Asma', classification: 'Persisten berat', therapy: 'Step 4: ICS 400-800 mcg + LABA harian; Step 5: ICS>800 mcg + LAMA + kortikosteroid oral + teofilin + antileukotrien' },
  { system: 'Respirasi', diagnosis: 'Serangan Asma', classification: 'Awal', therapy: 'Oksigen 2-4 lpm, nebul SABA (Ventolin 2.5mg); bila tak ada nebulizer: SC Terbutalin (SABA) 0.3-0.5mg / Aminofilin / Epinefrin 1:1000 0.3mL' },
  { system: 'Respirasi', diagnosis: 'Serangan Asma Ringan', therapy: 'Bila respon baik: pulang dengan SABA + kortikosteroid oral 3-5 hari' },
  { system: 'Respirasi', diagnosis: 'Serangan Asma Sedang', therapy: 'SABA + SAMA (Combivent) — rawat inap bila gagal 3x' },
  { system: 'Respirasi', diagnosis: 'Serangan Asma Berat', therapy: 'ICU: kortikosteroid sistemik oral/IV, dsb.' },
  { system: 'Respirasi', diagnosis: 'Asma — controller vs reliever', therapy: 'Controller: ICS (Budesonide/Pulmicort), LABA (Formoterol), kombinasi Symbicort. Reliever: SABA inhalasi (Salbutamol/Ventolin), kortikosteroid oral/IV, antikolinergik (Combivent)' },
  { system: 'Respirasi', diagnosis: 'Pneumonia Komunitas (berdasar CURB-65)', therapy: 'CURB-65 0-1: level 1/2. +komorbid/riwayat antibiotik 3bln: level 1+2/3 (oral). CURB-65>2: level 1+2/3 (IV). >2 + sepsis non-Pseudomonas: level 3/4; Pseudomonas: level 5. Level: 1) Beta-laktam + beta-laktamase, 2) Makrolid, 3) Fluorokuinolon, 4) Sefalosporin gen-3, 5) Karbapenem. Curiga MRSA: Linezolid/Vankomisin' },
  { system: 'Respirasi', diagnosis: 'TB Paru tanpa komplikasi', therapy: 'Kategori 1: 2 RHZE + 4(RH)3. Kategori 2: 2 RHZES + 1 RHZE + 5(RHE)3. Anak: 2 RHZ + 4 RH' },
  { system: 'Respirasi', diagnosis: 'TB — Dosis KDT (berat badan)', therapy: '<37kg: 2 tab 4 FDC; 37-55kg: 3 tab; 55-70kg: 4 tab; >70kg: 5 tab (+ Streptomisin sesuai berat)' },
  { system: 'Respirasi', diagnosis: 'TB — Drug-Induced Hepatitis, ikterus', therapy: 'Stop semua obat' },
  { system: 'Respirasi', diagnosis: 'TB — DIH tanpa RHZ, non-ikterik', therapy: '18-24 minggu regimen ES (Etambutol+Streptomisin)' },
  { system: 'Respirasi', diagnosis: 'TB — Neuritis Perifer (efek samping INH)', therapy: 'Vit B6 (Piridoksin) 50-100 mg/hari' },
  { system: 'Respirasi', diagnosis: 'TB Milier (ekstra paru)', therapy: '2 RHZE + 4 RH + kortikosteroid bila perlu' },
  { system: 'Respirasi', diagnosis: 'Bronkitis Akut', therapy: 'Simptomatik: antitusif/ekspektoran, antipiretik' },
  { system: 'Respirasi', diagnosis: 'Bronkiolitis Akut (dewasa)', therapy: 'Antibiotik, bronkodilator bila perlu' },
  { system: 'Respirasi', diagnosis: 'PPOK (GOLD staging)', therapy: 'Grup A (FEV1>80): vaksin influenza + SAMA/SABA. Grup B (FEV1 50-80): LABA/LAMA. Grup C (FEV1 30-50): LAMA+ICS. Grup D (FEV1<30): LAMA+ICS+Oksigen' },
  { system: 'Respirasi', diagnosis: 'Flu Burung (probable & confirmed)', therapy: 'Oseltamivir 2x75mg 5 hari, atau Zanamivir 2x2 puff 5 hari' },
  { system: 'Respirasi', diagnosis: 'Flu Burung profilaksis/suspek', therapy: 'Oseltamivir 1x75mg 7 hari' },
  { system: 'Respirasi', diagnosis: 'Abses Paru', therapy: 'Klindamisin 600mg IV/8jam atau oral, atau Metronidazol' },
  { system: 'Respirasi', diagnosis: 'Pneumonitis Hipertensif', therapy: 'Prednison' },

  // Neurologi (dewasa)
  { system: 'Neurologi', diagnosis: 'Migrain — abortif non-spesifik', therapy: 'Ibuprofen, dsb.' },
  { system: 'Neurologi', diagnosis: 'Migrain klasik (dengan aura) — abortif', therapy: 'Sumatriptan 2x50-100mg' },
  { system: 'Neurologi', diagnosis: 'Migrain common — abortif', therapy: 'Ergotamin 2x1mg' },
  { system: 'Neurologi', diagnosis: 'Migrain — profilaksis', therapy: 'Propranolol 40-240mg, Amitriptilin, atau Asam valproat 500-1000mg' },
  { system: 'Neurologi', diagnosis: 'Tension Type Headache — abortif', therapy: 'Parasetamol 1000mg, NSAID (Ibuprofen 1-2x400mg, Asam mefenamat 3x500mg), muscle relaxant' },
  { system: 'Neurologi', diagnosis: 'TTH — profilaksis', therapy: 'Amitriptilin 30-75mg' },
  { system: 'Neurologi', diagnosis: 'Cluster Headache — abortif', therapy: 'O2 100% sungkup 10-12 lpm 15-20 menit, Triptan/Ergotamin' },
  { system: 'Neurologi', diagnosis: 'Cluster Headache — profilaksis', therapy: 'CCB (Verapamil, Diltiazem), Litium/Kortikosteroid/Amitriptilin' },
  { system: 'Neurologi', diagnosis: 'Neuralgia Trigeminal', therapy: 'Carbamazepin 2x100mg (maks 600-1200mg), Gabapentin, Amitriptilin' },
  { system: 'Neurologi', diagnosis: 'Neuralgia Post-Herpetik', therapy: 'Gabapentin 300mg naik ke 600mg, atau Asam valproat/Amitriptilin/Carbamazepin' },
  { system: 'Neurologi', diagnosis: 'Kejang Parsial', therapy: 'Carbamazepin 2x100mg, maintenance 800-1200mg, atau Fenitoin' },
  { system: 'Neurologi', diagnosis: 'Petit Mal (Absence)', therapy: 'Etosuksimid 1-2x250mg maintenance 20-30 mg/kg, atau Asam valproat' },
  { system: 'Neurologi', diagnosis: 'Grand Mal / Mioklonik / Atonik', therapy: 'Asam valproat 15 mg/kg/hari 2-3x (maks 60 mg/kg), atau Fenitoin 300-400mg' },
  { system: 'Neurologi', diagnosis: 'Kejang pada ibu hamil', therapy: 'Lamotrigin/Gabapentin/Fenitoin' },
  { system: 'Neurologi', diagnosis: 'Status Epileptikus stage II', therapy: 'Diazepam 0.15-0.2 mg/kg, maks 10mg' },
  { system: 'Neurologi', diagnosis: 'Status Epileptikus stage III', therapy: 'Fenitoin 20 mg/kg, maks 1500mg' },
  { system: 'Neurologi', diagnosis: 'Status Epileptikus stage IV', therapy: 'Midazolam' },
  { system: 'Neurologi', diagnosis: 'Rabies — tatalaksana awal', therapy: 'Cuci air mengalir + sabun 10-15 menit' },
  { system: 'Neurologi', diagnosis: 'Rabies — hewan tak ditangkap, risiko minimal', therapy: 'VAR 0.5mL 4 dosis: hari 0 (2x), 7 (1x), 21 (1x)' },
  { system: 'Neurologi', diagnosis: 'Rabies — risiko tinggi', therapy: 'VAR + SAR heterolog 40 IU/kgBB, atau homolog 20 IU/kgBB' },
  { system: 'Neurologi', diagnosis: 'Tetanus — kejang', therapy: 'Diazepam IV 0.1-0.3 mg/kg/kali tiap 2-4 jam' },
  { system: 'Neurologi', diagnosis: 'Tetanus — antibiotik', therapy: 'Penisilin Prokain 50.000 IU/kg/kali tiap 12 jam; Metronidazol loading 15mg/kg/jam lanjut 7.5mg/kg/6jam 7-10 hari' },
  { system: 'Neurologi', diagnosis: 'Tetanus — ATS (perlu skin test dulu)', therapy: '50.000-100.000 IU dibagi 3 dosis (0-7-21)' },
  { system: 'Neurologi', diagnosis: 'Tetanus — HTIG', therapy: '3000-6000 IU IM' },
  { system: 'Neurologi', diagnosis: 'Meningitis Bakterial', therapy: 'Ceftriaxone + Vankomisin + Deksametason' },
  { system: 'Neurologi', diagnosis: 'Meningitis pada bayi <3 bulan', therapy: 'Ampisilin + Cefotaxime' },
  { system: 'Neurologi', diagnosis: 'Meningitis TB', therapy: 'OAT kategori 1 selama 9-12 bulan + Prednison' },
  { system: 'Neurologi', diagnosis: 'Meningitis Cryptococcus (jamur)', therapy: 'Amfoterisin B + Flukonazol' },
  { system: 'Neurologi', diagnosis: 'Toksoplasma Cerebri (multiple ring enhancement)', therapy: 'Pirimetamin + Sulfadiazin/Klindamisin' },
  { system: 'Neurologi', diagnosis: 'Abses Cerebri (soliter ring enhancement)', therapy: 'Metronidazol 500mg/8jam IV + Ceftriaxone IV' },
  { system: 'Neurologi', diagnosis: 'Guillain-Barré Syndrome', therapy: 'Plasmaferesis (200-250 mL plasma/kg 7-14 hari), atau IVIG/Kortikosteroid' },
  { system: 'Neurologi', diagnosis: 'Myasthenia Gravis', therapy: "Acetylcholinesterase inhibitor ('stigmin': Pyridostigmine, Neostigmine) + Timektomi bila perlu" },
  { system: 'Neurologi', diagnosis: 'Krisis Miastenik', therapy: 'Ventilator + kortikosteroid dosis tinggi + plasmaferesis/IVIG' },
  { system: 'Neurologi', diagnosis: 'Krisis Kolinergik', therapy: 'Ventilator + Atropin' },
  { system: 'Neurologi', diagnosis: "Bell's Palsy", therapy: 'Prednison 60mg/hari selama 5 hari, tapp-off 5mg/hari (selama 2 minggu) + eye patch/artificial tear' },
  { system: 'Neurologi', diagnosis: 'Demensia', therapy: 'Donepezil 5mg, Acetylcholinesterase inhibitor lain (Galantamine)' },
  { system: 'Neurologi', diagnosis: 'Sindrom Parkinson (berdasarkan usia)', therapy: '<50 tahun: Amantadin. 50-59 tahun: Bromokriptin. >60 tahun: Levodopa. Efek samping paling sedikit untuk usia muda: Pramipeksol' },
  { system: 'Neurologi', diagnosis: 'Stroke Iskemik <3 jam', therapy: 'rTPA: Alteplase 0.6-0.9 mg/kg' },
  { system: 'Neurologi', diagnosis: 'Stroke Iskemik >3 jam', therapy: 'Aspirin 80mg, Clopidogrel 75mg' },
  { system: 'Neurologi', diagnosis: 'Stroke Hemoragik — Intraserebral', therapy: 'Antifibrinolitik: asam traneksamat' },
  { system: 'Neurologi', diagnosis: 'Stroke Hemoragik — Subarachnoid', therapy: 'CCB: Nimodipin 15 mg/kg/jam, naik ke 30mg' },
  { system: 'Neurologi', diagnosis: 'Stroke Hemoragik — tatalaksana awal', therapy: 'Primary survey (ABCD); Manitol 20% loading 0.5-1 g/kg/20 menit lanjut 0.25-0.5 g/kg/4-6 jam, atau NaCl 3% + posisi semi-fowler' },
  { system: 'Neurologi', diagnosis: 'Transient Ischemic Attack (TIA)', therapy: 'Antiplatelet (Aspirin); bila akibat emboli: antikoagulan (Warfarin)' },
  { system: 'Neurologi', diagnosis: 'Trauma Medula Spinalis (bulbocavernosus +)', therapy: '<3 jam: Metilprednisolon IV bolus 30 mg/15 menit, istirahat 45 menit, lanjut 23 jam berikutnya 5.4 mg/kg/jam. 3-8 jam: lanjut 47 jam berikutnya 5.4 mg/kg/jam' },
  { system: 'Neurologi', diagnosis: 'Syok Spinal (bulbocavernosus −, DD Trauma Medula Spinalis)', therapy: 'Vasopressor' },
  { system: 'Neurologi', diagnosis: 'Carpal Tunnel Syndrome', therapy: 'Wrist splint 3-4 minggu, injeksi kortikosteroid, analgetik (Na Diklofenak, Gabapentin)' },
  { system: 'Neurologi', diagnosis: 'HNP (Hernia Nukleus Pulposus)', therapy: 'NSAID' },
  { system: 'Neurologi', diagnosis: 'Periodik Paralisis', therapy: 'KSR (kalium) 3x1' },
  { system: 'Neurologi', diagnosis: 'Chorea Huntington', therapy: 'Haloperidol' },
  { system: 'Neurologi', diagnosis: 'Sydenham Chorea', therapy: 'Penisilin (demam rematik) + Haloperidol' },
  { system: 'Neurologi', diagnosis: 'Tremor', therapy: 'Propranolol 60-80mg' },

  // Psikiatri
  { system: 'Psikiatri', diagnosis: 'Intoksikasi Opioid', therapy: 'Naloxone 0.4-0.8mg, bisa sampai 2mg, maks 10mg' },
  { system: 'Psikiatri', diagnosis: 'Withdrawal Opioid', therapy: 'Metadon 20-30mg (maks 50mg), atau Klonidin' },
  { system: 'Psikiatri', diagnosis: 'Intoksikasi Alkohol', therapy: 'Thiamin (B1) / Etanol-Metanol / Fomepizole' },
  { system: 'Psikiatri', diagnosis: 'Withdrawal Alkohol', therapy: 'Benzodiazepin 5-20mg tiap 4-6 jam' },
  { system: 'Psikiatri', diagnosis: 'Intoksikasi Benzodiazepin', therapy: 'Flumazenil 0.2mg IV' },
  { system: 'Psikiatri', diagnosis: 'Withdrawal Benzodiazepin', therapy: 'Fenobarbital' },
  { system: 'Psikiatri', diagnosis: 'Intoksikasi Stimulan (Amfetamin/MDMA/kokain/ketamin)', therapy: 'Simtomatik' },
  { system: 'Psikiatri', diagnosis: 'Withdrawal Stimulan', therapy: 'Bromokriptin' },
  { system: 'Psikiatri', diagnosis: 'Intoksikasi Halusinogen (ganja, LSD)', therapy: 'Simtomatik' },
  { system: 'Psikiatri', diagnosis: 'Kecanduan Rokok', therapy: 'Bupropion 2x150mg, atau Vareniklin Tartrat 2x1mg selama 12 minggu' },
  { system: 'Psikiatri', diagnosis: 'Keracunan Sianida', therapy: 'Natrium Thiosulfat' },
  { system: 'Psikiatri', diagnosis: 'Keracunan Jengkolat', therapy: 'Natrium Bikarbonat' },
  { system: 'Psikiatri', diagnosis: 'Keracunan Organofosfat', therapy: 'Sulfas Atropin 2mg IV' },
  { system: 'Psikiatri', diagnosis: 'Psikosis — Antipsikotik tipikal (AP1)', therapy: 'Haloperidol 5-15mg IM tiap 4-6 jam (maks 20mg/hari), atau Klorpromazin 150-600mg atau 50-100mg IM tiap 4-6 jam' },
  { system: 'Psikiatri', diagnosis: 'Psikosis — Antipsikotik atipikal (AP2)', therapy: 'Risperidon 2x2mg, Clozapin 1-2x12.5mg (untuk skizofrenia refrakter), Olanzapin 10-20mg' },
  { system: 'Psikiatri', diagnosis: 'Psikosis Organik (Delirium)', therapy: 'Haloperidol tab 0.5-1.5mg' },
  { system: 'Psikiatri', diagnosis: 'Sindrom Ekstrapiramidal — akatisia', therapy: 'Propranolol (beta-blocker)' },
  { system: 'Psikiatri', diagnosis: 'Sindrom Ekstrapiramidal — distonia akut', therapy: 'Sulfas atropin (Benztropine), Difenhidramin' },
  { system: 'Psikiatri', diagnosis: 'Sindrom Ekstrapiramidal — Parkinsonism/rabbit syndrome', therapy: 'Difenhidramin, Amantadin' },
  { system: 'Psikiatri', diagnosis: 'Neuroleptic Malignant Syndrome', therapy: 'Awal: STOP antipsikotik!! Dantrolen/Bromokriptin/Levodopa-Karbidopa/Benzodiazepin' },
  { system: 'Psikiatri', diagnosis: 'Depresi ringan-sedang (SSRI)', therapy: 'Fluoxetine 1x20mg, atau Sertraline 1x25-50mg' },
  { system: 'Psikiatri', diagnosis: 'Depresi ringan-sedang (Trisiklik)', therapy: 'Amitriptilin 2x25-50mg' },
  { system: 'Psikiatri', diagnosis: 'Gangguan Afektif Bipolar (tipe 1/kini manik)', therapy: 'Mood stabilizer + antipsikotik' },
  { system: 'Psikiatri', diagnosis: 'Gangguan Afektif Bipolar (tipe 2/kini depresi)', therapy: 'Mood stabilizer + antidepresan' },
  { system: 'Psikiatri', diagnosis: 'Mood Stabilizer (pilihan)', therapy: 'Litium 250-500mg, Lamotrigin 1x25mg, Asam valproat 3x250mg, Carbamazepin 2-3x400-600mg' },
  { system: 'Psikiatri', diagnosis: 'Gangguan Cemas (benzodiazepin)', therapy: 'Kerja singkat: Alprazolam 3x0.25-0.5mg. Kerja panjang: Diazepam 2-3x2-5mg/Estazolam/Klordiazepoksid 2-3x5-10mg/Lorazepam 2-3x1mg/Klobazam 2-3x10mg' },
  { system: 'Psikiatri', diagnosis: 'Gangguan Tidur (early/sleep onset insomnia)', therapy: 'Benzodiazepin kerja singkat: Triazolam, Midazolam' },
  { system: 'Psikiatri', diagnosis: 'Gangguan Tidur (middle/maintenance insomnia)', therapy: 'Benzodiazepin kerja panjang: Diazepam/Estazolam/Fenobarbital' },
  { system: 'Psikiatri', diagnosis: 'Gangguan Tidur (late/terminal insomnia)', therapy: 'Antidepresan: Amitriptilin/SSRI' },
  { system: 'Psikiatri', diagnosis: 'Narkolepsi, Hipersomnia', therapy: 'Metilfenidat / Modafinil' },
  { system: 'Psikiatri', diagnosis: 'Gangguan Somatoform', therapy: 'SSRI / Amitriptilin' },
  { system: 'Psikiatri', diagnosis: 'Gangguan Kebiasaan & Impuls (Trikotilomania, dkk)', therapy: 'SSRI' },
  { system: 'Psikiatri', diagnosis: 'Gangguan Makan (Bulimia, Binge Eating)', therapy: 'SSRI' },
  { system: 'Psikiatri', diagnosis: 'Anoreksia Nervosa', therapy: 'Stabilkan kondisi umum, Amitriptilin' },
  { system: 'Psikiatri', diagnosis: 'ADHD — stimulan', therapy: 'Metilfenidat 0.3-0.7 mg/kgBB/hari' },
  { system: 'Psikiatri', diagnosis: 'ADHD — non-stimulan', therapy: 'Atomoxetine 10mg' },
  { system: 'Psikiatri', diagnosis: 'Autism Spectrum Disorder', therapy: 'Antipsikotik AP2 (Risperidon/Aripiprazole) + SSRI' },
  { system: 'Psikiatri', diagnosis: 'Tic / Gilles de la Tourette Syndrome', therapy: 'Antipsikotik AP1 (Haloperidol)' },
  { system: 'Psikiatri', diagnosis: 'Gangguan Post-Partum — Baby Blues', therapy: 'Konseling' },
  { system: 'Psikiatri', diagnosis: 'Gangguan Post-Partum — Depresi', therapy: 'SSRI' },
  { system: 'Psikiatri', diagnosis: 'Gangguan Post-Partum — Psikotik', therapy: 'Antipsikotik AP1' },
  { system: 'Psikiatri', diagnosis: 'Fobia Spesifik (akut)', therapy: 'Benzodiazepin (Alprazolam, Diazepam 3x5mg), desensitisasi, exposure therapy' },
  { system: 'Psikiatri', diagnosis: 'PTSD (stabil/kausal)', therapy: 'SSRI' },

  // Mata
  { system: 'Mata', diagnosis: 'Blefaritis Anterior (Seboroik)', therapy: 'Cuci sampo bayi, kompres hangat + antibiotik topikal' },
  { system: 'Mata', diagnosis: 'Blefaritis Anterior (Ulseratif)', therapy: 'Cuci sampo bayi, kompres hangat + antibiotik topikal + oral' },
  { system: 'Mata', diagnosis: 'Blefaritis Posterior', therapy: 'Eyelid massage arah vertikal + antibiotik topikal + oral' },
  { system: 'Mata', diagnosis: 'Trikiasis, Distrikiasis', therapy: 'Epilasi' },
  { system: 'Mata', diagnosis: 'Entropion, Ektropion', therapy: 'Rujuk untuk rekonstruksi palpebra' },
  { system: 'Mata', diagnosis: 'Konjungtivitis Virus (Adenovirus)', therapy: 'Artificial tear' },
  { system: 'Mata', diagnosis: 'Konjungtivitis Virus (Varicella Zoster)', therapy: 'Asiklovir salep 3% 5x1 selama 10 hari' },
  { system: 'Mata', diagnosis: 'Konjungtivitis Bakteri', therapy: 'Antibiotik topikal (Kloramfenikol 4x1 selama 7 hari)' },
  { system: 'Mata', diagnosis: 'Konjungtivitis Chlamydia (Trakoma)', therapy: 'Antibiotik topikal (Eritromisin 0.5%/Tetrasiklin 1%) + oral (Eritromisin 50 mg/kgBB/hari, atau Doksisiklin 2x100mg 21 hari)' },
  { system: 'Mata', diagnosis: 'Konjungtivitis Gonore (GO)', therapy: 'Irigasi NaCl 4x/hari + antibiotik topikal (Kloramfenikol) + Ceftriaxone IM SD, bisa tambah Azitromisin 1gr IM. Neonatus: irigasi + Cefotaxime 100mg/kgBB IM SD' },
  { system: 'Mata', diagnosis: 'Konjungtivitis Alergi', therapy: 'Hindari alergen; mast cell stabilizer (Sodium Cromoglikat 2%) + antihistamin topikal + steroid topikal' },
  { system: 'Mata', diagnosis: 'Konjungtivitis Sicca (Dry Eye Syndrome)', therapy: 'Artificial tear (Karboksimetilselulosa, sodium hialuronat)' },
  { system: 'Mata', diagnosis: 'Episkleritis', therapy: 'Kortikosteroid topikal + kompres dingin' },
  { system: 'Mata', diagnosis: 'Skleritis', therapy: 'Kortikosteroid sistemik + NSAID' },
  { system: 'Mata', diagnosis: 'Pterygium (awal)', therapy: 'Artificial tear' },
  { system: 'Mata', diagnosis: 'Pterygium (definitif)', therapy: 'Ekstirpasi + conjunctival graft' },
  { system: 'Mata', diagnosis: 'Keratitis Bakteri', therapy: 'Antibiotik topikal (Polygram) + oral; bila GO: Ceftriaxone 1gr IV/12 jam 3 hari (rawat inap)' },
  { system: 'Mata', diagnosis: 'Keratitis Virus', therapy: 'Topikal Asiklovir 3% + Asiklovir oral 5x800mg 7-14 hari' },
  { system: 'Mata', diagnosis: 'Keratitis Jamur (Candida)', therapy: 'Amfoterisin B 1.5%' },
  { system: 'Mata', diagnosis: 'Keratitis Jamur (Aspergillus)', therapy: 'Natamycin 5%' },
  { system: 'Mata', diagnosis: 'Keratitis Acanthamoeba', therapy: 'Amoebisida (Poly Hexa Methylen Biguanide) 0.02%' },
  { system: 'Mata', diagnosis: 'Xeroftalmia', therapy: 'Vit A 30.000 unit/hari selama 1 minggu; dosis usia: <6bln 50.000IU, <1thn 100.000IU, >1thn 200.000IU' },
  { system: 'Mata', diagnosis: 'Uveitis Anterior', therapy: 'Steroid topikal + Sulfas atropin/Siklopentolat 1% (midriasis + sikloplegik)' },
  { system: 'Mata', diagnosis: 'Uveitis Posterior', therapy: 'Steroid topikal + sistemik' },
  { system: 'Mata', diagnosis: 'Glaukoma (akut, awal)', therapy: 'Stop produksi cairan: Acetazolamide 500mg PO lanjut 4x250mg/hari (akut), atau Timolol Maleat 0.5% 2x1 tetes (kronik). Keluarkan cairan: Pilocarpin 2% (miosis), Latanoprost. Simptomatik: antiemetik + analgetik + KCl' },
  { system: 'Mata', diagnosis: 'Kelainan Refraksi — Miopia', therapy: 'Lensa sferis negatif terkecil yang memberi visus terbaik' },
  { system: 'Mata', diagnosis: 'Kelainan Refraksi — Hipermetropia', therapy: 'Lensa sferis positif terbesar yang memberi visus terbaik' },
  { system: 'Mata', diagnosis: 'Kelainan Refraksi — Astigmatisme', therapy: 'Lensa silinder' },
  { system: 'Mata', diagnosis: 'Presbiopia', therapy: '40 tahun: +1.00D; 50 tahun: +2.00D; 60 tahun: +3.00D' },
  { system: 'Mata', diagnosis: 'Dakrioadenitis (virus) / Dakriosistitis (bakteri)', therapy: 'Kompres hangat + antibiotik sistemik + insisi bila abses' },
  { system: 'Mata', diagnosis: 'Hordeolum Eksterna', therapy: 'Kompres hangat + antibiotik topikal + insisi horizontal' },
  { system: 'Mata', diagnosis: 'Hordeolum Interna', therapy: 'Kompres hangat + antibiotik topikal + insisi vertikal' },
  { system: 'Mata', diagnosis: 'Kalazion', therapy: 'Kompres hangat + injeksi steroid + insisi kuretase' },
  { system: 'Mata', diagnosis: 'Xantelasma', therapy: 'Rujuk — diet rendah lemak + eksisi' },
  { system: 'Mata', diagnosis: 'Benda Asing Konjungtiva', therapy: 'Anestesi topikal + ekstraksi dengan lidi kapas + antibiotik topikal' },
  { system: 'Mata', diagnosis: 'Hifema (awal)', therapy: 'Bedrest posisi semi-fowler, sikloplegik topikal + turunkan TIO, asam traneksamat' },
  { system: 'Mata', diagnosis: 'Trauma Asam/Basa Mata', therapy: 'Irigasi segera 15-30 menit dengan 2L NaCl 0.9% per mata, sikloplegia + antibiotik; EDTA untuk trauma basa' },

  // THT
  { system: 'THT', diagnosis: 'Otitis Eksterna Sirkumskripta', therapy: 'Antibiotik topikal (Basitracin, Neomisin, Polymyxin B); definitif: insisi drainase bila furunkel belum pecah; berat: Ampisilin 4x250mg' },
  { system: 'THT', diagnosis: 'Otitis Eksterna Difusa', therapy: 'Tampon antibiotik (Ofloxacin)/Burowi; berat: Ampisilin 4x250mg' },
  { system: 'THT', diagnosis: 'Otitis Eksterna Maligna (+ parese N.VII)', therapy: 'Ciprofloxacin' },
  { system: 'THT', diagnosis: 'Otomikosis (Aspergillus)', therapy: 'Asam asetat 2% (ear/aural toilet) + Miconazole' },
  { system: 'THT', diagnosis: 'Otomikosis (Candida)', therapy: 'Asam asetat 2% + Nystatin' },
  { system: 'THT', diagnosis: 'Serumen Obturans (bila keras)', therapy: 'Carbol gliserin 10% / H2O2 3% selama 3 hari' },
  { system: 'THT', diagnosis: 'Miringitis Bullosa (cegah infeksi sekunder)', therapy: 'Antibiotik (Amoksisilin) + antinyeri + dekongestan' },
]

export const SKDI_SYSTEMS: SkdiSystem[] = [
  'Infeksi Tropis',
  'Rheumatologi',
  'Ginjal & Saluran Kemih',
  'Endokrin & Metabolik',
  'Gastroenterologi',
  'Hepatobilier',
  'Hematologi & Onkologi Medik',
  'Anak — Respirasi',
  'Anak — Neuro',
  'Anak — Kardio',
  'Anak — Digestif & Ginjal',
  'Anak — Endokrin & Gizi',
  'Anak — Infeksi & NICU',
  'Kardiovaskular',
  'Respirasi',
  'Neurologi',
  'Psikiatri',
  'Mata',
  'THT',
]

// Kata Kunci / Eponim — classic diagnostic "keyword" associations used in
// OSCE/UKMPPD prep to quickly recognize a diagnosis from its named sign.
export interface EponymEntry {
  diagnosis: string
  keyword: string
}

export const EPONYM_ENTRIES: EponymEntry[] = [
  { diagnosis: 'Keratokonus', keyword: 'Munson sign, Vogt striae, Rizzuti sign, Charleux sign' },
  { diagnosis: 'Age-related Macular Degeneration (AMD)', keyword: 'Drusen' },
  { diagnosis: 'Dry Eye Syndrome', keyword: 'Foamy tears' },
  { diagnosis: 'Retinitis Pigmentosa', keyword: 'Bone spicule' },
  { diagnosis: 'Trachoma', keyword: 'Herbert pits' },
  { diagnosis: 'Neuritis Optik', keyword: 'Fenomena Pulfrich, efek Uhthoff' },
  { diagnosis: "Grave's Ophthalmopathy", keyword: 'Dalrymple sign' },
  { diagnosis: 'Glaukoma Kongenital', keyword: "Haab's striae, buphthalmos" },
  { diagnosis: 'Presbikusis', keyword: 'Cocktail party sign' },
  { diagnosis: 'Otosklerosis', keyword: 'Paracusis Willisii, Schwartze/Flamingo sign, Carhart notch' },
  { diagnosis: 'Timpanosklerosis', keyword: 'Membran timpani: gambaran semilunar/tapal kuda' },
  { diagnosis: 'Furunkulosis Vestibulum Nasi', keyword: 'Rudolph sign' },
  { diagnosis: 'Fibrosis Kistik', keyword: 'Klorida keringat >60' },
  { diagnosis: 'Duchenne Muscular Dystrophy (DMD)', keyword: 'Gower sign' },
  { diagnosis: 'Cerebral Palsy', keyword: 'Gaya jalan gunting (scissor gait)' },
  { diagnosis: 'Laryngomalasia', keyword: 'Omega shape' },
  { diagnosis: 'Ankylosing Spondylitis', keyword: 'Bamboo spine, Schober test (+)' },
  { diagnosis: 'Guillain-Barré Syndrome', keyword: 'Disosiasi sitoalbumin' },
  { diagnosis: 'Myasthenia Gravis', keyword: 'EMG: Harvey-Masland test (+)' },
  { diagnosis: 'Parkinson Disease', keyword: 'T.R.A.P, Myerson test' },
  { diagnosis: 'Abses Cerebri', keyword: 'Ring enhancement (soliter)' },
  { diagnosis: 'Toksoplasma Cerebri', keyword: 'Multiple ring enhancement' },
  { diagnosis: 'Cryptococcus Meningitis', keyword: 'Tinta india: gambaran telur mata sapi, CT tanpa enhancement' },
  { diagnosis: 'Tiroiditis Hashimoto', keyword: 'Hürthle/Askanazy cells, anti-TPO (+)' },
  { diagnosis: 'Limfedema', keyword: 'Stemmer sign (+)' },
  { diagnosis: 'Von Willebrand Disease', keyword: 'Ristocetin test (+)' },
  { diagnosis: 'Multiple Myeloma', keyword: 'C.R.A.B, Bence Jones protein, M spike, Fried egg cell' },
  { diagnosis: 'Limfoma Hodgkin', keyword: 'Owl eyes (Reed-Sternberg cell)' },
  { diagnosis: "Limfoma Burkitt (Non-Hodgkin)", keyword: 'Starry sky' },
  { diagnosis: 'Anemia Sideroblastik', keyword: 'Ring sideroblast (Perl stain, basophilic stippling)' },
  { diagnosis: 'AML (Acute Myeloid Leukemia)', keyword: 'Auer rods' },
  { diagnosis: 'ALL (Acute Lymphoblastic Leukemia)', keyword: 'Nyeri tulang, blast >20%' },
  { diagnosis: 'CML (Chronic Myeloid Leukemia)', keyword: 'Translokasi 9;22, kromosom Philadelphia' },
  { diagnosis: 'CLL (Chronic Lymphocytic Leukemia)', keyword: 'Smudge cell' },
  { diagnosis: 'Pancoast Syndrome', keyword: 'Horner syndrome + tumor apeks paru' },
  { diagnosis: 'Takotsubo Cardiomyopathy (Broken Heart Syndrome)', keyword: 'Apical ballooning' },
  { diagnosis: 'Intoksikasi Digitalis', keyword: 'Salvador Dali moustache (EKG)' },
  { diagnosis: 'Coarctatio Aorta', keyword: 'Three sign' },
  { diagnosis: 'Transposition of Great Arteries (TGA)', keyword: 'Egg-on-a-string' },
  { diagnosis: 'Tetralogy of Fallot (TOF)', keyword: 'Boot-shaped heart' },
  { diagnosis: 'Ebstein Anomaly', keyword: 'Squared/box-shaped heart' },
  { diagnosis: 'Left Ventricular Enlargement', keyword: 'Shmoo sign' },
  { diagnosis: 'Regurgitasi Aorta', keyword: 'Austin Flint murmur (apex)' },
  { diagnosis: 'Emboli Pulmonal', keyword: "S1Q3T3, Palla sign, Westermark sign, Hampton's hump" },
  { diagnosis: 'Bronkiektasis', keyword: 'Tram-track line' },
  { diagnosis: 'Pityriasis Rosea', keyword: 'Skuama collarette, herald patch' },
  { diagnosis: 'Rubeola / Campak / Morbili', keyword: 'Koplik spot, 3C (cough, coryza, conjunctivitis)' },
  { diagnosis: 'Rubella (Campak Jerman)', keyword: "Forchheimer spot, pembesaran KGB" },
  { diagnosis: 'Roseola Infantum / Exanthema Subitum', keyword: 'Nagayama spot' },
  { diagnosis: 'Alopecia Areata', keyword: 'Exclamation mark hair (rambut tanda seru)' },
  { diagnosis: 'Donovanosis / Granuloma Inguinale', keyword: 'Closed safety pin sign, beefy red' },
  { diagnosis: 'Uretritis Gonore', keyword: 'Bull-headed clap' },
  { diagnosis: 'Lymphogranuloma Venereum (LGV)', keyword: 'Groove sign, "étage" bubonum' },
  { diagnosis: 'Rubella Kongenital', keyword: 'Blueberry muffin baby' },
  { diagnosis: 'Molluscum Contagiosum', keyword: 'Henderson-Patterson bodies' },
  { diagnosis: 'Varicella', keyword: 'Dew drop on rose petal' },
  { diagnosis: 'Sifilis Kongenital', keyword: "Hutchinson teeth" },
  { diagnosis: 'Gemelli Dikorion Diamnion', keyword: 'Lambda sign' },
  { diagnosis: 'Gemelli Monokorion Diamnion', keyword: 'T-sign' },
  { diagnosis: 'Developmental Dysplasia of the Hip', keyword: "Klisic test (+), Galeazzi sign" },
  { diagnosis: 'Achondroplasia (janin)', keyword: 'Trident hand' },
  { diagnosis: 'Ca Caput Pankreas', keyword: 'Virchow node, Sister Mary Joseph nodule, Trousseau syndrome' },
  { diagnosis: 'Adenocarcinoma Papillary Thyroid', keyword: 'Orphan Annie eyes' },
  { diagnosis: 'GIST (Gastrointestinal Stromal Tumor)', keyword: 'CD117, sel spindle Cajal' },
  { diagnosis: 'Schistosomiasis (fase akut)', keyword: 'Demam Siput, Katayama fever' },
  { diagnosis: 'Neurofibromatosis tipe 1', keyword: 'Neurofibromin, café-au-lait spots, Lisch nodule, defek tulang' },
  { diagnosis: 'Spondylolisthesis grade 5', keyword: 'Spondyloptosis' },
  { diagnosis: 'Leishmaniasis Visceral', keyword: 'Amastigot' },
  { diagnosis: 'Trypanosomiasis Amerika (Chagas)', keyword: "Chagoma, tanda Romaña" },
  { diagnosis: "Sindrom Reye", keyword: 'Konsumsi aspirin usia <6 tahun tidak sesuai indikasi' },
  { diagnosis: 'Renal Cell Carcinoma', keyword: 'Flank pain, flank mass, gross hematuria, gen VHL' },
  { diagnosis: 'Ca Buli (Bladder Cancer)', keyword: 'Intermittent, painless, gross hematuria' },
  { diagnosis: 'Scheuermann Disease', keyword: 'Usia muda, kifosis berlebihan' },
  { diagnosis: 'Pierre Robin Sequence', keyword: 'Micrognathia, glossoptosis, labioschizis' },
  { diagnosis: 'Nefroblastoma', keyword: 'Wilms tumor' },
  { diagnosis: 'Abses Hepar', keyword: 'Ludwig sign, chocolate anchovy sauce sign' },
  { diagnosis: 'Fenomena Tetesan Lilin', keyword: 'Kaarsvetlek sign' },
  { diagnosis: 'Dix-Hallpike Maneuver', keyword: 'Nylen-Bárány maneuver' },
  { diagnosis: 'Nyeri Goyang Portio', keyword: 'Candelier sign' },
  { diagnosis: "Racoon's Eye / Hematom Kacamata", keyword: 'Brill hematoma' },
  { diagnosis: "Bogorad Syndrome", keyword: "Crocodile tears syndrome (komplikasi Bell's palsy)" },
  { diagnosis: 'Radial Head Subluxation', keyword: 'Pulled elbow, nursemaid elbow' },
]
