// GENERATED FILE — do not edit by hand.
//
// The disease directory needs to know WHICH diseases have a note before it can
// draw the expand toggle, but the notes themselves are ~1 MB. Loading them just
// to answer that yes/no question meant every visitor to the tab downloaded the
// whole corpus. This index carries only the keys (a few kB), so the notes module
// is fetched lazily the first time a user actually opens a disease.
//
// Regenerate with: npm run gen:note-index
// Drift check: npm run gen:note-index -- --check

export const SKDI_NOTE_KEYS: ReadonlySet<string> = new Set([
  'AIDS dengan komplikasi',
  'Ablasio retina',
  'Aborsi mengancam',
  'Aborsi spontan inkomplit',
  'Aborsi spontan komplit',
  'Abrupsio plasenta',
  'Abses (peri)anal',
  'Abses Bezold',
  'Abses apendiks',
  'Abses folikel rambut atau kelenjar sebasea',
  'Abses hepar amoeba',
  'Abses otak',
  'Abses paru',
  'Abses peritonsilar',
  'Abses tubo-ovarium',
  'Acute Respiratory distress syndrome (ARDS)',
  'Acute kidney injury',
  'Acute medulla compression',
  'Addison\'s disease',
  'Adenoma tiroid',
  'Adiksi/ketergantungan Narkoba',
  'Afakia kongenital',
  'Afasia',
  'Agorafobia dengan/tanpa panik',
  'Agranulositosis',
  'Akalasia',
  'Akne vulgaris ringan',
  'Akne vulgaris sedang-berat',
  'Akondroplasia',
  'Akromegali, gigantisme',
  'Albino',
  'Alergi makanan',
  'Alopesia androgenik',
  'Alopesia areata',
  'Ambliopia',
  'Amnesia pascatrauma',
  'Amyotrophic lateral sclerosis (ALS)',
  'Anemia aplastik',
  'Anemia defisiensi besi',
  'Anemia defisiensi besi pada kehamilan',
  'Anemia hemolitik',
  'Anemia makrositik',
  'Anemia megaloblastik',
  'Aneurisma Aorta',
  'Aneurisma diseksi',
  'Angina Ludwig',
  'Angina pektoris',
  'Angioedema',
  'Anisometropia pada anak',
  'Anisometropia pada dewasa',
  'Anoreksia nervosa',
  'Apendisitis akut',
  'Aritmia lainnya',
  'Arteritis kranial',
  'Artritis reumatoid',
  'Artritis, osteoarthritis',
  'Asfiksia',
  'Askariasis',
  'Asma bronkial',
  'Aspirasi',
  'Astigmatism ringan',
  'Atelektasis',
  'Aterosklerosis',
  'Atresia anus',
  'Atresia biliaris',
  'Atresia esofagus',
  'Atresia intestinal',
  'Atrial flutter',
  'Atrofi optik',
  'Baby blues (post-partum depression)',
  'Bakteremia',
  'Barotrauma',
  'Basal cell carcinoma (Karsinoma sel basal)',
  'Bayi post matur',
  'Bells’ palsy',
  'Benda asing',
  'Benda asing di konjungtiva',
  'Benda asing di kornea',
  'Blefaritis',
  'Botulisme',
  'Bronkiektasis',
  'Bronkiolitis akut',
  'Bronkitis akut',
  'Bulimia',
  'Bundle Branch Block',
  'Buta senja',
  'Carpal tunnel syndrome',
  'Cerebral palsy',
  'Chalazion',
  'Chancroid',
  'Chronic motor of vocal tics disorder',
  'Claw foot, drop foot',
  'Claw hand, drop hand',
  'Cluster headache',
  'Complete spinal transaction',
  'Corpus alienum vaginae',
  'Cracked nipple',
  'Cushing\'s disease',
  'Cutaneus larva migran',
  'DIC (Disseminated Intravascular Coagulation)',
  'Dakrioadenitis',
  'Dakriosistitis',
  'Dakriostenosis',
  'Defisiensi hormon pertumbuhan',
  'Defisiensi mineral',
  'Defisiensi vitamin',
  'Degenerasi makula karena usia',
  'Demam dengue, DHF',
  'Demam reumatik',
  'Demam tifoid',
  'Demensia',
  'Dengue shock syndrome',
  'Depresi endogen, episode tunggal dan rekuran',
  'Dermatitis atopik (kecuali recalcitrant)',
  'Dermatitis kontak alergika',
  'Dermatitis kontak iritan',
  'Dermatitis numularis',
  'Dermatitis perioral',
  'Dermatitis seboroik',
  'Deviasi septum hidung',
  'Diabetes gestasional',
  'Diabetes insipidus',
  'Diabetes melitus tipe 1',
  'Diabetes melitus tipe 2',
  'Difteria (THT)',
  'Diplopia binokuler',
  'Diproporsi kepala panggul',
  'Disentri basiler, disentri amuba',
  'Dislipidemia',
  'Dislokasi lensa',
  'Dislokasi pada sendi ekstremitas',
  'Displasia bronkopulmonar',
  'Displasia fibrosa',
  'Displasia panggul',
  'Distosia',
  'Divertikulosis/divertikulitis',
  'Divertikulum Meckel',
  'Dorsal root syndrome',
  'Duchene muscular dystrophy',
  'Edema kornea',
  'Edema papil',
  'Edema paru',
  'Efusi pleura',
  'Efusi pleura masif',
  'Eklampsia',
  'Ekstrasistol supraventrikular, ventrikular',
  'Emboli arteri',
  'Emboli paru',
  'Emboli vena',
  'Emfisema paru',
  'Empiema dan hidrops kandung empedu',
  'Endoftalmitis',
  'Endometriosis',
  'Endometritis',
  'Ensefalitis',
  'Ensefalopati',
  'Ensefalopati hipertensi',
  'Enterokolitis nekrotik',
  'Entropion',
  'Epididimitis',
  'Epikantus',
  'Epilepsi',
  'Episkleritis',
  'Epispadia',
  'Epistaksis',
  'Erisipelas',
  'Eritema multiformis',
  'Eritrasma',
  'Erosi',
  'Esofagitis refluks',
  'Etmoiditis akut',
  'Exanthematous drug eruption, fixed drug eruption',
  'Faringitis',
  'Fenilketonuria',
  'Fibrilasi atrial',
  'Fibrilasi ventrikular',
  'Fibroadenoma mammae (FAM)',
  'Fibrokista',
  'Fibromatosis, fibroma, fibrosarkoma',
  'Filariasis',
  'Fimosis',
  'Fistula',
  'Fistula (vesiko-vaginal, uretero-vagina, rektovagina)',
  'Fistula dan kista brankial lateral dan medial',
  'Fistula pre-aurikular',
  'Fistula umbilikal, omphalocoele-gastroschisis',
  'Fisura anus',
  'Flu burung',
  'Fobia sosial',
  'Fobia spesifik',
  'Folikulitis superfisialis',
  'Fraktur dan dislokasi tulang belakang',
  'Fraktur klavikula',
  'Fraktur patologis',
  'Fraktur terbuka, tertutup',
  'Functional encoperasis',
  'Functional enuresis',
  'Furunkel pada hidung',
  'Furunkel, karbunkel',
  'Gagal hepar',
  'Gagal jantung akut',
  'Gagal jantung kronik',
  'Gangguan bipolar, episode depresif',
  'Gangguan bipolar, episode manik',
  'Gangguan campuran cemas depresi',
  'Gangguan cemas menyeluruh',
  'Gangguan depresif yang tidak terklasifikasikan',
  'Gangguan disosiasi (konversi)',
  'Gangguan distimia (depresi neurosis)',
  'Gangguan ejakulasi',
  'Gangguan ereksi',
  'Gangguan identitas gender',
  'Gangguan keinginan dan gairah seksual',
  'Gangguan kepribadian',
  'Gangguan lapang pandang',
  'Gangguan obsesif-kompulsif',
  'Gangguan panik',
  'Gangguan pergerakan lainnya',
  'Gangguan perkembangan pervasif',
  'Gangguan preferensi seksual',
  'Gangguan psikotik',
  'Gangguan siklotimia',
  'Gangguan skizoafektif',
  'Gangguan somatoform',
  'Gangguan tingkah laku (conduct disorder)',
  'Gangguan waham',
  'Gastritis',
  'Gastroenteritis (termasuk kolera, giardiasis)',
  'Gastrointestinal Stromal Tumor (GIST)',
  'Gilles de la tourette syndrome',
  'Ginekomastia',
  'Ginjal polikistik simtomatik',
  'Ginjal tapal kuda',
  'Glaukoma akut',
  'Glaukoma lainnya',
  'Glomerulonefritis akut',
  'Glomerulonefritis kronik',
  'Glositis',
  'Goiter',
  'Gonore',
  'Guillain Barre syndrome',
  'HIV AIDS tanpa komplikasi',
  'Haematothorax',
  'Hemangioma',
  'Hematokolpos',
  'Hematom epidural',
  'Hematom intraserebral',
  'Hematom subdural',
  'Hemianopia, bitemporal, and homonymous',
  'Hemoglobinopati',
  'Hemoroid grade 1-2',
  'Hemoroid grade 3-4',
  'Henoch-schoenlein purpura',
  'Hepatitis A',
  'Hepatitis B',
  'Hepatitis C',
  'Hernia (diaframatika, hiatus)',
  'Hernia nucleus pulposus (HNP)',
  'Hernia umbilikalis',
  'Herpes simpleks tanpa komplikasi',
  'Herpes zoster pada telinga',
  'Herpes zoster tanpa komplikasi',
  'Hidradenitis supuratif',
  'Hidrokel',
  'Hidrosefalus',
  'Hifema',
  'Higroma kistik',
  'Hiperemesis gravidarum',
  'Hiperglikemi hiperosmolar',
  'Hipermetropia ringan',
  'Hiperparatiroid',
  'Hiperpigmentasi pascainflamasi',
  'Hiperplasia endometrium',
  'Hiperplasia prostat jinak',
  'Hipersomnia',
  'Hipertensi esensial',
  'Hipertensi pada kehamilan',
  'Hipertensi pulmoner',
  'Hipertensi sekunder',
  'Hipertiroid',
  'Hipertrofi adenoid',
  'Hiperurisemia',
  'Hipoglikemia berat',
  'Hipoglikemia ringan',
  'Hipogonadisme',
  'Hipoksia janin',
  'Hipoparatiroid',
  'Hipopigmentasi pascainflamasi',
  'Hipopion',
  'Hipospadia',
  'Hipotiroid',
  'Hordeolum',
  'Ichthyosis vulgaris',
  'Ileus',
  'Impetigo',
  'Impetigo ulseratif (ektima)',
  'Imunodefisiensi',
  'Infark miokard',
  'Infark paru',
  'Infark serebral',
  'Infeksi intra-uterin: korioamnionitis',
  'Infeksi pada kehamilan: TORCH, hepatitis B, malaria',
  'Infeksi pada umbilikus',
  'Infeksi saluran kemih',
  'Infeksi saluran kemih bagian bawah',
  'Infeksi sitomegalovirus',
  'Infeksi virus Herpes genital',
  'Infertilitas',
  'Inflamasi pada aurikular',
  'Inflamasi, abses',
  'Influenza',
  'Inkompatibilitas darah',
  'Inkompatibilitas golongan darah',
  'Inkompeten serviks',
  'Inkontinensia feses',
  'Inkontinensia urine',
  'Insomnia',
  'Instabilitas sendi tumit',
  'Insufisiensi plasenta',
  'Insufisiensi vena kronik',
  'Intoksikasi akut zat psikoaktif',
  'Intoleransi makanan',
  'Intra-Uterine Fetal Death (IUFD)',
  'Intususepsi atau invaginasi',
  'Inversio uterus',
  'Inverted nipple',
  'Iridosisklitis, iritis',
  'Irritable Bowel Syndrome',
  'Janin tumbuh lambat',
  'Juvenile chronic arthritis',
  'Kandidiasis mulut',
  'Kandidosis mukokutan ringan',
  'Kardiomiopati',
  'Karies gigi',
  'Karsinoma endometrium',
  'Karsinoma kolon',
  'Karsinoma laring',
  'Karsinoma nasofaring',
  'Karsinoma ovarium',
  'Karsinoma pankreas',
  'Karsinoma paru',
  'Karsinoma payudara',
  'Karsinoma prostat',
  'Karsinoma sel renal',
  'Karsinoma serviks',
  'Karsinoma tiroid',
  'Karsinoma uroterial',
  'Katarak',
  'Kehamilan ektopik',
  'Kehamilan ganda',
  'Kehamilan normal',
  'Kehamilan posterm',
  'Kejang',
  'Kejang demam',
  'Kekerasan tajam',
  'Kekerasan tumpul',
  'Kelainan janin',
  'Kelainan letak janin setelah 36 minggu',
  'Kematian mendadak',
  'Keracunan makanan',
  'Keratitis',
  'Kerato-konjungtivitis sicca',
  'Keratokonus',
  'Keratosis seboroik',
  'Ketoasidosis diabetikum nonketotik',
  'Ketuban pecah dini (KPD)',
  'Kista Gartner',
  'Kista Nabotian',
  'Kista dan abses kelenjar bartolini',
  'Kista epitel',
  'Kista ganglion',
  'Kista ovarium',
  'Kistik fibrosis',
  'Kistokel',
  'Klaudikasio',
  'Koarktasio aorta',
  'Kole(doko)litiasis',
  'Kolesistitis',
  'Kolesteatoma',
  'Kolik renal',
  'Kolitis',
  'Kolitis ulseratif',
  'Koma',
  'Kondiloma akuminatum',
  'Konjungtivitis',
  'Kor pulmonale akut',
  'Kor pulmonale kronik',
  'Koriokarsinoma',
  'Korioretinitis',
  'Krisis adrenal',
  'Labirintitis',
  'Lagoftalmus',
  'Laringitis',
  'Laserasi duktus lakrimal',
  'Laserasi kelopak mata',
  'Leiomioma, leiomiosarkoma, liposarkoma',
  'Leishmaniasis dan tripanosomiasis',
  'Lentigo',
  'Lepra',
  'Leptospirosis (tanpa komplikasi)',
  'Lesi batang otak',
  'Lesi korosif pada esofagus',
  'Lesi meniskus, medial, dan lateral',
  'Lesi pada ligamentosa panggul',
  'Leukemia akut, kronik',
  'Leukoplakia',
  'Liken simpleks kronik/neurodermatitis',
  'Limfadenitis',
  'Limfadenopati',
  'Limfangitis',
  'Limfedema (primer, sekunder)',
  'Limfoma',
  'Limfoma non-Hodgkin\'s, Hodgkin\'s',
  'Lipoma',
  'Luka akibat bahan kimia',
  'Luka akibat sengatan listrik',
  'Luka bakar derajat 1 dan 2',
  'Luka bakar derajat 3 dan 4',
  'Luka bakar kornea',
  'Luka listrik dan petir',
  'Luka tembak',
  'Lupus eritematosis kulit',
  'Lupus eritematosus sistemik',
  'Mabuk perjalanan',
  'Malabsorbsi',
  'Malaria',
  'Malaria serebral',
  'Malformasi kongenital',
  'Malformasi kongenital uterus',
  'Malnutrisi energi-protein',
  'Malpresentasi',
  'Malrotasi traktus gastro-intestinal',
  'Mastitis',
  'Mastoiditis',
  'Mata kering',
  'Mati batang otak',
  'Melanoma maligna',
  'Melasma',
  'Meniere\'s disease',
  'Meningitis',
  'Menopause, perimenopausal syndome',
  'Miastenia gravis',
  'Micrognatia and macrognatia',
  'Mieloma multipel',
  'Mielopati',
  'Migren',
  'Mikroftalmos',
  'Mild Cognitive Impairment (MCI)',
  'Miliaria',
  'Miopia ringan',
  'Miringitis bullosa',
  'Mola hidatidosa',
  'Moluskum kontagiosum',
  'Morbili tanpa komplikasi',
  'Multi Drug Resistance (MDR) TB',
  'Napkin eczema',
  'Nekrosis kaput femoris',
  'Nekrosis tubular akut',
  'Neoplasma hepar',
  'Neuralgia trigeminal',
  'Neuritis optik',
  'Neurofibromatosis (Von Recklaing Hausen disease)',
  'Neurogenic bladder',
  'Neuropati',
  'Neuropati optik',
  'Nevus pigmentosus',
  'Nightmare',
  'Nyeri neuropatik',
  'Obesitas',
  'Obstructed venous return',
  'Obstructive Sleep Apnea (OSA)',
  'Optic disc cupping',
  'Osteogenesis imperfekta',
  'Osteomielitis',
  'Osteoporosis',
  'Osteosarkoma',
  'Otitis eksterna',
  'Otitis media akut',
  'Otitis media kronik',
  'Otitis media serosa',
  'Otosklerosis',
  'Pankreatitis',
  'Parafilia',
  'Parafimosis',
  'Parkinson',
  'Parotitis',
  'Partus lama',
  'Pedikulosis kapitis',
  'Pedikulosis pubis',
  'Pembunuhan anak sendiri',
  'Pengguguran kandungan',
  'Penyakit Alzheimer',
  'Penyakit Buerger\'s (Thromboangiitis Obliterans)',
  'Penyakit Crohn',
  'Penyakit Hirschsprung',
  'Penyakit Paget',
  'Penyakit Raynaud',
  'Penyakit cacing tambang',
  'Penyakit ginjal kronik',
  'Penyakit jantung reumatik',
  'Penyakit paru intersisial',
  'Penyakit radang panggul',
  'Perdarahan Vitreous',
  'Perdarahan gastrointestinal',
  'Perdarahan post partum',
  'Perdarahan retina, oklusi pembuluh darah retina',
  'Perdarahan subarakhnoid',
  'Perdarahan subkonjungtiva',
  'Perforasi membran timpani',
  'Perforasi usus',
  'Peritonitis',
  'Perlemakan hepar',
  'Peroneal palsy',
  'Persalinan preterm',
  'Pertusis',
  'Pes',
  'Pica',
  'Pielonefritis tanpa komplikasi',
  'Pitiriasis rosea',
  'Pitiriasis vesikolor',
  'Plasenta previa',
  'Pnemokoniasis',
  'Pneumonia aspirasi',
  'Pneumonia, bronkopneumonia',
  'Pneumothorax',
  'Pneumothorax ventil',
  'Poliarteritis nodosa',
  'Polihidramnion',
  'Polikistik ovarium',
  'Polimialgia reumatik',
  'Polimiositis',
  'Poliomielitis',
  'Polip',
  'Polip serviks',
  'Polip/adenoma',
  'Polisitemia',
  'Porfiria',
  'Post traumatic stress disorder',
  'Preeklampsia',
  'Presbiakusis',
  'Presbiopia',
  'Priapismus',
  'Proktitis',
  'Prolaktinemia',
  'Prolaps rektum, anus',
  'Prolaps tali pusat',
  'Prolaps uterus, sistokel, rektokel',
  'Prostatitis',
  'Pseudo-croop acute epiglotitis',
  'Psoriasis vulgaris',
  'Pterigium',
  'Ptosis',
  'Pubertas prekoks',
  'Rabies',
  'Radicular syndrome',
  'Reaksi anafilaktik',
  'Reaksi gigitan serangga',
  'Reaksi lepra',
  'Reaksi terhadap stres yg berat, & gangguan penyesuaian',
  'Rectratile testis',
  'Reffered pain',
  'Refluks gastroesofagus',
  'Rektokel',
  'Retardasi mental',
  'Retensi plasenta',
  'Retinopati (diabetik, hipertensi, prematur)',
  'Retraksi kelopak mata',
  'Rhabdomiosarkoma',
  'Rhinitis akut',
  'Rhinitis alergika',
  'Rhinitis kronik',
  'Rhinitis medikamentosa',
  'Rhinitis vasomotor',
  'Ricketsia, osteomalasia',
  'Ruptur esofagus',
  'Ruptur ginjal',
  'Ruptur kandung kencing',
  'Ruptur perineum tingkat 1-2',
  'Ruptur perineum tingkat 3-4',
  'Ruptur serviks',
  'Ruptur tendon Achilles',
  'Ruptur uretra',
  'Ruptur uteri',
  'SARS',
  'Salpingitis',
  'Sarcoma Ewing',
  'Seminoma testis',
  'Sepsis',
  'Serumen prop',
  'Servisitis',
  'Sifilis',
  'Sifilis stadium 1 dan 2',
  'Sindrom Horner',
  'Sindrom Reye',
  'Sindrom Stevens-Johnson',
  'Sindrom kauda equine',
  'Sindrom metabolik',
  'Sindrom nefrotik',
  'Sinusitis',
  'Sinusitis frontal akut',
  'Sinusitis kronik',
  'Sinusitis maksilaris akut',
  'Siringomielia',
  'Sirosis hepatis',
  'Skabies',
  'Skistosomiasis',
  'Skizofrenia',
  'Skleritis',
  'Sklerosis multipel',
  'Skotoma',
  'Skrofuloderma',
  'Sleep walking',
  'Sleep-wake cycle disturbance',
  'Spermatokel',
  'Spina bifida',
  'Spondilitis TB',
  'Spondilitis, spondilodisitis',
  'Spondilolisis',
  'Spondilolistesis',
  'Squamous cell carcinoma (Karsinoma sel skuamosa)',
  'Status asmatikus (asma akut berat)',
  'Status epileptikus',
  'Stenosis pilorik',
  'Striktura uretra',
  'Strongiloidiasis',
  'Subclavian steal syndrome',
  'Subinvolusio uterus',
  'Sumbing pada bibir dan palatum',
  'Syok (septik, hipovolemik, kardiogenik, neurogenik)',
  'TIA',
  'Taeniasis',
  'Takikardi: supraventrikular, ventrikular',
  'Tarsal tunnel syndrome',
  'Telogen eflluvium',
  'Tendinitis Achilles',
  'Tenggelam',
  'Tenosinovitis supuratif',
  'Tension headache',
  'Teratoma ovarium (kista dermoid)',
  'Teratoma sakrokoksigeal',
  'Teratoma testis',
  'Testis tidak turun/ kriptorkidismus',
  'Tetanus',
  'Tetanus neonatorum',
  'Timoma',
  'Timpanosklerosis',
  'Tinea barbe',
  'Tinea fasialis',
  'Tinea kapitis',
  'Tinea korporis',
  'Tinea kruris',
  'Tinea manus',
  'Tinea pedis',
  'Tinea unguium',
  'Tiroiditis',
  'Tirotoksikosis',
  'Toksikologi forensik',
  'Toksoplasmosis',
  'Toksoplasmosis serebral',
  'Tonsilitis',
  'Torsi dan ruptur kista',
  'Torsio testis',
  'Tortikolis',
  'Toxic epidermal necrolysis',
  'Trakeitis',
  'Transient tics disorder',
  'Trauma Medula Spinalis',
  'Trauma akustik akut',
  'Trauma aurikular',
  'Trauma kimia',
  'Trauma sendi',
  'Trauma suhu',
  'Trikiasis',
  'Trikotilomania',
  'Tromboemboli',
  'Tromboflebitis',
  'Trombosis arteri',
  'Trombosis vena dalam',
  'Tuberkulosis dengan HIV',
  'Tuberkulosis paru tanpa komplikasi',
  'Tuli (kongenital, perseptif, konduktif)',
  'Tumor Filoides',
  'Tumor Wilms',
  'Tumor iris',
  'Tumor mediastinum',
  'Tumor primer',
  'Tumor sekunder',
  'Tumor tulang primer, sekunder',
  'Ulkus (gaster, duodenum)',
  'Ulkus mulut (aptosa, herpes)',
  'Ulkus pada tungkai',
  'Uncoordinated speech',
  'Urtikaria akut',
  'Urtikaria kronis',
  'Vaginitis',
  'Vaginosis bakterialis',
  'Varikokel',
  'Varisela tanpa komplikasi',
  'Varises (primer, sekunder)',
  'Varises esofagus',
  'Vasa previa',
  'Vertigo (Benign paroxysmal positional vertigo)',
  'Veruka vulgaris',
  'Vitiligo',
  'Vulnus laseratum, punctum',
  'Vulnus perforatum, penetratum',
  'Vulvitis',
  'Xanthelasma',
  'Xanthoma',
  'Xerophtalmia',
])
