// ─────────────────────────────────────────────────────────────────────────────
// Maps an SKDI disease name to the OSCE station note that genuinely covers it.
//
// Many SKDI entries are the same condition the OSCE case bank already documents
// in far more depth (anamnesis / pemeriksaan fisik / kriteria diagnosis /
// tatalaksana / tips), just under a different heading — e.g. SKDI "Tetanus"
// versus the station note "Rabies / Tetanus".
//
// This map is CURATED BY HAND, not generated by fuzzy string matching. Naive
// substring matching produces clinically dangerous links: "Koma" matches
// "GlauKOMA Akut", "Xanthelasma" matches "ASMA". Every pair below was checked
// individually. If a disease has no genuine equivalent it is deliberately
// absent here and carries its own entry in skdiDiseaseNotes.ts instead.
// ─────────────────────────────────────────────────────────────────────────────

export const SKDI_DISEASE_NOTE_ALIASES: Record<string, string> = {
  // ─── Saraf (Neurologi) ───
  'Kejang demam': 'Kejang Demam Sederhana (KDS)',
  'Meningitis': 'Meningitis / Meningoensefalitis',
  'Ensefalitis': 'Meningitis / Meningoensefalitis',
  'Malaria serebral': 'Malaria (falciparum/vivax) — apus darah tebal/tipis',
  'Tetanus': 'Rabies / Tetanus',
  'Rabies': 'Rabies / Tetanus',
  'Neuralgia trigeminal': 'Neuralgia Trigeminal',
  'Cluster headache': 'Cluster Headache',
  'TIA': 'Stroke Hemoragik / TIA',
  'Ensefalopati hipertensi': 'Ensefalopati Hipertensi',
  'Parkinson': 'Parkinson Disease',
  'Epilepsi': 'Epilepsi',
  'Carpal tunnel syndrome': 'Carpal Tunnel Syndrome (CTS)',
  'Tarsal tunnel syndrome': 'Tarsal Tunnel Syndrome',
  'Neuropati': 'Neuropati Perifer e.c. DM',

  // ─── Psikiatri ───
  'Skizofrenia': 'Skizofrenia Paranoid',
  'Gangguan waham': 'Gangguan Waham Menetap',
  'Gangguan psikotik': 'Gangguan Psikotik Akut',
  'Gangguan skizoafektif': 'Skizoafektif',
  'Gangguan bipolar, episode depresif': 'Gangguan Afektif Bipolar (manik/depresi)',
  'Depresi endogen, episode tunggal dan rekuran': 'Depresi (ringan/sedang/berat)',
  'Gangguan depresif yang tidak terklasifikasikan': 'Depresi (ringan/sedang/berat)',
  'Baby blues (post-partum depression)': 'Baby Blues / Depresi Postpartum',
  'Gangguan panik': 'Gangguan Panik',
  'Gangguan cemas menyeluruh': 'Gangguan Cemas Menyeluruh (GAD)',
  'Trikotilomania': 'Trikotilomania',
  'Insomnia': 'Insomnia (primer/early/middle/late)',

  // ─── Indera ───
  'Konjungtivitis': 'Konjungtivitis (bakteri/vernal/viral)',
  'Blefaritis': 'Hordeolum / Blefaritis',
  'Hordeolum': 'Hordeolum / Blefaritis',
  'Dakrioadenitis': 'Dakrioadenitis / Dakriosistitis',
  'Dakriosistitis': 'Dakrioadenitis / Dakriosistitis',
  'Episkleritis': 'Episkleritis / Keratitis',
  'Keratitis': 'Episkleritis / Keratitis',
  'Hifema': 'Hifema',
  'Glaukoma akut': 'Glaukoma Akut Sudut Tertutup',
  'Otitis eksterna': 'Otitis Eksterna',
  'Otitis media akut': 'Otitis Media Akut (OMA) — semua stadium',
  'Mastoiditis': 'Serumen Prop / Mastoiditis',
  'Serumen prop': 'Serumen Prop / Mastoiditis',
  'Rhinitis alergika': 'Rhinitis Alergika',
  'Sinusitis': 'Sinusitis Maksilaris',
  'Sinusitis maksilaris akut': 'Sinusitis Maksilaris',
  'Epistaksis': 'Epistaksis Anterior — tindakan tampon',

  // ─── Respirasi ───
  'Pertusis': 'Pertusis',
  'Faringitis': 'Faringitis Akut',
  'Tonsilitis': 'Tonsilitis (akut/kronis eksaserbasi)',
  'Laringitis': 'Laringitis Akut / Sindroma Croup',
  'Abses peritonsilar': 'Abses Peritonsil',
  'Asma bronkial': 'Asma (berbagai derajat & eksaserbasi) — tindakan nebulisasi',
  'Status asmatikus (asma akut berat)': 'Asma (berbagai derajat & eksaserbasi) — tindakan nebulisasi',
  'Bronkitis akut': 'Bronkitis Akut',
  'Bronkiolitis akut': 'Bronkiolitis (anak)',
  'Bronkiektasis': 'Bronkiektasis',
  'Pneumonia, bronkopneumonia': 'Pneumonia (lobaris/aspirasi/CAP)',
  'Pneumonia aspirasi': 'Pneumonia (lobaris/aspirasi/CAP)',
  'Tuberkulosis paru tanpa komplikasi': 'Tuberkulosis Paru',
  'Efusi pleura': 'Efusi Pleura Massive',
  'Abses paru': 'Abses Paru',

  // ─── Kardiovaskular ───
  'Angina pektoris': 'Angina Pektoris Stabil',

  // ─── Gastrointestinal & Hepatobilier ───
  'Peritonitis': 'Peritonitis',
  'Gastritis': 'Gastritis / Dispepsia / GERD',
  'Demam tifoid': 'Demam Tifoid',
  'Ileus': 'Ileus Obstruktif — pasang NGT',
  'Taeniasis': 'Ascariasis / Taeniasis / Amoebiasis (parasit)',
  'Hepatitis A': 'Hepatitis A / B',
  'Kolesistitis': 'Kolesistitis / Kolelitiasis',
  'Disentri basiler, disentri amuba': 'Disentri (Amoeba / Basiler)',

  // ─── Ginjal & Saluran Kemih ───
  'Glomerulonefritis akut': 'Glomerulonefritis Akut Pasca-Streptokokus (GNAPS)',
  'Gonore': 'Servisitis / Uretritis Gonore',
  'Sindrom nefrotik': 'Sindrom Nefrotik / Sindrom Nefritik',
  'Fimosis': 'Fimosis / Parafimosis — tindakan sirkumsisi',
  'Parafimosis': 'Fimosis / Parafimosis — tindakan sirkumsisi',
  'Prostatitis': 'Prostatitis',

  // ─── Reproduksi & Obstetri ───
  'Servisitis': 'Servisitis / Uretritis Gonore',
  'Hiperemesis gravidarum': 'Hiperemesis Gravidarum (HEG)',
  'Ketuban pecah dini (KPD)': 'Ketuban Pecah Dini (KPD)',
  'Endometritis': 'Endometritis',
  'Mastitis': 'Mastitis / Cracked Nipple',
  'Cracked nipple': 'Mastitis / Cracked Nipple',

  // ─── Hematologi & Imunologi ───
  'Anemia defisiensi besi': 'Anemia Defisiensi Besi',
  'Malaria': 'Malaria (falciparum/vivax) — apus darah tebal/tipis',
  'Leptospirosis (tanpa komplikasi)': 'Leptospirosis / Weil Disease',

  // ─── Muskuloskeletal ───
  'Artritis, osteoarthritis': 'Osteoarthritis (OA)',
  'Ruptur tendon Achilles': 'Ruptur Tendon Achilles',

  // ─── Integumen ───
  'Filariasis': 'Filariasis',
  'Dermatitis atopik (kecuali recalcitrant)': 'Dermatitis Atopik',
  'Dermatitis seboroik': 'Dermatitis Seboroik',
}
