export type SurgicalDiscipline =
  | 'general' | 'digestive' | 'cardiothoracic-vascular' | 'oncology' | 'pediatric'
  | 'plastic-reconstructive' | 'neurosurgery' | 'orthopaedics-trauma' | 'urology'
  | 'oral-maxillofacial' | 'vascular' | 'transplant' | 'endocrine' | 'minimally-invasive'
  | 'colorectal' | 'trauma-critical-care' | 'ophthalmic'

export type SimulationMode =
  | 'anatomy-rehearsal' | 'operative-sequence' | 'instrument-handling' | 'exposure-dissection'
  | 'hemostasis' | 'reconstruction' | 'physiology-response' | 'complication-rescue' | 'team-crisis'

export interface SurgicalSimulationModule {
  id: string
  discipline: SurgicalDiscipline
  title: string
  anatomyTargets: readonly string[]
  pathologyContext: readonly string[]
  modes: readonly SimulationMode[]
  learningObjectives: readonly string[]
  phases: readonly string[]
  criticalStructures: readonly string[]
  physiologyOverlays: readonly string[]
  complicationConcepts: readonly string[]
  assessmentDomains: readonly string[]
  boundary: typeof SURGICAL_SIMULATOR_BOUNDARY
}

export const SURGICAL_SIMULATOR_BOUNDARY = {
  educationalSimulationOnly: true,
  patientSpecificProcedurePlanning: false,
  autonomousProcedureGuidance: false,
  treatmentRecommendation: false,
  genericAtlasIsPatientAnatomy: false,
  academicAccuracyGateRequired: true,
  qualifiedHumanReviewRequired: true,
  validatedPatientDataRequiredForPatientSpecificUse: true,
} as const

const module = (value: Omit<SurgicalSimulationModule, 'boundary'>): SurgicalSimulationModule => ({ ...value, boundary: SURGICAL_SIMULATOR_BOUNDARY })

export const SURGICAL_SIMULATOR_MODULES: readonly SurgicalSimulationModule[] = [
  module({ id:'lap-appendectomy', discipline:'general', title:'Laparoscopic appendectomy', anatomyTargets:['cecum','appendix','terminal ileum','mesoappendix'], pathologyContext:['acute appendicitis'], modes:['anatomy-rehearsal','operative-sequence','instrument-handling','exposure-dissection','hemostasis','complication-rescue'], learningObjectives:['Recognize regional anatomy and safe exposure concepts','Understand operative phases and complication checkpoints'], phases:['orientation and access concept','abdominal survey','appendiceal identification and exposure','mesoappendiceal control concept','appendiceal division concept','specimen/review and closure concept'], criticalStructures:['cecum','terminal ileum','right ureter','iliac vessels'], physiologyOverlays:['perfusion','inflammation','bleeding-state'], complicationConcepts:['bleeding','adjacent-organ injury','contamination','stump complication'], assessmentDomains:['anatomy recognition','sequence reasoning','instrument economy','hazard recognition'] }),
  module({ id:'inguinal-hernia-repair', discipline:'general', title:'Inguinal hernia repair', anatomyTargets:['inguinal canal','inferior epigastric vessels','spermatic cord','myopectineal orifice'], pathologyContext:['direct hernia','indirect hernia','femoral hernia'], modes:['anatomy-rehearsal','operative-sequence','exposure-dissection','reconstruction'], learningObjectives:['Differentiate groin hernia anatomy','Recognize nerves, vessels and danger zones'], phases:['regional orientation','hernia classification','dissection-plane concept','defect/mesh-position concept','closure review'], criticalStructures:['inferior epigastric vessels','vas deferens','gonadal vessels','ilioinguinal nerve','femoral vessels'], physiologyOverlays:['tissue perfusion'], complicationConcepts:['vascular injury','nerve injury','recurrence concept','chronic pain concept'], assessmentDomains:['anatomy recognition','plane selection','hazard recognition'] }),
  module({ id:'lap-cholecystectomy', discipline:'digestive', title:'Laparoscopic cholecystectomy', anatomyTargets:['gallbladder','cystic duct','cystic artery','common bile duct','hepatic hilum'], pathologyContext:['cholelithiasis','cholecystitis'], modes:['anatomy-rehearsal','operative-sequence','instrument-handling','exposure-dissection','hemostasis','complication-rescue'], learningObjectives:['Understand hepatobiliary anatomy and anatomical variation','Practice critical-view reasoning in a non-patient-specific simulator'], phases:['orientation','exposure concept','hepatocystic-triangle dissection concept','identity verification checkpoint','division concept','gallbladder-bed separation','final survey'], criticalStructures:['common bile duct','common hepatic duct','right hepatic artery','portal vein','duodenum'], physiologyOverlays:['bile flow','arterial perfusion','bleeding-state'], complicationConcepts:['bile-duct injury','hemorrhage','bile leak','thermal injury'], assessmentDomains:['anatomy identification','verification discipline','hazard recognition'] }),
  module({ id:'colorectal-resection', discipline:'colorectal', title:'Colorectal resection concepts', anatomyTargets:['colon','rectum','mesocolon','mesorectum','ureters','pelvic autonomic nerves'], pathologyContext:['colorectal cancer','diverticular disease'], modes:['anatomy-rehearsal','operative-sequence','exposure-dissection','reconstruction'], learningObjectives:['Understand mesenteric and pelvic planes','Connect vascular territories to bowel perfusion'], phases:['localization','mobilization-plane concept','vascular-pedicle anatomy','resection-margin concept','reconstruction/anastomosis concept','perfusion review'], criticalStructures:['ureters','iliac vessels','hypogastric nerves','duodenum','spleen'], physiologyOverlays:['mesenteric perfusion','tissue oxygenation'], complicationConcepts:['anastomotic leak','ischemia','bleeding','nerve injury'], assessmentDomains:['plane recognition','vascular anatomy','structure preservation'] }),
  module({ id:'liver-pancreas-resection', discipline:'digestive', title:'Hepatopancreatobiliary resection concepts', anatomyTargets:['liver segments','portal triad','hepatic veins','pancreas','duodenum'], pathologyContext:['hepatic tumor','pancreatic tumor'], modes:['anatomy-rehearsal','operative-sequence','exposure-dissection','hemostasis','reconstruction'], learningObjectives:['Explore segmental anatomy and vascular/biliary relationships','Recognize high-risk structures and reconstruction concepts'], phases:['cross-sectional orientation','vascular/biliary mapping','resection-plane concept','hemostasis concept','reconstruction concept'], criticalStructures:['portal vein','hepatic artery','hepatic veins','common bile duct','superior mesenteric vessels'], physiologyOverlays:['portal flow','arterial perfusion','bile flow'], complicationConcepts:['hemorrhage','bile leak','pancreatic fistula','organ ischemia'], assessmentDomains:['3D anatomy','vascular reasoning','hazard recognition'] }),
  module({ id:'cabg-valve', discipline:'cardiothoracic-vascular', title:'Cardiac revascularization and valve surgery concepts', anatomyTargets:['coronary arteries','aortic root','mitral apparatus','cardiac chambers'], pathologyContext:['coronary artery disease','valvular heart disease'], modes:['anatomy-rehearsal','operative-sequence','physiology-response','reconstruction','team-crisis'], learningObjectives:['Connect cardiac anatomy to perfusion and valve mechanics','Understand major operative phases without patient-specific guidance'], phases:['cardiac orientation','target anatomy','circulatory-support concept','repair/revascularization concept','reperfusion physiology','post-repair assessment concept'], criticalStructures:['coronary ostia','conduction system regions','circumflex artery','aortic root'], physiologyOverlays:['coronary flow','pressure-volume relation','valve flow','myocardial oxygen delivery'], complicationConcepts:['ischemia','bleeding','low-output state','arrhythmia concept'], assessmentDomains:['anatomy','physiology reasoning','crisis recognition'] }),
  module({ id:'thoracic-resection', discipline:'cardiothoracic-vascular', title:'Thoracic and pulmonary resection concepts', anatomyTargets:['lung lobes','bronchopulmonary segments','pulmonary arteries','pulmonary veins','bronchi','mediastinum'], pathologyContext:['lung tumor','thoracic disease'], modes:['anatomy-rehearsal','operative-sequence','exposure-dissection','hemostasis'], learningObjectives:['Understand hilar and segmental relationships','Connect airway and pulmonary vascular anatomy'], phases:['thoracic orientation','hilar exposure concept','vessel/airway identification','resection concept','air-leak/hemostasis review'], criticalStructures:['pulmonary artery','pulmonary veins','bronchi','phrenic nerve','recurrent laryngeal nerve'], physiologyOverlays:['ventilation','perfusion','V/Q relation'], complicationConcepts:['vascular bleeding','air leak','nerve injury','respiratory compromise'], assessmentDomains:['hilar anatomy','structure identification','hazard recognition'] }),
  module({ id:'tumor-resection', discipline:'oncology', title:'Oncologic resection principles', anatomyTargets:['tumor-bearing organ','regional lymphatics','adjacent neurovascular structures'], pathologyContext:['solid malignancy'], modes:['anatomy-rehearsal','operative-sequence','exposure-dissection','reconstruction'], learningObjectives:['Understand margin, compartment and nodal anatomy concepts','Balance oncologic extent with structure preservation'], phases:['staging-context review','anatomic localization','margin/plane concept','regional-node concept','reconstruction concept'], criticalStructures:['organ-specific vessels','nerves','adjacent viscera'], physiologyOverlays:['perfusion','lymphatic drainage'], complicationConcepts:['bleeding','organ dysfunction','wound complication'], assessmentDomains:['oncologic anatomy','margin reasoning','structure preservation'] }),
  module({ id:'pediatric-congenital', discipline:'pediatric', title:'Pediatric congenital surgery concepts', anatomyTargets:['age-specific abdominal/thoracic anatomy','congenital anomaly relationships'], pathologyContext:['congenital malformation','pediatric hernia'], modes:['anatomy-rehearsal','operative-sequence','reconstruction','physiology-response'], learningObjectives:['Recognize developmental anatomy and scale differences','Understand age-specific physiological vulnerability'], phases:['developmental anatomy orientation','anomaly mapping','repair concept','physiology review'], criticalStructures:['age- and anomaly-specific neurovascular structures'], physiologyOverlays:['weight/age-context physiology','fluid/temperature vulnerability'], complicationConcepts:['hypothermia','fluid imbalance','injury to small structures'], assessmentDomains:['developmental anatomy','scale awareness','hazard recognition'] }),
  module({ id:'reconstructive-flap', discipline:'plastic-reconstructive', title:'Reconstructive flap and burn surgery concepts', anatomyTargets:['skin','fascia','muscle','perforators','recipient vessels'], pathologyContext:['tissue defect','burn injury'], modes:['anatomy-rehearsal','operative-sequence','exposure-dissection','reconstruction','physiology-response'], learningObjectives:['Understand reconstructive ladder and vascular territories','Visualize flap perfusion and tissue layers'], phases:['defect analysis','donor/recipient anatomy','flap-design concept','transfer/inset concept','perfusion review'], criticalStructures:['perforators','named pedicles','motor nerves'], physiologyOverlays:['microvascular perfusion','tissue oxygenation','burn depth'], complicationConcepts:['flap ischemia','venous congestion','wound failure'], assessmentDomains:['vascular anatomy','tissue handling concept','reconstructive reasoning'] }),
  module({ id:'aneurysm-clipping', discipline:'neurosurgery', title:'Cerebral aneurysm clipping simulation concepts', anatomyTargets:['circle of Willis','aneurysm neck','parent artery','perforators','cranial nerves'], pathologyContext:['intracranial aneurysm','subarachnoid hemorrhage'], modes:['anatomy-rehearsal','operative-sequence','exposure-dissection','physiology-response','complication-rescue'], learningObjectives:['Explore microsurgical neurovascular relationships','Understand temporary/permanent flow consequences conceptually'], phases:['3D vascular orientation','corridor/exposure concept','proximal-control concept','aneurysm-neck/perforator inspection','clip-placement concept','flow-preservation verification'], criticalStructures:['parent artery','perforators','optic apparatus','cranial nerves'], physiologyOverlays:['arterial flow','territorial perfusion','conceptual ICG flow state'], complicationConcepts:['parent-vessel compromise','perforator ischemia','aneurysm rupture','brain injury'], assessmentDomains:['microsurgical anatomy','flow-preservation reasoning','hazard recognition'] }),
  module({ id:'spine-decompression', discipline:'neurosurgery', title:'Spine decompression and neural protection concepts', anatomyTargets:['vertebrae','spinal canal','dura','nerve roots','segmental vessels'], pathologyContext:['spinal stenosis','compressive lesion'], modes:['anatomy-rehearsal','operative-sequence','exposure-dissection'], learningObjectives:['Recognize neural and bony relationships','Understand decompression boundaries and neural hazards'], phases:['level orientation','posterior-element anatomy','decompression concept','neural structure review'], criticalStructures:['spinal cord','nerve roots','dura','vertebral artery in cervical context'], physiologyOverlays:['neural perfusion'], complicationConcepts:['dural injury','neural injury','vascular injury'], assessmentDomains:['level anatomy','neural protection','hazard recognition'] }),
  module({ id:'fracture-fixation', discipline:'orthopaedics-trauma', title:'Fracture reduction and fixation concepts', anatomyTargets:['bone','periosteum','joint surface','regional nerves and vessels'], pathologyContext:['fracture','polytrauma'], modes:['anatomy-rehearsal','operative-sequence','instrument-handling','reconstruction'], learningObjectives:['Understand fracture morphology and reduction concepts','Preserve soft tissue and neurovascular structures'], phases:['imaging/anatomy orientation','approach concept','reduction concept','fixation construct concept','alignment review'], criticalStructures:['regional nerves','regional arteries','joint cartilage'], physiologyOverlays:['bone perfusion','healing biology'], complicationConcepts:['malalignment','neurovascular injury','compartment syndrome concept','infection'], assessmentDomains:['3D fracture reasoning','alignment','structure preservation'] }),
  module({ id:'arthroplasty', discipline:'orthopaedics-trauma', title:'Joint arthroplasty concepts', anatomyTargets:['joint surfaces','ligaments','muscle envelope','neurovascular structures'], pathologyContext:['degenerative joint disease'], modes:['anatomy-rehearsal','operative-sequence','reconstruction'], learningObjectives:['Understand joint geometry, alignment and soft-tissue balance concepts'], phases:['joint orientation','exposure concept','bone-preparation concept','implant-position concept','stability/alignment review'], criticalStructures:['major nerves','major vessels','tendons'], physiologyOverlays:['load distribution concept'], complicationConcepts:['instability','fracture','neurovascular injury','infection'], assessmentDomains:['alignment reasoning','anatomy','reconstruction concept'] }),
  module({ id:'endourology', discipline:'urology', title:'Endourology and urinary tract surgery concepts', anatomyTargets:['kidney','collecting system','ureter','bladder','prostate'], pathologyContext:['urolithiasis','obstruction','prostatic disease'], modes:['anatomy-rehearsal','operative-sequence','instrument-handling'], learningObjectives:['Navigate urinary tract anatomy conceptually','Understand obstruction, drainage and tissue-risk concepts'], phases:['tract orientation','target localization','instrument navigation concept','treatment-zone concept','drainage review'], criticalStructures:['ureteral wall','renal vessels','urethral sphincter'], physiologyOverlays:['urine flow','renal perfusion'], complicationConcepts:['perforation','bleeding','obstruction','infection concept'], assessmentDomains:['anatomy navigation','instrument control','hazard recognition'] }),
  module({ id:'maxillofacial-reconstruction', discipline:'oral-maxillofacial', title:'Craniofacial and maxillofacial reconstruction concepts', anatomyTargets:['mandible','maxilla','orbit','facial nerves','facial vessels'], pathologyContext:['facial fracture','jaw lesion'], modes:['anatomy-rehearsal','operative-sequence','reconstruction'], learningObjectives:['Understand occlusion, facial buttresses and neurovascular anatomy'], phases:['3D craniofacial orientation','fracture/defect mapping','reduction concept','reconstruction concept','symmetry/occlusion review'], criticalStructures:['inferior alveolar nerve','facial nerve branches','orbit','tooth roots'], physiologyOverlays:['regional perfusion'], complicationConcepts:['malocclusion','nerve injury','ocular injury','infection'], assessmentDomains:['3D reconstruction','structure preservation','symmetry reasoning'] }),
  module({ id:'vascular-revascularization', discipline:'vascular', title:'Peripheral vascular reconstruction concepts', anatomyTargets:['arteries','veins','branch points','distal runoff territories'], pathologyContext:['peripheral arterial disease','aneurysm','venous disease'], modes:['anatomy-rehearsal','operative-sequence','reconstruction','physiology-response'], learningObjectives:['Connect vascular anatomy to flow and ischemia','Understand reconstruction and perfusion verification concepts'], phases:['vascular mapping','exposure/control concept','reconstruction concept','flow restoration','distal perfusion review'], criticalStructures:['adjacent nerves','arterial branches','deep veins'], physiologyOverlays:['flow','pressure gradient concept','tissue perfusion'], complicationConcepts:['thrombosis','embolization','bleeding','ischemia'], assessmentDomains:['vascular anatomy','flow reasoning','hazard recognition'] }),
  module({ id:'organ-transplant', discipline:'transplant', title:'Kidney and liver transplantation concepts', anatomyTargets:['donor organ anatomy','recipient vessels','biliary/urinary reconstruction'], pathologyContext:['end-stage organ disease'], modes:['anatomy-rehearsal','operative-sequence','reconstruction','physiology-response','team-crisis'], learningObjectives:['Understand graft orientation and vascular reconstruction','Connect reperfusion to organ physiology'], phases:['donor/recipient anatomy','implant orientation','vascular reconstruction concept','reperfusion concept','duct/urinary reconstruction concept'], criticalStructures:['recipient vessels','graft vessels','bile duct or ureter'], physiologyOverlays:['ischemia-reperfusion','graft perfusion'], complicationConcepts:['vascular thrombosis','bleeding','leak','graft dysfunction concept'], assessmentDomains:['anatomy','reconstruction reasoning','reperfusion recognition'] }),
  module({ id:'endocrine-surgery', discipline:'endocrine', title:'Thyroid, parathyroid and adrenal surgery concepts', anatomyTargets:['thyroid','parathyroids','recurrent laryngeal nerves','adrenal glands','regional vessels'], pathologyContext:['thyroid lesion','hyperparathyroidism','adrenal lesion'], modes:['anatomy-rehearsal','operative-sequence','exposure-dissection','physiology-response'], learningObjectives:['Recognize endocrine surgical anatomy and vulnerable structures','Connect gland manipulation/resection to endocrine physiology'], phases:['regional anatomy','gland identification','neurovascular preservation concept','resection concept','physiology review'], criticalStructures:['recurrent laryngeal nerve','external branch superior laryngeal nerve','parathyroids','adrenal vein'], physiologyOverlays:['calcium physiology','catecholamine physiology','thyroid hormone context'], complicationConcepts:['nerve injury','hypocalcemia concept','bleeding','hemodynamic crisis concept'], assessmentDomains:['anatomy','structure preservation','physiology reasoning'] }),
  module({ id:'minimally-invasive-skills', discipline:'minimally-invasive', title:'Laparoscopic and minimally invasive core skills', anatomyTargets:['camera-space relationship','generic tissue planes','ports as educational geometry'], pathologyContext:['procedure-agnostic training'], modes:['instrument-handling','exposure-dissection','hemostasis','reconstruction'], learningObjectives:['Practice camera orientation, depth, bimanual coordination and tissue respect','Recognize simulated hazards without translating the simulator into autonomous real-world guidance'], phases:['camera navigation','target acquisition','bimanual manipulation','dissection-plane exercise','suturing/reconstruction exercise','crisis drill'], criticalStructures:['simulated no-touch structures'], physiologyOverlays:['bleeding-state'], complicationConcepts:['simulated bleeding','thermal-spread concept','tissue injury'], assessmentDomains:['economy of motion','camera control','bimanual coordination','hazard recognition'] }),
  module({ id:'trauma-crisis', discipline:'trauma-critical-care', title:'Trauma operative crisis simulation', anatomyTargets:['thorax','abdomen','pelvis','major vessels'], pathologyContext:['hemorrhagic shock','polytrauma'], modes:['anatomy-rehearsal','physiology-response','complication-rescue','team-crisis'], learningObjectives:['Integrate anatomy, physiology and team communication in simulated crisis','Recognize hemorrhage compartments and changing physiology'], phases:['initial anatomy/physiology state','source localization concept','hemorrhage-control decision simulation','resuscitation response','reassessment'], criticalStructures:['aorta','vena cava','solid organs','pelvic vessels'], physiologyOverlays:['blood volume state','perfusion','shock trajectory','oxygen delivery'], complicationConcepts:['ongoing hemorrhage','coagulopathy concept','hypothermia concept','organ hypoperfusion'], assessmentDomains:['situational awareness','anatomy','physiology reasoning','team communication'] }),
  module({ id:'ophthalmic-microsurgery', discipline:'ophthalmic', title:'Ophthalmic microsurgery concepts', anatomyTargets:['cornea','anterior chamber','lens','retina','optic nerve'], pathologyContext:['cataract','retinal disease'], modes:['anatomy-rehearsal','instrument-handling','operative-sequence'], learningObjectives:['Understand microsurgical ocular anatomy and instrument-space relationships'], phases:['microscopic orientation','anterior/posterior segment target identification','instrument-control exercise','tissue-protection review'], criticalStructures:['corneal endothelium','iris','posterior capsule','retina','optic nerve'], physiologyOverlays:['aqueous flow','retinal perfusion'], complicationConcepts:['capsular injury concept','retinal injury','pressure disturbance concept'], assessmentDomains:['microsurgical precision','anatomy','instrument control'] }),
]

export const getSurgicalSimulationModule = (id: string) => SURGICAL_SIMULATOR_MODULES.find((entry) => entry.id === id)
export const getSurgicalModulesForDiscipline = (discipline: SurgicalDiscipline) => SURGICAL_SIMULATOR_MODULES.filter((entry) => entry.discipline === discipline)
export const getSurgicalModulesForStructure = (structure: string) => {
  const q = structure.trim().toLowerCase()
  return SURGICAL_SIMULATOR_MODULES.filter((entry) => entry.anatomyTargets.some((target) => target.toLowerCase().includes(q)))
}
