import { S, type Blok } from './usmle'

// ─────────────────────────────────────────────────────────────────────────────
// Susunan kurikulumnya. Lihat kepala usmle.ts untuk aturan sitasi — aturan itu
// berlaku penuh di berkas ini, dan tidak satu pun rujukan di bawah dikarang.
//
// URUTANNYA MENGIKUTI URUTAN BELAJAR, bukan urutan abjad. Praklinik dahulu
// karena Step 1 berdiri di atasnya, Step 2 CK sesudah klinik, Step 3 sesudah
// lulus, dan jalur ECFMG berjalan mendampingi semuanya, bukan sesudahnya —
// itu kekeliruan urutan yang paling mahal bagi lulusan luar negeri, sebab
// beberapa syaratnya harus dipenuhi SEBELUM mendaftar ujian pertama.
// ─────────────────────────────────────────────────────────────────────────────

// Sistem organ menurut Content Outline USMLE. Dipakai sebagai nilai `sistem`
// pada topik, dan ditulis sekali di sini supaya tidak pernah berbeda ejaannya.
export const SISTEM = [
  'Cardiovascular',
  'Respiratory',
  'Gastrointestinal',
  'Renal & Urinary',
  'Reproductive & Endocrine',
  'Musculoskeletal, Skin & Connective tissue',
  'Nervous system & Special senses',
  'Blood & Lymphoreticular',
  'Immune system',
  'Behavioral health',
  'Multisystem processes',
] as const

export const KURIKULUM: Blok[] = [
  // ───────────────────────────── PRAKLINIK ────────────────────────────────
  {
    id: 'anatomi', jenjang: 'preklinik', judul: 'Anatomy', emoji: '🦴',
    ringkas: 'Gross anatomy, embryology, and neuroanatomy — the map every later subject is drawn on.',
    topik: [
      { id: 'an-thorax', judul: 'Thorax and mediastinum', blok: 'Anatomy', sistem: 'Cardiovascular',
        mengapa: 'Chest tube placement, pericardial anatomy, and the course of the phrenic and vagus nerves are asked as applied questions, not as lists.',
        sumber: [S.bookshelf, S.statpearls] },
      { id: 'an-abdomen', judul: 'Abdomen, pelvis and perineum', blok: 'Anatomy', sistem: 'Gastrointestinal',
        mengapa: 'Peritoneal versus retroperitoneal position explains where blood and infection travel, which is what the vignette actually tests.',
        sumber: [S.bookshelf, S.statpearls] },
      { id: 'an-limb', judul: 'Upper and lower limb', blok: 'Anatomy', sistem: 'Musculoskeletal, Skin & Connective tissue',
        mengapa: 'Nerve injury patterns — where the lesion must be for this exact deficit — are among the most reliably recurring items.',
        sumber: [S.bookshelf, S.statpearls] },
      { id: 'an-head', judul: 'Head, neck and cranial nerves', blok: 'Anatomy', sistem: 'Nervous system & Special senses',
        mengapa: 'Cranial nerve course and the foramina they pass through localise lesions faster than any imaging description.',
        sumber: [S.bookshelf, S.statpearls] },
      { id: 'an-neuro', judul: 'Neuroanatomy and tracts', blok: 'Anatomy', sistem: 'Nervous system & Special senses',
        mengapa: 'Level-and-side localisation from a deficit pattern is the single highest-yield neuroanatomy skill.',
        sumber: [S.bookshelf, S.aan] },
      { id: 'an-embryo', judul: 'Embryology and congenital malformation', blok: 'Anatomy',
        mengapa: 'Most congenital lesions asked are explained by one failed embryological step; the step is the answer.',
        sumber: [S.bookshelf] },
    ],
  },
  {
    id: 'histologi', jenjang: 'preklinik', judul: 'Histology & Cell biology', emoji: '🔬',
    ringkas: 'Normal tissue architecture — the baseline against which every pathology slide is read.',
    topik: [
      { id: 'hi-epitel', judul: 'Epithelia, glands and cell junctions', blok: 'Histology',
        mengapa: 'Junction type explains barrier failure, and barrier failure explains a large share of disease mechanisms.',
        sumber: [S.bookshelf] },
      { id: 'hi-ikat', judul: 'Connective tissue, cartilage and bone', blok: 'Histology', sistem: 'Musculoskeletal, Skin & Connective tissue',
        mengapa: 'Collagen types map directly onto the inherited connective tissue diseases that are examined every year.',
        sumber: [S.bookshelf] },
      { id: 'hi-otot', judul: 'Muscle and nerve tissue', blok: 'Histology',
        mengapa: 'Excitation–contraction coupling is asked as a physiology question but answered from histology.',
        sumber: [S.bookshelf] },
      { id: 'hi-organ', judul: 'Organ histology by system', blok: 'Histology',
        mengapa: 'Recognising normal is the prerequisite for the pathology images that follow.',
        sumber: [S.bookshelf] },
      { id: 'hi-sel', judul: 'Cell biology: cytoskeleton, trafficking, cell cycle', blok: 'Cell biology',
        mengapa: 'Microtubule and trafficking defects underlie both inherited syndromes and several drug mechanisms.',
        sumber: [S.bookshelf] },
    ],
  },
  {
    id: 'fisiologi', jenjang: 'preklinik', judul: 'Physiology', emoji: '⚙️',
    ringkas: 'How the normal system behaves, quantitatively — the reference every pathophysiology answer is measured against.',
    topik: [
      { id: 'fi-jantung', judul: 'Cardiac physiology and haemodynamics', blok: 'Physiology', sistem: 'Cardiovascular',
        mengapa: 'Pressure–volume loops, preload/afterload and the cardiac cycle answer far more questions than they appear to.',
        sumber: [S.bookshelf, S.ahaAcc] },
      { id: 'fi-paru', judul: 'Respiratory mechanics and gas exchange', blok: 'Physiology', sistem: 'Respiratory',
        mengapa: 'The A–a gradient and the five causes of hypoxaemia convert a blood gas into a diagnosis.',
        sumber: [S.bookshelf] },
      { id: 'fi-ginjal', judul: 'Renal physiology, acid–base and electrolytes', blok: 'Physiology', sistem: 'Renal & Urinary',
        mengapa: 'Acid–base is the most examinable calculation in medicine and the one most often done wrong under time pressure.',
        sumber: [S.bookshelf, S.kdigo] },
      { id: 'fi-endokrin', judul: 'Endocrine axes and feedback', blok: 'Physiology', sistem: 'Reproductive & Endocrine',
        mengapa: 'Almost every endocrine vignette is solved by asking which level of one axis is broken.',
        sumber: [S.bookshelf] },
      { id: 'fi-cerna', judul: 'Gastrointestinal secretion, motility and absorption', blok: 'Physiology', sistem: 'Gastrointestinal',
        mengapa: 'Site of absorption predicts the deficiency after each type of resection or bypass.',
        sumber: [S.bookshelf] },
      { id: 'fi-saraf', judul: 'Neurophysiology and special senses', blok: 'Physiology', sistem: 'Nervous system & Special senses',
        mengapa: 'Membrane potentials and reflex arcs sit underneath both neurology and anaesthetic pharmacology.',
        sumber: [S.bookshelf] },
    ],
  },
  {
    id: 'biokimia', jenjang: 'preklinik', judul: 'Biochemistry & Molecular biology', emoji: '🧪',
    ringkas: 'Pathways, their control points, and the diseases produced when a single enzyme fails.',
    topik: [
      { id: 'bi-glikolisis', judul: 'Glycolysis, gluconeogenesis and the TCA cycle', blok: 'Biochemistry',
        mengapa: 'Rate-limiting enzymes and their regulators are the reliable core; the intermediate names are not.',
        sumber: [S.bookshelf] },
      { id: 'bi-glikogen', judul: 'Glycogen storage and metabolism', blok: 'Biochemistry',
        mengapa: 'The storage diseases are distinguished by organ involved and hypoglycaemia pattern, not by enzyme name alone.',
        sumber: [S.bookshelf] },
      { id: 'bi-lipid', judul: 'Lipid metabolism and lipoproteins', blok: 'Biochemistry',
        mengapa: 'Familial dyslipidaemias link directly to the statin/PCSK9 pharmacology asked beside them.',
        sumber: [S.bookshelf, S.ahaAcc] },
      { id: 'bi-asamamino', judul: 'Amino acid metabolism and the urea cycle', blok: 'Biochemistry',
        mengapa: 'Urea cycle defects and the aminoacidopathies are a standing source of newborn vignettes.',
        sumber: [S.bookshelf] },
      { id: 'bi-purin', judul: 'Purine and pyrimidine metabolism', blok: 'Biochemistry',
        mengapa: 'Explains gout, Lesch–Nyhan, and the mechanism of several chemotherapeutics at once.',
        sumber: [S.bookshelf] },
      { id: 'bi-vitamin', judul: 'Vitamins, cofactors and deficiency syndromes', blok: 'Biochemistry',
        mengapa: 'Deficiency presentations are asked far more often than the biochemistry that produces them.',
        sumber: [S.bookshelf, S.who] },
      { id: 'bi-dna', judul: 'DNA replication, repair, transcription and translation', blok: 'Molecular biology',
        mengapa: 'Repair defects map onto specific cancer syndromes, which is how the topic is actually tested.',
        sumber: [S.bookshelf] },
      { id: 'bi-teknik', judul: 'Laboratory techniques: PCR, blotting, sequencing, CRISPR', blok: 'Molecular biology',
        mengapa: 'Questions ask which technique answers a stated question — the choice, not the protocol.',
        sumber: [S.bookshelf] },
    ],
  },
  {
    id: 'genetika', jenjang: 'preklinik', judul: 'Genetics', emoji: '🧬',
    ringkas: 'Inheritance patterns, population genetics, and the syndromes that recur every year.',
    topik: [
      { id: 'ge-pola', judul: 'Modes of inheritance and pedigree analysis', blok: 'Genetics',
        mengapa: 'A pedigree question is answered in seconds once the pattern is named correctly.',
        sumber: [S.bookshelf] },
      { id: 'ge-populasi', judul: 'Hardy–Weinberg and population genetics', blok: 'Genetics',
        mengapa: 'One of the few genetics calculations that appears in numeric form.',
        sumber: [S.bookshelf] },
      { id: 'ge-kromosom', judul: 'Chromosomal disorders and imprinting', blok: 'Genetics',
        mengapa: 'Imprinting explains why the same deletion gives two different syndromes — a favourite discriminator.',
        sumber: [S.bookshelf] },
      { id: 'ge-kanker', judul: 'Cancer genetics and tumour suppressor syndromes', blok: 'Genetics', sistem: 'Multisystem processes',
        mengapa: 'Two-hit logic connects genetics to the oncology asked in Step 2 CK.',
        sumber: [S.bookshelf, S.acs] },
    ],
  },
  {
    id: 'mikrobiologi', jenjang: 'preklinik', judul: 'Microbiology', emoji: '🦠',
    ringkas: 'Organisms by class, the disease each causes, and how the diagnosis is actually made.',
    topik: [
      { id: 'mi-gram', judul: 'Gram-positive and gram-negative bacteria', blok: 'Microbiology',
        mengapa: 'Organism-to-syndrome matching is the backbone of both Step 1 and empirical therapy later.',
        sumber: [S.bookshelf, S.idsa] },
      { id: 'mi-atipik', judul: 'Mycobacteria, spirochaetes and atypicals', blok: 'Microbiology',
        mengapa: 'These are the organisms missed by routine culture, which is exactly why they are asked.',
        sumber: [S.who, S.idsa] },
      { id: 'mi-virus', judul: 'Virology: DNA and RNA viruses', blok: 'Microbiology',
        mengapa: 'Genome structure predicts both the antiviral target and the vaccine strategy.',
        sumber: [S.bookshelf, S.cdc] },
      { id: 'mi-jamur', judul: 'Mycology and parasitology', blok: 'Microbiology',
        mengapa: 'Geography and immune status in the stem usually name the organism before the labs do.',
        sumber: [S.cdc, S.who] },
      { id: 'mi-antimikroba', judul: 'Antimicrobial mechanisms and resistance', blok: 'Microbiology',
        mengapa: 'Resistance mechanism explains the drug choice, and drug choice is what the question rewards.',
        sumber: [S.idsa, S.who] },
    ],
  },
  {
    id: 'imunologi', jenjang: 'preklinik', judul: 'Immunology', emoji: '🛡️',
    ringkas: 'Innate and adaptive response, hypersensitivity, transplant, and immunodeficiency.',
    topik: [
      { id: 'im-dasar', judul: 'Innate and adaptive immunity, antigen presentation', blok: 'Immunology', sistem: 'Immune system',
        mengapa: 'MHC restriction underlies transplant, autoimmunity and vaccine questions alike.',
        sumber: [S.bookshelf] },
      { id: 'im-hipersens', judul: 'Hypersensitivity types I–IV', blok: 'Immunology', sistem: 'Immune system',
        mengapa: 'Naming the type converts a confusing stem into a single mechanism.',
        sumber: [S.bookshelf] },
      { id: 'im-defisiensi', judul: 'Primary and secondary immunodeficiency', blok: 'Immunology', sistem: 'Immune system',
        mengapa: 'The pattern of infecting organism points to the arm of immunity that has failed.',
        sumber: [S.bookshelf] },
      { id: 'im-transplan', judul: 'Transplant immunology and rejection', blok: 'Immunology', sistem: 'Immune system',
        mengapa: 'Rejection timing — hyperacute to chronic — is a clean, examinable discriminator.',
        sumber: [S.bookshelf] },
      { id: 'im-vaksin', judul: 'Vaccines and immunisation schedules', blok: 'Immunology', sistem: 'Immune system',
        mengapa: 'Live versus inactivated decides what is safe in pregnancy and immunosuppression.',
        sumber: [S.cdc, S.who] },
    ],
  },
  {
    id: 'patologi', jenjang: 'preklinik', judul: 'Pathology & Pathophysiology', emoji: '🩻',
    ringkas: 'Cell injury, inflammation, neoplasia, and then disease mechanism system by system.',
    topik: [
      { id: 'pa-cedera', judul: 'Cell injury, necrosis and apoptosis', blok: 'Pathology',
        mengapa: 'Necrosis pattern names the organ and the mechanism together.',
        sumber: [S.bookshelf] },
      { id: 'pa-radang', judul: 'Acute and chronic inflammation, repair', blok: 'Pathology',
        mengapa: 'Granuloma formation and wound healing sequence recur constantly.',
        sumber: [S.bookshelf] },
      { id: 'pa-hemodinamik', judul: 'Haemodynamic disorders, thrombosis and shock', blok: 'Pathology', sistem: 'Multisystem processes',
        mengapa: 'Virchow triad and shock physiology anchor both Step 1 and critical care later.',
        sumber: [S.bookshelf, S.ssc] },
      { id: 'pa-neoplasia', judul: 'Neoplasia: carcinogenesis, grading, staging, markers', blok: 'Pathology', sistem: 'Multisystem processes',
        mengapa: 'Grading versus staging, and which one drives treatment, is asked directly.',
        sumber: [S.acs] },
      { id: 'pa-sistem', judul: 'Systemic pathology by organ system', blok: 'Pathology',
        mengapa: 'This is where preclinical pathology and clinical medicine become the same subject.',
        sumber: [S.bookshelf, S.statpearls] },
    ],
  },
  {
    id: 'farmakologi', jenjang: 'preklinik', judul: 'Pharmacology', emoji: '💊',
    ringkas: 'Kinetics, dynamics, drug classes by system, toxicology and antidotes.',
    topik: [
      { id: 'fa-kinetik', judul: 'Pharmacokinetics and pharmacodynamics', blok: 'Pharmacology',
        mengapa: 'Half-life, clearance and loading dose appear as calculations with predictable structure.',
        sumber: [S.bookshelf] },
      { id: 'fa-otonom', judul: 'Autonomic pharmacology', blok: 'Pharmacology',
        mengapa: 'Receptor logic here generalises to cardiology, ophthalmology and toxicology at once.',
        sumber: [S.bookshelf] },
      { id: 'fa-kardio', judul: 'Cardiovascular and antithrombotic drugs', blok: 'Pharmacology', sistem: 'Cardiovascular',
        mengapa: 'The largest single drug group in both Steps, and the one with the most examinable adverse effects.',
        sumber: [S.ahaAcc] },
      { id: 'fa-antimikroba', judul: 'Antimicrobial, antiviral and antifungal agents', blok: 'Pharmacology',
        mengapa: 'Mechanism, spectrum and toxicity are asked together, not separately.',
        sumber: [S.idsa] },
      { id: 'fa-cns', judul: 'CNS and psychiatric pharmacology', blok: 'Pharmacology', sistem: 'Behavioral health',
        mengapa: 'Serotonin syndrome, NMS and withdrawal states are recurring emergency items.',
        sumber: [S.apa, S.bookshelf] },
      { id: 'fa-toksik', judul: 'Toxicology and antidotes', blok: 'Pharmacology', sistem: 'Multisystem processes',
        mengapa: 'A short, closed list with an unusually high yield per item.',
        sumber: [S.statpearls, S.cdc] },
    ],
  },
  {
    id: 'perilaku', jenjang: 'preklinik', judul: 'Behavioral science & Ethics', emoji: '🧠',
    ringkas: 'Development, psychiatry basics, communication, ethics and health systems.',
    topik: [
      { id: 'pe-perkembangan', judul: 'Human development across the lifespan', blok: 'Behavioral science', sistem: 'Behavioral health',
        mengapa: 'Milestones decide whether a paediatric stem is normal or a red flag.',
        sumber: [S.aap] },
      { id: 'pe-etika', judul: 'Medical ethics, consent and capacity', blok: 'Behavioral science',
        mengapa: 'Ethics items have a single defensible answer and are among the most reliably scoreable.',
        sumber: [S.usmleOutline] },
      { id: 'pe-komunikasi', judul: 'Communication and breaking bad news', blok: 'Behavioral science',
        mengapa: 'Step 2 CK and Step 3 both test the next best statement, not the next best test.',
        sumber: [S.usmleOutline] },
      { id: 'pe-sistem', judul: 'Health systems, quality and patient safety', blok: 'Behavioral science', sistem: 'Multisystem processes',
        mengapa: 'Systems-based practice is an explicit Step 3 competency, not background reading.',
        sumber: [S.usmleOutline, S.acgme] },
    ],
  },
  {
    id: 'biostat', jenjang: 'preklinik', judul: 'Biostatistics & Epidemiology', emoji: '📊',
    ringkas: 'Study design, test characteristics, measures of association, and interpretation.',
    topik: [
      { id: 'bs-desain', judul: 'Study design and levels of evidence', blok: 'Biostatistics',
        mengapa: 'Naming the design determines which measure of association is even valid.',
        sumber: [S.bookshelf] },
      { id: 'bs-tes', judul: 'Sensitivity, specificity, predictive values, likelihood ratios', blok: 'Biostatistics',
        mengapa: 'The most consistently examined calculation across all three Steps.',
        sumber: [S.bookshelf, S.uspstf] },
      { id: 'bs-asosiasi', judul: 'Risk, odds, NNT and confidence intervals', blok: 'Biostatistics',
        mengapa: 'Interpreting an interval that crosses 1 is asked more often than computing one.',
        sumber: [S.bookshelf] },
      { id: 'bs-bias', judul: 'Bias, confounding and validity', blok: 'Biostatistics',
        mengapa: 'Questions describe a flawed study and ask you to name the flaw exactly.',
        sumber: [S.bookshelf] },
    ],
  },

  // ───────────────────────────── STEP 1 ───────────────────────────────────
  {
    id: 'step1-bentuk', jenjang: 'step1', judul: 'Step 1 — format and what it now tests', emoji: '📘',
    ringkas: 'How the exam is built, and what changed when it became pass/fail.',
    topik: [
      { id: 's1-format', judul: 'Exam structure, timing and pass/fail reporting', blok: 'Step 1',
        mengapa: 'Step 1 is reported as pass/fail, which moved the selection weight onto Step 2 CK — this changes how the year should be spent, not merely how it is scored.',
        sumber: [S.usmleOutline] },
      { id: 's1-outline', judul: 'Content outline: systems × physician tasks', blok: 'Step 1',
        mengapa: 'The blueprint is two-dimensional. Studying only by system leaves the task dimension — mechanism, diagnosis, management — untrained.',
        sumber: [S.usmleOutline] },
      { id: 's1-integrasi', judul: 'Integrated reasoning across disciplines', blok: 'Step 1',
        mengapa: 'A single item routinely spans biochemistry, pathology and pharmacology; discipline-siloed revision fails these.',
        sumber: [S.usmleOutline] },
    ],
  },

  // ───────────────────────────── STEP 2 CK ────────────────────────────────
  {
    id: 'step2-dalam', jenjang: 'step2ck', judul: 'Internal Medicine', emoji: '🫀',
    ringkas: 'The largest share of Step 2 CK — diagnosis and management across adult medicine.',
    topik: [
      { id: 's2-kardio', judul: 'Cardiology: ACS, heart failure, arrhythmia, valve disease', blok: 'Internal Medicine', sistem: 'Cardiovascular',
        mengapa: 'Highest single-topic yield in Step 2 CK, and management steps are graded finely.',
        sumber: [S.ahaAcc] },
      { id: 's2-paru', judul: 'Pulmonology: asthma, COPD, PE, pneumonia, ILD', blok: 'Internal Medicine', sistem: 'Respiratory',
        mengapa: 'Severity classification drives the treatment step the question is asking for.',
        sumber: [S.gina, S.gold] },
      { id: 's2-ginjal', judul: 'Nephrology: AKI, CKD, electrolytes, acid–base', blok: 'Internal Medicine', sistem: 'Renal & Urinary',
        mengapa: 'Pre-renal versus intrinsic versus post-renal is decided from the data given, every time.',
        sumber: [S.kdigo] },
      { id: 's2-endokrin', judul: 'Endocrinology: diabetes, thyroid, adrenal, pituitary', blok: 'Internal Medicine', sistem: 'Reproductive & Endocrine',
        mengapa: 'Diabetes management steps and DKA/HHS protocols are asked in fine detail.',
        sumber: [S.ada] },
      { id: 's2-cerna', judul: 'Gastroenterology and hepatology', blok: 'Internal Medicine', sistem: 'Gastrointestinal',
        mengapa: 'GI bleeding, cirrhosis complications and IBD each carry standing management algorithms.',
        sumber: [S.statpearls] },
      { id: 's2-infeksi', judul: 'Infectious disease and antimicrobial choice', blok: 'Internal Medicine',
        mengapa: 'Empirical therapy by source and host is a direct, repeated question form.',
        sumber: [S.idsa] },
      { id: 's2-hemonk', judul: 'Haematology and oncology', blok: 'Internal Medicine', sistem: 'Blood & Lymphoreticular',
        mengapa: 'Anaemia workup by indices, and the oncological emergencies, are both high yield.',
        sumber: [S.acs] },
      { id: 's2-rheum', judul: 'Rheumatology and immunology', blok: 'Internal Medicine', sistem: 'Musculoskeletal, Skin & Connective tissue',
        mengapa: 'Autoantibody patterns are only useful when tied to the clinical picture, which is how they are asked.',
        sumber: [S.statpearls] },
      { id: 's2-neuro', judul: 'Neurology', blok: 'Internal Medicine', sistem: 'Nervous system & Special senses',
        mengapa: 'Stroke timing windows and status epilepticus sequences are strictly time-defined.',
        sumber: [S.aan, S.ahaAcc] },
      { id: 's2-kritis', judul: 'Critical care and sepsis', blok: 'Internal Medicine', sistem: 'Multisystem processes',
        mengapa: 'Early recognition and the first hour of management are examined as an ordered sequence.',
        sumber: [S.ssc] },
    ],
  },
  {
    id: 'step2-bedah', jenjang: 'step2ck', judul: 'Surgery', emoji: '🔪',
    ringkas: 'Acute abdomen, trauma, perioperative care, and surgical subspecialties.',
    topik: [
      { id: 's2-akut', judul: 'Acute abdomen and common general surgery', blok: 'Surgery', sistem: 'Gastrointestinal',
        mengapa: 'Which imaging, and whether to operate, are the two decisions the vignette tests.',
        sumber: [S.statpearls] },
      { id: 's2-trauma', judul: 'Trauma: primary and secondary survey', blok: 'Surgery', sistem: 'Multisystem processes',
        mengapa: 'The order is the answer — a correct intervention given out of order scores as wrong.',
        sumber: [S.statpearls] },
      { id: 's2-periop', judul: 'Perioperative assessment and complications', blok: 'Surgery',
        mengapa: 'Postoperative fever by day is a classic, tightly defined discriminator.',
        sumber: [S.ahaAcc, S.statpearls] },
      { id: 's2-subspesial', judul: 'Vascular, thoracic, urology, orthopaedics, ENT', blok: 'Surgery',
        mengapa: 'Limb and organ-threatening emergencies dominate what is asked from these fields.',
        sumber: [S.statpearls] },
    ],
  },
  {
    id: 'step2-anak', jenjang: 'step2ck', judul: 'Pediatrics', emoji: '🧒',
    ringkas: 'Newborn care, growth and development, and paediatric disease.',
    topik: [
      { id: 's2-neonatus', judul: 'Neonatology and newborn problems', blok: 'Pediatrics',
        mengapa: 'Jaundice, respiratory distress and sepsis in the newborn have separate, strict algorithms.',
        sumber: [S.aap] },
      { id: 's2-tumbuh', judul: 'Growth, development and preventive paediatrics', blok: 'Pediatrics', sistem: 'Behavioral health',
        mengapa: 'Deciding normal versus delayed is the commonest paediatric task on the exam.',
        sumber: [S.aap, S.who] },
      { id: 's2-anakinfeksi', judul: 'Paediatric infection and immunisation', blok: 'Pediatrics', sistem: 'Immune system',
        mengapa: 'Schedule and catch-up rules are asked as fact, and they are checkable fact.',
        sumber: [S.cdc, S.aap] },
      { id: 's2-anakkronik', judul: 'Congenital and chronic paediatric disease', blok: 'Pediatrics',
        mengapa: 'This is where preclinical genetics reappears as a management question.',
        sumber: [S.aap] },
    ],
  },
  {
    id: 'step2-obgyn', jenjang: 'step2ck', judul: 'Obstetrics & Gynaecology', emoji: '🤰',
    ringkas: 'Antenatal care, labour, complications, and gynaecological disease.',
    topik: [
      { id: 's2-antenatal', judul: 'Antenatal care and screening', blok: 'Ob/Gyn', sistem: 'Reproductive & Endocrine',
        mengapa: 'What is offered at which gestation is precisely defined and precisely asked.',
        sumber: [S.acog] },
      { id: 's2-persalinan', judul: 'Labour, delivery and obstetric emergencies', blok: 'Ob/Gyn', sistem: 'Reproductive & Endocrine',
        mengapa: 'Postpartum haemorrhage and pre-eclampsia are time-critical ordered sequences.',
        sumber: [S.acog, S.who] },
      { id: 's2-ginekologi', judul: 'Gynaecology: bleeding, masses, endocrinology', blok: 'Ob/Gyn', sistem: 'Reproductive & Endocrine',
        mengapa: 'Age of the patient reshapes the differential more than any other single variable here.',
        sumber: [S.acog] },
      { id: 's2-kontrasepsi', judul: 'Contraception and fertility', blok: 'Ob/Gyn', sistem: 'Reproductive & Endocrine',
        mengapa: 'Contraindications by method are a closed, examinable list.',
        sumber: [S.acog, S.who] },
    ],
  },
  {
    id: 'step2-psikiatri', jenjang: 'step2ck', judul: 'Psychiatry', emoji: '🧩',
    ringkas: 'Diagnosis by criteria, first-line treatment, and psychiatric emergencies.',
    topik: [
      { id: 's2-mood', judul: 'Mood, anxiety and psychotic disorders', blok: 'Psychiatry', sistem: 'Behavioral health',
        mengapa: 'Duration criteria separate the diagnoses, and duration is always stated in the stem.',
        sumber: [S.apa] },
      { id: 's2-zat', judul: 'Substance use, intoxication and withdrawal', blok: 'Psychiatry', sistem: 'Behavioral health',
        mengapa: 'Withdrawal timing and the drugs that are dangerous to stop abruptly are asked directly.',
        sumber: [S.apa, S.statpearls] },
      { id: 's2-darurat', judul: 'Psychiatric emergencies and risk assessment', blok: 'Psychiatry', sistem: 'Behavioral health',
        mengapa: 'Safety comes before diagnosis in the answer order, and the exam enforces it.',
        sumber: [S.apa] },
    ],
  },
  {
    id: 'step2-lain', jenjang: 'step2ck', judul: 'Preventive medicine and other fields', emoji: '🩹',
    ringkas: 'Screening, epidemiology in practice, dermatology, ophthalmology and emergency medicine.',
    topik: [
      { id: 's2-skrining', judul: 'Screening and preventive care by age and risk', blok: 'Preventive medicine',
        mengapa: 'Recommendations are graded and specific; the grade itself is sometimes the question.',
        sumber: [S.uspstf] },
      { id: 's2-derma', judul: 'Dermatology', blok: 'Other', sistem: 'Musculoskeletal, Skin & Connective tissue',
        mengapa: 'Lesion morphology plus distribution is usually sufficient to answer without a biopsy.',
        sumber: [S.statpearls] },
      { id: 's2-mata', judul: 'Ophthalmology and ENT', blok: 'Other', sistem: 'Nervous system & Special senses',
        mengapa: 'The sight- and hearing-threatening emergencies are a short list worth knowing completely.',
        sumber: [S.statpearls] },
      { id: 's2-gawat', judul: 'Emergency medicine and resuscitation', blok: 'Other', sistem: 'Multisystem processes',
        mengapa: 'Resuscitation algorithms are ordered and the order is graded.',
        sumber: [S.ahaAcc] },
    ],
  },

  // ───────────────────────────── STEP 3 ───────────────────────────────────
  {
    id: 'step3', jenjang: 'step3', judul: 'Step 3 — FIP, ACM and CCS', emoji: '🏥',
    ringkas: 'The final Step: independent practice, taken in two days with a simulation component.',
    topik: [
      { id: 's3-fip', judul: 'Day 1 — Foundations of Independent Practice', blok: 'Step 3',
        mengapa: 'Weighted toward biostatistics, epidemiology, pharmacology, ethics and patient safety rather than bedside diagnosis.',
        sumber: [S.usmleOutline] },
      { id: 's3-acm', judul: 'Day 2 — Advanced Clinical Medicine', blok: 'Step 3',
        mengapa: 'Longitudinal cases: the same patient across visits, testing management over time rather than a single decision.',
        sumber: [S.usmleOutline] },
      { id: 's3-ccs', judul: 'Computer-based Case Simulations (CCS)', blok: 'Step 3',
        mengapa: 'A free-entry simulation with no answer options; ordering sequence and timing are scored, and unnecessary orders cost marks.',
        sumber: [S.usmleOutline] },
      { id: 's3-kapan', judul: 'When Step 3 is taken, and why timing matters', blok: 'Step 3',
        mengapa: 'For international graduates the timing interacts with visa sponsorship, which makes it a scheduling decision, not only an academic one.',
        sumber: [S.usmleOutline, S.ecfmg] },
    ],
  },

  // ───────────────────────────── ECFMG ────────────────────────────────────
  {
    id: 'ecfmg', jenjang: 'ecfmg', judul: 'ECFMG certification pathway', emoji: '🌍',
    ringkas: 'What an international medical graduate must complete, and in which order.',
    topik: [
      { id: 'ec-syarat', judul: 'Eligibility: medical school listing and credentials', blok: 'ECFMG',
        mengapa: 'The school must be listed in the World Directory with the required note. This is checked before anything else, and it is the step most often discovered too late.',
        sumber: [S.ecfmg] },
      { id: 'ec-ujian', judul: 'Examination requirement: Step 1 and Step 2 CK', blok: 'ECFMG',
        mengapa: 'Both are required for certification, and each has its own eligibility period.',
        sumber: [S.ecfmg, S.usmleOutline] },
      { id: 'ec-komunikasi', judul: 'Communication skills requirement', blok: 'ECFMG',
        mengapa: 'After Step 2 CS was discontinued, this requirement is met through a defined set of pathways — the accepted options change, so confirm the current list directly with ECFMG.',
        sumber: [S.ecfmg] },
      { id: 'ec-verifikasi', judul: 'Credential verification and EPIC', blok: 'ECFMG',
        mengapa: 'Primary-source verification takes months and runs in parallel with exams; starting it late delays certification even when every exam is passed.',
        sumber: [S.ecfmg] },
      { id: 'ec-match', judul: 'Residency application, the Match and visas', blok: 'ECFMG',
        mengapa: 'ERAS timing, programme requirements and J-1 versus H-1B sponsorship shape which programmes can even consider an application.',
        sumber: [S.ecfmg, S.acgme] },
    ],
  },

  // ─────────────────────── SPESIALIS & SUBSPESIALIS ───────────────────────
  {
    id: 'spesialis', jenjang: 'spesialis', judul: 'Specialty and subspecialty training', emoji: '🎓',
    ringkas: 'What comes after licensure: residency, board certification, and fellowship.',
    topik: [
      { id: 'sp-struktur', judul: 'How US specialty training is structured', blok: 'Specialty',
        mengapa: 'Residency is accredited by ACGME; certification is granted by an ABMS member board. They are separate bodies with separate requirements, and conflating them causes real planning errors.',
        sumber: [S.acgme, S.abms] },
      { id: 'sp-daftar', judul: 'The ABMS member boards and their specialties', blok: 'Specialty',
        mengapa: 'The authoritative list of what counts as a recognised specialty, kept current by ABMS itself.',
        sumber: [S.abms] },
      { id: 'sp-subspesialis', judul: 'Subspecialty certificates and fellowship', blok: 'Specialty',
        mengapa: 'Most subspecialties require prior primary certification; the prerequisite chain determines the order of training.',
        sumber: [S.abms, S.acgme] },
      { id: 'sp-mok', judul: 'Continuing certification and CME', blok: 'Specialty',
        mengapa: 'Certification is time-limited and maintained; this continues for the length of a career.',
        sumber: [S.abms] },
      { id: 'sp-indonesia', judul: 'Indonesian specialist training, for comparison', blok: 'Specialty',
        mengapa: 'PPDS entry, collegium examinations and STR/SIP registration follow a different structure from the US pathway, and this app is used by people planning either — or both.',
        sumber: [{ badan: 'Konsil Kedokteran Indonesia / Kementerian Kesehatan RI', nama: 'Regulation of specialist registration and training', tautan: 'https://www.kemkes.go.id' }] },
    ],
  },
]

export const JENJANG_LABEL: Record<string, { judul: string; ringkas: string }> = {
  preklinik: { judul: 'Preclinical', ringkas: 'The basic sciences, in the order they are usually taught.' },
  step1: { judul: 'USMLE Step 1', ringkas: 'Mechanism of disease across the basic sciences. Reported pass/fail.' },
  step2ck: { judul: 'USMLE Step 2 CK', ringkas: 'Clinical science: diagnosis and management. Still scored numerically.' },
  step3: { judul: 'USMLE Step 3', ringkas: 'Independent practice, over two days, including case simulations.' },
  ecfmg: { judul: 'ECFMG', ringkas: 'Certification pathway for international medical graduates.' },
  spesialis: { judul: 'Specialty & Subspecialty', ringkas: 'Residency, board certification, and fellowship.' },
}

/** Semua topik, diratakan — dipakai pencarian dan penghitung kemajuan. */
export function semuaTopik() {
  return KURIKULUM.flatMap((b) => b.topik.map((t) => ({ ...t, blokId: b.id, jenjang: b.jenjang })))
}
