export type BrainMacroDomain = 'cerebrum'|'diencephalon'|'basal-ganglia'|'limbic'|'brainstem'|'cerebellum'|'white-matter'|'ventricular-csf'|'meninges'|'vascular'|'cranial-nerves'
export interface BrainMacroNode { id:string; label:string; domain:BrainMacroDomain; parentId?:string; nodeHints:string[]; function:string; relations:string[]; geometryStatus:'native-or-source-match-required'|'reference-only'; reviewStatus:'academic-review-pending'; sourceAnchors:string[]; boundary:string }
const B='Generic educational neuroanatomy only; do not infer lesion localization, diagnosis, prognosis, surgical corridor safety, vascular territory infarction, seizure focus, cognitive phenotype, or patient-specific anatomy from this atlas.'
const S=['NCBI:Neuroanatomy']
const n=(id:string,label:string,domain:BrainMacroDomain,parentId:string|undefined,nodeHints:string[],fn:string,relations:string[],geometryStatus:BrainMacroNode['geometryStatus']='native-or-source-match-required'):BrainMacroNode=>({id,label,domain,parentId,nodeHints,function:fn,relations,geometryStatus,reviewStatus:'academic-review-pending',sourceAnchors:S,boundary:B})
export const BRAIN_CNS_MACRO_WAVE1:readonly BrainMacroNode[]=[
 n('brain','Brain','cerebrum',undefined,['brain','encephalon'],'Integrates sensory, motor, autonomic, endocrine and cognitive functions.',['cerebrum','diencephalon','brainstem','cerebellum']),
 n('cerebrum','Cerebrum','cerebrum','brain',['cerebrum','cerebral hemisphere'],'Supratentorial cortex, white matter and deep nuclei.',['frontal-lobe','parietal-lobe','temporal-lobe','occipital-lobe','insula']),
 ...[['frontal-lobe','Frontal lobe'],['parietal-lobe','Parietal lobe'],['temporal-lobe','Temporal lobe'],['occipital-lobe','Occipital lobe'],['insula','Insula']].map(([id,label])=>n(id,label,'cerebrum','cerebrum',[label.toLowerCase()],`Major cortical territory: ${label}.`,['cortex','subcortical white matter'])),
 n('precentral-gyrus','Precentral gyrus / primary motor cortex','cerebrum','frontal-lobe',['precentral gyrus','primary motor cortex'],'Primary cortical motor output.',['central sulcus','corticospinal tract'],'reference-only'),
 n('postcentral-gyrus','Postcentral gyrus / primary somatosensory cortex','cerebrum','parietal-lobe',['postcentral gyrus','somatosensory cortex'],'Primary cortical somatosensory reception.',['central sulcus','thalamocortical fibers'],'reference-only'),
 n('primary-visual-cortex','Primary visual cortex','cerebrum','occipital-lobe',['calcarine cortex','V1'],'First cortical stage for geniculocortical visual input.',['LGN','optic radiations'],'reference-only'),
 n('auditory-cortex','Primary auditory cortex','cerebrum','temporal-lobe',['Heschl gyrus','primary auditory cortex'],'Primary cortical auditory processing.',['MGN','superior temporal gyrus'],'reference-only'),
 n('diencephalon','Diencephalon','diencephalon','brain',['diencephalon'],'Central region around third ventricle.',['thalamus','hypothalamus']),
 n('thalamus','Thalamus','diencephalon','diencephalon',['thalamus'],'Major sensory, motor and associative relay hub.',['cortex','internal capsule','third ventricle']),
 n('lgn','Lateral geniculate nucleus','diencephalon','thalamus',['lateral geniculate nucleus','LGN'],'Visual thalamic relay.',['optic tract','optic radiations'],'reference-only'),
 n('mgn','Medial geniculate nucleus','diencephalon','thalamus',['medial geniculate nucleus','MGN'],'Auditory thalamic relay.',['inferior colliculus','auditory radiations'],'reference-only'),
 n('hypothalamus','Hypothalamus','diencephalon','diencephalon',['hypothalamus'],'Coordinates homeostatic, autonomic, endocrine and circadian functions.',['pituitary stalk','third ventricle','brainstem'],'reference-only'),
 n('basal-ganglia','Basal ganglia','basal-ganglia','brain',['basal ganglia'],'Deep nuclei for action selection and movement scaling.',['caudate','putamen','globus-pallidus','subthalamic-nucleus','substantia-nigra']),
 ...[['caudate','Caudate nucleus'],['putamen','Putamen'],['globus-pallidus','Globus pallidus'],['subthalamic-nucleus','Subthalamic nucleus'],['substantia-nigra','Substantia nigra']].map(([id,label])=>n(id,label,'basal-ganglia','basal-ganglia',[label.toLowerCase()],`Basal-ganglia circuit node: ${label}.`,['motor','associative','limbic loops'],'reference-only')),
 n('limbic-system','Limbic system','limbic','brain',['limbic system'],'Distributed memory, emotion and motivation network.',['hippocampus','amygdala','cingulate-gyrus','fornix'],'reference-only'),
 ...[['hippocampus','Hippocampal formation'],['amygdala','Amygdala'],['cingulate-gyrus','Cingulate gyrus']].map(([id,label])=>n(id,label,'limbic','limbic-system',[label.toLowerCase()],`Limbic network structure: ${label}.`,['memory','emotion','autonomic integration'],'reference-only')),
 n('white-matter','Cerebral white matter','white-matter','cerebrum',['cerebral white matter'],'Projection, commissural and association fibers.',['corpus-callosum','internal-capsule','corona-radiata']),
 ...[['corpus-callosum','Corpus callosum'],['internal-capsule','Internal capsule'],['corona-radiata','Corona radiata'],['fornix','Fornix'],['optic-radiations','Optic radiations']].map(([id,label])=>n(id,label,'white-matter',id==='fornix'?'limbic-system':'white-matter',[label.toLowerCase()],`Major white-matter pathway: ${label}.`,['cortex','deep nuclei','brainstem'],'reference-only')),
 n('brainstem','Brainstem','brainstem','brain',['brainstem'],'Connects cerebrum, cerebellum and spinal cord; houses cranial-nerve nuclei.',['midbrain','pons','medulla']),
 ...[['midbrain','Midbrain'],['pons','Pons'],['medulla','Medulla oblongata']].map(([id,label])=>n(id,label,'brainstem','brainstem',[label.toLowerCase()],`Brainstem division: ${label}.`,['cranial nerves','ascending tracts','descending tracts'])),
 n('superior-colliculus','Superior colliculus','brainstem','midbrain',['superior colliculus'],'Visual orienting tectal structure.',['midbrain','oculomotor circuits'],'reference-only'),
 n('inferior-colliculus','Inferior colliculus','brainstem','midbrain',['inferior colliculus'],'Auditory midbrain relay.',['lateral lemniscus','MGN'],'reference-only'),
 n('cerebellum','Cerebellum','cerebellum','brain',['cerebellum'],'Coordinates timing, balance, error correction and motor learning.',['vermis','hemispheres','dentate-nucleus','cerebellar-peduncles']),
 n('vermis','Cerebellar vermis','cerebellum','cerebellum',['cerebellar vermis'],'Midline postural/axial cerebellar region.',['hemispheres','fourth ventricle'],'reference-only'),
 n('dentate-nucleus','Dentate nucleus','cerebellum','cerebellum',['dentate nucleus'],'Major deep cerebellar output nucleus.',['superior cerebellar peduncle'],'reference-only'),
 ...[['superior-cerebellar-peduncle','Superior cerebellar peduncle'],['middle-cerebellar-peduncle','Middle cerebellar peduncle'],['inferior-cerebellar-peduncle','Inferior cerebellar peduncle']].map(([id,label])=>n(id,label,'white-matter','cerebellum',[label.toLowerCase()],`Cerebellar connection: ${label}.`,['brainstem','cerebellum'],'reference-only')),
 n('ventricular-system','Ventricular system','ventricular-csf','brain',['ventricular system'],'CSF-containing cavities and conduits.',['lateral-ventricles','third-ventricle','cerebral-aqueduct','fourth-ventricle'],'reference-only'),
 ...[['lateral-ventricles','Lateral ventricles'],['third-ventricle','Third ventricle'],['cerebral-aqueduct','Cerebral aqueduct'],['fourth-ventricle','Fourth ventricle'],['choroid-plexus','Choroid plexus']].map(([id,label])=>n(id,label,'ventricular-csf','ventricular-system',[label.toLowerCase()],`CSF system structure: ${label}.`,['CSF pathway'],'reference-only')),
 n('meninges','Meninges','meninges','brain',['meninges'],'Protective coverings and CSF-space boundaries.',['dura','arachnoid','pia','subarachnoid-space'],'reference-only'),
 ...[['dura','Dura mater'],['arachnoid','Arachnoid mater'],['pia','Pia mater'],['subarachnoid-space','Subarachnoid space']].map(([id,label])=>n(id,label,'meninges','meninges',[label.toLowerCase()],`Meningeal compartment: ${label}.`,['brain surface','CSF spaces'],'reference-only')),
 n('circle-of-willis','Circle of Willis','vascular','brain',['circle of Willis'],'Arterial anastomotic ring at brain base.',['ACA','MCA origins','PCA','communicating arteries'],'reference-only'),
 ...[['aca','Anterior cerebral artery'],['mca','Middle cerebral artery'],['pca','Posterior cerebral artery'],['basilar','Basilar artery'],['vertebral-arteries','Vertebral arteries']].map(([id,label])=>n(id,label,'vascular','circle-of-willis',[label.toLowerCase()],`Major cerebral arterial structure: ${label}.`,['cerebral perfusion territories'],'reference-only')),
 n('cranial-nerves','Cranial nerves','cranial-nerves','brain',['cranial nerves'],'Twelve paired nerves connecting brain/brainstem with sensory, motor and autonomic targets.',['CN I-XII'],'reference-only'),
 ...['Olfactory','Optic','Oculomotor','Trochlear','Trigeminal','Abducens','Facial','Vestibulocochlear','Glossopharyngeal','Vagus','Accessory','Hypoglossal'].map((label,i)=>n(`cn${i+1}`,`CN ${i+1} · ${label}`,'cranial-nerves','cranial-nerves',[`${label.toLowerCase()} nerve`,`CN ${i+1}`],`Cranial nerve ${i+1}: ${label}.`,['brain or brainstem origin','foraminal course'],'reference-only')),
] as const
export const BRAIN_MACRO_REQUIRED_IDS=['brain','cerebrum','frontal-lobe','parietal-lobe','temporal-lobe','occipital-lobe','insula','thalamus','hypothalamus','caudate','putamen','globus-pallidus','subthalamic-nucleus','substantia-nigra','hippocampus','amygdala','corpus-callosum','internal-capsule','brainstem','midbrain','pons','medulla','cerebellum','dentate-nucleus','lateral-ventricles','third-ventricle','cerebral-aqueduct','fourth-ventricle','dura','arachnoid','pia','circle-of-willis','aca','mca','pca','basilar','vertebral-arteries','cn1','cn2','cn3','cn4','cn5','cn6','cn7','cn8','cn9','cn10','cn11','cn12'] as const
export function validateBrainCnsMacroWave1(records:readonly BrainMacroNode[]=BRAIN_CNS_MACRO_WAVE1):string[]{const e:string[]=[];const ids=new Set<string>();for(const x of records){if(ids.has(x.id))e.push(`duplicate:${x.id}`);ids.add(x.id);if(!x.label.trim())e.push(`label:${x.id}`);if(!x.function.trim())e.push(`function:${x.id}`);if(!x.sourceAnchors.length)e.push(`source:${x.id}`);if(x.reviewStatus!=='academic-review-pending')e.push(`review:${x.id}`);if(!x.boundary.includes('Generic educational neuroanatomy'))e.push(`boundary:${x.id}`)}for(const x of records)if(x.parentId&&!ids.has(x.parentId))e.push(`parent:${x.id}:${x.parentId}`);for(const id of BRAIN_MACRO_REQUIRED_IDS)if(!ids.has(id))e.push(`required:${id}`);return e}
