import { BRAIN_CNS_MACRO_WAVE1 } from './brainCnsMacroWave1'

export type BrainStructuralDomain = 'cortical-landmark'|'deep-nucleus'|'white-matter-tract'|'brainstem-nucleus'|'cerebellar-structure'|'csf-cistern'
export interface BrainStructuralNode { id:string; label:string; domain:BrainStructuralDomain; parentId:string; nodeHints:string[]; function:string; relations:string[]; geometryStatus:'reference-only'; reviewStatus:'academic-review-pending'; evidenceAnchor:string; boundary:string }
const B='Generic educational neuroanatomy only; do not infer lesion localization, diagnosis, prognosis, seizure focus, infarct territory, surgical corridor safety, cognitive phenotype, or patient-specific anatomy from this structural atlas.'
const n=(id:string,label:string,domain:BrainStructuralDomain,parentId:string,nodeHints:string[],fn:string,relations:string[],evidenceAnchor='NCBI:Neuroanatomy'):BrainStructuralNode=>({id,label,domain,parentId,nodeHints,function:fn,relations,geometryStatus:'reference-only',reviewStatus:'academic-review-pending',evidenceAnchor,boundary:B})
export const BRAIN_CNS_STRUCTURAL_WAVE2:readonly BrainStructuralNode[]=[
 n('central-sulcus','Central sulcus','cortical-landmark','cerebrum',['central sulcus'],'Separates frontal and parietal lobes; landmark between primary motor and somatosensory cortex.',['precentral-gyrus','postcentral-gyrus']),
 n('lateral-sulcus','Lateral sulcus','cortical-landmark','cerebrum',['lateral sulcus','Sylvian fissure'],'Separates temporal lobe from frontal/parietal opercula.',['insula','frontal-lobe','temporal-lobe']),
 n('calcarine-sulcus','Calcarine sulcus','cortical-landmark','occipital-lobe',['calcarine sulcus'],'Medial occipital landmark associated with primary visual cortex.',['primary-visual-cortex','cuneus','lingual gyrus']),
 n('cingulate-sulcus','Cingulate sulcus','cortical-landmark','limbic-system',['cingulate sulcus'],'Medial cortical landmark bordering cingulate cortex.',['cingulate-gyrus','medial frontal cortex']),
 n('caudate-head','Caudate head','deep-nucleus','caudate',['head of caudate'],'Anterior caudate subdivision adjacent to frontal horn of lateral ventricle.',['lateral-ventricles','internal-capsule']),
 n('caudate-body','Caudate body','deep-nucleus','caudate',['body of caudate'],'Central caudate subdivision following lateral ventricle body.',['thalamus','lateral-ventricles']),
 n('caudate-tail','Caudate tail','deep-nucleus','caudate',['tail of caudate'],'Posterior-inferior caudate subdivision extending toward temporal horn.',['amygdala','temporal-lobe']),
 n('gpe','Globus pallidus externus','deep-nucleus','globus-pallidus',['external globus pallidus','GPe'],'External pallidal segment in basal-ganglia indirect pathway circuitry.',['putamen','subthalamic-nucleus']),
 n('gpi','Globus pallidus internus','deep-nucleus','globus-pallidus',['internal globus pallidus','GPi'],'Major basal-ganglia output nucleus toward thalamic motor circuits.',['thalamus','internal-capsule']),
 n('substantia-nigra-pars-compacta','Substantia nigra pars compacta','deep-nucleus','substantia-nigra',['substantia nigra pars compacta','SNc'],'Dopaminergic modulatory subdivision of substantia nigra.',['striatum','midbrain']),
 n('substantia-nigra-pars-reticulata','Substantia nigra pars reticulata','deep-nucleus','substantia-nigra',['substantia nigra pars reticulata','SNr'],'Major inhibitory basal-ganglia output subdivision.',['superior-colliculus','thalamus']),
 n('anterior-limb-internal-capsule','Anterior limb of internal capsule','white-matter-tract','internal-capsule',['anterior limb internal capsule'],'Projection fibers between frontal cortex and deep nuclei/thalamus.',['caudate','lentiform nucleus']),
 n('genu-internal-capsule','Genu of internal capsule','white-matter-tract','internal-capsule',['genu internal capsule'],'Contains important corticobulbar projection fibers.',['cortex','brainstem']),
 n('posterior-limb-internal-capsule','Posterior limb of internal capsule','white-matter-tract','internal-capsule',['posterior limb internal capsule'],'Major corticospinal and somatosensory projection corridor.',['thalamus','cerebral-peduncle']),
 n('arcuate-fasciculus','Arcuate fasciculus','white-matter-tract','white-matter',['arcuate fasciculus'],'Association pathway linking frontal and posterior temporal/parietal language regions.',['broca-region','temporal-lobe']),
 n('uncinate-fasciculus','Uncinate fasciculus','white-matter-tract','white-matter',['uncinate fasciculus'],'Frontotemporal association pathway.',['prefrontal-cortex','temporal-lobe']),
 n('red-nucleus','Red nucleus','brainstem-nucleus','midbrain',['red nucleus'],'Midbrain motor coordination nucleus with cerebellar connections.',['superior-cerebellar-peduncle','thalamus']),
 n('periaqueductal-gray','Periaqueductal gray','brainstem-nucleus','midbrain',['periaqueductal gray','PAG'],'Gray matter surrounding cerebral aqueduct involved in defensive/autonomic/pain-modulatory networks.',['cerebral-aqueduct','hypothalamus']),
 n('locus-coeruleus','Locus coeruleus','brainstem-nucleus','pons',['locus coeruleus'],'Pontine noradrenergic nucleus involved in arousal and autonomic regulation.',['fourth-ventricle','forebrain']),
 n('nucleus-solitary-tract','Nucleus of the solitary tract','brainstem-nucleus','medulla',['nucleus tractus solitarius','NTS'],'Medullary visceral sensory nucleus.',['CN IX','CN X','autonomic networks']),
 n('inferior-olivary-nucleus','Inferior olivary nucleus','brainstem-nucleus','medulla',['inferior olive'],'Major precerebellar nucleus providing climbing-fiber input.',['cerebellum','inferior-cerebellar-peduncle']),
 n('cerebellar-cortex','Cerebellar cortex','cerebellar-structure','cerebellum',['cerebellar cortex'],'Layered cerebellar surface gray matter.',['vermis','hemispheres','deep nuclei']),
 n('fastigial-nucleus','Fastigial nucleus','cerebellar-structure','cerebellum',['fastigial nucleus'],'Medial deep cerebellar nucleus linked to axial/vestibular functions.',['vermis','brainstem']),
 n('interposed-nuclei','Interposed nuclei','cerebellar-structure','cerebellum',['emboliform nucleus','globose nucleus','interposed nuclei'],'Deep cerebellar nuclei between fastigial and dentate.',['cerebellar cortex','superior-cerebellar-peduncle']),
 n('foramen-monro','Interventricular foramen (Monro)','csf-cistern','ventricular-system',['foramen of Monro','interventricular foramen'],'Connects each lateral ventricle to third ventricle.',['lateral-ventricles','third-ventricle']),
 n('median-aperture','Median aperture (Magendie)','csf-cistern','fourth-ventricle',['foramen of Magendie','median aperture'],'Median CSF outlet from fourth ventricle to subarachnoid space.',['fourth-ventricle','cisterna-magna']),
 n('lateral-apertures','Lateral apertures (Luschka)','csf-cistern','fourth-ventricle',['foramina of Luschka','lateral apertures'],'Lateral CSF outlets from fourth ventricle.',['fourth-ventricle','cerebellopontine-angle-cistern']),
 n('cisterna-magna','Cisterna magna','csf-cistern','subarachnoid-space',['cisterna magna'],'Large posterior fossa subarachnoid cistern.',['medulla','cerebellum','median-aperture']),
 n('interpeduncular-cistern','Interpeduncular cistern','csf-cistern','subarachnoid-space',['interpeduncular cistern'],'Basal cistern between cerebral peduncles.',['midbrain','circle-of-willis']),
] as const
export const BRAIN_STRUCTURAL_REQUIRED_IDS=['central-sulcus','lateral-sulcus','calcarine-sulcus','caudate-head','caudate-body','caudate-tail','gpe','gpi','substantia-nigra-pars-compacta','substantia-nigra-pars-reticulata','anterior-limb-internal-capsule','genu-internal-capsule','posterior-limb-internal-capsule','arcuate-fasciculus','red-nucleus','periaqueductal-gray','locus-coeruleus','nucleus-solitary-tract','inferior-olivary-nucleus','cerebellar-cortex','fastigial-nucleus','interposed-nuclei','foramen-monro','median-aperture','lateral-apertures','cisterna-magna'] as const
export function validateBrainCnsStructuralWave2(records:readonly BrainStructuralNode[]=BRAIN_CNS_STRUCTURAL_WAVE2){const errors:string[]=[];const macroIds=new Set(BRAIN_CNS_MACRO_WAVE1.map(x=>x.id));const ids=new Set<string>();for(const x of records){if(ids.has(x.id))errors.push(`duplicate:${x.id}`);ids.add(x.id);if(!x.label.trim())errors.push(`label:${x.id}`);if(!x.parentId)errors.push(`parent:${x.id}`);if(!x.evidenceAnchor.trim())errors.push(`evidence:${x.id}`);if(x.geometryStatus!=='reference-only')errors.push(`geometry:${x.id}`);if(x.reviewStatus!=='academic-review-pending')errors.push(`review:${x.id}`);if(!x.boundary.includes('patient-specific anatomy'))errors.push(`boundary:${x.id}`)}for(const x of records){if(!ids.has(x.parentId)&&!macroIds.has(x.parentId))errors.push(`parent-missing:${x.id}:${x.parentId}`)}for(const id of BRAIN_STRUCTURAL_REQUIRED_IDS)if(!ids.has(id))errors.push(`required:${id}`);return errors}
