import type { AnatomyRegionId, AnatomyStructure, AnatomySystemId } from './types'

type Options = Partial<Pick<AnatomyStructure, 'synonyms' | 'laterality' | 'parentId' | 'tags' | 'assetGroupId' | 'reviewStatus'>>
const s = (id: string, label: string, system: AnatomySystemId, regions: readonly AnatomyRegionId[], options: Options = {}): AnatomyStructure => ({
  id, label, system, regions, synonyms: options.synonyms ?? [], laterality: options.laterality ?? 'none',
  parentId: options.parentId, tags: options.tags ?? [], assetGroupId: options.assetGroupId,
  reviewStatus: options.reviewStatus ?? 'reference',
})
const bilateral = (stem: string, label: string, system: AnatomySystemId, regions: readonly AnatomyRegionId[], parentId: string, extra: Options = {}) => ([
  s(`right-${stem}`, `Right ${label}`, system, regions, { ...extra, laterality: 'right', parentId }),
  s(`left-${stem}`, `Left ${label}`, system, regions, { ...extra, laterality: 'left', parentId }),
] as const)

export const WHOLE_BODY_CORE_STRUCTURES: readonly AnatomyStructure[] = [
  s('body', 'Human body', 'regional', ['whole-body'], { synonyms: ['whole body'], tags: ['root'] }),
  s('head-region', 'Head', 'regional', ['head'], { parentId: 'body' }),
  s('neck-region', 'Neck', 'regional', ['neck'], { parentId: 'body' }),
  s('thorax-region', 'Thorax', 'regional', ['thorax'], { parentId: 'body', synonyms: ['chest'] }),
  s('abdomen-region', 'Abdomen', 'regional', ['abdomen'], { parentId: 'body' }),
  s('pelvis-region', 'Pelvis and perineum', 'regional', ['pelvis-perineum'], { parentId: 'body', synonyms: ['pelvis'] }),
  s('back-region', 'Back and spine', 'regional', ['back-spine'], { parentId: 'body', synonyms: ['back'] }),
  ...bilateral('upper-limb-region', 'upper limb', 'regional', ['upper-limb'], 'body'),
  ...bilateral('lower-limb-region', 'lower limb', 'regional', ['lower-limb'], 'body'),

  s('skeleton', 'Skeleton', 'skeletal', ['whole-body'], { parentId: 'body', synonyms: ['bone', 'bones'], assetGroupId: 'skeletal-whole-body' }),
  s('skull', 'Skull', 'skeletal', ['head'], { parentId: 'skeleton', synonyms: ['cranium'] }),
  s('mandible', 'Mandible', 'skeletal', ['head'], { parentId: 'skull', synonyms: ['jaw bone'] }),
  s('vertebral-column', 'Vertebral column', 'skeletal', ['neck','thorax','abdomen','pelvis-perineum','back-spine'], { parentId: 'skeleton', synonyms: ['spine'] }),
  s('cervical-spine', 'Cervical spine', 'skeletal', ['neck','back-spine'], { parentId: 'vertebral-column', synonyms: ['cervical vertebrae'] }),
  s('thoracic-spine', 'Thoracic spine', 'skeletal', ['thorax','back-spine'], { parentId: 'vertebral-column', synonyms: ['thoracic vertebrae'] }),
  s('lumbar-spine', 'Lumbar spine', 'skeletal', ['abdomen','back-spine'], { parentId: 'vertebral-column', synonyms: ['lumbar vertebrae'] }),
  s('sacrum', 'Sacrum', 'skeletal', ['pelvis-perineum','back-spine'], { parentId: 'vertebral-column' }),
  s('sternum', 'Sternum', 'skeletal', ['thorax'], { parentId: 'skeleton' }),
  s('ribs', 'Ribs', 'skeletal', ['thorax'], { parentId: 'skeleton', synonyms: ['rib cage'] }),
  s('bony-pelvis', 'Bony pelvis', 'skeletal', ['pelvis-perineum'], { parentId: 'skeleton', synonyms: ['pelvic bones'] }),
  ...bilateral('clavicle', 'clavicle', 'skeletal', ['thorax','upper-limb'], 'skeleton'),
  ...bilateral('scapula', 'scapula', 'skeletal', ['upper-limb','back-spine'], 'skeleton'),
  ...bilateral('humerus', 'humerus', 'skeletal', ['upper-limb'], 'skeleton'),
  ...bilateral('radius', 'radius', 'skeletal', ['upper-limb'], 'skeleton'),
  ...bilateral('ulna', 'ulna', 'skeletal', ['upper-limb'], 'skeleton'),
  ...bilateral('femur', 'femur', 'skeletal', ['lower-limb'], 'skeleton'),
  ...bilateral('patella', 'patella', 'skeletal', ['lower-limb'], 'skeleton'),
  ...bilateral('tibia', 'tibia', 'skeletal', ['lower-limb'], 'skeleton'),
  ...bilateral('fibula', 'fibula', 'skeletal', ['lower-limb'], 'skeleton'),

  s('skeletal-muscle-system', 'Skeletal muscle system', 'muscular', ['whole-body'], { parentId: 'body', synonyms: ['muscle','muscles'], assetGroupId: 'muscular-whole-body' }),
  s('pectoralis-major', 'Pectoralis major', 'muscular', ['thorax','upper-limb'], { parentId: 'skeletal-muscle-system' }),
  s('deltoid', 'Deltoid', 'muscular', ['upper-limb'], { parentId: 'skeletal-muscle-system' }),
  s('biceps-brachii', 'Biceps brachii', 'muscular', ['upper-limb'], { parentId: 'skeletal-muscle-system', synonyms: ['biceps'] }),
  s('triceps-brachii', 'Triceps brachii', 'muscular', ['upper-limb'], { parentId: 'skeletal-muscle-system', synonyms: ['triceps'] }),
  s('rectus-abdominis', 'Rectus abdominis', 'muscular', ['abdomen'], { parentId: 'skeletal-muscle-system' }),
  s('erector-spinae', 'Erector spinae', 'muscular', ['back-spine'], { parentId: 'skeletal-muscle-system' }),
  s('gluteus-maximus', 'Gluteus maximus', 'muscular', ['pelvis-perineum','lower-limb'], { parentId: 'skeletal-muscle-system' }),
  s('quadriceps-femoris', 'Quadriceps femoris', 'muscular', ['lower-limb'], { parentId: 'skeletal-muscle-system', synonyms: ['quadriceps'] }),
  s('hamstrings', 'Hamstrings', 'muscular', ['lower-limb'], { parentId: 'skeletal-muscle-system' }),

  s('heart', 'Heart', 'cardiovascular', ['thorax'], { parentId: 'thorax-region', synonyms: ['cardiac'], assetGroupId: 'cardiovascular-core' }),
  s('ascending-aorta', 'Ascending aorta', 'arterial', ['thorax'], { parentId: 'heart' }),
  s('aortic-arch', 'Aortic arch', 'arterial', ['thorax'], { parentId: 'ascending-aorta' }),
  s('descending-aorta', 'Descending aorta', 'arterial', ['thorax','abdomen'], { parentId: 'aortic-arch' }),
  s('abdominal-aorta', 'Abdominal aorta', 'arterial', ['abdomen'], { parentId: 'descending-aorta' }),
  s('pulmonary-artery', 'Pulmonary artery', 'arterial', ['thorax'], { parentId: 'heart', synonyms: ['pulmonary trunk'] }),
  s('pulmonary-veins', 'Pulmonary veins', 'venous', ['thorax'], { parentId: 'heart', synonyms: ['pulmonary vein'] }),
  ...bilateral('common-carotid', 'common carotid artery', 'arterial', ['neck'], 'aortic-arch'),
  ...bilateral('subclavian-artery', 'subclavian artery', 'arterial', ['thorax','upper-limb'], 'aortic-arch'),
  ...bilateral('brachial-artery', 'brachial artery', 'arterial', ['upper-limb'], 'aortic-arch'),
  ...bilateral('common-iliac-artery', 'common iliac artery', 'arterial', ['pelvis-perineum'], 'abdominal-aorta'),
  ...bilateral('femoral-artery', 'femoral artery', 'arterial', ['lower-limb'], 'abdominal-aorta'),
  s('superior-vena-cava', 'Superior vena cava', 'venous', ['thorax'], { parentId: 'heart', synonyms: ['SVC'] }),
  s('inferior-vena-cava', 'Inferior vena cava', 'venous', ['thorax','abdomen'], { parentId: 'heart', synonyms: ['IVC'] }),
  ...bilateral('internal-jugular-vein', 'internal jugular vein', 'venous', ['neck'], 'superior-vena-cava'),
  ...bilateral('femoral-vein', 'femoral vein', 'venous', ['lower-limb'], 'inferior-vena-cava'),

  s('brain', 'Brain', 'nervous-cns', ['head'], { parentId: 'head-region', assetGroupId: 'nervous-cns' }),
  s('cerebrum', 'Cerebrum', 'nervous-cns', ['head'], { parentId: 'brain' }),
  s('cerebellum', 'Cerebellum', 'nervous-cns', ['head'], { parentId: 'brain' }),
  s('brainstem', 'Brainstem', 'nervous-cns', ['head'], { parentId: 'brain' }),
  s('spinal-cord', 'Spinal cord', 'nervous-cns', ['neck','thorax','abdomen','back-spine'], { parentId: 'brain', assetGroupId: 'nervous-cns' }),
  s('vagus-nerve', 'Vagus nerve', 'nervous-pns', ['head','neck','thorax','abdomen'], { parentId: 'brain', synonyms: ['cranial nerve X'] }),
  ...bilateral('brachial-plexus', 'brachial plexus', 'nervous-pns', ['neck','upper-limb'], 'spinal-cord'),
  ...bilateral('sciatic-nerve', 'sciatic nerve', 'nervous-pns', ['pelvis-perineum','lower-limb'], 'spinal-cord'),

  s('esophagus', 'Esophagus', 'digestive', ['neck','thorax','abdomen'], { parentId: 'body', synonyms: ['oesophagus'] }),
  s('stomach', 'Stomach', 'digestive', ['abdomen'], { parentId: 'esophagus' }),
  s('duodenum', 'Duodenum', 'digestive', ['abdomen'], { parentId: 'stomach' }),
  s('jejunum', 'Jejunum', 'digestive', ['abdomen'], { parentId: 'duodenum' }),
  s('ileum', 'Ileum', 'digestive', ['abdomen','pelvis-perineum'], { parentId: 'jejunum' }),
  s('cecum', 'Cecum', 'digestive', ['abdomen'], { parentId: 'ileum' }),
  s('appendix', 'Vermiform appendix', 'digestive', ['abdomen'], { parentId: 'cecum', synonyms: ['appendix'] }),
  s('colon', 'Colon', 'digestive', ['abdomen','pelvis-perineum'], { parentId: 'cecum', synonyms: ['large intestine'] }),
  s('rectum', 'Rectum', 'digestive', ['pelvis-perineum'], { parentId: 'colon' }),
  s('liver', 'Liver', 'hepatobiliary', ['abdomen'], { parentId: 'abdomen-region' }),
  s('gallbladder', 'Gallbladder', 'hepatobiliary', ['abdomen'], { parentId: 'liver' }),
  s('pancreas', 'Pancreas', 'hepatobiliary', ['abdomen'], { parentId: 'abdomen-region' }),

  ...bilateral('kidney', 'kidney', 'urinary', ['abdomen'], 'abdomen-region', { synonyms: ['kidney'] }),
  ...bilateral('ureter', 'ureter', 'urinary', ['abdomen','pelvis-perineum'], 'abdomen-region'),
  s('urinary-bladder', 'Urinary bladder', 'urinary', ['pelvis-perineum'], { parentId: 'pelvis-region', synonyms: ['bladder'] }),
  s('urethra', 'Urethra', 'urinary', ['pelvis-perineum'], { parentId: 'urinary-bladder' }),

  s('pituitary-gland', 'Pituitary gland', 'endocrine', ['head'], { parentId: 'head-region', synonyms: ['pituitary'] }),
  s('thyroid-gland', 'Thyroid gland', 'endocrine', ['neck'], { parentId: 'neck-region', synonyms: ['thyroid'] }),
  s('parathyroid-glands', 'Parathyroid glands', 'endocrine', ['neck'], { parentId: 'thyroid-gland' }),
  ...bilateral('adrenal-gland', 'adrenal gland', 'endocrine', ['abdomen'], 'abdomen-region', { synonyms: ['suprarenal gland'] }),

  s('spleen', 'Spleen', 'lymphatic', ['abdomen'], { parentId: 'abdomen-region' }),
  s('thoracic-duct', 'Thoracic duct', 'lymphatic', ['abdomen','thorax','neck'], { parentId: 'body' }),
  s('cervical-lymph-node-stations', 'Cervical lymph node stations', 'lymphatic', ['neck'], { parentId: 'thoracic-duct', tags: ['lymph-node-station'] }),
  ...bilateral('axillary-lymph-nodes', 'axillary lymph nodes', 'lymphatic', ['upper-limb','thorax'], 'body', { tags: ['lymph-node-station'] }),
  ...bilateral('inguinal-lymph-nodes', 'inguinal lymph nodes', 'lymphatic', ['pelvis-perineum','lower-limb'], 'body', { tags: ['lymph-node-station'] }),

  s('skin', 'Skin', 'integumentary', ['whole-body'], { parentId: 'body', synonyms: ['integument'], assetGroupId: 'integumentary-whole-body' }),
  s('uterus', 'Uterus', 'reproductive', ['pelvis-perineum'], { parentId: 'pelvis-region' }),
  ...bilateral('ovary', 'ovary', 'reproductive', ['pelvis-perineum'], 'pelvis-region'),
  s('prostate', 'Prostate', 'reproductive', ['pelvis-perineum'], { parentId: 'pelvis-region' }),
  ...bilateral('testis', 'testis', 'reproductive', ['pelvis-perineum'], 'pelvis-region'),

  ...bilateral('temporomandibular-joint', 'temporomandibular joint', 'articular', ['head'], 'head-region'),
  ...bilateral('glenohumeral-joint', 'glenohumeral joint', 'articular', ['upper-limb'], 'body', { synonyms: ['shoulder joint'], assetGroupId: 'articular-core' }),
  ...bilateral('elbow-joint', 'elbow joint', 'articular', ['upper-limb'], 'body'),
  ...bilateral('wrist-joint', 'wrist joint', 'articular', ['upper-limb'], 'body'),
  ...bilateral('hip-joint', 'hip joint', 'articular', ['pelvis-perineum','lower-limb'], 'body', { assetGroupId: 'articular-core' }),
  ...bilateral('knee-joint', 'knee joint', 'articular', ['lower-limb'], 'body', { assetGroupId: 'articular-core' }),
  ...bilateral('ankle-joint', 'ankle joint', 'articular', ['lower-limb'], 'body'),

  s('thoracolumbar-fascia', 'Thoracolumbar fascia', 'fascial', ['thorax','abdomen','back-spine'], { parentId: 'back-region', assetGroupId: 'fascial-core' }),
  s('deep-cervical-fascia', 'Deep cervical fascia', 'fascial', ['neck'], { parentId: 'neck-region', assetGroupId: 'fascial-core' }),
  ...bilateral('plantar-fascia', 'plantar fascia', 'fascial', ['lower-limb'], 'body', { assetGroupId: 'fascial-core' }),
  ...bilateral('eye', 'eye', 'sensory', ['head'], 'head-region', { synonyms: ['globe'], assetGroupId: 'sensory-head' }),
  ...bilateral('inner-ear', 'inner ear', 'sensory', ['head'], 'head-region', { assetGroupId: 'sensory-head' }),
]
