import type {
  AnatomyAtlasNode,
  AnatomyLaterality,
  AnatomyRegion,
  AnatomyScale,
  AnatomySystem,
} from './atlasTypes.ts'

const DRAFT_VERSION = 'panacea-whole-body-structural-draft-2026-09-09'

const FILE_BY_SYSTEM: Record<AnatomySystem, string> = {
  skeletal: 'skeletal.glb',
  muscular: 'muscular.glb',
  arterial: 'cardiovascular.glb',
  venous: 'cardiovascular.glb',
  lymphatic: 'lymphoid.glb',
  nervous: 'nervous.glb',
  respiratory: 'visceral.glb',
  cardiovascular: 'cardiovascular.glb',
  gastrointestinal: 'visceral.glb',
  hepatobiliary: 'visceral.glb',
  urinary: 'visceral.glb',
  'female-reproductive': 'visceral.glb',
  'male-reproductive': 'visceral.glb',
  endocrine: 'visceral.glb',
  integumentary: 'surface.glb',
  'fascia-connective': 'muscular.glb',
}

function draftNode(
  id: string,
  canonicalName: string,
  system: AnatomySystem,
  regions: readonly AnatomyRegion[],
  sourceNodeHints: readonly string[],
  options: {
    parentId?: string
    synonyms?: readonly string[]
    laterality?: AnatomyLaterality
    scale?: AnatomyScale
    notes?: readonly string[]
  } = {},
): AnatomyAtlasNode {
  return {
    id,
    canonicalName,
    synonyms: options.synonyms ?? [],
    system,
    regions,
    laterality: options.laterality ?? 'not-applicable',
    scale: options.scale ?? 'regional',
    parentId: options.parentId,
    sourceBindings: sourceNodeHints.length ? [{
      file: FILE_BY_SYSTEM[system],
      sourceNodeHints,
      status: 'candidate',
      meshMode: 'metadata-only',
    }] : [],
    provenance: [{
      sourceId: 'panacea-structural-manifest',
      sourceVersion: DRAFT_VERSION,
      sourceLocator: `src/lib/anatomy/wholeBodyAtlas.ts#${id}`,
      evidenceKind: 'internal-structural',
      academicReview: 'pending',
      modelAssetReview: 'pending',
      note: 'Structural navigation target only. Candidate source-node hints require source-level and qualified anatomy review before being promoted as verified geometry.',
    }],
    reviewStatus: 'structural-draft',
    educationalOnly: true,
    notes: options.notes,
  }
}

const systemRoot = (
  id: string,
  canonicalName: string,
  system: AnatomySystem,
  hints: readonly string[],
): AnatomyAtlasNode => draftNode(id, canonicalName, system, ['whole-body'], hints, { scale: 'whole-body' })

export const WHOLE_BODY_ATLAS_NODES: readonly AnatomyAtlasNode[] = [
  systemRoot('system-skeletal', 'Skeletal system', 'skeletal', ['bone', 'skeleton']),
  draftNode('skeletal-skull', 'Skull', 'skeletal', ['head-neck'], ['skull', 'cranium'], { parentId: 'system-skeletal', scale: 'regional' }),
  draftNode('skeletal-vertebral-column', 'Vertebral column', 'skeletal', ['back-spine'], ['vertebra', 'spine'], { parentId: 'system-skeletal', synonyms: ['spine'] }),
  draftNode('skeletal-thoracic-cage', 'Thoracic cage', 'skeletal', ['thorax'], ['rib', 'sternum'], { parentId: 'system-skeletal', synonyms: ['rib cage'] }),
  draftNode('skeletal-upper-limb', 'Upper limb skeleton', 'skeletal', ['upper-limb'], ['clavicle', 'scapula', 'humerus', 'radius', 'ulna', 'carpal'], { parentId: 'system-skeletal', laterality: 'bilateral' }),
  draftNode('skeletal-pelvic-girdle', 'Pelvic girdle', 'skeletal', ['pelvis'], ['pelvis', 'ilium', 'ischium', 'pubis'], { parentId: 'system-skeletal' }),
  draftNode('skeletal-lower-limb', 'Lower limb skeleton', 'skeletal', ['lower-limb'], ['femur', 'patella', 'tibia', 'fibula', 'tarsal'], { parentId: 'system-skeletal', laterality: 'bilateral' }),
  systemRoot('system-muscular', 'Muscular system', 'muscular', ['muscle']),
  draftNode('muscular-head-neck', 'Head and neck musculature', 'muscular', ['head-neck'], ['muscle', 'neck'], { parentId: 'system-muscular' }),
  draftNode('muscular-thorax', 'Thoracic musculature', 'muscular', ['thorax'], ['pectoralis', 'intercostal'], { parentId: 'system-muscular' }),
  draftNode('muscular-abdominal-wall', 'Abdominal wall musculature', 'muscular', ['abdomen'], ['rectus abdominis', 'oblique', 'transversus'], { parentId: 'system-muscular' }),
  draftNode('muscular-back', 'Back musculature', 'muscular', ['back-spine'], ['erector spinae', 'multifidus', 'latissimus'], { parentId: 'system-muscular' }),
  draftNode('muscular-upper-limb', 'Upper limb musculature', 'muscular', ['upper-limb'], ['deltoid', 'biceps', 'triceps', 'forearm'], { parentId: 'system-muscular', laterality: 'bilateral' }),
  draftNode('muscular-lower-limb', 'Lower limb musculature', 'muscular', ['lower-limb'], ['glute', 'quadriceps', 'hamstring', 'gastrocnemius'], { parentId: 'system-muscular', laterality: 'bilateral' }),
  systemRoot('system-arterial', 'Arterial system', 'arterial', ['artery', 'aorta']),
  draftNode('arterial-aorta', 'Aorta', 'arterial', ['thorax', 'abdomen'], ['aorta'], { parentId: 'system-arterial', laterality: 'midline', scale: 'organ' }),
  draftNode('arterial-head-neck', 'Head and neck arterial tree', 'arterial', ['head-neck'], ['carotid', 'vertebral artery'], { parentId: 'system-arterial' }),
  draftNode('arterial-upper-limb', 'Upper limb arterial tree', 'arterial', ['upper-limb'], ['subclavian', 'axillary artery', 'brachial artery', 'radial artery', 'ulnar artery'], { parentId: 'system-arterial', laterality: 'bilateral' }),
  draftNode('arterial-lower-limb', 'Lower limb arterial tree', 'arterial', ['lower-limb', 'pelvis'], ['iliac artery', 'femoral artery', 'popliteal artery', 'tibial artery'], { parentId: 'system-arterial', laterality: 'bilateral' }),
  systemRoot('system-venous', 'Venous system', 'venous', ['vein', 'vena cava']),
  draftNode('venous-caval', 'Caval venous pathways', 'venous', ['thorax', 'abdomen'], ['superior vena cava', 'inferior vena cava'], { parentId: 'system-venous', scale: 'regional' }),
  draftNode('venous-head-neck', 'Head and neck venous tree', 'venous', ['head-neck'], ['jugular vein'], { parentId: 'system-venous' }),
  draftNode('venous-upper-limb', 'Upper limb venous tree', 'venous', ['upper-limb'], ['axillary vein', 'brachial vein', 'cephalic vein', 'basilic vein'], { parentId: 'system-venous', laterality: 'bilateral' }),
  draftNode('venous-lower-limb', 'Lower limb venous tree', 'venous', ['lower-limb', 'pelvis'], ['femoral vein', 'popliteal vein', 'saphenous'], { parentId: 'system-venous', laterality: 'bilateral' }),
  systemRoot('system-lymphatic', 'Lymphatic and lymphoid system', 'lymphatic', ['lymph', 'spleen', 'thymus']),
  draftNode('lymphatic-nodes', 'Lymph node groups', 'lymphatic', ['head-neck', 'thorax', 'abdomen', 'pelvis', 'upper-limb', 'lower-limb'], ['lymph node'], { parentId: 'system-lymphatic', scale: 'regional' }),
  draftNode('lymphatic-spleen', 'Spleen', 'lymphatic', ['abdomen'], ['spleen'], { parentId: 'system-lymphatic', scale: 'organ' }),
  draftNode('lymphatic-thymus', 'Thymus', 'lymphatic', ['thorax'], ['thymus'], { parentId: 'system-lymphatic', scale: 'organ' }),
  systemRoot('system-nervous', 'Nervous system', 'nervous', ['brain', 'spinal cord', 'nerve']),
  draftNode('nervous-brain', 'Brain', 'nervous', ['head-neck'], ['brain', 'cerebrum', 'cerebellum', 'brainstem'], { parentId: 'system-nervous', scale: 'organ' }),
  draftNode('nervous-spinal-cord', 'Spinal cord', 'nervous', ['back-spine'], ['spinal cord'], { parentId: 'system-nervous', scale: 'organ' }),
  draftNode('nervous-cranial', 'Cranial nerve layer', 'nervous', ['head-neck'], ['cranial nerve'], { parentId: 'system-nervous' }),
  draftNode('nervous-peripheral', 'Peripheral nerve layer', 'nervous', ['upper-limb', 'lower-limb', 'thorax', 'abdomen', 'pelvis'], ['nerve'], { parentId: 'system-nervous' }),
  systemRoot('system-respiratory', 'Respiratory system', 'respiratory', ['trachea', 'bronch', 'lung', 'pleura']),
  systemRoot('system-cardiovascular', 'Cardiovascular organ system', 'cardiovascular', ['heart', 'coronary']),
  draftNode('cardiovascular-heart', 'Heart', 'cardiovascular', ['thorax'], ['heart'], { parentId: 'system-cardiovascular', scale: 'organ' }),
  draftNode('cardiovascular-coronary', 'Coronary vessel layer', 'cardiovascular', ['thorax'], ['coronary'], { parentId: 'cardiovascular-heart', scale: 'substructure' }),
  systemRoot('system-gastrointestinal', 'Gastrointestinal tract', 'gastrointestinal', ['esophagus', 'stomach', 'intestine', 'colon', 'rectum']),
  draftNode('gi-esophagus', 'Esophagus', 'gastrointestinal', ['head-neck', 'thorax', 'abdomen'], ['esophagus'], { parentId: 'system-gastrointestinal', scale: 'organ' }),
  draftNode('gi-stomach', 'Stomach', 'gastrointestinal', ['abdomen'], ['stomach'], { parentId: 'system-gastrointestinal', scale: 'organ' }),
  draftNode('gi-small-intestine', 'Small intestine', 'gastrointestinal', ['abdomen', 'pelvis'], ['duodenum', 'jejunum', 'ileum'], { parentId: 'system-gastrointestinal', scale: 'organ' }),
  draftNode('gi-colon', 'Colon', 'gastrointestinal', ['abdomen', 'pelvis'], ['colon', 'cecum'], { parentId: 'system-gastrointestinal', scale: 'organ' }),
  draftNode('gi-rectum', 'Rectum', 'gastrointestinal', ['pelvis'], ['rectum'], { parentId: 'system-gastrointestinal', scale: 'organ' }),
  systemRoot('system-hepatobiliary', 'Hepatobiliary and pancreatic organs', 'hepatobiliary', ['liver', 'gallbladder', 'pancreas']),
  draftNode('hepatobiliary-liver', 'Liver', 'hepatobiliary', ['abdomen'], ['liver'], { parentId: 'system-hepatobiliary', scale: 'organ' }),
  draftNode('hepatobiliary-gallbladder', 'Gallbladder', 'hepatobiliary', ['abdomen'], ['gallbladder'], { parentId: 'system-hepatobiliary', scale: 'organ' }),
  draftNode('hepatobiliary-pancreas', 'Pancreas', 'hepatobiliary', ['abdomen'], ['pancreas'], { parentId: 'system-hepatobiliary', scale: 'organ' }),
  systemRoot('system-urinary', 'Urinary system', 'urinary', ['kidney', 'ureter', 'bladder', 'urethra']),
  draftNode('urinary-kidneys', 'Kidneys', 'urinary', ['abdomen'], ['kidney'], { parentId: 'system-urinary', laterality: 'bilateral', scale: 'organ' }),
  draftNode('urinary-ureters', 'Ureters', 'urinary', ['abdomen', 'pelvis'], ['ureter'], { parentId: 'system-urinary', laterality: 'bilateral', scale: 'organ' }),
  draftNode('urinary-bladder', 'Urinary bladder', 'urinary', ['pelvis'], ['bladder'], { parentId: 'system-urinary', scale: 'organ', synonyms: ['bladder'] }),
  draftNode('urinary-urethra', 'Urethra', 'urinary', ['pelvis'], ['urethra'], { parentId: 'system-urinary', scale: 'organ' }),
  systemRoot('system-female-reproductive', 'Female reproductive system', 'female-reproductive', ['ovary', 'uterus', 'cervix', 'vagina']),
  draftNode('female-ovaries', 'Ovaries', 'female-reproductive', ['pelvis'], ['ovary'], { parentId: 'system-female-reproductive', laterality: 'bilateral', scale: 'organ' }),
  draftNode('female-uterine-tubes', 'Uterine tubes', 'female-reproductive', ['pelvis'], ['fallopian', 'uterine tube'], { parentId: 'system-female-reproductive', laterality: 'bilateral', scale: 'organ', synonyms: ['fallopian tubes'] }),
  draftNode('female-uterus', 'Uterus', 'female-reproductive', ['pelvis'], ['uterus'], { parentId: 'system-female-reproductive', scale: 'organ' }),
  draftNode('female-cervix', 'Cervix', 'female-reproductive', ['pelvis'], ['cervix'], { parentId: 'female-uterus', scale: 'substructure' }),
  draftNode('female-vagina', 'Vagina', 'female-reproductive', ['pelvis'], ['vagina'], { parentId: 'system-female-reproductive', scale: 'organ' }),
  systemRoot('system-male-reproductive', 'Male reproductive system', 'male-reproductive', ['testis', 'epididymis', 'vas deferens', 'prostate', 'penis']),
  draftNode('male-testes', 'Testes', 'male-reproductive', ['pelvis'], ['testis'], { parentId: 'system-male-reproductive', laterality: 'bilateral', scale: 'organ' }),
  draftNode('male-epididymides', 'Epididymides', 'male-reproductive', ['pelvis'], ['epididymis'], { parentId: 'system-male-reproductive', laterality: 'bilateral', scale: 'organ' }),
  draftNode('male-ductus-deferentes', 'Ductus deferentes', 'male-reproductive', ['pelvis'], ['vas deferens', 'ductus deferens'], { parentId: 'system-male-reproductive', laterality: 'bilateral', scale: 'organ', synonyms: ['vas deferens'] }),
  draftNode('male-seminal-vesicles', 'Seminal vesicles', 'male-reproductive', ['pelvis'], ['seminal vesicle'], { parentId: 'system-male-reproductive', laterality: 'bilateral', scale: 'organ' }),
  draftNode('male-prostate', 'Prostate', 'male-reproductive', ['pelvis'], ['prostate'], { parentId: 'system-male-reproductive', scale: 'organ' }),
  draftNode('male-penis', 'Penis', 'male-reproductive', ['pelvis'], ['penis'], { parentId: 'system-male-reproductive', scale: 'organ' }),
  systemRoot('system-endocrine', 'Endocrine system', 'endocrine', ['pituitary', 'thyroid', 'parathyroid', 'adrenal']),
  draftNode('endocrine-pituitary', 'Pituitary gland', 'endocrine', ['head-neck'], ['pituitary'], { parentId: 'system-endocrine', scale: 'organ', synonyms: ['hypophysis'] }),
  draftNode('endocrine-thyroid', 'Thyroid gland', 'endocrine', ['head-neck'], ['thyroid'], { parentId: 'system-endocrine', scale: 'organ' }),
  draftNode('endocrine-parathyroid', 'Parathyroid glands', 'endocrine', ['head-neck'], ['parathyroid'], { parentId: 'system-endocrine', scale: 'organ' }),
  draftNode('endocrine-adrenals', 'Adrenal glands', 'endocrine', ['abdomen'], ['adrenal'], { parentId: 'system-endocrine', laterality: 'bilateral', scale: 'organ' }),
  draftNode('endocrine-pancreatic-islets', 'Pancreatic endocrine tissue', 'endocrine', ['abdomen'], [], { parentId: 'system-endocrine', scale: 'micro', notes: ['Conceptual cross-scale target only; gross pancreatic mesh must not be presented as endocrine-cell localization.'] }),
  systemRoot('system-integumentary', 'Integumentary system', 'integumentary', ['skin']),
  draftNode('integumentary-skin', 'Skin surface', 'integumentary', ['whole-body'], ['skin', 'body'], { parentId: 'system-integumentary', scale: 'whole-body' }),
  systemRoot('system-fascia-connective', 'Fascia and connective tissue layer', 'fascia-connective', ['fascia', 'tendon', 'ligament']),
  draftNode('fascia-deep', 'Deep fascia layer', 'fascia-connective', ['whole-body'], ['fascia'], { parentId: 'system-fascia-connective', scale: 'regional' }),
  draftNode('connective-tendon', 'Tendon layer', 'fascia-connective', ['upper-limb', 'lower-limb'], ['tendon'], { parentId: 'system-fascia-connective', laterality: 'bilateral' }),
  draftNode('connective-ligament', 'Ligament layer', 'fascia-connective', ['back-spine', 'upper-limb', 'lower-limb', 'pelvis'], ['ligament'], { parentId: 'system-fascia-connective', laterality: 'bilateral' }),
]
