import assert from 'node:assert/strict'
import { buatAlurKembali } from '../../src/lib/alurHalaman.ts'

const route = (pathname: string, search = '', hash = '') => ({ pathname, search, hash })
const history = buatAlurKembali()
history.catat({ ...route('/health-data', '?t=labs', '#recent'), index: 0 })
history.catat({ ...route('/health-data/tutorial'), index: 1 })
assert.equal(history.tujuan(true), -1, 'adjacent parent uses real history, retaining its query and hash')
history.catat(route('/health-data/tutorial', '?step=2'))
assert.equal(history.tujuan(true), '/health-data?t=labs#recent', 'query-only navigation must not masquerade as the parent entry')
history.catat(route('/health-data/tutorial', '?step=2'))
assert.equal(history.tujuan(true), '/health-data?t=labs#recent', 'duplicate effect execution must not change the destination')
history.catat(route('/health-data', '?t=vitals'))
history.catat(route('/health-data/tutorial'))
history.catat(route('/settings'))
history.catat(route('/health-data/tutorial', '?step=3'))
assert.equal(history.tujuan(true), '/health-data?t=vitals', 'latest visited parent wins after an unrelated detour')

const duplicateEntry = buatAlurKembali()
duplicateEntry.catat({ ...route('/health-data', '?t=labs'), key: 'parent' })
duplicateEntry.catat({ ...route('/health-data/tutorial'), key: 'child-1' })
duplicateEntry.catat({ ...route('/health-data/tutorial'), key: 'child-2' })
assert.equal(duplicateEntry.tujuan(true), '/health-data?t=labs', 'same URL pushed twice is not an adjacent parent')

const direct = buatAlurKembali()
const popped = buatAlurKembali()
popped.catat({ ...route('/health-data', '?t=labs'), index: 4 })
popped.catat({ ...route('/health-data/tutorial', '?step=2'), index: 3 })
assert.equal(popped.tujuan(true), '/health-data?t=labs', 'observed parent after POP is not the preceding browser entry')
direct.catat(route('/health-data/tutorial', '?step=3'))
assert.equal(direct.tujuan(false), '/health-data', 'direct deep link falls back to canonical parent')
const outside = buatAlurKembali()
outside.catat(route('/settings'))
assert.equal(outside.tujuan(false), '/', 'external browser history must not navigate out of the app')
assert.equal(outside.tujuan(true), -1, 'known router history remains usable for a route without a parent')
outside.catat(route('/'))
assert.equal(outside.tujuan(true), '/', 'home is the navigation boundary')

const bounded = buatAlurKembali()
bounded.catat(route('/health-data', '?t=old'))
for (let i = 0; i < 65; i++) bounded.catat(route(`/qa-${i}`))
bounded.catat(route('/health-data/tutorial'))
assert.equal(bounded.tujuan(false), '/health-data', 'route cache is bounded and safely falls back after eviction')
console.log('alur-kembali-query: parent query/hash, query changes, direct links, history boundary and bounded memory passed')
