import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const os = readFileSync('src/pages/BodyExposureOS.tsx', 'utf8')
const projector = readFileSync('src/pages/bodyhub/UnifiedHumanSimulationProjector.tsx', 'utf8')
const atlas = readFileSync('src/components/BodyAllSystems3D.tsx', 'utf8')
const physiology = readFileSync('src/pages/bodyhub/AtlasPhysiologyBridgePanel.tsx', 'utf8')
const pathophysiology = readFileSync('src/pages/bodyhub/PathophysiologyNetworkPanel.tsx', 'utf8')
const pharmacology = readFileSync('src/pages/bodyhub/PharmacologyMechanismPanel.tsx', 'utf8')
const imaging = readFileSync('src/pages/bodyhub/PencitraanVolumetrikPanel.tsx', 'utf8')
const surgery = readFileSync('src/pages/bodyhub/SurgicalLab.tsx', 'utf8')
const endoscopy = readFileSync('src/pages/bodyhub/VirtualEndoscopyWorkbench.tsx', 'utf8')

assert.match(os, /projectorDomain: 'localization'/, 'Body Exposure top-level navigation must expose lesion localization in the same projector')
assert.match(os, /projectorDomain: 'imaging'/, 'Body Exposure top-level navigation must expose imaging in the same projector')
assert.match(os, /requestedDomain=\{current\.projectorDomain\}/, 'top-level mode must drive the unified projector')
assert.match(os, /Deep reference labs/, 'legacy Body Explorer capability must be preserved on demand instead of deleted')

assert.match(projector, /type SimulationDomain[\s\S]*'localization'/, 'unified projector must own localization as a first-class projection')
assert.match(projector, /type SimulationDomain[\s\S]*'imaging'/, 'unified projector must own imaging as a first-class projection')
assert.match(projector, /LokalisasiLesiPanel/, 'localization reasoning must render inside the unified projector')
assert.match(projector, /PencitraanVolumetrikPanel/, 'volumetric imaging must render inside the unified projector')
assert.match(projector, /Body → system → organ → tissue → cell → organelle → molecule → genome/, 'one projector must expose the full biological scale ladder')
assert.match(projector, /selectedStructureName/, 'exact rendered structure context must persist across projections')
assert.match(projector, /penjelasanTertulis/, 'selected source anatomy must expose an in-projector teaching explanation')
assert.match(projector, /Explain structure/, 'teaching context must remain progressively disclosed inside the same projector')
assert.match(projector, /onStructureSelect=\{setSelectedStructureName\}/, '3D structure selection must feed projector state')
assert.match(projector, /selectedSourceStructureName=\{selectedStructureName\}/, 'selected source structure must propagate into downstream projection adapters')
assert.match(physiology, /selectedSourceStructureName\?: string \| null/, 'physiology adapter must accept exact selected source structure context')
assert.match(physiology, /visibleSourceTargets/, 'physiology must narrow its source-atlas context to the exact containing target when available')
assert.match(pathophysiology, /data-structure-specific-mechanism="not-inferred"/, 'pathophysiology must preserve structure context without inventing a structure-to-disease mapping')
assert.match(pharmacology, /data-structure-specific-mechanism="not-inferred"/, 'pharmacology must preserve structure context without inventing a structure-to-drug mapping')
assert.match(projector, /PencitraanVolumetrikPanel selectedSourceStructureName=\{selectedStructureName\}/, 'imaging must receive the persistent exact atlas structure context')
assert.match(projector, /SurgicalLab selectedSourceStructureName=\{selectedStructureName\}/, 'surgery must receive the persistent exact atlas structure context')
assert.match(imaging, /data-atlas-dicom-registration="not-performed"/, 'atlas structure context must never imply registration to patient DICOM')
assert.match(imaging, /data-patient-specific-localization="not-inferred"/, 'imaging must not infer patient localization from reference atlas selection')
assert.match(surgery, /data-structure-procedure-inference="not-inferred"/, 'surgery must not infer an operative route from a selected atlas mesh')
assert.match(surgery, /data-patient-specific-surgical-target="not-generated"/, 'surgery must not generate a patient-specific operative target from generic atlas context')
assert.match(projector, /VirtualEndoscopyWorkbench selectedSystemId=\{selectedSystemId\} selectedSourceStructureName=\{selectedStructureName\}/, 'endoscopy must receive the persistent exact atlas structure context')
assert.match(endoscopy, /data-structure-route-inference="not-inferred"/, 'endoscopy must not infer a scope route from a selected atlas mesh')
assert.match(endoscopy, /data-patient-specific-scope-navigation="not-generated"/, 'endoscopy must not turn a reference atlas structure into patient-specific scope navigation')

assert.match(atlas, /THREE\.Raycaster/, 'whole-body atlas must support direct mesh picking')
assert.match(atlas, /onStructureSelect\?: \(sourceName: string\) => void/, 'mesh selection must be exposed to the parent projector')
assert.match(atlas, /applyProjectedSelection/, 'selected anatomy must be visually isolated without mutating source geometry')
assert.doesNotMatch(atlas, /new THREE\.(?:SphereGeometry|CapsuleGeometry|LatheGeometry)/, 'gross anatomy selection must remain on source meshes, never primitive stand-ins')

console.log('Body Exposure one-projector contract verified: exact structure selection + localization + imaging + cross-scale continuity.')
