import assert from 'node:assert/strict'
import { ENDOCRINE_EVIDENCE, ENDOCRINE_FEEDBACK_BOUNDARY, ENDOCRINE_FEEDBACK_DEFAULTS, ENDOCRINE_TEACHING_EQUATIONS, deriveEndocrineFeedback, normalizeEndocrineFeedbackInputs } from '../../src/lib/endocrineFeedbackLab.ts'

const baseline = deriveEndocrineFeedback(ENDOCRINE_FEEDBACK_DEFAULTS)
for (const [key, value] of Object.entries(baseline)) { if (key !== 'dominantConstraint') assert.ok(typeof value === 'number' && value >= 0 && value <= 1, `${key} must remain a normalized 0–1 teaching signal`) }
const lowController = deriveEndocrineFeedback({ ...ENDOCRINE_FEEDBACK_DEFAULTS, hypothalamicDrive: 0.1 })
const highController = deriveEndocrineFeedback({ ...ENDOCRINE_FEEDBACK_DEFAULTS, hypothalamicDrive: 0.9 })
assert.ok(highController.pituitarySignal > lowController.pituitarySignal)
assert.ok(highController.hormoneSignal > lowController.hormoneSignal)
const lowPituitary = deriveEndocrineFeedback({ ...ENDOCRINE_FEEDBACK_DEFAULTS, pituitaryGain: 0.1 })
const highPituitary = deriveEndocrineFeedback({ ...ENDOCRINE_FEEDBACK_DEFAULTS, pituitaryGain: 0.9 })
assert.ok(highPituitary.pituitarySignal > lowPituitary.pituitarySignal)
const lowGland = deriveEndocrineFeedback({ ...ENDOCRINE_FEEDBACK_DEFAULTS, glandCapacity: 0.1 })
const highGland = deriveEndocrineFeedback({ ...ENDOCRINE_FEEDBACK_DEFAULTS, glandCapacity: 0.9 })
assert.ok(highGland.hormoneSignal > lowGland.hormoneSignal)
const lowSensitivity = deriveEndocrineFeedback({ ...ENDOCRINE_FEEDBACK_DEFAULTS, receptorSensitivity: 0.1 })
const highSensitivity = deriveEndocrineFeedback({ ...ENDOCRINE_FEEDBACK_DEFAULTS, receptorSensitivity: 0.9 })
assert.ok(highSensitivity.receptorEffectSignal > lowSensitivity.receptorEffectSignal)
assert.ok(highSensitivity.feedbackSuppressionSignal > lowSensitivity.feedbackSuppressionSignal)
const lowClearance = deriveEndocrineFeedback({ ...ENDOCRINE_FEEDBACK_DEFAULTS, hormoneClearance: 0.1 })
const highClearance = deriveEndocrineFeedback({ ...ENDOCRINE_FEEDBACK_DEFAULTS, hormoneClearance: 0.9 })
assert.ok(highClearance.hormoneSignal < lowClearance.hormoneSignal)
const lowFeedback = deriveEndocrineFeedback({ ...ENDOCRINE_FEEDBACK_DEFAULTS, feedbackGain: 0.1 })
const highFeedback = deriveEndocrineFeedback({ ...ENDOCRINE_FEEDBACK_DEFAULTS, feedbackGain: 0.9 })
assert.ok(highFeedback.feedbackSuppressionSignal > lowFeedback.feedbackSuppressionSignal)
assert.ok(highFeedback.controllerResidualSignal < lowFeedback.controllerResidualSignal)
const normalized = normalizeEndocrineFeedbackInputs({ hypothalamicDrive: 4, glandCapacity: -3, feedbackGain: Number.NaN })
assert.equal(normalized.hypothalamicDrive, 1); assert.equal(normalized.glandCapacity, 0); assert.equal(normalized.feedbackGain, 0)
for (const token of ['dH/dt = secretion − clearance', 'θ = C / (C + Kd)', 'negative feedback: target signal ↑ → upstream drive ↓']) assert.ok(ENDOCRINE_TEACHING_EQUATIONS.some((item) => item.expression === token))
assert.deepEqual(ENDOCRINE_EVIDENCE.map((item) => item.pmid), ['29764284', '8701079', '16595713'])
for (const source of ENDOCRINE_EVIDENCE) assert.equal(source.url, `https://pubmed.ncbi.nlm.nih.gov/${source.pmid}/`)
assert.match(ENDOCRINE_FEEDBACK_BOUNDARY, /synthetic dimensionless signals/i)
assert.match(ENDOCRINE_FEEDBACK_BOUNDARY, /does not calculate serum hormone concentrations/i)
assert.match(ENDOCRINE_FEEDBACK_BOUNDARY, /patient-specific treatment/i)
console.log('endocrine feedback lab: directional control, receptor response, feedback, provenance and safety boundary locked')
