import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { ATLAS_MODULE_INFO, partsForModule } from '../../src/lib/systemAtlas.gen'
const specialty = await readFile(new URL('../../src/pages/bodyhub/SpecialtyLab.tsx', import.meta.url), 'utf8')
const bodyExplorer = await readFile(new URL('../../src/pages/BodyExplorer.tsx', import.meta.url), 'utf8')
const viewer = await readFile(new URL('../../src/components/AtlasViewer3D.tsx', import.meta.url), 'utf8')
const moduleId = 'obgin'
const info = ATLAS_MODULE_INFO[moduleId]
const parts = partsForModule(moduleId)
const names = parts.map((part) => part.name.toLowerCase())
const sources = [...new Set(parts.map((part) => part.source))]
const triangles = parts.reduce((sum, part) => sum + Math.max(0, part.triangles), 0)
assert.ok(info, 'female pelvis atlas module must be generated')
assert.ok(parts.length >= 6, 'female pelvis module must expose multiple source-backed reproductive structures')
assert.ok(parts.every((part) => Number.isFinite(part.triangles) && part.triangles > 0), 'every female pelvis structure must have positive indexed source geometry')
assert.ok(triangles > 0, 'female pelvis module must expose positive triangle geometry')
assert.deepEqual(sources, ['hra-female'], 'female pelvis geometry must retain HuBMAP HRA female provenance')
assert.ok(names.some((name) => name.includes('uterus')), 'female pelvis atlas must expose source-backed uterus geometry')
assert.ok(names.some((name) => name.includes('ovary')), 'female pelvis atlas must expose source-backed ovary geometry')
assert.ok(names.some((name) => name.includes('uterine tube')), 'female pelvis atlas must expose source-backed uterine tube geometry')
assert.ok(names.some((name) => name.includes('vagina')), 'female pelvis atlas must expose source-backed vaginal geometry')
assert.ok(names.some((name) => name.includes('bladder')), 'female pelvis atlas must retain bladder context from the same reference body')
assert.match(bodyExplorer, /const SpecialtyLab = lazy/, 'Body Exposure must keep the specialty atlas reachable')
assert.match(bodyExplorer, /key: 'spesialisasi'/, 'Body Exposure must keep the specialty navigation entry reachable')
assert.match(specialty, /Women’s health.*\['obstetri', 'obgin', 'payudara'\]/, 'female pelvis module must stay reachable from Women’s health')
assert.match(specialty, /berkas=\{`atlas\/\$\{modul\}\.glb`\}/, 'specialty atlas must load the shipped module GLB')
assert.match(specialty, /partsForModule\(modul\)/, 'specialty atlas must use generated source metadata')
assert.match(specialty, /SUMBER\[asal\]/, 'specialty atlas must visibly expose source provenance')
assert.match(specialty, /Uterus, ovaries, uterine/, 'female pelvis atlas must disclose its bounded reproductive scope')
assert.match(viewer, /body3dPixelRatio/, 'viewer must keep bounded mobile pixel-ratio behavior')
assert.match(viewer, /IntersectionObserver/, 'viewer must suspend rendering when offscreen')
assert.match(viewer, /visibilitychange/, 'viewer must suspend rendering while hidden')
assert.match(viewer, /Hanya mesh dengan metadata terverifikasi/, 'viewer must limit picking to verified metadata-backed meshes')
assert.doesNotMatch(specialty, /SphereGeometry|BoxGeometry|CylinderGeometry/, 'female pelvis acceptance must not depend on synthetic primitive anatomy')
console.log(`female pelvis source 3D acceptance passed: ${parts.length} structures, ${triangles} triangles, source=${sources.join(',')}`)
