import assert from 'node:assert/strict'
import { RENAL_EVIDENCE, RENAL_HOMEOSTASIS_BOUNDARY, RENAL_HOMEOSTASIS_DEFAULTS, RENAL_TEACHING_EQUATIONS, deriveRenalHomeostasis, normalizeRenalHomeostasisInputs } from '../../src/lib/renalHomeostasisLab.ts'

const baseline = deriveRenalHomeostasis(RENAL_HOMEOSTASIS_DEFAULTS)
for (const [key, value] of Object.entries(baseline)) { if (key !== 'dominantAxis') assert.ok(typeof value === 'number' && value >= 0 && value <= 1, `${key} must remain normalized`) }
const lowPerfusion = deriveRenalHomeostasis({ ...RENAL_HOMEOSTASIS_DEFAULTS, perfusionDrive: .1 })
const highPerfusion = deriveRenalHomeostasis({ ...RENAL_HOMEOSTASIS_DEFAULTS, perfusionDrive: .9 })
assert.ok(highPerfusion.filtrationSignal > lowPerfusion.filtrationSignal)
const lowCapacity = deriveRenalHomeostasis({ ...RENAL_HOMEOSTASIS_DEFAULTS, filtrationCapacity: .1 })
const highCapacity = deriveRenalHomeostasis({ ...RENAL_HOMEOSTASIS_DEFAULTS, filtrationCapacity: .9 })
assert.ok(highCapacity.filtrationSignal > lowCapacity.filtrationSignal)
const lowSodium = deriveRenalHomeostasis({ ...RENAL_HOMEOSTASIS_DEFAULTS, sodiumReabsorption: .1 })
const highSodium = deriveRenalHomeostasis({ ...RENAL_HOMEOSTASIS_DEFAULTS, sodiumReabsorption: .9 })
assert.ok(highSodium.sodiumRetentionSignal > lowSodium.sodiumRetentionSignal)
assert.ok(highSodium.volumeConservationSignal > lowSodium.volumeConservationSignal)
const lowWater = deriveRenalHomeostasis({ ...RENAL_HOMEOSTASIS_DEFAULTS, waterReabsorption: .1 })
const highWater = deriveRenalHomeostasis({ ...RENAL_HOMEOSTASIS_DEFAULTS, waterReabsorption: .9 })
assert.ok(highWater.waterRetentionSignal > lowWater.waterRetentionSignal)
assert.ok(highWater.concentratingSignal > lowWater.concentratingSignal)
const lowRaas = deriveRenalHomeostasis({ ...RENAL_HOMEOSTASIS_DEFAULTS, raasDrive: .1 })
const highRaas = deriveRenalHomeostasis({ ...RENAL_HOMEOSTASIS_DEFAULTS, raasDrive: .9 })
assert.ok(highRaas.sodiumRetentionSignal > lowRaas.sodiumRetentionSignal)
assert.ok(highRaas.waterRetentionSignal > lowRaas.waterRetentionSignal)
const lowAcid = deriveRenalHomeostasis({ ...RENAL_HOMEOSTASIS_DEFAULTS, acidExcretion: .1 })
const highAcid = deriveRenalHomeostasis({ ...RENAL_HOMEOSTASIS_DEFAULTS, acidExcretion: .9 })
assert.ok(highAcid.acidBaseSupportSignal > lowAcid.acidBaseSupportSignal)
const normalized = normalizeRenalHomeostasisInputs({ perfusionDrive: 4, filtrationCapacity: -3, acidExcretion: Number.NaN })
assert.equal(normalized.perfusionDrive, 1); assert.equal(normalized.filtrationCapacity, 0); assert.equal(normalized.acidExcretion, 0)
for (const token of ['GFR ∝ Kf × net filtration pressure','filtered load = GFR × plasma concentration','excretion = filtration + secretion − reabsorption','Cₓ = Uₓ × V / Pₓ']) assert.ok(RENAL_TEACHING_EQUATIONS.some((item) => item.expression === token))
assert.deepEqual(RENAL_EVIDENCE.map((item) => item.pmid), ['40700075','40175029','25502115'])
for (const source of RENAL_EVIDENCE) assert.equal(source.url, `https://pubmed.ncbi.nlm.nih.gov/${source.pmid}/`)
assert.match(RENAL_HOMEOSTASIS_BOUNDARY, /synthetic dimensionless signals/i)
assert.match(RENAL_HOMEOSTASIS_BOUNDARY, /does not calculate measured or estimated GFR/i)
assert.match(RENAL_HOMEOSTASIS_BOUNDARY, /patient-specific diagnosis or treatment/i)
console.log('renal homeostasis lab: directional physiology, formula ledger, provenance and safety boundary locked')
