import type { PanaceaToolDefinition } from './types.js'

const TOOL_DEFINITIONS: readonly PanaceaToolDefinition[] = Object.freeze([
  {
    name: 'panacea_capabilities',
    title: 'List Panaceamed MCP capabilities',
    description: 'Lists tools authorized for the current MCP transport.',
    domain: 'system',
    transports: ['stdio', 'http'],
    sideEffect: 'none',
    clinicalRisk: 'none',
    maxInputBytes: 1024,
    timeoutMs: 2_000,
  },
  {
    name: 'panacea_orchestration_create_task',
    title: 'Create an agent task packet',
    description: 'Builds a deterministic coordination packet for ChatGPT, Claude Code, or another explicit agent.',
    domain: 'orchestration',
    transports: ['stdio', 'http'],
    sideEffect: 'none',
    clinicalRisk: 'none',
    maxInputBytes: 16 * 1024,
    timeoutMs: 2_000,
  },
  {
    name: 'panacea_orchestration_create_handoff',
    title: 'Create an agent handoff packet',
    description: 'Builds a structured handoff containing work, checks, failures, risks, and next action.',
    domain: 'orchestration',
    transports: ['stdio', 'http'],
    sideEffect: 'none',
    clinicalRisk: 'none',
    maxInputBytes: 32 * 1024,
    timeoutMs: 2_000,
  },
  {
    name: 'panacea_orchestration_verify_completion',
    title: 'Verify completion evidence',
    description: 'Checks whether implemented, tested, PR, merge, and deployment claims have their required evidence.',
    domain: 'orchestration',
    transports: ['stdio', 'http'],
    sideEffect: 'none',
    clinicalRisk: 'none',
    maxInputBytes: 8 * 1024,
    timeoutMs: 2_000,
  },
  {
    name: 'panacea_fhir_capabilities',
    title: 'Describe Panaceamed FHIR and HL7 preview capabilities',
    description: 'Returns bounded FHIR R4 and HL7 v2 preview capabilities and safety boundaries.',
    domain: 'interoperability',
    transports: ['stdio', 'http'],
    sideEffect: 'none',
    clinicalRisk: 'reference',
    maxInputBytes: 1024,
    timeoutMs: 2_000,
  },
  {
    name: 'panacea_fhir_build_observation_bundle_preview',
    title: 'Build a FHIR observation bundle preview',
    description: 'Builds a caller-supplied FHIR R4 collection preview using only Panaceamed-verified codes; no submission.',
    domain: 'interoperability',
    transports: ['stdio', 'http'],
    sideEffect: 'none',
    clinicalRisk: 'clinical-preview',
    maxInputBytes: 64 * 1024,
    timeoutMs: 5_000,
  },
  {
    name: 'panacea_fhir_inspect_resource',
    title: 'Inspect FHIR resource structure',
    description: 'Performs bounded structural inspection only; this is not full FHIR validation.',
    domain: 'interoperability',
    transports: ['stdio', 'http'],
    sideEffect: 'none',
    clinicalRisk: 'clinical-preview',
    maxInputBytes: 128 * 1024,
    timeoutMs: 5_000,
  },
  {
    name: 'panacea_fhir_satusehat_preview',
    title: 'Build a SATUSEHAT transaction preview',
    description: 'Builds a SATUSEHAT-shaped FHIR transaction preview from caller-supplied data without OAuth or network submission.',
    domain: 'interoperability',
    transports: ['stdio', 'http'],
    sideEffect: 'none',
    clinicalRisk: 'clinical-preview',
    maxInputBytes: 128 * 1024,
    timeoutMs: 5_000,
  },
  {
    name: 'panacea_hl7v2_parse_preview',
    title: 'Parse bounded HL7 v2 preview',
    description: 'Parses bounded MSH, PID, PV1, OBR, and OBX segments while reporting unsupported content.',
    domain: 'interoperability',
    transports: ['stdio', 'http'],
    sideEffect: 'none',
    clinicalRisk: 'clinical-preview',
    maxInputBytes: 160 * 1024,
    timeoutMs: 5_000,
  },
  {
    name: 'panacea_hl7v2_to_fhir_preview',
    title: 'Convert bounded HL7 v2 to FHIR preview',
    description: 'Creates a partial preview from supported HL7 v2 fields and preserves unknown coding systems as unmapped.',
    domain: 'interoperability',
    transports: ['stdio', 'http'],
    sideEffect: 'none',
    clinicalRisk: 'clinical-preview',
    maxInputBytes: 160 * 1024,
    timeoutMs: 5_000,
  },
  {
    name: 'panacea_terminology_search',
    title: 'Search bounded medical terminology',
    description: 'Searches ICD, RxNorm, explicit ATC codes, or the verified local LOINC registry with source identity preserved.',
    domain: 'terminology',
    transports: ['stdio', 'http'],
    sideEffect: 'none',
    clinicalRisk: 'reference',
    maxInputBytes: 8 * 1024,
    timeoutMs: 15_000,
  },
  {
    name: 'panacea_terminology_resolve',
    title: 'Resolve a terminology identifier',
    description: 'Resolves supported terminology identifiers without guessing unsupported code systems or relationships.',
    domain: 'terminology',
    transports: ['stdio', 'http'],
    sideEffect: 'none',
    clinicalRisk: 'reference',
    maxInputBytes: 8 * 1024,
    timeoutMs: 15_000,
  },
  {
    name: 'panacea_terminology_crosswalk_preview',
    title: 'Preview verified terminology crosswalk',
    description: 'Returns only explicitly verified relationships; all unknown crosswalks remain unmapped.',
    domain: 'terminology',
    transports: ['stdio', 'http'],
    sideEffect: 'none',
    clinicalRisk: 'reference',
    maxInputBytes: 8 * 1024,
    timeoutMs: 5_000,
  },
  {
    name: 'panacea_repo_qa_plan',
    title: 'Plan allowlisted repository QA',
    description: 'Returns the fixed command plan for one approved local QA profile without executing it.',
    domain: 'repo-qa',
    transports: ['stdio'],
    sideEffect: 'local-read',
    clinicalRisk: 'none',
    maxInputBytes: 1024,
    timeoutMs: 2_000,
  },
  {
    name: 'panacea_repo_qa_run',
    title: 'Run allowlisted repository QA',
    description: 'Executes one approved local QA profile using fixed commands and shell:false.',
    domain: 'repo-qa',
    transports: ['stdio'],
    sideEffect: 'local-test',
    clinicalRisk: 'none',
    maxInputBytes: 1024,
    timeoutMs: 15 * 60_000,
  },
])

export function createPanaceaToolRegistry(): readonly PanaceaToolDefinition[] {
  return TOOL_DEFINITIONS
}

export function findPanaceaToolDefinition(name: string): PanaceaToolDefinition | undefined {
  return TOOL_DEFINITIONS.find((definition) => definition.name === name)
}
