import { lazy, Suspense, useEffect, useRef, useState } from 'react'
import type { BodySystemId } from '../lib/bodySystemSourceWave'
import { resolveBodySystemIdFromAtlasLabel } from '../lib/bodySystemPhysiologyBridge'
import { BodyExplorer } from './BodyExplorer'
import './bodyExposureOS.css'

const BodyAllSystems3D = lazy(() => import('../components/BodyAllSystems3D'))
const AtlasPhysiologyBridgePanel = lazy(() => import('./bodyhub/AtlasPhysiologyBridgePanel'))
const BodySystemDeepDiveWorkspace = lazy(() => import('./bodyhub/BodySystemDeepDiveWorkspace'))
const PathophysiologyNetworkPanel = lazy(() => import('./bodyhub/PathophysiologyNetworkPanel'))
const PharmacologyMechanismPanel = lazy(() => import('./bodyhub/PharmacologyMechanismPanel'))
type ExposureMode='atlas'|'physiology'|'imaging'|'surgery'|'molecular'|'clinical'
type Mode={key:ExposureMode;label:string;panel:string;description:string}
const MODES:Mode[]=[{key:'atlas',label:'Atlas',panel:'Layers',description:'Whole-body layers, structures, organs and surface-to-depth exploration.'},{key:'physiology',label:'Physiology',panel:'Physiology',description:'Connect anatomy to organ function, motion and reference physiology.'},{key:'imaging',label:'Imaging',panel:'DICOM → 3D',description:'Move between anatomy, radiology views and volumetric imaging tools.'},{key:'surgery',label:'Surgery',panel:'Surgical layers',description:'Explore operative approaches as ordered tissue and anatomical layers.'},{key:'molecular',label:'Micro → Gene',panel:'Tissue → gene',description:'Descend from organs into tissue, cells, molecular pathways and genes.'},{key:'clinical',label:'Clinical',panel:'Diseases',description:'Relate structures to disease, drugs and clinically oriented learning.'}]
export function BodyExposureOS(){
 const rootRef=useRef<HTMLElement|null>(null),explorerRef=useRef<HTMLDivElement|null>(null),systemsRef=useRef<HTMLDivElement|null>(null);const[activeMode,setActiveMode]=useState<ExposureMode>('atlas'),[immersive,setImmersive]=useState(false),[selectedBodySystemId,setSelectedBodySystemId]=useState<BodySystemId>('cardiovascular')
 useEffect(()=>{const sync=()=>setImmersive(document.fullscreenElement===rootRef.current);document.addEventListener('fullscreenchange',sync);return()=>document.removeEventListener('fullscreenchange',sync)},[])
 function openPanel(mode:Mode){setActiveMode(mode.key);const buttons=Array.from(explorerRef.current?.querySelectorAll<HTMLButtonElement>('button')??[]);const target=buttons.find(b=>b.textContent?.trim()===mode.panel&&!(b.getAttribute('aria-label')??'').startsWith('Jump to '));if(target){target.click();const reduce=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;requestAnimationFrame(()=>target.scrollIntoView({behavior:reduce?'auto':'smooth',block:'center',inline:'center'}));return}explorerRef.current?.scrollIntoView({behavior:'smooth',block:'start'})}
 async function toggleImmersive(){try{if(document.fullscreenElement)await document.exitFullscreen();else await rootRef.current?.requestFullscreen()}catch{}}
 function captureSystemAtlasSelection(event:React.MouseEvent<HTMLDivElement>){const button=(event.target as HTMLElement).closest<HTMLButtonElement>('button[role="tab"]');if(!button)return;const id=resolveBodySystemIdFromAtlasLabel(button.textContent);if(id)setSelectedBodySystemId(id)}
 function captureExplorerSelection(event:React.MouseEvent<HTMLDivElement>){const button=(event.target as HTMLElement).closest('button');if(!button)return;const matched=MODES.find(m=>m.panel===button.textContent?.trim());if(matched)setActiveMode(matched.key)}
 const current=MODES.find(m=>m.key===activeMode)??MODES[0]
 return <section ref={rootRef} className="body-exposure-os" aria-labelledby="body-exposure-os-title"><div className="body-exposure-os__ambient" aria-hidden/>
 <header className="body-exposure-os__glass relative z-[2] overflow-hidden rounded-[28px] border border-white/10 p-4 sm:p-5 lg:p-6"><div className="max-w-4xl"><div className="flex flex-wrap items-center gap-2"><span className="text-[10px] font-black uppercase tracking-[.24em] text-emerald-200">Body Exposure · Human Body OS</span><span className="rounded-full border border-white/10 px-2.5 py-1 text-[9px] font-black text-white/60">whole-body first</span></div><h2 id="body-exposure-os-title" className="mt-2 text-2xl font-black text-white sm:text-3xl">One body. Every scale. One continuous learning space.</h2><p className="mt-2 max-w-3xl text-sm text-white/60">Start from the complete human body, select a system, then transform into organ-specific function, failure mechanisms, pharmacology and deeper anatomy without leaving the workspace.</p></div><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={()=>systemsRef.current?.scrollIntoView({behavior:'smooth'})} className="min-h-[44px] rounded-full border border-emerald-300/25 bg-emerald-300/10 px-4 text-xs font-black text-emerald-100">Explore 11 systems</button><button type="button" onClick={toggleImmersive} className="min-h-[44px] rounded-full border border-white/12 bg-white/[.055] px-4 text-xs font-black text-white/80">{immersive?'Exit immersive':'Immersive view'}</button></div></header>
 <nav className="body-exposure-os__dock relative z-[3] mt-3 overflow-x-auto rounded-[22px] border border-white/[.08] bg-black/55 p-1.5" aria-label="Body Exposure modes"><div className="flex min-w-max gap-1.5">{MODES.map(mode=><button key={mode.key} type="button" aria-pressed={mode.key===activeMode} onClick={()=>openPanel(mode)} className={`min-h-[42px] rounded-[16px] border px-4 text-xs font-black ${mode.key===activeMode?'border-emerald-300/25 bg-emerald-300/10 text-white':'border-transparent text-white/45'}`}>{mode.label}</button>)}</div></nav>
 <div className="relative z-[2] mt-2 px-1 text-[10px] font-bold text-white/40" aria-live="polite"><span className="text-emerald-200/80">{current.label}</span> · {current.description}</div>
 <div ref={systemsRef} onClickCapture={captureSystemAtlasSelection} className="relative z-[2] mt-3"><Suspense fallback={<div>Loading system atlas…</div>}><BodyAllSystems3D/></Suspense></div>
 <div className="relative z-[2] mt-3"><Suspense fallback={<div>Loading anatomy-physiology bridge…</div>}><AtlasPhysiologyBridgePanel selectedAtlasSystemId={selectedBodySystemId} onSystemChange={setSelectedBodySystemId}/></Suspense></div>
 <div className="relative z-[2] mt-3"><Suspense fallback={<div>Loading organ-specific function…</div>}><BodySystemDeepDiveWorkspace selectedAtlasSystemId={selectedBodySystemId}/></Suspense></div>
 <div className="relative z-[2] mt-3"><Suspense fallback={<div>Loading pathophysiology network…</div>}><PathophysiologyNetworkPanel selectedAtlasSystemId={selectedBodySystemId}/></Suspense></div>
 <div className="relative z-[2] mt-3"><Suspense fallback={<div>Loading pharmacology mechanism network…</div>}><PharmacologyMechanismPanel selectedAtlasSystemId={selectedBodySystemId}/></Suspense></div>
 <div id="body-exposure-core" ref={explorerRef} onClickCapture={captureExplorerSelection} className="body-exposure-os__core relative z-[1] mt-3 rounded-[30px] border border-white/[.08] bg-black/45 p-2 sm:p-3"><BodyExplorer/></div></section>}
